### ISSUE TITLE
Ganged motors with one direction pin

### ISSUE THREAD

**Issue by wu5** [bdring/FluidNC#100]
How to set up two motors per axis if their drivers are using one direction pin? 
```
  x:  
    motor0:
      stepstick:
        direction_pin: gpio.26
        step_pin: gpio.12
        
    motor1:
      stepstick:
        direction_pin: gpio.26
        step_pin: gpio.22
```
        
        
`[MSG:ERR: Configuration error at /machine/axes/x/motor1/stepstick: ERR: Setting up pin [gpio.26] failed. Details: Pin is already used.]␊`
