### ISSUE TITLE
Problem: 3.7.6 fail with my config, but 3.7.5 ok

### ISSUE THREAD

**Issue by andrewthecat** [bdring/FluidNC#1009]
### Wiki Search Terms

configuration format changelog

### Controller Board

CNC32 ( MKS DLC32 schematics )

### Machine Description

generic 3018

### Configuration file

```yaml
board: MKS-DLC32
name: K40 MOD
meta: 2022-12-27 by Tong

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 254
  pulse_us: 6
  dir_delay_us: 10
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 200
    max_rate_mm_per_min: 1500
    acceleration_mm_per_sec2: 500
    max_travel_mm: 300
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 6000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36:low
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2:high

  y:
    steps_per_mm: 200
    max_rate_mm_per_min: 1500
    acceleration_mm_per_sec2: 500
    max_travel_mm: 183
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 6000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35:low
      hard_limits: true
      pulloff_mm: 3.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6:low

  z:
    steps_per_mm: 200
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 500
    max_travel_mm: 80
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_pos_pin: gpio.34:low
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4:high

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.4:low:pu
  cycle_start_pin: gpio.22:low:pu
  macro0_pin: gpio.33:low:pu
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

pwm:
  pwm_hz: 5000
  direction_pin: NO_PIN
  output_pin: gpio.32
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 10000=100.000%
  off_on_alarm: false

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: false
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.7.6]                                                                                                                                                                                        
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]                                                                                                                                                                        
[MSG:INFO: Local filesystem type is spiffs]                                                                                                                                                                       
[MSG:INFO: Configuration file:config.yaml]                                                                                                                                                                        
[MSG:INFO: Machine K40 MOD]                                                                                                                                                                                       
[MSG:INFO: Board MKS-DLC32]                                                                                                                                                                                       
[MSG:INFO: I2SO BCK:gpio.16 WS:gpio.17 DATA:gpio.21]                                                                                                                                                              
[MSG:INFO: SPI SCK:gpio.14 MOSI:gpio.13 MISO:gpio.12]                                                                                                                                                             
[MSG:INFO: Stepping:I2S_static Pulse:6us Dsbl Delay:0us Dir Delay:10us Idle Delay:254ms]                                                                                                                          
[MSG:INFO: Axis count 3]                                                                                                                                                                                          
[MSG:INFO: Shared stepper disable I2SO.0]                                                                                                                                                                         
[MSG:INFO: Axis X (0.000,300.000)]                                                                                                                                                                                
[MSG:INFO:   Motor0]                                                                                                                                                                                              
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:NO_PIN]                                                                                                                                                   
[MSG:INFO:  X Neg Limit gpio.36:low]                                                                                                                                                                              
[MSG:INFO: Axis Y (0.000,183.000)]                                                                                                                                                                                
[MSG:INFO:   Motor0]                                                                                                                                                                                              
[MSG:INFO:     stepstick Step:I2SO.5 Dir:I2SO.6:low Disable:NO_PIN]                                                                                                                                               
[MSG:INFO:  Y Neg Limit gpio.35:low]                                                                                                                                                                              
[MSG:INFO: Axis Z (-80.000,0.000)]                                                                                                                                                                                
[MSG:INFO:   Motor0]                                                                                                                                                                                              
[MSG:INFO:     stepstick Step:I2SO.3 Dir:I2SO.4 Disable:NO_PIN]                                                                                                                                                   
[MSG:INFO:  Z Pos Limit gpio.34:low]                                                                                                                                                                              
[MSG:INFO: feed_hold_pin gpio.4:low:pu]                                                                                                                                                                           
[MSG:INFO: cycle_start_pin gpio.22:low:pu]                                                                                                                                                                        
[MSG:INFO: macro0_pin gpio.33:low:pu]                                                                                                                                                                             
[MSG:INFO: Kinematic system: Cartesian]                                                                                                                                                                           
[MSG:INFO: PWM Spindle Ena:NO_PIN Out:gpio.32 Dir:NO_PIN Freq:5000Hz Period:8191]                                                                                                                                 
[MSG:INFO: Using spindle PWM]                                                                                                                                                                                     
[MSG:INFO: Connecting to STA SSID:andrewthecat_2G]                                                                                                                                                                
[MSG:INFO: Connecting.]                                                                                                                                                                                           
[MSG:INFO: Connecting..]                                                                                                                                                                                          
[MSG:INFO: Connecting...]                                                                                                                                                                                         
[MSG:INFO: Connected - IP is 192.168.1.129]                                                                                                                                                                       
[MSG:INFO: WiFi on]                                                                                                                                                                                               
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]                                                                                                                                                        
[MSG:INFO: SSDP Started]                                                                                                                                                                                          
[MSG:INFO: HTTP started on port 80]                                                                                                                                                                               
[MSG:INFO: Telnet started on port 23]     




[MSG:INFO: FluidNC v3.7.5]                                                                                                                                                                                        
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]                                                                                                                                                                        
[MSG:INFO: Local filesystem type is spiffs]                                                                                                                                                                       
[MSG:INFO: Configuration file:config.yaml]                                                                                                                                                                        
[MSG:INFO: Machine K40 MOD]                                                                                                                                                                                       
[MSG:INFO: Board MKS-DLC32]                                                                                                                                                                                       
[MSG:INFO: I2SO BCK:gpio.16 WS:gpio.17 DATA:gpio.21]                                                                                                                                                              
[MSG:INFO: SPI SCK:gpio.14 MOSI:gpio.13 MISO:gpio.12]                                                                                                                                                             
[MSG:INFO: Stepping:I2S_static Pulse:6us Dsbl Delay:0us Dir Delay:10us Idle Delay:254ms]                                                                                                                          
[MSG:INFO: Axis count 3]                                                                                                                                                                                          
[MSG:INFO: Shared stepper disable I2SO.0]                                                                                                                                                                         
[MSG:INFO: Axis X (0.000,300.000)]                                                                                                                                                                                
[MSG:INFO:   Motor0]                                                                                                                                                                                              
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:NO_PIN]                                                                                                                                                   
[MSG:INFO:  X Neg Limit gpio.36:low]                                                                                                                                                                              
[MSG:INFO: Axis Y (0.000,183.000)]                                                                                                                                                                                
[MSG:INFO:   Motor0]                                                                                                                                                                                              
[MSG:INFO:     stepstick Step:I2SO.5 Dir:I2SO.6:low Disable:NO_PIN]                                                                                                                                               
[MSG:INFO:  Y Neg Limit gpio.35:low]                                                                                                                                                                              
[MSG:INFO: Axis Z (-80.000,0.000)]                                                                                                                                                                                
[MSG:INFO:   Motor0]                                                                                                                                                                                              
[MSG:INFO:     stepstick Step:I2SO.3 Dir:I2SO.4 Disable:NO_PIN]                                                                                                                                                   
[MSG:INFO:  Z Pos Limit gpio.34:low]                                                                                                                                                                              
[MSG:INFO: feed_hold_pin gpio.4:low:pu]                                                                                                                                                                           
[MSG:INFO: cycle_start_pin gpio.22:low:pu]                                                                                                                                                                        
[MSG:INFO: macro0_pin gpio.33:low:pu]                                                                                                                                                                             
[MSG:INFO: Kinematic system: Cartesian]                                                                                                                                                                           
[MSG:INFO: PWM Spindle Ena:NO_PIN Out:gpio.32 Dir:NO_PIN Freq:5000Hz Period:8191]                                                                                                                                 
[MSG:INFO: Using spindle PWM]                                                                                                                                                                                     
[MSG:INFO: Connecting to STA SSID:andrewthecat_2G]                                                                                                                                                                
[MSG:INFO: Connecting.]                                                                                                                                                                                           
[MSG:INFO: Connecting..]                                                                                                                                                                                          
[MSG:INFO: Connecting...]                                                                                                                                                                                         
[MSG:INFO: Connected - IP is 192.168.1.129]                                                                                                                                                                       
[MSG:INFO: WiFi on]                                                                                                                                                                                               
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]                                                                                                                                                        
[MSG:INFO: SSDP Started]                                                                                                                                                                                          
[MSG:INFO: HTTP started on port 80]                                                                                                                                                                               
[MSG:INFO: Telnet started on port 23]
```

### What happened?

I updated firmware to version 3.7.6. After that, the settings page in webui stopped opening because the controller is returning an invalid(truncated) json. Machine does not respond to home. Moving works, but not correctly. I tried flash erase and flash again, same result. Then I rolled back to 3.7.5 and the problem disappeared. https://imgur.com/a/JceVPVt
