### ISSUE TITLE
Problem: Laser Stays on during M8 delay_ms

### ISSUE THREAD

**Issue by AussieMakerGeek** [bdring/FluidNC#1027]
### Wiki Search Terms

M8 Delay

### Controller Board

MKS Tinybee

### Machine Description

Machine independent but this is a converted Gravograph LS800 laser cutter

### Input Circuits

```yaml
N/A
```

### Configuration file

```yaml
board: MKS-Tinybee
name: LS800
meta: 
stepping: 
  engine: I2S_static
  idle_ms: 254
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 2
  segments: 12

i2so: 
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

spi: 
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard: 
  cs_pin: NO_PIN
  card_detect_pin: NO_PIN
  frequency_hz: 8000000

uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  baud: 115200
  mode: 8N1

uart_channel1:
  uart_num: 1

kinematics: 
  Cartesian: 

axes: 
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN
  x: 
    steps_per_mm: 59.500000
    max_rate_mm_per_min: 80000.000000
    acceleration_mm_per_sec2: 12000
    max_travel_mm: 610.000000
    soft_limits: true
    homing: 
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 1.000000
      feed_mm_per_min: 1500.000000
      seek_mm_per_min: 3000.000000
      settle_ms: 500
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: gpio.33
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 4.000000
      stepstick: 
        step_pin: I2SO.1
        direction_pin: I2SO.2
        disable_pin: I2SO.0
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
        reset_pin: NO_PIN

  y: 
    steps_per_mm: 120.000000
    max_rate_mm_per_min: 20000.000000
    acceleration_mm_per_sec2: 2000
    max_travel_mm: 305.000000
    soft_limits: true
    homing: 
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 304.00
      feed_mm_per_min: 1500.000000
      seek_mm_per_min: 3000.000000
      settle_ms: 500
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: gpio.32
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 4.000000
      stepstick: 
        step_pin: I2SO.4
        direction_pin: I2SO.5:low
        disable_pin: I2SO.3
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
        reset_pin: NO_PIN

  z: 
    steps_per_mm: 1200.000000
    max_rate_mm_per_min: 1000.000000
    acceleration_mm_per_sec2: 500.000000
    max_travel_mm: 250.000000
    soft_limits: false
    homing: 
      cycle: 0
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000000
      feed_mm_per_min: 300.000000
      seek_mm_per_min: 500.000000
      settle_ms: 500
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: gpio.22
      limit_pos_pin: gpio.35
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 15.000000
      stepstick: 
        step_pin: I2SO.7
        direction_pin: I2SO.8:low
        disable_pin: I2SO.6
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
        reset_pin: NO_PIN

  a: 
    steps_per_mm: 337.000000
    max_rate_mm_per_min: 8000.000000
    acceleration_mm_per_sec2: 60.000000
    max_travel_mm: 80.000000
    soft_limits: false
    homing: 
      cycle: -1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000000
      feed_mm_per_min: 300.000000
      seek_mm_per_min: 500.000000
      settle_ms: 500
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000000
      stepstick: 
        step_pin: I2SO.10
        direction_pin: I2SO.11:low
        disable_pin: I2SO.9
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
        reset_pin: NO_PIN

control: 
  safety_door_pin: gpio.39:low
  reset_pin: NO_PIN
  feed_hold_pin: gpio.36:low
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant: 
  #flood_pin: I2SO.16
  flood_pin: I2SO.17
  mist_pin: I2SO.18
  delay_ms: 7000

probe: 
  pin: NO_PIN
  toolsetter_pin: NO_PIN
  check_mode_start: true

macros: 
  startup_line0: 
  startup_line1: 
  macro0: $H
  macro1: $HZ
  macro2: G91&G0F1000A+10
  macro3: G90&G0X-45&G0X100

start: 
  must_home: true
  deactivate_parking: false
  check_limits: false

parking: 
  enable: false
  axis: Z
  target_mpos_mm: -5.000000
  rate_mm_per_min: 800.000000
  pullout_distance_mm: 5.000000
  pullout_rate_mm_per_min: 250.000000

user_outputs: 
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN

Laser: 
  pwm_hz: 10000
  output_pin: gpio.2:pd
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000000% 100=95.000000%
  off_on_alarm: true

arc_tolerance_mm: 0.002000
junction_deviation_mm: 0.010000
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
```

### Startup Messages

```text
N/A
```

### User Interface Software

Lightburn

### What happened?

Laser stays active during M8 delay_ms this is a major issue when multiple M8 commands are in the same gcode file, the code is still paused for delay_ms even if M8 is already active.

I'm not sure if this is standard in all gcode processors but I would have thought the state of M8/7 would be tracked so that a subsequent M8/7 would not cause a delay since there is no need for it. Or possibly give me the option to control this behavior.

### GCode File

; LightBurn 1.3.00
; GRBL device profile, current position
; Bounds: X0 Y-3.7 to X12.7 Y0
G00 G17 G40 G21 G54
G91
M4
; Cut @ 5 mm/sec, 90% power
;Initial M8, using delay_ms
M8
G0 X9.626Y-1.477
M3
; Layer C01
G1 X0.147Y0.272S90F300
G1 X0.196Y0.236
;..........
; Cut @ 5 mm/sec, 90% power
;Second M8 still causses delay_ms but there is no need as M8 is already active
M8 ; Laser is still on during this delay
G0 X-6.475Y-0.183
; Layer C00
G1 X-0.033Y-0.322
G1 X-0.093Y-0.301
G1 X-0.147Y-0.272
;.........
M9
G1 S0
M5
; return to starting pos
G0 X-3.188Y1.639
M2

### Other Information

I have also observed the same behavior on my vinyl cutter (also FluidNC with an MKS DLC32) as I use M8 for controlling suction fans. There is delay_ms  at the end of the job (with M9 command) where the cutter stays down. The cutter solenoid/pressure is controlled by PWM in Laser mode as well. I've just never really taken notice of it since it's not of any concern with a vinyl cutter.
