### ISSUE TITLE
Problem: homing starts with fault_pin active

### ISSUE THREAD

**Issue by marsjo** [bdring/FluidNC#1041]
### Wiki Search Terms

homing
fault_pin

### Controller Board

my own partially based on 6-Pack

### Machine Description

Dual X-Axis with closed loop steppers 

### Configuration file

```yaml
board: marsBoard I
name: direct

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 6
  dir_delay_us: 4
  disable_delay_us: 0
  segments: 6

control:
  fault_pin: gpio.2:pu:low
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN

axes:  
  x:
    steps_per_mm: 200
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 1280.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      feed_mm_per_min: 100.000
      seek_mm_per_min: 5000.000
      settle_ms: 200

    motor0:
      limit_pos_pin: gpio.36:high
      pulloff_mm: 9.400
      standard_stepper:
        direction_pin: I2SO.4:high
        step_pin: I2SO.5
        disable_pin: I2SO.7

    motor1:
      limit_pos_pin: gpio.39:high
      pulloff_mm: 3.950
      standard_stepper:
        direction_pin: I2SO.0:high
        step_pin: I2SO.1
        disable_pin: I2SO.3

  y:
    steps_per_mm: 250
    max_rate_mm_per_min: 15000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 1030.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      feed_mm_per_min: 100.000
      seek_mm_per_min: 5000.000
      settle_ms: 50
    
    motor0:
      limit_pos_pin: gpio.34:high
      pulloff_mm: 5.000
      standard_stepper:
        direction_pin: I2SO.8:high
        step_pin: I2SO.9
        disable_pin: I2SO.11

  z:
    steps_per_mm: 2000
    max_rate_mm_per_min: 1500.000
    acceleration_mm_per_sec2: 150.000
    soft_limits: true
    max_travel_mm: 300.000
    
    homing:
      cycle: 1
      positive_direction: true
      feed_mm_per_min: 500.000
      seek_mm_per_min: 1500.000
      settle_ms: 100
      seek_scaler: 1.8
    
    motor0:
      limit_neg_pin: gpio.26:low
      limit_pos_pin: gpio.35:high
      pulloff_mm: 5.000
      standard_stepper:
        direction_pin: I2SO.12:high
        step_pin: I2SO.13
        disable_pin: I2SO.15

probe:
  toolsetter_pin: gpio.25:low
  pin: gpio.27:high
  check_mode_start: true

pwm:
  pwm_hz: 5000
  direction_pin: NO_PIN
  output_pin: gpio.13
  enable_pin: I2SO.28
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 1000
  spindown_ms: 5000
  tool_num: 0
  speed_map: 4000=0.000% 25000=100.000%
```

### Startup Messages

```text
[...]
Grbl 3.7 [FluidNC v3.7.9 (wifi) '$' for help]
[MSG:ERR: fault_pin is active at startup]
[MSG:INFO: ALARM: Control Pin Initially On]
ALARM:11
```

### User Interface Software

CNCJS

### What happened?

One of my x-Motors lost steps and went to fault-state. FluidNC registered the error and went into alarm state (`fault_pin`) as expected.
I reseted fluidNC but forgot to turn off the motor current - i.e. the motor remained in fault-state. Then I started homing and FluidNC started the homing cycles also moving X-Axis but only one side as the motor in fault-state will not move.

```
MSG:INFO: Stopped by fault_pin]
[MSG:INFO: ALARM: Hard Stop]
ALARM:13
[MSG:ERR: Reset to continue]
client> $H
error:8 (Not idle)
client>
[MSG:INFO: ALARM: Unhomed]
ALARM:14
Grbl 3.7 [FluidNC v3.7.9 (wifi) '$' for help]
[MSG:ERR: fault_pin is active at startup]
[MSG:INFO: ALARM: Control Pin Initially On]
ALARM:11
client> $H
[MSG:INFO: ALARM: Homing Fail Approach]
ALARM:9 (Homing fail)
ok
```

I would expect that homing can not be executed while the `fault_pin` is active. Maybe I miss something but at least in my setup it is really bad as my motors have a lot of force for my wooden CNC.
