### ISSUE TITLE
GRBL ESP32 conversion issues

### ISSUE THREAD

**Issue by pcdonovan** [bdring/FluidNC#1043]
### Wiki Search Terms

Configuration, 5v PWM, No Motion, Examples

### Controller Board

Barts Universal 6-pack with External Driver Chips Opto input module, 5v Module, Mosfet Module

### Machine Description

XYYZ Gantry Router current running GRBL ESP32 with the 5v module controlling a SUPERPID Speed controller on a Makita router. The Mosfet Module controls the Mist coolant solenoid, and the Opto Module controlling the endstops.
4 external 542t drivers.  

All working perfectly on GRBL ESP32

### Configuration file

```yaml
ame: TOPSCNC HEAVY
board: 6-pack
kinematics: {}
stepping:
  engine: I2S_STATIC
  idle_ms: 250
  dir_delay_us: 0
  pulse_us: 4
  disable_delay_us: 0
axes:
  x:
    steps_per_mm: 100
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 300
    soft_limits: false
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: true
      settle_ms: 250
      seek_mm_per_min: 2000
      feed_mm_per_min: 200
      seek_scaler: 1.1
      feed_scaler: 5
    motor0:
      limit_all_pin: gpio.33
      hard_limits: false
      stepstick:
        direction_pin: i2so.1
        step_pin: i2so.2
        disable_pin: i2so.0:low
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
  y:
    steps_per_mm: 100
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 300
    soft_limits: false
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: true
      settle_ms: 250
      seek_mm_per_min: 2000
      feed_mm_per_min: 200
      seek_scaler: 1.1
      feed_scaler: 5
    motor0:
      limit_all_pin: gpio.32
      hard_limits: false
      stepstick:
        direction_pin: i2so.4
        step_pin: i2so.5
        disable_pin: i2so.7:low
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
    motor1:
      limit_all_pin: gpio.34
      hard_limits: false
      stepstick:
        direction_pin: i2so.9
        step_pin: i2so.10
        disable_pin: i2so.8:low
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
  z:
    steps_per_mm: 100
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 300
    soft_limits: false
    homing:
      cycle: 1
      mpos_mm: 0
      positive_direction: false
      settle_ms: 250
      seek_mm_per_min: 2000
      feed_mm_per_min: 200
      seek_scaler: 1.1
      feed_scaler: 5
    motor0:
      limit_all_pin: gpio.35
      hard_limits: false
      stepstick:
        direction_pin: i2so.12
        step_pin: i2so.13
        disable_pin: i2so.15:low
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
coolant:
  flood_pin: gpio.4
  mist_pin: gpio.26
  delay_ms: 1000
probe:
  pin: gpio.14:pu
  check_mode_start: false
start:
  must_home: true
  check_limits: true
  deactivate_parking: false
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.01
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
Laser:
  enable_pin: gpio.25:low
  speed_map: 0=0.000%  30000=100.000%
  output_pin: gpio.2
```

### Startup Messages

```text
[MSG:INFO: Restarting]
ok
ets Jun  8 2016 00:22:57
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4
[MSG:INFO: FluidNC v3.7.9 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine TOPSCNC HEAVY]
[MSG:INFO: Board 6-pack]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.2 Dir:I2SO.1 Disable:I2SO.0:low]
[MSG:INFO:  X All Limit gpio.33]
[MSG:INFO: Axis Y (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.5 Dir:I2SO.4 Disable:I2SO.7:low]
[MSG:INFO:  Y All Limit gpio.32]
[MSG:INFO:   Motor1]
[MSG:INFO:     stepstick Step:I2SO.10 Dir:I2SO.9 Disable:I2SO.8:low]
[MSG:INFO:  Y2 All Limit gpio.34]
[MSG:INFO: Axis Z (0.000,300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.13 Dir:I2SO.12 Disable:I2SO.15:low]
[MSG:INFO:  Z All Limit gpio.35]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:gpio.25:low Out:gpio.2 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Flood coolant gpio.4]
[MSG:INFO: Mist coolant gpio.26]
[MSG:INFO: Probe Pin: gpio.14:pu]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
Grbl 3.7 [FluidNC v3.7.9 (wifi) '$' for help]
[MSG:INFO: ALARM: Unhomed]
ALARM:14
```

### User Interface Software

FluidNC Web Installer/ Web UI and CNC js

### What happened?

Installed FluidNC via the web installer, Sent my Grbl ESP32 Machine file for conversion.  Uploaded the config.yaml and had errors popping up with no movement.  Found the lines that were in error, deleted.  It was pointing me to the user defined output lines so I deleted them.  I was then able to start the firmware without any errors.  Still no stepper movement, spindle started when sending m5 and stopped on M3 I inverted the signal now it starts properly with M3 and stops with M5  but cannot change speed by any controls,  it was working perfectly with GRBL ESP32.  Mist solenoid works 
I've tried inverting the signal to the drivers with no change.
Ive tried using the Spindle PWM unable to change speed of the router
I've tried using Spindle Laser unable to change speed of the router

Github generated conversion config.yaml
name: TOPSCNC HEAVY
board: 6-pack

kinematics:
  Cartesian:

stepping:
  engine: I2S_stream
  idle_ms: 250
  dir_delay_us: 0
  pulse_us: 4
  disable_delay_us: 0

axes:
  x:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 2
      mpos_mm: 0.000
      positive_direction: true
      settle_ms: 250.000
      seek_mm_per_min: 2000.000
      feed_mm_per_min: 200.000
      seek_scaler: 1.100
      feed_scaler: 5.000
    motor0:
      limit_all_pin: gpio.33
      hard_limits: false
      stepstick:
        direction_pin: i2so.1
        step_pin: i2so.2
        disable_pin: i2so.0
    motor1:
      null_motor:
  y:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 2
      mpos_mm: 0.000
      positive_direction: true
      settle_ms: 250.000
      seek_mm_per_min: 2000.000
      feed_mm_per_min: 200.000
      seek_scaler: 1.100
      feed_scaler: 5.000
    motor0:
      limit_all_pin: gpio.32
      hard_limits: false
      stepstick:
        direction_pin: i2so.4
        step_pin: i2so.5
        disable_pin: i2so.7
    motor1:
      limit_all_pin: gpio.34
      hard_limits: false
      stepstick:
        direction_pin: i2so.9
        step_pin: i2so.10
        disable_pin: i2so.8
  z:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      mpos_mm: 0.000
      positive_direction: false
      settle_ms: 250.000
      seek_mm_per_min: 2000.000
      feed_mm_per_min: 200.000
      seek_scaler: 1.100
      feed_scaler: 5.000
    motor0:
      limit_all_pin: gpio.35
      hard_limits: false
      stepstick:
        direction_pin: i2so.12
        step_pin: i2so.13
        disable_pin: i2so.15
    motor1:
      null_motor:

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5

control:

coolant:
  flood_pin: gpio.4
  mist_pin: gpio.26
  delay_ms: 1000.000

probe:
  pin: gpio.14:pu
  check_mode_start: false

macros:
  startup_line0: 
  startup_line1: 
  macro0: 
  macro1: 
  macro2: 
  macro3: 

start:
  must_home: true
  check_limits: true
  deactivate_parking: false

user_outputs:
  digital0_pin: gpio.36
  digital1_pin: gpio.16
  digital2_pin: gpio.27

PWM:
  tool_num: 0
  speed_map: 0=0.0% 1000=100.0%
  spinup_ms: 0
  spindown_ms: 0
  output_pin: gpio.2
  enable_pin: gpio.25
  disable_with_s0: false
  s0_with_disable: false
  pwm_hz: 5000
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false 

### Other Information

 GRBL ESP32 Machine file
uploaded and recieved back an configuration YAML 
  Pin assignments for the ESP32 I2S 6-axis board
    
    2020-11-04 B. Dring for K.O.
    Grbl_ESP32 is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Grbl is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with Grbl_ESP32.  If not, see <http://www.gnu.org/licenses/>.
*/
#define MACHINE_NAME            "TOPSCNC HEAVY"

#define N_AXIS 3

// === Special Features

// I2S (steppers & other output-only pins)
#define USE_I2S_OUT
#define USE_I2S_STEPS
//#define DEFAULT_STEPPER ST_I2S_STATIC

#define I2S_OUT_BCK             GPIO_NUM_22
#define I2S_OUT_WS              GPIO_NUM_17
#define I2S_OUT_DATA            GPIO_NUM_21

// Motor Socket #1
#define X_DISABLE_PIN           I2SO(0)
#define X_DIRECTION_PIN         I2SO(1)
#define X_STEP_PIN              I2SO(2)

// Motor Socket #2
#define Y_DIRECTION_PIN         I2SO(4)
#define Y_STEP_PIN              I2SO(5)
#define Y_DISABLE_PIN           I2SO(7)

// Motor Socket #3
#define Y2_DISABLE_PIN          I2SO(8)
#define Y2_DIRECTION_PIN        I2SO(9)
#define Y2_STEP_PIN             I2SO(10)

// Motor Socket #4
#define Z_DIRECTION_PIN         I2SO(12)
#define Z_STEP_PIN              I2SO(13)
#define Z_DISABLE_PIN           I2SO(15)

/*
    Socket I/O reference
    The list of modules is here...
    https://github.com/bdring/6-Pack_CNC_Controller/wiki/CNC-I-O-Module-List
    Click on each module to get example for using the modules in the sockets
*/

// 4x Input Module in Socket #1
// https://github.com/bdring/6-Pack_CNC_Controller/wiki/4x-Switch-Input-module
#define X_LIMIT_PIN             GPIO_NUM_33
#define Y_LIMIT_PIN             GPIO_NUM_32
#define Z_LIMIT_PIN             GPIO_NUM_35
#define Y2_LIMIT_PIN            GPIO_NUM_34

#define DEFAULT_INVERT_LIMIT_PINS       0 // Default for NO Switches
#define DEFAULT_INVERT_PROBE_PIN        0

// 5v Output Module inSocket #2
// https://github.com/bdring/6-Pack_CNC_Controller/wiki/4x-5V-Buffered-Output-Module
#define SPINDLE_TYPE            SpindleType::PWM
#define SPINDLE_OUTPUT_PIN      GPIO_NUM_2  // 5v PWM Output
#define SPINDLE_ENABLE_PIN      GPIO_NUM_25  // Inverted 5v Enable
#define USER_DIGITAL_PIN_4       GPIO_NUM_39  // 5v Power for SuperPID
#define USER_DIGITAL_PIN_0      GPIO_NUM_36  // M7 on M9 Off Unused

// Quad MOSFET module in socket #3
// https://github.com/bdring/6-Pack_CNC_Controller/wiki/Quad-MOSFET-Module
#define COOLANT_MIST_PIN       GPIO_NUM_26  //24v Mist Solenoid
#define COOLANT_FLOOD_PIN      GPIO_NUM_4    
#define USER_DIGITAL_PIN_1     GPIO_NUM_16   
#define USER_DIGITAL_PIN_2     GPIO_NUM_27

// Open module in socket #4
#define PROBE_PIN               GPIO_NUM_14

// === Default settings
#define DEFAULT_STEP_PULSE_MICROSECONDS I2S_OUT_USEC_PER_PULSE
