### ISSUE TITLE
Problem: TLO reset after cancelling program

### ISSUE THREAD

**Issue by AlexT-38** [bdring/FluidNC#1046]
### Wiki Search Terms

TLO reset

### Controller Board

MKS DLC32

### Machine Description

ISEL

### Configuration file

```yaml
board: MKS DLC32 2.0
name: MKS DLC32 XYZ
meta: FOR/REV/PWM v0.9 (13/02/2023)
stepping:
  engine: I2S_stream
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 5
  disable_delay_us: 0
  segments: 6
axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 1280.000
    max_rate_mm_per_min: 2500.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 341.000
    soft_limits: false
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_all_pin: gpio.36
      hard_limits: true
      pulloff_mm: 0.5000
      standard_stepper:
        step_pin: I2SO.1
        direction_pin: I2SO.2
  y:
    steps_per_mm: 1280.000
    max_rate_mm_per_min: 2500.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 430.000
    soft_limits: false
    homing:
      cycle: 3
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 435.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_all_pin: gpio.35
      hard_limits: true
      pulloff_mm: 0.5000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.6:low
  z:
    steps_per_mm: 1280.000
    max_rate_mm_per_min: 2500.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 163.000
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_all_pin: gpio.34
      hard_limits: true
      pulloff_mm: 0.5000
      standard_stepper:
        step_pin: I2SO.3
        direction_pin: I2SO.4
kinematics:
  Cartesian:
i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17
spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14
sdcard:
  cs_pin: gpio.15
  card_detect_pin: gpio.39
control:
#gpio.0:high //gpio.0 does not seem to work.
#sometimes, fluidnc will spam "MSG:INFO: Ceck door" and will not funcion until the door input is closed
#sometimes, having te door input closed wil prevent fluidnc from booting at all.
# door/inerlock will be disabled unil this is fully understood.
#reset pin should be active high, but stupid chinese vfd uses NO output.
  safety_door_pin: NO_PIN
  reset_pin: gpio.23:low
  feed_hold_pin: gpio.19:high
  cycle_start_pin: gpio.18:low
  macro0_pin: gpio.4:low
coolant:
  flood_pin: gpio.27
  mist_pin: gpio.33
  delay_ms: 500
probe:
  pin: gpio.22
  check_mode_start: true
macros:
  startup_line0: 
  startup_line1:
#HOME: retract, stop and move to location G30, probe z-height. Tool length offset is probe result minus probe position, which is -150mm (relative to spindle nose minus 20mm)
  macro0: G53 G0Z0 & M9 M5 & G30 & M0 & G53 G38.2 Z-160 F200 & G53 G38.4 Z0 F10 & G53 G0 Z0
  macro1:
  macro2: 
  macro3: 
start:
  must_home: false
  deactivate_parking: false
  check_limits: false
user_outputs:
#gpio.32 (LC/Spindle) J7 800mA open collector output on the MKS-DLC32
  analog0_pin: gpio.32
  analog0_hz: 5000
#i2so.7 (BEEPER) J4 500mA open collector output on the MKS-DLC32
  digital0_pin: I2SO.7
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
10V:
  forward_pin: gpio.5:low
  reverse_pin: gpio.26:high
  pwm_hz: 5000
#vfd programed to invert signal so that an open circuit sets zero speed
  output_pin: gpio.25
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 15000
  spindown_ms: 15000
  tool_num: 0
  speed_map: 0=0.000% 240=23.5% 24000=100.000%
  off_on_alarm: true
```

### Startup Messages

```text
$SS
[MSG:INFO: FluidNC v3.6.6]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config_frp.yaml]
[MSG:INFO: Machine MKS DLC32 XYZ]
[MSG:INFO: Board MKS DLC32 2.0]
[MSG:INFO: I2SO BCK:gpio.16 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.14 MOSI:gpio.13 MISO:gpio.12]
[MSG:INFO: SD Card cs_pin:gpio.15 detect:gpio.39]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:5us Idle Delay:255ms]
[MSG:INFO: User Digital Output:0 on Pin:I2SO.7]
[MSG:INFO: User Analog Output 0 on Pin:gpio.32 Freq:5000Hz]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable I2SO.0]
[MSG:INFO: Axis X (0.000,341.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2 Disable:NO_PIN]
[MSG:INFO:  X All Limit gpio.36]
[MSG:INFO: Axis Y (5.000,435.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.5 Dir:I2SO.6:low Disable:NO_PIN]
[MSG:INFO:  Y All Limit gpio.35]
[MSG:INFO: Axis Z (-163.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.3 Dir:I2SO.4 Disable:NO_PIN]
[MSG:INFO:  Z All Limit gpio.34]
[MSG:INFO: reset_pin gpio.23:low]
[MSG:INFO: feed_hold_pin gpio.19]
[MSG:INFO: cycle_start_pin gpio.18:low]
[MSG:INFO: macro0_pin gpio.4:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:NO_PIN Out:gpio.25 Dir:NO_PIN Fwd:gpio.5:low Rev:gpio.26 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant gpio.27]
[MSG:INFO: Mist coolant gpio.33]
[MSG:INFO: Probe Pin: gpio.22]
[MSG:INFO: Connecting to STA SSID:The hidden network]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.0.22]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://bbcnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

WebUI

### What happened?

After stopping a program from running, by hitting the feed hold button and then clicking the reset button next to the resume button and progress bar in the GRBL panel of the WebUI, the tool length offset TLO is reset to zero.
When the program is restarted, this causes the tool to be smashed into the stock.

TLO should not be reset by any event that does not also reset the machine position, ie firmware restart or power loss (or the reset TLO comand).
