### ISSUE TITLE
Problem: Unresponsive after Jog at 1000 mm/min

### ISSUE THREAD

**Issue by sokrdz** [bdring/FluidNC#1048]
### Wiki Search Terms

axes, UART sections, jogging

### Controller Board

4 Axis TMC2209 CNC Controller By Bart Dring

### Machine Description

3 Axis Mill 

### Configuration file

```yaml
'''yaml
board: FluidNC 4X 2209
name: Michael's Mill
meta: 2023-01-25 MKD Initial
stepping:
  engine: I2S_stream
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
  segments: 12

homing_init_lock: false

uart1:
  txd_pin: gpio.16
  rxd_pin: gpio.4
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 115200
  mode: 8N1

uart2:
  txd_pin: gpio.25
  rxd_pin: gpio.27
  rts_pin: gpio.26
  cts_pin: NO_PIN
  baud: 9600
  mode: 8N1

axes:
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN
  x:
    steps_per_mm: 200.000000
    max_rate_mm_per_min: 1250.000000
    acceleration_mm_per_sec2: 2025.000000
    max_travel_mm: 500.000000
    soft_limits: false
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 2.500000
      feed_mm_per_min: 500.000000
      seek_mm_per_min: 500.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000
    motor0:
      limit_neg_pin: gpio.36
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000000
      tmc_2209:
        run_mode: StealthChop
        homing_mode: StealthChop
        stallguard: 0
        stallguard_debug: false
        toff_coolstep: 3
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0
        r_sense_ohms: 0.110000
        run_amps: 1.5000000
        hold_amps: 0.500000
        microsteps: 8
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        uart_num: 1
        addr: 1
  y:
    steps_per_mm: 202.500000
    max_rate_mm_per_min: 1250.000000
    acceleration_mm_per_sec2: 2025.000000
    max_travel_mm: 500.000000
    soft_limits: false
    homing:
      cycle: 3
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 2.500000
      feed_mm_per_min: 500.000000
      seek_mm_per_min: 500.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000
    motor0:
      limit_neg_pin: gpio.39
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000000
      tmc_2209:
        run_mode: StealthChop
        homing_mode: StealthChop
        stallguard: 0
        stallguard_debug: false
        toff_coolstep: 3
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7
        r_sense_ohms: 0.110000
        run_amps: 1.500000
        hold_amps: 0.500000
        microsteps: 8
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        uart_num: 1
        addr: 2
  z:
    steps_per_mm: 399.000000
    max_rate_mm_per_min: 500.000000
    acceleration_mm_per_sec2: 350.000000
    max_travel_mm: 300.000000
    soft_limits: false
    homing:
      cycle: 3
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 2.500000
      feed_mm_per_min: 200.000000
      seek_mm_per_min: 300.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.34
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000000
      tmc_2209:
        run_mode: StealthChop
        homing_mode: StealthChop
        stallguard: 0
        stallguard_debug: false
        toff_coolstep: 3
        step_pin: I2SO.10
        direction_pin: I2SO.9:low
        disable_pin: I2SO.8
        r_sense_ohms: 0.110000
        run_amps: 1.50000
        hold_amps: 0.500000
        microsteps: 8
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        uart_num: 1
        addr: 3
  a:
    steps_per_mm: 400.000000
    max_rate_mm_per_min: 200.000000
    acceleration_mm_per_sec2: 25.000000
    max_travel_mm: 200.000000
    soft_limits: false
    homing:
      cycle: 0
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000000
      feed_mm_per_min: 100.000000
      seek_mm_per_min: 200.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.35:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000000
      tmc_2209:
        run_mode: StealthChop
        homing_mode: StealthChop
        stallguard: 0
        stallguard_debug: false
        toff_coolstep: 3
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15
        r_sense_ohms: 0.110000
        run_amps: 1.000000
        hold_amps: 0.500000
        microsteps: 16
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        uart_num: 1
        addr: 4
kinematics:
  Cartesian:
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  frequency_hz: 10000000
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0
probe:
  pin: NO_PIN
  check_mode_start: true
macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:
start:
  must_home: false
  deactivate_parking: false
  check_limits: false
parking:
  enable: false
  axis: Z
  target_mpos_mm: -5.000000
  rate_mm_per_min: 800.000000
  pullout_distance_mm: 5.000000
  pullout_rate_mm_per_min: 250.000000
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
arc_tolerance_mm: 0.002000
junction_deviation_mm: 0.010000
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
Huanyang:
  uart_num: 2
  addr: 1
  modbus_id: 1
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000000% 0=25.000000% 6000=25.000000% 24000=100.000000%
  off_on_alarm: false
'''
```

### Startup Messages

```text
$SS
[MSG:INFO: FluidNC v3.7.8]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:3_7_8_working1.yml]
[MSG:WARN: Ignored key homing_init_lock]
[MSG:WARN: Ignored key addr]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine Michael's Mill]
[MSG:INFO: Board FluidNC 4X 2209]
[MSG:INFO: UART1 Tx:gpio.16 Rx:gpio.4 RTS:NO_PIN Baud:115200]
[MSG:INFO: UART2 Tx:gpio.25 Rx:gpio.27 RTS:gpio.26 Baud:9600]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:10000000]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 4]
[MSG:INFO: Axis X (-497.500,2.500)]
[MSG:INFO:   Motor0]
[MSG:DBG: TMCStepper Library Ver. 0x703]
[MSG:INFO:     tmc_2209 UART1 Addr:1 CS:NO_PIN Step:I2SO.2 Dir:I2SO.1 Disable:I2SO.0 R:0.110]
[MSG:INFO:  X Neg Limit gpio.36]
[MSG:DBG:  X Neg Limit 1]
[MSG:INFO: Axis Y (2.500,502.500)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 UART1 Addr:2 CS:NO_PIN Step:I2SO.5 Dir:I2SO.4 Disable:I2SO.7 R:0.110]
[MSG:INFO:  Y Neg Limit gpio.39]
[MSG:DBG:  Y Neg Limit 0]
[MSG:INFO: Axis Z (-297.500,2.500)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 UART1 Addr:3 CS:NO_PIN Step:I2SO.10 Dir:I2SO.9:low Disable:I2SO.8 R:0.110]
[MSG:INFO:  Z Pos Limit gpio.34]
[MSG:DBG:  Z Pos Limit 0]
[MSG:INFO: Axis A (0.000,200.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 UART1 Addr:4 CS:NO_PIN Step:I2SO.13 Dir:I2SO.12 Disable:I2SO.15 R:0.110]
[MSG:INFO:  A Pos Limit gpio.35:low]
[MSG:DBG:  A Pos Limit 1]
[MSG:INFO: X Axis driver test passed]
[MSG:DBG: X Axis StealthChop]
[MSG:INFO: Y Axis driver test passed]
[MSG:DBG: Y Axis StealthChop]
[MSG:INFO: Z Axis driver test passed]
[MSG:DBG: Z Axis StealthChop]
[MSG:ERR: A Axis TMC driver not detected - expected 0x21 got 0x0]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Huanyang Spindle  Tx:gpio.25 Rx:gpio.27 RTS:gpio.26 Baud:9600]
[MSG:INFO: Using spindle Huanyang]
[MSG:INFO: Connecting to STA SSID:ASUS_F8]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.50.252]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:DBG: index.html.gz hash "3B628023FBEBA2C44FCC0CD494849DE07F5D327C98AD70F5DF5B2CD374B0DD81"]
[MSG:DBG: preferences.json hash "41CBF80F4E7C60280316E56CB9D9F9F0077DCC6641EFD8B9295BC3651A485A7E"]
[MSG:DBG: 3_7_8_working1.yml hash "48EDFE714DE81918E022D6DE2A0BC0A3A4BFB925631C6A71FF5DC2FBFE4301C7"]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

FluidTerm

### What happened?

I find this issue happens only during setting up for cutting a work piece. While executing g-code from loaded .nc files, movement is stable. 

To debug, I execute the following command: $J=G91 X10.0 F100

<Idle|MPos:0.000,0.000,0.000,0.000|FS:0,0|Pn:XA>
$J=G91 X10.0 F100
ok
<Jog|MPos:6.455,0.000,0.000,0.000|FS:100,0|Pn:XA>
<Idle|MPos:10.000,0.000,0.000,0.000|FS:0,0|Pn:XA>

With a F100 rate, i don't run into any unresponsive issues. However, after 1 command using a higher rate F1000, my machine became unresponsive in the X-axis.  The status (?) stays consistent throughout the jogging, meaning, it is reporting that the jog executed and results in an accurate MPos. Soft limits in config file are false. I find my X-axis is the least stable and will stop responding the most. 

Resetting ESP32 through fluid term does not resolve the issue. However, a hard reset (cutting power) does resolve the issue until I start commanding higher rates.
