### ISSUE TITLE
Problem: I2S does not work?

### ISSUE THREAD

**Issue by AlexMoiseevs** [bdring/FluidNC#1053]
### Wiki Search Terms

read everything

### Controller Board

6-pack

### Machine Description

Test

### Configuration file

```yaml
board: 6 Pack
name: 6 Pack OLED
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  dir_delay_us: 10
  pulse_us: 5
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 800.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        step_pin: i2so.2
        direction_pin: i2so.1:low
        disable_pin: i2so.0:low


  y:
    motor0:
      null_motor:

  z:
    motor0:
      null_motor:


i2c0:
   sda_pin: gpio.14
   scl_pin: gpio.13
        
oled:
   i2c_num: 0
   i2c_address: 60
   width: 128
   height: 64
   radio_delay_ms: 1000

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.18
```

### Startup Messages

```text
Ok
```

### What happened?

when moving , the date signal changes . actually it is logical. but because of the awkward synchronization signals, nothing is written to the register.

the chip 74hc595n is powered by 3.3 volts. manually closing the corresponding contacts, the register is recorded.
![2023-10-28_13-03-29](https://github.com/bdring/FluidNC/assets/118102538/7337bc5e-c387-4ff0-9f47-e27f667d1694)
