### ISSUE TITLE
Machine no longer responds to $HZ after upgrading to v3.7.9

### ISSUE THREAD

**Issue by AussieMakerGeek** [bdring/FluidNC#1055]
### Wiki Search Terms

Limit Switches
Homing

### Controller Board

MKS Tinybee

### Machine Description

Gantry Co2 Laser with Z axis
Gravograph LS800 converted to FluidNC

### Configuration file

```yaml
board: MKS-Tinybee
name: LS800
meta: 
stepping: 
  engine: I2S_static
  idle_ms: 254
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 2
  segments: 12

i2so: 
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

spi: 
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard: 
  cs_pin: NO_PIN
  card_detect_pin: NO_PIN
  frequency_hz: 8000000

uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  baud: 115200
  mode: 8N1

uart_channel1:
  uart_num: 1

kinematics: 
  Cartesian: 

axes: 
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN
  x: 
    steps_per_mm: 59.500000
    max_rate_mm_per_min: 80000.000000
    acceleration_mm_per_sec2: 12000
    max_travel_mm: 610.000000
    soft_limits: true
    homing: 
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 1.000000
      feed_mm_per_min: 1500.000000
      seek_mm_per_min: 3000.000000
      settle_ms: 500
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: gpio.33
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 4.000000
      stepstick: 
        step_pin: I2SO.1
        direction_pin: I2SO.2
        disable_pin: I2SO.0
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
        reset_pin: NO_PIN

  y: 
    steps_per_mm: 120.000000
    max_rate_mm_per_min: 20000.000000
    acceleration_mm_per_sec2: 2000
    max_travel_mm: 305.000000
    soft_limits: true
    homing: 
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 304.00
      feed_mm_per_min: 1500.000000
      seek_mm_per_min: 3000.000000
      settle_ms: 500
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: gpio.32
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 4.000000
      stepstick: 
        step_pin: I2SO.4
        direction_pin: I2SO.5:low
        disable_pin: I2SO.3
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
        reset_pin: NO_PIN

  z: 
    steps_per_mm: 1200.000000
    max_rate_mm_per_min: 1000.000000
    acceleration_mm_per_sec2: 500.000000
    max_travel_mm: 250.000000
    soft_limits: false
    homing: 
      cycle: 0
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000000
      feed_mm_per_min: 300.000000
      seek_mm_per_min: 500.000000
      settle_ms: 500
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: gpio.22
      limit_pos_pin: gpio.35
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 15.000000
      stepstick: 
        step_pin: I2SO.7
        direction_pin: I2SO.8:low
        disable_pin: I2SO.6
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
        reset_pin: NO_PIN

  a: 
    steps_per_mm: 337.000000
    max_rate_mm_per_min: 8000.000000
    acceleration_mm_per_sec2: 60.000000
    max_travel_mm: 80.000000
    soft_limits: false
    homing: 
      cycle: -1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000000
      feed_mm_per_min: 300.000000
      seek_mm_per_min: 500.000000
      settle_ms: 500
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000000
      stepstick: 
        step_pin: I2SO.10
        direction_pin: I2SO.11:low
        disable_pin: I2SO.9
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
        reset_pin: NO_PIN

control: 
  safety_door_pin: gpio.39:low
  reset_pin: NO_PIN
  feed_hold_pin: gpio.36:low
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant: 
  #flood_pin: I2SO.16
  flood_pin: I2SO.18
  #mist_pin: I2SO.18
  mist_pin: NO_PIN
  delay_ms: 0

probe: 
  pin: NO_PIN
  toolsetter_pin: NO_PIN
  check_mode_start: true

macros: 
  startup_line0: 
  startup_line1: 
  macro0: M6 T0&M3 S20&G1&G4 P0.2&G0&M5
  macro1: $HZ
  macro2: G91&G0F1000A+10
  macro3: G90&G0X-45&G0X100

start: 
  must_home: true
  deactivate_parking: false
  check_limits: false

parking: 
  enable: false
  axis: Z
  target_mpos_mm: -5.000000
  rate_mm_per_min: 800.000000
  pullout_distance_mm: 5.000000
  pullout_rate_mm_per_min: 250.000000

user_outputs: 
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN

Laser: 
  pwm_hz: 10000
  output_pin: gpio.2:pd
  enable_pin: I2SO.17:HIGH
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000000% 100=100.000000%
  off_on_alarm: true

arc_tolerance_mm: 0.002000
junction_deviation_mm: 0.010000
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
```

### Startup Messages

```text
$ss
[MSG:INFO: FluidNC v3.7.9 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine LS800]
[MSG:INFO: Board MKS-Tinybee]
[MSG:INFO: UART1 Tx:gpio.17 Rx:gpio.16 RTS:NO_PIN Baud:115200]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:2us Dir Delay:1us Idle Delay:254ms]
[MSG:INFO: Axis count 4]
[MSG:INFO: Axis X (1.000,611.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33]
[MSG:INFO: Axis Y (-1.000,304.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32]
[MSG:INFO: Axis Z (0.000,250.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Z Neg Limit gpio.22]
[MSG:INFO:  Z Pos Limit gpio.35]
[MSG:INFO: Axis A (-80.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.10 Dir:I2SO.11:low Disable:I2SO.9]
[MSG:INFO: safety_door_pin gpio.39:low]
[MSG:INFO: feed_hold_pin gpio.36:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:I2SO.17 Out:gpio.2:pd Freq:10000Hz Period:4095]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Flood coolant I2SO.18]
[MSG:INFO: Connecting to STA SSID:<redacted>]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.0.10]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://LS800.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
ok
```

### What happened?

I upgraded from v3.7.5 due to issue previously raised
Machine operates as expected with the exception that I can not home the Z Axis.
I can home X/Y, I can jog X,Y and **Z** Axes
Z Axis will no longer home when issuing $HZ from any interface.

**Homing order is '0' for the Z axis but it's as if it's '-1'**

The machine responds as if it does, but there is no movement:

$Message/Level=Debug
ok
$HZ
[MSG:DBG: Homing Cycle Z]
[MSG:DBG: Homing nextPhase CycleDone]
[MSG:DBG: mpos was 0.000,0.000,0.000]
[MSG:DBG: mpos becomes 0.000,0.000,0.000]
[MSG:DBG: mpos transformed 0.000,0.000,0.000]
[MSG:DBG: Homing done]
ok

Homing switch is working fine when manually activated:
[MSG:DBG:  Z Pos Limit 1]
[MSG:DBG: Limit switch tripped for Z motor 0]
[MSG:DBG:  Z Pos Limit 0]
[MSG:DBG:  Z Pos Limit 1]
[MSG:DBG: Limit switch tripped for Z motor 0]
[MSG:DBG:  Z Pos Limit 0]
[MSG:DBG:  Z Pos Limit 1]
[MSG:DBG: Limit switch tripped for Z motor 0]
[MSG:DBG:  Z Pos Limit 0]

### GCode File

$HZ

### Other Information

Homing of X/Y works fine:
[MSG:DBG: Homing Cycle Y]
[MSG:DBG: Homing nextPhase FastApproach]
[MSG:DBG: Starting from 0.000,0.000,0.000]
[MSG:DBG: Planned move to 0.000,335.500,0.000 @ 3000.000]
[MSG:DBG:  Y Neg Limit 1]
[MSG:DBG: Homing limited Y]
[MSG:DBG: Homing nextPhase Pulloff0]
[MSG:DBG: Starting from 0.000,43.975,0.000]
[MSG:DBG: Planned move to 0.000,39.975,0.000 @ 1500.000]
[MSG:DBG:  Y Neg Limit 0]
[MSG:DBG: CycleStop Pulloff0]
[MSG:DBG: Homing nextPhase SlowApproach]
[MSG:DBG: Starting from 0.000,39.975,0.000]
[MSG:DBG: Planned move to 0.000,44.375,0.000 @ 1500.000]
[MSG:DBG:  Y Neg Limit 1]
[MSG:DBG: Homing limited Y]
[MSG:DBG: Homing nextPhase Pulloff1]
[MSG:DBG: Starting from 0.000,43.850,0.000]
[MSG:DBG: Planned move to 0.000,39.850,0.000 @ 1500.000]
[MSG:DBG:  Y Neg Limit 0]
[MSG:DBG: CycleStop Pulloff1]
[MSG:DBG: Homing nextPhase Pulloff2]
[MSG:DBG: mpos was 0.000,39.850,0.000]
[MSG:DBG: mpos becomes 0.000,304.000,0.000]
[MSG:DBG: mpos transformed 0.000,304.000,0.000]
[MSG:DBG: Homing Cycle X]
[MSG:DBG: Homing nextPhase FastApproach]
[MSG:DBG: Starting from 0.000,304.000,0.000]
[MSG:DBG: Planned move to -671.000,304.000,0.000 @ 3000.000]
[MSG:DBG:  X Neg Limit 1]
[MSG:DBG: Homing limited X]
[MSG:DBG: Homing nextPhase Pulloff0]
[MSG:DBG: Starting from -43.765,304.000,0.000]
[MSG:DBG: Planned move to -39.765,304.000,0.000 @ 1500.000]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG: CycleStop Pulloff0]
[MSG:DBG: Homing nextPhase SlowApproach]
[MSG:DBG: Starting from -39.765,304.000,0.000]
[MSG:DBG: Planned move to -44.165,304.000,0.000 @ 1500.000]
[MSG:DBG:  X Neg Limit 1]
[MSG:DBG: Homing limited X]
[MSG:DBG: Homing nextPhase Pulloff1]
[MSG:DBG: Starting from -43.681,304.000,0.000]
[MSG:DBG: Planned move to -39.681,304.000,0.000 @ 1500.000]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG: CycleStop Pulloff1]
[MSG:DBG: Homing nextPhase Pulloff2]
[MSG:DBG: mpos was -39.681,304.000,0.000]
[MSG:DBG: mpos becomes 1.000,304.000,0.000]
[MSG:DBG: mpos transformed 1.008,304.000,0.000]
[MSG:DBG: Homing done]

Homing worked fine with the same config and wiring on the older release.

I really thought I was doing something wrong and thats still possible but all my validation is checking out.
