### ISSUE TITLE
Problem: Unknown pin prefix when firmware > 3.7.0

### ISSUE THREAD

**Issue by srgkasuro** [bdring/FluidNC#1060]
### Wiki Search Terms

my config worked fine with firmware 3.7.0
I did an update to 3.7.9. because I fond a bug with G-Code parsing an wanted to see if it is already fixed.
but my old Config-file stopped working with multiple errors like:

[MSG:ERR: Unknown prefix:gpio:13:low]
[MSG:ERR: Setting up pin: gpio:13:low failed:Unknown pin prefix]
[MSG:ERR: Unknown prefix:gpio:25]
[MSG:ERR: Setting up pin: gpio:25 failed:Unknown pin prefix]

I tried different Firmwares down to 3.7.4 with no luck.

back to 3.7.0 it is working fine.

### Controller Board

6-pack

### Machine Description

Router with external Stepper drivers

### Configuration file

```yaml
board: 6 Pack
name: 6 Pack External XYZ Haunyang
stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 800
    max_rate_mm_per_min: 4500.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 480.000
    soft_limits: false

    homing:
      cycle: 2
      positive_direction: true
      allow_single_axis: true
      mpos_mm: 114.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio:13:low
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 4500.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 100.000
    soft_limits: false

    homing:
      cycle: 1
      positive_direction: true
      allow_single_axis: true
      mpos_mm: 100.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio:25
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7

  a:
    steps_per_mm: 800
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 550.000
    soft_limits: false

    homing:
      cycle: 3
      positive_direction: false
      allow_single_axis: true
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio:14
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8

  c:
    steps_per_mm: 800
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false

    homing:
      cycle: -1
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.18
        direction_pin: I2SO.17
        disable_pin: I2SO.16

  b:
    steps_per_mm: 800
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 43.000
    soft_limits: false

    homing:  
      cycle: 3
      positive_direction: true
      allow_single_axis: true
      mpos_mm: 40.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio:15
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15

  y:
    steps_per_mm: 453
    max_rate_mm_per_min: 4000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false

    homing:
      cycle: 4
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio:36
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 0.000
      standard_stepper:
        step_pin: I2SO.21
        direction_pin: I2SO.20
        disable_pin: I2SO.23


i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.2
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

parking:
  enable: false
  axis: Z
  pullout_distance_mm: 5.000
  pullout_rate_mm_per_min: 250.000
  target_mpos_mm: -5.000
  rate_mm_per_min: 800.000

coolant:
  flood_pin: I2SO.24
  mist_pin: NO_PIN
  delay_ms: 0

probe:
  pin: NO_PIN
  check_mode_start: true

relay:
  direction_pin: NO_PIN
  output_pin: I2SO.25
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 1000
  spindown_ms: 100
  tool_num: 0
  speed_map: 0=0.000% 0=100.000% 1=100.000%
  off_on_alarm: true

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

uart1:
  rts_pin: NO_PIN
  txd_pin: gpio.33
  rxd_pin: gpio.32
  baud: 115200
  mode: 8N1

uart_channel1:
   uart_num: 1

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: gpio.26
  digital1_pin: gpio.4
  digital2_pin: gpio.16
  digital3_pin: gpio.27

start:
  must_home: false
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.7.4]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:DBG: Spiffs mount failed: ESP_FAIL]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:6_pack_drehfraese_4.yaml]
[MSG:ERR: Unknown prefix:gpio:13:low]
[MSG:ERR: Setting up pin: gpio:13:low failed:Unknown pin prefix]
[MSG:ERR: Unknown prefix:gpio:25]
[MSG:ERR: Setting up pin: gpio:25 failed:Unknown pin prefix]
[MSG:ERR: Unknown prefix:gpio:14]
[MSG:ERR: Setting up pin: gpio:14 failed:Unknown pin prefix]
[MSG:ERR: Unknown prefix:gpio:15]
[MSG:ERR: Setting up pin: gpio:15 failed:Unknown pin prefix]
[MSG:ERR: Unknown prefix:gpio:36]
[MSG:ERR: Setting up pin: gpio:36 failed:Unknown pin prefix]
[MSG:WARN: pulloff_mm value 0.000 constrained to range (0.100,100000.000)]
[MSG:INFO: Using default speed map]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine 6 Pack External XYZ Haunyang]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: UART1 Tx:gpio.33 Rx:gpio.32 RTS:NO_PIN Baud:115200]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: User Digital Output:0 on Pin:gpio.26]
[MSG:INFO: User Digital Output:1 on Pin:gpio.4]
[MSG:INFO: User Digital Output:2 on Pin:gpio.16]
[MSG:INFO: User Digital Output:3 on Pin:gpio.27]
[MSG:INFO: Axis count 6]
[MSG:INFO: Axis X (-366.000,114.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.1 Disable:I2SO.0]
[MSG:INFO:  X Pos Limit ERROR_PIN (for gpio:13:low)]
[MSG:ERR: Cannot set mode on pin gpio:13:low. The config is incorrect.]
[MSG:ERR: Critical error in main_init: Requested pin ERROR_PIN (for gpio:13:low) does not have the expected behavior.]
[MSG:INFO: Connecting to STA SSID:SPEED]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.101.195]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:DBG: 6_pack_drehfraese_3.yaml hash "E47B1C64C1F6F41F4D79FC1F01EF10C4D0D9C2035E3BB41491B0ABA8441B1A6F"]
[MSG:DBG: 6_pack_drehfraese_4.yaml hash "B015F18AA5AEA9CEFB9E33F005285867512EFCA8BEF26DFD1D97BBCC0E1DD61B"]
[MSG:DBG: CNC_All_Axes_TEST.nc hash "34C624C442BCB486FE4A364168F4EA253FE659860627D0A86C5FCA2B25840120"]
[MSG:DBG: Stabwechsel.nc hash "68A88D6CDBA4FCA63D329D3AFEC88C6EB61983532B087E7F50B944145BB6E59F"]
[MSG:DBG: Test1.nc hash "5418B03ED833D36CA71176A9FD7F8C55607D68CAED48F12AE347403AAF1276EB"]
[MSG:DBG: Test2.nc hash "8D9F5A68C676CD02C0BF98AB785FFD8D09FCFFE88224132E5E70E7040755F60A"]
[MSG:DBG: favicon.ico hash "B8B2871A343CA0F9A7A130213226962AD2BE4DFD28D7D8B756C3557569CB876D"]
[MSG:DBG: index.html.gz hash "3B628023FBEBA2C44FCC0CD494849DE07F5D327C98AD70F5DF5B2CD374B0DD81"]
[MSG:DBG: labyrinth_v6_nF_mitSchleifen.nc hash "B57C4D26A7815FAD2E533C6D7A9FFA9AE624093BFC03518A2E6B20B615291CB1"]
[MSG:DBG: labyrinth_v6_neueFraese.nc hash "F496D7683F1C3A9FD34EE046530E95EED8A4DCB54DC316C55412DC9F177F1C87"]
[MSG:DBG: macrocfg.json hash "B2286D84128AA530EC8505E427D3B1B370332CE93AA8B240C428EB23B609E2FB"]
[MSG:DBG: preferences.json hash "27C4E23A5A808CBFCC12CBD3B06F7701C486CFDDA7A0A59B823E1A8166A122C9"]
[MSG:DBG: schleifen.nc hash "EE2141634A559B30A7569EA5442D21CFAB143CBA187E235EE70F743B1ACFD831"]
[MSG:INFO: Telnet started on port 23]
ok
```

### User Interface Software

WebUI

### What happened?

I did a firmwareupdate OTA:
uploaded firmware.bin over Web-Interface
uploaded index.html.gz

restart and the Pins did not work anymore
