### ISSUE TITLE
No Movement

### ISSUE THREAD

**Issue by kuito** [bdring/FluidNC#1075]
### Wiki Search Terms

motors not moving
faq motors not moving
wiring correctly motors not moving

### Controller Board

https://amzn.to/3uS7FIF -- i realize you guys do not like these types of boards, but I have gotten it to work with other firmware so I know the board isn't it.. plus i've thoroughly tested all three boards

### Machine Description

I am using an X-Carve Pro as the actual machine (4ftx4ft--XYYZ), but I am using the above esp32, dev board, dm542t (drivers), and nema32 motors, XYYZ.  48v power supply powering only the drivers/motors, and the esp32 is being powered via usb-c. 

I don't have photos right this second but I can definitely get some if need be.

### Configuration file

```yaml
board: ESP32 TERM ADAPTER
name: GRFN_PRJX_ESP32_TERM_ADTR_XYYZ-PWM-neu
meta: Customized Config
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 10
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.17:low
  x:
    steps_per_mm: 42.353
    max_rate_mm_per_min: 7620.000
    acceleration_mm_per_sec2: 250.000
    max_travel_mm: 1219.000
    soft_limits: false
    homing:
      cycle: 2
      feed_mm_per_min: 25.000
      seek_mm_per_min: 750.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: gpio.12
        direction_pin: gpio.14

  y:
    steps_per_mm: 42.353
    max_rate_mm_per_min: 7620.000
    acceleration_mm_per_sec2: 350.000
    max_travel_mm: 1219.000
    soft_limits: false
    homing:
      cycle: 2
      feed_mm_per_min: 25.000
      seek_mm_per_min: 750.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.34
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: gpio.27
        direction_pin: gpio.26

    motor1:
      limit_neg_pin: gpio.36
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: gpio.33
        direction_pin: gpio.32

  z:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 300.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 50.000
    soft_limits: false
    homing:
      cycle: 1
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.39
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: gpio.15
        direction_pin: gpio.2

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

# sdcard:
#   card_detect_pin: NO_PIN
#   cs_pin: gpio.5

# probe:
#   pin: gpio.22:low
#   check_mode_start: true

control:
  safety_door_pin: NO_PIN
  reset_pin: 
  feed_hold_pin: 
  cycle_start_pin:
  estop_pin:

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

start:
  must_home: false

coolant:
  mist_pin: gpio.21
  delay_ms: 0

PWM:
  pwm_hz: 5000
  output_pin: gpio.25
  enable_pin: gpio.13
  direction_pin: gpio.4
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 30000
  spindown_ms: 10000
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%
```

### Startup Messages

```text
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4

[MSG:INFO: FluidNC 3.7.10 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:esp32_term_adapter_xyyz-neu.yml]
[MSG:INFO: Machine GRFN_PRJX_ESP32_TERM_ADTR_XYYZ-PWM-neu]
[MSG:INFO: Board ESP32 TERM ADAPTER]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: Stepping:RMT Pulse:10us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.17:low]
[MSG:INFO: Axis X (-1219.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.12 Dir:gpio.14 Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.35]
[MSG:INFO: Axis Y (-1219.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.27 Dir:gpio.26 Disable:NO_PIN]
[MSG:INFO:  Y Neg Limit gpio.34]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:gpio.33 Dir:gpio.32 Disable:NO_PIN]
[MSG:INFO:  Y2 Neg Limit gpio.36]
[MSG:INFO: Axis Z (-50.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.15 Dir:gpio.2 Disable:NO_PIN]
[MSG:INFO:  Z Neg Limit gpio.39]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: PWM Spindle Ena:gpio.13 Out:gpio.25 Dir:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle PWM]
[MSG:INFO: Mist coolant gpio.21]
[MSG:INFO: Connecting to STA SSID:icee]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.1.189]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC 3.7.10 (wifi) '$' for help]
```

### User Interface Software

FluidTerm, WebUI

### What happened?

I have it rigged up for only 1 motor (x/motor0)
- I plug the esp32 on
- power on the power supply
- all the lights look good
- and then I run FluidTerm
- select 2 to connect via the usb/serial
- I see/read the Start Messages which look find to me.  
- Then I try:  $md (which locks the motors) 
- Then $me (which allows you to move the motor with your fingers)
- Then I attempt X10 or X-10
- I then take a multimeter to see if the dir pin changes based on X10 vs X-10 which it does.

I've re-wired, I've tested continuity to make sure the wires are ok and connected.

I have then loaded grbl on a separate card and swap the wires for the same motor, connect this card, and then use OB CONTROL to connect and am able to do X10 without an issue.

Again, I have tried the exact setup except with different firmware and with an arduino uno with old school grbl and everything works as expected.

### GCode File

NA

### Other Information

I've done so much troubleshooting, and have really tried to figure this out on my own, but it is quite disheartening with how much time i've spent and then throw together basic grbl and it works np.  So I am probably missing something somewhere, and I am hoping you guys can help me out, but if you are too busy, no worries.

Ultimately, I would love to do a youtube video on switching the X-Carve Pro from their proprietary mega uno with built in drivers to a controller->drivers->motors system preferably with fluidnc cuz I want to be able to add a lot more to this machine eventually.

Thank you.
