### ISSUE TITLE
Problem: Turning on the motors when loading. What for? 

### ISSUE THREAD

**Issue by AlexMoiseevs** [bdring/FluidNC#1079]
### Wiki Search Terms

I searched everywhere

### Controller Board

6-pack

### Machine Description

test 

### Configuration file

```yaml
board: 6 Pack
name: 6 Pack OLED
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

i2c0:
   sda_pin: gpio.14
   scl_pin: gpio.13
        
oled:
   i2c_num: 0
   i2c_address: 60
   width: 128
   height: 64
   radio_delay_ms: 1000

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

axes:
  shared_stepper_disable_pin: gpio.16:low
  x:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 500.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: i2so.0
        direction_pin: i2so.1
        

  y:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 500.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: i2so.2
        direction_pin: i2so.3:low

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: i2so.4
        direction_pin: i2so.5

  z:
    motor0:
      null_motor:
```

### Startup Messages

```text
OK
```

### What happened?

I2S_STATIC configuration, if you put shared_stepper_isable_pin on the contrary, then the download goes well. but the motors do not work accordingly. if shared_stepper_disable_pin is correct, then there is a wild overcurrent when loading . how can this be avoided?
