### ISSUE TITLE
Problem: with configurations in ultimate bee, updated to FluidNC, only one y axis moter working 

### ISSUE THREAD

**Issue by Bigrigins** [bdring/FluidNC#1086]
### Wiki Search Terms

axis, homing, spindle, gpio , config yaml  

### Controller Board

Spark Concepts CNC XPRO V5

### Machine Description

 Bulkman 3D  1500x1500 Ultimate Bee , Duel y machine , soft limit switch's on Y+ ,X+, and Z+ Huanyang VFD and 2.2 kW water cooled spindle. high torque NEMA 23 stepper moters. XPRO V5 controller

### Input Circuits

```yaml
set pins up to what was recommended on FluidNC Wikipage
```

### Configuration file

```yaml
board: tmc_5160_xpro v5
name: ULTIMATE BEE
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 2
  dir_delay_us: 0
  disable_delay_us: 0


axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 400.00
    max_rate_mm_per_min: 300.00
    acceleration_mm_per_sec2: 100.00
    max_travel_mm: 1240.00
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1500.00
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.00
      tmc_5160:
        cs_pin: gpio.17
        spi_index: 1
        r_sense_ohms: 0.075
        run_amps: 2.5
        hold_amps: 0.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: true
        step_pin: gpio.12
        direction_pin: gpio.14
        tpfd: 4
       

  y:
    steps_per_mm: 400.00
    max_rate_mm_per_min: 300.00
    acceleration_mm_per_sec2: 100.00
    max_travel_mm: 1240.00
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1500.00
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor1:
      limit_neg_pin: gpio.34
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.00
      tmc_5160:
        cs_pin: NO_PIN
        spi_index: 2
        r_sense_ohms: 0.075
        run_amps: 2.5
        hold_amps: 0.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: true
        step_pin: gpio.27
        direction_pin: gpio.26
        tpfd: 4
       

        motor0: A/Y2
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.00
      tmc_5160:
        cs_pin: NO_PIN
        spi_index: 4
        r_sense_ohms: 0.075
        run_amps: 2.5
        hold_amps: 0.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: true
        step_pin: gpio.33
        direction_pin: gpio.32
        tpfd: 4
       

  z:
    steps_per_mm: 400.00
    max_rate_mm_per_min: 300.00
    acceleration_mm_per_sec2: 100.00
    max_travel_mm: 160.00
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1500.00
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.39
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.00
      tmc_5160:
        cs_pin: NO_PIN
        spi_index: 3
        r_sense_ohms: 0.075
        run_amps: 2.5
        hold_amps: 0.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: true
        step_pin: gpio.15
        direction_pin: gpio.2
        tpfd: 4
       


spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: gpio.16: low
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.13: low
  macro1_pin: gpio.0: low
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

probe:
  pin: gpio.22: low
  check_mode_start: false

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: true
 
uart1:
  txd_pin: gpio.4
  rxd_pin: gpio.25
  rts_pin: NO_PIN
  baud: 115200
  mode: 8N1

  coolant:
    mist_pin: gpio.21
    delay_ms: 0  

    PWM:
  pwm_hz: 5000
  output_pin: gpio.25
  enable_pin: gpio.4
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 24000
  spindown_ms: 6000
  tool_num: 0
  speed_map: 0=0.000% 24000=100.000%



### Startup###

```text
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4

[MSG:INFO: FluidNC 3.7.10 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:Ultimatebee.yaml]
[MSG:WARN: Ignored key motor0]
[MSG:WARN: Ignored key coolant]
[MSG:ERR: Skipping key mist_pin indent 4 this indent 2]
[MSG:ERR: Skipping key delay_ms indent 4 this indent 2]
[MSG:ERR: Skipping key PWM indent 4 this indent 2]
[MSG:WARN: Ignored key pwm_hz]
[MSG:WARN: Ignored key output_pin]
[MSG:WARN: Ignored key enable_pin]
[MSG:WARN: Ignored key direction_pin]
[MSG:WARN: Ignored key disable_with_s0]
[MSG:WARN: Ignored key s0_with_disable]
[MSG:WARN: Ignored key spinup_ms]
[MSG:WARN: Ignored key spindown_ms]
[MSG:WARN: Ignored key tool_num]
[MSG:WARN: Ignored key speed_map]
[MSG:INFO: Machine ULTIMATE BEE ]
[MSG:INFO: Board tmc_5160_xpro v5]
[MSG:INFO: UART1 Tx:gpio.4 Rx:gpio.25 RTS:NO_PIN Baud:115200]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-1090.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:gpio.12 Dir:gpio.14 CS:gpio.17 Disable:NO_PIN Index:1 R:0.075]
[MSG:INFO:  X Neg Limit gpio.35]
[MSG:INFO: Axis Y (-1090.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:   Motor1]
[MSG:INFO:     tmc_5160 Step:gpio.33 Dir:gpio.32 CS:NO_PIN Disable:NO_PIN Index:4 R:0.075]
[MSG:INFO: Axis Z (-10.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:gpio.15 Dir:gpio.2 CS:NO_PIN Disable:NO_PIN Index:3 R:0.075]
[MSG:INFO:  Z Neg Limit gpio.39]
[MSG:INFO: X Axis driver test passed]
[MSG:INFO: Y2 Axis driver test passed]
[MSG:INFO: Z Axis driver test passed]
[MSG:INFO: safety_door_pin gpio.16:low]
[MSG:INFO: macro0_pin gpio.13:low]
[MSG:INFO: macro1_pin gpio.0:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Probe Pin: gpio.22:low]
[MSG:INFO: BT Started with FluidNC]

Grbl 3.7 [FluidNC 3.7.10 (bt) '$' for help]
[MSG:INFO: ALARM: Unhomed]
ALARM:14
```

### What happened?

Bought this machine in December of 2022 worked on the machine when I had free time throughout the year had it all put together in May started to configure the XPRO V5 software (not FluidNC) had everything configured was ready to surface the spoil board sent everything home and that's when it started binding again.  Apparently i didn't have it  all worked out.  YA2 worked as it should, along with x and z. When Y would move it would shutter. Then Y moter would just stop completely ,  YA2 would continue moving causing the Gantry to bind,  forcing me to hit E stop. I would have to realign everything and try again,   even trying to jog would shutter and bind. Problem was it was intermitting,  sometimes it would work sometimes it wouldn't which led me to believe that it was a bad drive. So was able to get in contact with spark Concepts they sent me a new controller out back in  November, the new controller of course was loaded with the new FluidNC.  So after researching and studying I started to try and configure FluidNC,  so this is where I'm at.  It seems to be the same issue that I was having with the old software  in XPro V5. I should also mention that I put a new stepper motor on thinking possibly that the motor was bad , it wasn't, new motor is still having the same issue. The only other thing I haven't done is run new wire,  the new wire will be here today. I can't possibly imagine that I have a bad driver in a brand new controller, what are the odds lol. So any help would be greatly appreciated , any ideas,  things I can try. I'm at a loss like I said I've had this thing for almost a year I'm getting very  frustrated, want to be able to start using this thing and start making some chips!! thanks again for any advice or help.

**Comment by bdring** [comment]
Your indentation is off in many places.

Look at motor0 under Y. It should have the indentation level as the other motors.

Also, it is best to have motor0 defined before motor1. Also motor0 has A/Y2 after it, You cannot do that. If you want a comment follow the [comment rules](http://wiki.fluidnc.com/en/config/overview#file-specifications).

Your spindle indentation is also off. The PWM should not be indented and the sub items should.

Try using a [free yaml file editor](http://wiki.fluidnc.com/en/support/troubleshooting_config_files#editing-the-file). It can help you spot errors and will visually format the file.

You might not get it right the first time, but the startup messages will give you some clues. Do not try using the machine until the startup messages are free from errors and warning.

**Comment by Bigrigins** [comment]
> Your indentation is off in many places.
> 
> Look at motor0 under Y. It should have the indentation level as the other motors.
> 
> Also, it is best to have motor0 defined before motor1. Also motor0 has A/Y2 after it, You cannot do that. If you want a comment follow the [comment rules](http://wiki.fluidnc.com/en/config/overview#file-specifications).
> 
> Your spindle indentation is also off. The PWM should not be indented and the sub items should.
> 
> Try using a [free yaml file editor](http://wiki.fluidnc.com/en/support/troubleshooting_config_files#editing-the-file). It can help you spot errors and will visually format the file.
> 
> You might not get it right the first time, but the startup messages will give you some clues. Do not try using the machine until the startup messages are free from errors and warning.

I understand everything you said and I will correct everything thst you suggested when I get home in front of my machine laptop, but I'm not understanding what you mean by indentation.  could you elaborate? I looked at the different Motors and they all seem to be the same other than your gpio pins Direction pins etc etc I'm confused on the indentation or what I'm looking for.

**Comment by bdring** [comment]
![image](https://github.com/bdring/FluidNC/assets/189677/2856855a-84ba-4882-be2f-61feac828be9)

**Comment by Bigrigins** [comment]
> ![image](https://private-user-images.githubusercontent.com/189677/290229767-2856855a-84ba-4882-be2f-61feac828be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Nzk0MTcsIm5iZiI6MTcwMjQ3OTExNywicGF0aCI6Ii8xODk2NzcvMjkwMjI5NzY3LTI4NTY4NTVhLTg0YmEtNDg4Mi1iZTJmLTYxZmVhYzgyOGJlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNDUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzg4ODQxZDY3NDdkNGMzOGYwM2IwOGFlODQ2NDFjNzg2ZjZiODRlMzA0OWY5NWYzZWU4NzEyMjRhYzFmYWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gBvMXcxHZFcLXjQ-lnVEfFLsLz_Te6T1FM9pJ-Jk0uA)

Yeah I see that and plan  to correct that when I get in front of my computer. Please excuse my ignorance but that is a indentation that your referring to?

**Comment by Bigrigins** [comment]
> > ![image](https://private-user-images.githubusercontent.com/189677/290229767-2856855a-84ba-4882-be2f-61feac828be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Nzk0MTcsIm5iZiI6MTcwMjQ3OTExNywicGF0aCI6Ii8xODk2NzcvMjkwMjI5NzY3LTI4NTY4NTVhLTg0YmEtNDg4Mi1iZTJmLTYxZmVhYzgyOGJlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNDUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzg4ODQxZDY3NDdkNGMzOGYwM2IwOGFlODQ2NDFjNzg2ZjZiODRlMzA0OWY5NWYzZWU4NzEyMjRhYzFmYWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gBvMXcxHZFcLXjQ-lnVEfFLsLz_Te6T1FM9pJ-Jk0uA)
> 
> Yeah I see that and plan to correct that when I get in front of my computer. Please excuse my ignorance but that is a indentation that your referring to?

**Comment by bdring** [comment]
Yes, YAML is a hierarchy.  Things like  `limit_neg_pin:` belong to a specific motor. The file tells describes that using indenting.

Motor0 has to be indented at the exact place so we know what axis letter it belongs to. The stuff the belongs to motor0 have to be indented under motor0.

Right now it looks like motor0 is indented under tmc_5160 and FluidNC is rejecting that.

Please consider donating to this project.

**Comment by Bigrigins** [comment]
> Yes, YAML is a hierarchy. Things like `limit_neg_pin:` belong to a specific motor. The file tells describes that using indenting.
> 
> Motor0 has to be indented at the exact place so we know what axis letter it belongs to. The stuff the belongs to motor0 have to be indented under motor0.
> 
> Right now it looks like motor0 is indented under tmc_5160 and FluidNC is rejecting that.
> 
> Please consider donating to this project.

I will for sure donate after I figure this out 👍, see that's the problem motor 0 A/Y2 is the only moter working on that axis, the other moter is the one not working , motor one is not working that's what I'm trying to achieve. I appreciate all your help this far.

**Comment by Bigrigins** [comment]
> Yes, YAML is a hierarchy. Things like `limit_neg_pin:` belong to a specific motor. The file tells describes that using indenting.
> 
> Motor0 has to be indented at the exact place so we know what axis letter it belongs to. The stuff the belongs to motor0 have to be indented under motor0.
> 
> Right now it looks like motor0 is indented under tmc_5160 and FluidNC is rejecting that.
> 
> Please consider donating to this project.

Donated to your cause 👍

So what do you suggest that I put in there? how do you suggest a fix other than changing 0 and 1?

**Comment by MitchBradley** [comment]
Fix the indentation by making sure that each section name is preceded by the correct number of spaces.

For the motors that work, the "    motorN" section name is preceded by 4 spaces and no junk after it.  The bad line is the "        motor0: A/Y2" line that starts with 8 spaces and has extra junk after it (the junk being "A/Y2"

Fix that and the motors will probably work.

You will also need to fix the mis-indented coolant and PWM sections.  You have them as
```
  coolant:
    mist_pin: gpio.21
    delay_ms: 0  

    PWM:
```
but they should be
```
coolant:
  mist_pin: gpio.21
  delay_ms: 0  

PWM:
```
In other words, "coolant:" and "PWM" should both be at the left margin, with no preceding spaces.

**Comment by bdring** [comment]
I tried cleaning up your file, but you have a lot of reused pins. I just removed those uses. You will have to add missing features back after you spend some time on the wiki.

Try this. I don't know that controller, so some motors like Y0 and Y1 might be reversed. Just change the wiring. You might contact the seller for additional help.

```yaml
board: tmc_5160_xpro v5
name: ULTIMATE BEE
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 2
  dir_delay_us: 0
  disable_delay_us: 0


axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 400.00
    max_rate_mm_per_min: 300.00
    acceleration_mm_per_sec2: 100.00
    max_travel_mm: 1240.00
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1500.00
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.00
      tmc_5160:
        cs_pin: gpio.17
        spi_index: 1
        r_sense_ohms: 0.075
        run_amps: 2.5
        hold_amps: 0.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: true
        step_pin: gpio.12
        direction_pin: gpio.14
        tpfd: 4
       

  y:
    steps_per_mm: 400.00
    max_rate_mm_per_min: 300.00
    acceleration_mm_per_sec2: 100.00
    max_travel_mm: 1240.00
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1500.00
      seek_scaler: 1.100
      feed_scaler: 1.100
      
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.00
      tmc_5160:
        cs_pin: NO_PIN
        spi_index: 4
        r_sense_ohms: 0.075
        run_amps: 2.5
        hold_amps: 0.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: true
        step_pin: gpio.33
        direction_pin: gpio.32
        tpfd: 4
       

    motor1:
      limit_neg_pin: gpio.34
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.00
      tmc_5160:
        cs_pin: NO_PIN
        spi_index: 2
        r_sense_ohms: 0.075
        run_amps: 2.5
        hold_amps: 0.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: true
        step_pin: gpio.27
        direction_pin: gpio.26
        tpfd: 4
       
  z:
    steps_per_mm: 400.00
    max_rate_mm_per_min: 300.00
    acceleration_mm_per_sec2: 100.00
    max_travel_mm: 160.00
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1500.00
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.39
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.00
      tmc_5160:
        cs_pin: NO_PIN
        spi_index: 3
        r_sense_ohms: 0.075
        run_amps: 2.5
        hold_amps: 0.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: true
        step_pin: gpio.15
        direction_pin: gpio.2
        tpfd: 4

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5


macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: true

coolant:
  mist_pin: gpio.21
  delay_ms: 0  

PWM:
  pwm_hz: 5000
  output_pin: gpio.25
  enable_pin: gpio.4
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 24000
  spindown_ms: 6000
  tool_num: 0
  speed_map: 0=0.000% 24000=100.000%
```
