### ISSUE TITLE
Problem: Motors are not locked when make home - 3.7.11

### ISSUE THREAD

**Issue by ahmetbozaci** [bdring/FluidNC#1089]
### Wiki Search Terms

NA

### Controller Board

MKS DLC 32

### Machine Description

nema17, tmc2209, dual y motors, with end stops

### Configuration file

```yaml
board: MKS-DLC32 V2.1
name: XProCraft
meta: 25-11-2023

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 6
  dir_delay_us: 10
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 720
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36:low
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2:low

  y:
    steps_per_mm: 80
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 900
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35:low
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6:high
i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  cs_pin: gpio.15
  card_detect_pin: gpio.39

Laser:
  pwm_hz: 5000
  output_pin: gpio.32
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: false
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
```

### Startup Messages

```text
NA
```

### What happened?

Typically, I go through the process of homing my setup, during which the motors are expected to lock as intended. However, in version 3.7.11, I've encountered an issue where the motors remain unlocked after homing. without homing and not locked motors, I am getting an error on the Lightburn as expected. To address this, I've resorted to using the command $X to unlock, moving the axis, at which point the motors finally lock, allowing me to proceed with the homing process.
It is no problem in the 3.7.9 version.
