### ISSUE TITLE
Z Height Changes During Program

### ISSUE THREAD

**Issue by avivgil** [bdring/FluidNC#1093]
### Wiki Search Terms

z-height, TLO

### Controller Board

custom esp32 board with 74AHCT125's for driving 4 DM556 stepper drivers

### Machine Description

Cindymill

### Configuration file

```yaml
start:
  must_home: false
  deactivate_parking: true
axes:
  shared_stepper_disable_pin: gpio.23
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 3000
    acceleration_mm_per_sec2: 50
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.15
      limit_pos_pin: NO_PIN
      pulloff_mm: 2
      standard_stepper:
        step_pin: gpio.18
        direction_pin: gpio.4:low
        disable_pin: NO_PIN
    homing:
      cycle: 2
      positive_direction: false
      allow_single_axis: true
      seek_mm_per_min: 1000
      feed_mm_per_min: 25
  y:
    steps_per_mm: 80
    max_rate_mm_per_min: 3000
    acceleration_mm_per_sec2: 50
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.5
      hard_limits: false
      pulloff_mm: 2
      standard_stepper:
        step_pin: gpio.21
        direction_pin: gpio.22
        disable_pin: NO_PIN
    motor1:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.13
      hard_limits: false
      pulloff_mm: 1.7
      standard_stepper:
        step_pin: gpio.27
        direction_pin: gpio.26
        disable_pin: NO_PIN
    homing:
      cycle: 2
      positive_direction: true
      allow_single_axis: true
      seek_mm_per_min: 500
      feed_mm_per_min: 25
  z:
    steps_per_mm: 100
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 25
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.17
      hard_limits: false
      pulloff_mm: 2
      standard_stepper:
        step_pin: gpio.19
        direction_pin: gpio.16
        disable_pin: NO_PIN
    homing:
      cycle: 1
      positive_direction: true
      allow_single_axis: true
      seek_mm_per_min: 500
      feed_mm_per_min: 25
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
probe:
  pin: gpio.32:low
  toolsetter_pin: NO_PIN
  check_mode_start: true
```

### Startup Messages

```text
> $SS
[MSG:INFO: FluidNC v3.7.11 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine New configuration]
[MSG:INFO: Board None]
[MSG:DBG: SPI not defined]
[MSG:DBG: See http://wiki.fluidnc.com/en/config/sd_card#sdfallbackcs-access-sd-without-a-config-file]
[MSG:INFO: Stepping:RMT Pulse:10us Dsbl Delay:10us Dir Delay:10us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.23]
[MSG:INFO: Axis X (0.000,1000.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.18 Dir:gpio.4:low Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.15]
[MSG:DBG:  X Neg Limit 0]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.21 Dir:gpio.22 Disable:NO_PIN]
[MSG:INFO:  Y Pos Limit gpio.5]
[MSG:DBG:  Y Pos Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:gpio.27 Dir:gpio.26 Disable:NO_PIN]
[MSG:INFO:  Y2 Pos Limit gpio.13]
[MSG:DBG:  Y2 Pos Limit 0]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.19 Dir:gpio.16 Disable:NO_PIN]
[MSG:INFO:  Z Pos Limit gpio.17]
[MSG:DBG:  Z Pos Limit 0]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Probe Pin: gpio.32:low]
[MSG:INFO: Connecting to STA SSID:Media]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.1.214]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:DBG: config.yaml hash "7A3170FC0F3A95B18FBF6814DBE92B6BF05593EAD1F119A2B5ADF22F8F07B3D6"]
[MSG:DBG: index.html.gz hash "3B628023FBEBA2C44FCC0CD494849DE07F5D327C98AD70F5DF5B2CD374B0DD81"]
[MSG:INFO: Telnet started on port 23]
ok
```

### What happened?

This issue driving me insane, I've been using the exact same setup for many months with great success. This issue started a few weeks ago and I've been unable to get around it since. I use Fusion to to create GCODE, and my Z height changes (physically changes) when moving between different geometries in the program. Needless to say, when I jog on all 3 axis, using a dial indicator - all movements are accurate and correct work coordinates are maintained. Drilling operations, oddly, also complete successfully - [here's an example of](https://drive.google.com/file/d/1t9tIcU5XP1DHNc0jiw0Y-3rmjKB5ybbM/view) a 4 hole drill, with the following GCODE:

```
G90 G94 G17
G21

G54
G0 X216 Y-380
M3 S18000
G4 P1.8
G0 X216 Y-380 Z2
Z1
G1 X216 Y-380 Z-3 F889
G0 Z1
X208
G1 X208 Y-380 Z-3 F889
G0 Z1
X198
G1 X198 Y-380 Z-3 F889
G0 Z1
X190
G1 X190 Y-380 Z-3 F889
G0 Z1
Z2

M5
M30
```

On other operations, like a boring operation on the same holes as the drilling above, what happens is after I set the Z0 with my probe, the first hole is bored, and on the plunge / retract from that hole, the Z axis physically moves up further than the start point - while the reported coordinates do not reflect this. The end result is each hole in the operation is drilled about 1.3mm height than the previous hole, to the point where the tool doesn't even enter the material on later holes. 

[Here's an example of the issue ](https://drive.google.com/file/d/1vjK25UYSBsiyz-_a8491e0oBVUPDu4T0/view) - you can see a retract height of 2mm, but the Z axis is raised to 3mm after the first hole, then 4mm on the next, and etc - needless to say the coordinates reported by the machine do not reflect this, namely the machine thinks its operating normally while in reality the Z axis height is moving higher and higher. The GCODE for the above bore video:
```
G90 G94 G17
G21

G54
G0 X216 Y-380
M3 S18000
G4 P1.8
G0 X216 Y-380 Z4
Z0.683
G1 X216 Y-380 Z0 F1778
X215.969 Y-379.969
X215.938 Y-380
X215.967 Y-380.053 Z-0.194
X216.028 Y-380.056 Z-0.387
X216.062 Y-380.006 Z-0.581
X216.038 Y-379.951 Z-0.775
X215.978 Y-379.941 Z-0.969
X215.939 Y-379.987 Z-1.162
X215.957 Y-380.045 Z-1.356
X216.016 Y-380.06 Z-1.55
X216.06 Y-380.019 Z-1.744
X216.047 Y-379.959 Z-1.938
X215.99 Y-379.938 Z-2.131
X215.943 Y-379.975 Z-2.325
X215.949 Y-380.036 Z-2.519
X216.003 Y-380.062 Z-2.712
X216.055 Y-380.03 Z-2.906
X216.055 Y-379.97 Z-3.1
X216.001 Y-379.938
X215.946 Y-379.968
X215.945 Y-380.03
X215.999 Y-380.062
X216.054 Y-380.032
X216.055 Y-379.97
X216.012 Y-379.957
X216 Y-380
G0 Z2
X208
Z0.683
G1 X208 Y-380 Z0 F1778
X207.969 Y-379.969
X207.938 Y-380
X207.967 Y-380.053 Z-0.194
X208.028 Y-380.056 Z-0.387
X208.062 Y-380.006 Z-0.581
X208.038 Y-379.951 Z-0.775
X207.978 Y-379.941 Z-0.969
X207.939 Y-379.987 Z-1.162
X207.957 Y-380.045 Z-1.356
X208.016 Y-380.06 Z-1.55
X208.06 Y-380.019 Z-1.744
X208.047 Y-379.959 Z-1.938
X207.99 Y-379.938 Z-2.131
X207.943 Y-379.975 Z-2.325
X207.949 Y-380.036 Z-2.519
X208.003 Y-380.062 Z-2.712
X208.055 Y-380.03 Z-2.906
X208.055 Y-379.97 Z-3.1
X208.001 Y-379.938
X207.946 Y-379.968
X207.945 Y-380.03
X207.999 Y-380.062
X208.054 Y-380.032
X208.055 Y-379.97
X208.012 Y-379.957
X208 Y-380
G0 Z2
X198
Z0.683
G1 X198 Y-380 Z0 F1778
X197.969 Y-379.969
X197.938 Y-380
X197.967 Y-380.053 Z-0.194
X198.028 Y-380.056 Z-0.387
X198.062 Y-380.006 Z-0.581
X198.038 Y-379.951 Z-0.775
X197.978 Y-379.941 Z-0.969
X197.939 Y-379.987 Z-1.162
X197.957 Y-380.045 Z-1.356
X198.016 Y-380.06 Z-1.55
X198.06 Y-380.019 Z-1.744
X198.047 Y-379.959 Z-1.938
X197.99 Y-379.938 Z-2.131
X197.943 Y-379.975 Z-2.325
X197.949 Y-380.036 Z-2.519
X198.003 Y-380.062 Z-2.712
X198.055 Y-380.03 Z-2.906
X198.055 Y-379.97 Z-3.1
X198.001 Y-379.938
X197.946 Y-379.968
X197.945 Y-380.03
X197.999 Y-380.062
X198.054 Y-380.032
X198.055 Y-379.97
X198.012 Y-379.957
X198 Y-380
G0 Z2
X190
Z0.683
G1 X190 Y-380 Z0 F1778
X189.969 Y-379.969
X189.938 Y-380
X189.967 Y-380.053 Z-0.194
X190.028 Y-380.056 Z-0.387
X190.062 Y-380.006 Z-0.581
X190.038 Y-379.951 Z-0.775
X189.978 Y-379.941 Z-0.969
X189.939 Y-379.987 Z-1.162
X189.957 Y-380.045 Z-1.356
X190.016 Y-380.06 Z-1.55
X190.06 Y-380.019 Z-1.744
X190.047 Y-379.959 Z-1.938
X189.99 Y-379.938 Z-2.131
X189.943 Y-379.975 Z-2.325
X189.949 Y-380.036 Z-2.519
X190.003 Y-380.062 Z-2.712
X190.055 Y-380.03 Z-2.906
X190.055 Y-379.97 Z-3.1
X190.001 Y-379.938
X189.946 Y-379.968
X189.945 Y-380.03
X189.999 Y-380.062
X190.054 Y-380.032
X190.055 Y-379.97
X190.012 Y-379.957
X190 Y-380
G0 Z4

M5
M30

```

I can not see any evidence of steps being missing mechanically, everything is clean and no issues at all occur during jogs as stated, nor during the drill operation. Could this be an issue related to stepping config? Extremely odd if so since nothing has changed and this all worked perfectly until some random point in time a few weeks ago. How can I go about further debugging the stepping here? Thanks!
