### ISSUE TITLE
Problem: Custom XyyZ RMT setup problem

### ISSUE THREAD

**Issue by MarcinanProfesjonalista** [bdring/FluidNC#1102]
### Wiki Search Terms

Setup configuration problem for custom board

### Controller Board

Custom board 
Schematics
![Schematic_ESP32 CNC DIY Shield copy_2024-01-03](https://github.com/bdring/FluidNC/assets/49427297/e8447b46-3933-490c-be6b-01470ef03a04)
Testing setup
![20240103_170526](https://github.com/bdring/FluidNC/assets/49427297/eb148dd0-b376-4c00-89f2-d3101a71789d)

### Machine Description

XYYZ machine. Runned on basic HSS86 that need STEP, DIR, ENABLE, ALARM,( PENDING) singals. 

### Input Circuits

```yaml
I'm testing Output for X axis. Does ESP32 put any pulses on outputs.
```

### Configuration file

```yaml
board: Marcin_nowa
name: 4 External XYYZ
meta: 2024-01-01 Marcin
stepping:
  engine: RMT
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.13
  x:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.39
      limit_pos_pin: gpio.36
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: gpio.18
        direction_pin: gpio.5
        disable_pin: NO_PIN

  y:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 3
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: gpio.34
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: gpio.17
        direction_pin: gpio.16
        disable_pin: NO_PIN
    
    motor1:
      limit_neg_pin: gpio.32
      limit_pos_pin: gpio.33
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: gpio.4
        direction_pin: gpio.0
        disable_pin: NO_PIN

  z:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 150.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.27
      limit_pos_pin: gpio.25
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: gpio.2
        direction_pin: gpio.15
        disable_pin: NO_PIN

probe:
  pin: gpio.26
  check_mode_start: false
  
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.23
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  
        
i2so:
  bck_pin: NO_PIN
  data_pin: NO_PIN
  ws_pin: NO_PIN

spi:
  miso_pin: NO_PIN
  mosi_pin: NO_PIN
  sck_pin: NO_PIN

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: NO_PIN

start:
  must_home: false
```

### Startup Messages

```text
Grbl 3.7 [FluidNC v3.7.12 (wifi) '$' for help]
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4

[MSG:INFO: FluidNC v3.7.12 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:marcin_nowa.yaml]
[MSG:INFO: Machine 4 External XYYZ]
[MSG:INFO: Board Marcin_nowa]
[MSG:INFO: I2SO BCK:NO_PIN WS:NO_PIN DATA:NO_PIN]
[MSG:INFO: Not setting up I2SO: WS pin has incorrect capabilities]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13]
[MSG:INFO: Axis X (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.18 Dir:gpio.5 Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.39]
[MSG:INFO:  X Pos Limit gpio.36]
[MSG:INFO: Axis Y (0.000,300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.17 Dir:gpio.16 Disable:NO_PIN]
[MSG:INFO:  Y Neg Limit gpio.35]
[MSG:INFO:  Y Pos Limit gpio.34]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:gpio.4 Dir:gpio.0 Disable:NO_PIN]
[MSG:INFO:  Y2 Neg Limit gpio.32]
[MSG:INFO:  Y2 Pos Limit gpio.33]
[MSG:INFO: Axis Z (0.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.2 Dir:gpio.15 Disable:NO_PIN]
[MSG:INFO:  Z Neg Limit gpio.27]
[MSG:INFO:  Z Pos Limit gpio.25]
[MSG:INFO: feed_hold_pin gpio.23]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Probe Pin: gpio.26]
[MSG:INFO: Connecting to STA SSID:DEKARSKA5_LOKAL7]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 172.16.31.250]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC v3.7.12 (wifi) '$' for help]
ok
[VER:3.7 FluidNC v3.7.12:]
[OPT:PHS]
[MSG: Machine: 4 External XYYZ]
[MSG: Mode=STA:SSID=DEKARSKA5_LOKAL7:Status=Connected:IP=172.16.31.250:MAC=08-D1-F9-E7-15-9C]
ok

Grbl 3.7 [FluidNC v3.7.12 (wifi) '$' for help]
```

### What happened?

I'm upgrading from old ESP32 GRBL software to that FluidNC becouse it got beter safety functions. But It don't send any singals on outputs.
