### ISSUE TITLE
Problem: I am unsuccessfull with setting up 6-pack with external DM556T drivers

### ISSUE THREAD

**Issue by nicolas-lang** [bdring/FluidNC#1111]
### Wiki Search Terms

DM556t --> no result
External Stepper --> the wiki page is missing values for t3 and t4 variable used in the image
faq
Config file

### Controller Board

6-pack Controller purchased directly from Bart - the circuit board has the tag "V1p8"

### Machine Description

Gantry CNC XYYZ with external [DM556T drivers](https://www.omc-stepperonline.com/download/DM556T.pdf), X and Y are belt driven, Z is a trapezoidal spindle. The router is relais switched.
I have created a modified "Stepstick Board w. LED indicators" to use the ["Common 5V"](https://github.com/bdring/Grbl_Esp32/wiki/External-Stepper-Drivers) wiring for the DM556T. To implement this, I have used the [6 Pack Ext Drvs LEDs](https://oshwlab.com/bdring/6-pack-ext-drvs-leds) as a template, replaced GND with +5V and switched the LED polarity.
![image](https://github.com/bdring/FluidNC/assets/635895/25b5bada-4082-4767-a82e-84cd92455688)
![image](https://github.com/bdring/FluidNC/assets/635895/11b1191a-11d3-41b1-869f-2c3bb84e16b5)

### Input Circuits

```yaml
No inputs configured yet.
```

### Configuration file

```yaml
board: 6 Pack
name: 6 Pack Ext-DMT-556T XYYZ
meta: by Nicolas Lang
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 30
  dir_delay_us: 10
  disable_delay_us: 1000000

start:
  must_home: false
  deactivate_parking: false
  check_limits: false

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 66.423
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 844.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 3000.000
      settle_ms: 500
    motor0:
      limit_neg_pin: NO_PIN
      #gpio.02
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

  y:
    steps_per_mm: 33.396
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 1020.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 3000.000
      settle_ms: 500

    motor0:
      limit_neg_pin: NO_PIN
      #gpio.25
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.5:low
        direction_pin: I2SO.4:low
        disable_pin: I2SO.7:low
    motor1:
      limit_neg_pin: NO_PIN
      #gpio.39
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.10:low
        direction_pin: I2SO.9:low
        disable_pin: I2SO.8:low

  z:
    steps_per_mm: 266.666
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 100.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      #gpio.36
      limit_all_pin: NO_PIN
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.13:low
        direction_pin: I2SO.12:low
        disable_pin: I2SO.15:low

  # a:
  # steps_per_mm: 800.000
  # max_rate_mm_per_min: 5000.000
  # acceleration_mm_per_sec2: 100.000
  # max_travel_mm: 360.000
  # soft_limits: false
  # homing:
  # cycle: 3
  # positive_direction: true
  # mpos_mm: 150.000
  # feed_mm_per_min: 100.000
  # seek_mm_per_min: 800.000
  # settle_ms: 500
  # seek_scaler: 1.100
  # feed_scaler: 1.100

  # motor0:
  # limit_neg_pin: NO_PIN
  # limit_pos_pin: NO_PIN
  # limit_all_pin: NO_PIN
  # hard_limits: false
  # pulloff_mm: 3.000
  # standard_stepper:
  # step_pin: I2SO.13
  # direction_pin: I2SO.12
  # disable_pin: I2SO.15

#probe:
#  pin: gpio.34
#  check_mode_start: true
#probe2?:
#  pin: gpio.33
#  check_mode_start: true
#switch:
#  pin: gpio.35
#unused input pin:
#  pin: gpio.32

coolant:
  flood_pin: NO_PIN
  mist_pin: gpio.4
  delay_ms: 500

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.020

relay:
  output_pin: gpio.13:low:pu
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 5000
  spindown_ms: 5000
  tool_num: 100
  speed_map: 0=0.000% 0=100.000% 1=100%
```

### Startup Messages

```text
$ss
[MSG:INFO: FluidNC 3.7.10 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:6_Pack_Ext-DMT-556T_XYYZ.yaml]
[MSG:WARN: Decreasing stepping/pulse_us to 20, the maximum value for I2S_STREAM]
[MSG:INFO: Machine 6 Pack Ext-DMT-556T XYYZ]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_stream Pulse:20us Dsbl Delay:1000000us Dir Delay:10us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,844.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.1 Disable:I2SO.0]
[MSG:INFO: Axis Y (0.000,1020.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.5:low Dir:I2SO.4:low Disable:I2SO.7:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.10:low Dir:I2SO.9:low Disable:I2SO.8:low]
[MSG:INFO: Axis Z (-100.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13:low Dir:I2SO.12:low Disable:I2SO.15:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Relay Spindle Ena:NO_PIN Out:gpio.13:low:pu Dir:NO_PIN]
[MSG:INFO: Using spindle Relay]
[MSG:INFO: Mist coolant gpio.4]
[MSG:INFO: Connecting to STA SSID:***]
```

### User Interface Software

WebUI

### What happened?

TL/DR: I tried to jog, no motors moved.

I have only been testing with the X-Axis:

I have been able to test the motor "enable/disable" feature successfully with my 6Pack. My Breakout Board's LED glows brightly or goes dark depending on the setting. My stepper driver locks the motor fully if enabled, the motor moves freely if disabled .
I have disconnected the enable/disable cable for now, as this keeps the driver enabled all the time, ensuring that the correct invert setting for the driver is not an issue.
When i try to move (jog or gcode) my motor in the "ESP3D for FluidNC" WebUI,  like "nothing" happens, the driver is being enabled and the step led glows-dimly but nothing moves. The step led glows really dimly. When i invert the signal the LED stay very bright and just darkens slightly.

I have used an arduino which just sends 50ms 5V pulses to the stepper driver and it makes the stepper move without any issue, so my motor wiring and driver should be OK.
In previous CNC setup, I have used 5V/10us pulses for the same drivers.

### GCode File

G91
G21
G0 X100 Y100
G1 F100 X-100 Y-100

### Other Information

Right now my main concern is to scope the issue: Do I have a electrical problem (like a missing pullup) or a software-missconfiguration.
To me both sides "look good" and this is frustrating as obviously not everything "is good" as the result is not the desired one.
