### ISSUE TITLE
Problem: Downloading files to SD

### ISSUE THREAD

**Issue by MikeGarber** [bdring/FluidNC#1124]
### Wiki Search Terms

"crash"

### Controller Board

Custom (for software evaluation)  Just a WROOM-32 and a Lexar 32GB micro SD
![20240203_121742 1](https://github.com/bdring/FluidNC/assets/11590856/a48aff7c-565f-44a6-adda-2f877170a776)

### Machine Description

No machine, yet; just evaluating the software

### Input Circuits

```yaml
(not applicable)
```

### Configuration file

```yaml
name: 4xiDraw Drawing machine
meta: Hi Mom!

start:
  must_home: false

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.25

kinematics:
  corexy:
#  WallPlotter:
#    left_axis: 0
#    left_anchor_x: -100.000
#    left_anchor_y: 100.000
#    right_axis: 1
#    right_anchor_x: 100.000
#    right_anchor_y: 100.000
#    segment_length: 5.000
    
stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  x:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
      stepstick:
        direction_pin: gpio.14
        step_pin: gpio.12
        disable_pin: gpio.27:high     
    motor1:
      null_motor:

  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
#      limit_all_pin: gpio.4:low:pu
      stepstick:
        direction_pin: gpio.15
        step_pin: gpio.26
        disable_pin: gpio.13:high     
    motor1:
      null_motor:

  z:
    steps_per_mm: 100
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 5
    homing:
      cycle: 1
      mpos_mm: 0
      positive_direction: true

    motor0:
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.33
# 33???
        min_pulse_us: 1000
        max_pulse_us: 2000

    motor1:
      null_motor:
```

### Startup Messages

```text
Select a COM port
0: COM3 (\Device\Serial0)
1: COM9 (\Device\Silabser2)
Choice: 1
FluidTerm v1.2.0 (5a7b637-dirty) using COM9
Exit: Ctrl-C, Ctrl-Q or Ctrl-], Clear screen: CTRL-W
Upload: Ctrl-U, Reset ESP32: Ctrl-R, Send Override: Ctrl-O
Resetting MCU
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4
[MSG:INFO: uart_channel0 created]
[MSG:RST]
[MSG:INFO: FluidNC 3.7.14-webui3-test https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine 4xiDraw Drawing machine]
[MSG:INFO: Board None]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.25 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.12 Dir:gpio.14 Disable:gpio.27]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.26 Dir:gpio.15 Disable:gpio.13]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (-5.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     rc_servo Pin:gpio.33 Pulse Len(1000,2000 period:1048575)]
[MSG:INFO:     Update timer for rc_servo at 20 ms]
[MSG:INFO:   Motor1]
[MSG:INFO: Kinematic system: CoreXY]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC 3.7.14-webui3-test (wifi) '$' for help]
$$
$22=1
$21=0
$20=0
$102=100.000
$101=800.000
$100=800.000
$112=5000.000
$111=2000.000
$110=2000.000
$122=100.000
$121=25.000
$120=25.000
$132=5.000
$131=1000.000
$130=1000.000
$10=1
$30=0
ok
```

### User Interface Software

WEBUI

### What happened?

On the WEBUI dashboard, I can see the SD files I put there directly from my laptop.  I can successfully rename existing files, and upload new ones.  But when I go to the Tablet tab and press Upload (lower rt corner) and select a new file to load, it crashes:

Select a COM port
0: COM3 (\Device\Serial0)
1: COM9 (\Device\Silabser2)
2: COM15 (\Device\ssudmdm0000)
Choice: 1
FluidTerm v1.2.0 (5a7b637-dirty) using COM9
Exit: Ctrl-C, Ctrl-Q or Ctrl-], Clear screen: CTRL-W
Upload: Ctrl-U, Reset ESP32: Ctrl-R, Send Override: Ctrl-O
[MSG:INFO: WebUI: Request from 192.168.0.2]
[MSG:ERR: mount_to_vfs failed code 0xffffffff]
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x4015af26  PS      : 0x00060130  A0      : 0x8015b2cb  A1      : 0x3ffb1f20
A2      : 0x00000000  A3      : 0x3fff2018  A4      : 0x00002001  A5      : 0x00000001
A6      : 0x3fff0b94  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x00000000
A10     : 0x00000000  A11     : 0x3fff2018  A12     : 0x00002001  A13     : 0x00000001
A14     : 0x00060f20  A15     : 0x00000001  SAR     : 0x00000020  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000008  LBEG    : 0x4008b5e4  LEND    : 0x4008b5fa  LCOUNT  : 0x00000000

Backtrace: 0x4015af23:0x3ffb1f20 0x4015b2c8:0x3ffb1f40 0x4015b61d:0x3ffb1f60 0x4015c96c:0x3ffb1fa0 0x400d54b3:0x3ffb1fe0 0x400daaaa:0x3ffb2020 0x401062f7:0x3ffb20b0 0x401ef8c5:0x3ffb2110 0x400f3019:0x3ffb2140 0x400f324b:0x3ffb21a0 0x400f32a7:0x3ffb21d0 0x400f4069:0x3ffb2210 0x400e672f:0x3ffb2250 0x40121415:0x3ffb2290

ELF file SHA256: 16273dc4c49443d4

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4
[MSG:INFO: uart_channel0 created]
[MSG:RST]
[MSG:INFO: FluidNC 3.7.14-webui3-test https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:ERR: Skipping configuration file due to panic]
[MSG:INFO: Using default configuration]
[MSG:INFO: Axes: using defaults]
[MSG:INFO: Machine Default (Test Drive)]
[MSG:INFO: Board None]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC 3.7.14-webui3-test (wifi) '$' for help]

### GCode File

(not applicable)

### Other Information

Any help would be appreciated ($).
You have an amazing body of work here!!!
