### ISSUE TITLE
Problem: $ESP400 behavior

### ISSUE THREAD

**Issue by ColPaulR** [bdring/FluidNC#1137]
### Wiki Search Terms

ESP400 EEPROM

### Controller Board

MKS Tinybee

### Machine Description

4-axis external drivers gantry CNC with laser

### Configuration file

```yaml
board: MKS TinyBee V1.0_001
name: CNC Router XYYZA 0-10V spindle and laser
meta: (01.02.2022) by Skorpi

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  x:
    # X
    steps_per_mm: 250
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 1300.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 1265.00
      feed_mm_per_min: 300.000
      seek_mm_per_min: 2000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: GPIO.33:low
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.1
        direction_pin: I2SO.2:low
        disable_pin: I2SO.0

  y:
    # Y
    steps_per_mm: 250
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 1300.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000  
      feed_mm_per_min: 300.000
      seek_mm_per_min: 2000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: GPIO.32:low
      hard_limits: true
      pulloff_mm: 3.20
      standard_stepper:
        step_pin: I2SO.4
        direction_pin: I2SO.5:low
        disable_pin: I2SO.3
    motor1:
      limit_neg_pin: GPIO.22:low
      hard_limits: true
      pulloff_mm: 1.00
      standard_stepper:
        step_pin: I2SO.7
        direction_pin: I2SO.8:low
        disable_pin: I2SO.6
 
  z:
    # Z
    steps_per_mm: 250
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: GPIO.35:low
      hard_limits: true
      pulloff_mm: 1.500
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.11
        disable_pin: I2SO.9

  a:
    # Rotary
    steps_per_mm: 33.333333333333333333333333333333333333333333333333
    max_rate_mm_per_min: 18000.000
    acceleration_mm_per_sec2: 1500.000
    max_travel_mm: 325.000
    soft_limits: false

    motor0:
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.14
        disable_pin: I2SO.12

i2so:
  bck_pin: GPIO.25
  data_pin: GPIO.27
  ws_pin: GPIO.26

spi:
  miso_pin: GPIO.19
  mosi_pin: GPIO.23
  sck_pin: GPIO.18

#sdcard:
#  cs_pin: GPIO.5
#  card_detect_pin: GPIO.34

status_outputs:
  #report_interval_ms: 500
  #idle_pin: gpio.26
  #run_pin: gpio.4
  #hold_pin: I2SO.23
  #alarm_pin: gpio.27  
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  #feed_hold_pin: GPIO.39:low
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

10V:
  # BEEPER Pin 1 on EXP1
  forward_pin: I2SO.21  
  pwm_hz: 5000
  # GPIO.21 is LCD_EN Pin 3 on EXP1
  output_pin: GPIO.21
  enable_pin: I2SO.22:LOW    
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 6000
  spindown_ms: 6000
  tool_num: 0
  speed_map: 0=0.000% 4000=0.000% 24000=50.000%
  off_on_alarm: true

Laser:
  pwm_hz: 5000
  output_pin: GPIO.4
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 100
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: true

macros:
  startup_line0:
  startup_line1:
  macro0: 
  macro1:
  macro2:
  macro3:
  after_homing: G92x1265y0z0

coolant:
  flood_pin: I2SO.20
  mist_pin: I2SO.19
  delay_ms: 1000

probe:
  pin: GPIO.13:low:pu
  check_mode_start: false

start:
  must_home: false

verbose_errors: true
use_line_numbers: true

 # USB  TX0(1)  RX0(3)
 # J3-> TX2(17) RX2(16)


 # J1P1 -> I2SO.22 -> ################### 10V SPINDLE ENABLE PIN
 # J1P2 -> I2SO.23 -> ################### HOLD PIN -> 
 
 # HE0(I2SO.17)   HE1(I2SO.18)   HBED(I2SO.16)
 # FAN2(I2SO.20)
 #                   EXP1                                   EXP2
 #(BEEPER) I2SO.21 | 1  2 | 13 (BTN_ENC)    (SPI MISO) 19 | 1  2 | 18 (SPI SCK)
 #    (LCD_EN)  21 | 3  4 |  4 (LCD_RS)      (BTN_EN1) 14 | 3  4 |  5 (SPI CS)
 #    (LCD_D4)   0 | 5  6   16 (LCD_D5)      (BTN_EN2) 12 | 5  6   23 (SPI MOSI)
 #    (LCD_D6)  15 | 7  8 | 17 (LCD_D7)      (SPI_DET) 34 | 7  8 | RESET
 #             GND | 9 10 | 5V                        GND | 9 10 | 3.3V
 #
 #                            EXP1
 # SPINDLE FORWARD  I2SO.21 | 1  2 | 13 PROBE
 # SPINDLE OUTPUT       21  | 3  4 |  4 LASER OUTPUT
 # UNUSED OUTPUT         0  | 5  6   16 RXD2    
 # SPINDLE ENABLE       15  | 7  8 | 17 TXD2 
 #                      GND | 9 10 | 5V               
 #
 #                              EXP2
 # UNAVAILABLE  (SPI MISO)  19 | 1  2 | 18 (SPI SCK)  UNAVAILABLE
 # UNUSED IO    (BTN_EN1)   14 | 3  4 |  5 (SPI CS)   UNAVAILABLE
 # UNUSED IO    (BTN_EN2)   12 | 5  6 | 23 (SPI MOSI) UNAVAILABLE
 # UNAVAILABLE  (SPI_DET)   34 | 7  8 | RESET         UNAVAILABLE
 #                         GND | 9 10 | 3.3V                     
 #
 #        J40
 # 1 - +5V
 # 2 - GND
 # 3 - MT_DET - GPIO.35 with capacitance
 #
 #        J41
 # 1 - 3D_TOUCH - GPIO.2 OUTPUT   
 # 2 - +5V
 # 3 - GND
 #
 #        TB1
 # 1 - GND
 # 2 - TB - SENSOR VN - GPIO.39  with capacitance - ESTOP Normally Open
 #
 #        TH1
 # 1 - GND
 # 2 - TH1 - SENSOR VP - GPIO.36 with capacitance
 #
 #        TH2
 # 1 - GND
 # 2 - TH2 - SENSOR VP - UNAVAILABLE
 #
 #        J11
 # 1 - FAN1 - I2SO.19
 # 2 - 24VDC
```

### Startup Messages

```text
[MSG:INFO: WiFi Disconnected]
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4
[MSG:INFO: uart_channel0 created]
[MSG:RST]
[MSG:INFO: FluidNC 3.7.13 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:XYZAB_laser_5Jan24v2.yaml]
[MSG:INFO: Machine CNC Router XYYZA 0-10V spindle and laser]
[MSG:INFO: Board MKS TinyBee V1.0_001]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: Status outputs Interval:500 Idle:NO_PIN Cycle:NO_PIN Hold:NO_PIN Alarm:NO_PIN]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 4]
[MSG:INFO: Axis X (-35.000,1265.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Y2 Neg Limit gpio.22:low]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.35:low]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:I2SO.22:low Out:gpio.21 Dir:NO_PIN Fwd:I2SO.21 Rev:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.20]
[MSG:INFO: Mist coolant I2SO.19]
[MSG:INFO: Probe Pin: gpio.13:low:pu]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Y2 Neg Limit gpio.22:low]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.35:low]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:I2SO.22:low Out:gpio.21 Dir:NO_PIN Fwd:I2SO.21 Rev:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.20]
[MSG:INFO: Mist coolant I2SO.19]
[MSG:INFO: Probe Pin: gpio.13:low:pu]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Y2 Neg Limit gpio.22:low]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.35:low]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:I2SO.22:low Out:gpio.21 Dir:NO_PIN Fwd:I2SO.21 Rev:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.20]
[MSG:INFO: Mist coolant I2SO.19]
[MSG:INFO: Probe Pin: gpio.13:low:pu]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Y2 Neg Limit gpio.22:low]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.35:low]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:I2SO.22:low Out:gpio.21 Dir:NO_PIN Fwd:I2SO.21 Rev:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.20]
[MSG:INFO: Mist coolant I2SO.19]
[MSG:INFO: Probe Pin: gpio.13:low:pu]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Y2 Neg Limit gpio.22:low]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.35:low]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:I2SO.22:low Out:gpio.21 Dir:NO_PIN Fwd:I2SO.21 Rev:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.20]
[MSG:INFO: Mist coolant I2SO.19]
[MSG:INFO: Probe Pin: gpio.13:low:pu]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Y2 Neg Limit gpio.22:low]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.35:low]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:I2SO.22:low Out:gpio.21 Dir:NO_PIN Fwd:I2SO.21 Rev:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.20]
[MSG:INFO: Mist coolant I2SO.19]
[MSG:INFO: Probe Pin: gpio.13:low:pu]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Axis X (-35.000,1265.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Y2 Neg Limit gpio.22:low]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.35:low]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:I2SO.22:low Out:gpio.21 Dir:NO_PIN Fwd:I2SO.21 Rev:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.20]
[MSG:INFO: Mist coolant I2SO.19]
[MSG:INFO: Probe Pin: gpio.13:low:pu]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Axis X (-35.000,1265.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Y2 Neg Limit gpio.22:low]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.35:low]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:I2SO.22:low Out:gpio.21 Dir:NO_PIN Fwd:I2SO.21 Rev:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.20]
[MSG:INFO: Mist coolant I2SO.19]
[MSG:INFO: Probe Pin: gpio.13:low:pu]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Axis X (-35.000,1265.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO:  Y2 Neg Limit gpio.22:low]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.35:low]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:I2SO.22:low Out:gpio.21 Dir:NO_PIN Fwd:I2SO.21 Rev:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.4 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.20]
[MSG:INFO: Mist coolant I2SO.19]
[MSG:INFO: Probe Pin: gpio.13:low:pu]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.0.48]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC 3.7.13 (wifi) '$' for help]
```

### User Interface Software

Fluidterm, CNCjs and Commander

### What happened?

I realize that CNC3D Command and FluidNC are not official supported/compatible, but my FluidNC system has been working with Commander. I switched from CNCjs to Commander to get the XHC-HB04 Pendant support. I notice that FluidNC is are exhibiting some strange (to me at least) behavior once I started investing what was going on with Commander.

I upgraded Commander to Build 301 and FluidNC did not seem to respond once I hit the connect button. I started looking at the raw serial traffic through Commander's monitor window. Commander sends $ESP400 that spits out lots of data. It takes so long that Commander loses sync/quits trying to get status with the "?" message.

I rolled back to Commander Build 300 thinking that the $ESP400 or some startup queries were different between the builds, but I still have the same issue. $ESP400 still dumps lots of data. Attached is a log of Commander serial data.

[FluidNC Serial Log 18Feb24.txt](https://github.com/bdring/FluidNC/files/14323772/FluidNC.Serial.Log.18Feb24.txt)

I have a backup MKS Tinybee that I use for development. I cleared the eeprom and reflashed the latest FluidNC non-test release (v3.7.13), uploaded my YAML and index.html.gz. Using Fluidterm, I get a VERY slow response to $ESP400 with some error messages, per below. Neither Tinybee's have an SD card in them.

```
$ESP400
[MSG:JSON:{"EEPROM":[{"F":"nvs","P":"Start/Message","H":"Start/Message","T":"S","V":"Grbl \\V [FluidNC \\B (\\]
[MSG:ERR: Device not responding]
[MSG:JSON:R) \\H]","S":"40","M":"0"},{"F":"nvs","P":"Firmware/Build","H":"Firmware/Build","T":"S","V":"","S":"]
[MSG:ERR: Device not responding]
[MSG:JSON:20","M":"0"},{"F":"nvs","P":"SD/FallbackCS","H":"SD/FallbackCS","T":"I","V":"-1","S":"40","M":"-1"},]
[MSG:ERR: Device not responding]
[MSG:JSON:{"F":"nvs","P":"Report/Status","H":"Report/Status","T":"I","V":"1","S":"3","M":"0"},{"F":"nvs","P":"]
[MSG:ERR: Device not responding]
[MSG:JSON:Config/Filename","H":"Config/Filename","T":"S","V":"XYZAB_laser_5Jan24v2.yaml","S":"50","M":"1"},{"F]
[MSG:ERR: Device not responding]
[MSG:JSON:":"nvs","P":"Message/Level","H":"Message/Level","T":"B","V":"3","O":[{"Debug":"4"},{"Error":"1"},{"I]
[MSG:ERR: Device not responding]
[MSG:JSON:nfo":"3"},{"None":"0"},{"Verbose":"5"},{"Warning":"2"}]},{"F":"nvs","P":"WiFi/Mode","H":"WiFi/Mode",]
[MSG:ERR: Device not responding]
[MSG:JSON:"T":"B","V":"3","O":[{"AP":"2"},{"Off":"0"},{"STA":"1"},{"STA>AP":"3"}]},{"F":"nvs","P":"Sta/SSID","]
[MSG:ERR: Device not responding]
[MSG:JSON:H":"Sta/SSID","T":"S","V":"RounsavallWPA2","S":"32","M":"0"},{"F":"nvs","P":"Sta/Password","H":"Sta/]
[MSG:ERR: Device not responding]
[MSG:JSON:Password","T":"S","V":"********","S":"64","M":"8"},{"F":"nvs","P":"Sta/MinSecurity","H":"Sta/MinSecu]
[MSG:ERR: Device not responding]
[MSG:JSON:rity","T":"B","V":"3","O":[{"OPEN":"0"},{"WEP":"1"},{"WPA-PSK":"2"},{"WPA-WPA2-PSK":"4"},{"WPA2-ENTE]
[MSG:ERR: Device not responding]
[MSG:JSON:RPRISE":"5"},{"WPA2-PSK":"3"}]},{"F":"nvs","P":"WiFi/FastScan","H":"WiFi/FastScan","T":"B","V":"0","]
[MSG:ERR: Device not responding]
[MSG:JSON:O":[{"OFF":"0"},{"ON":"1"}]},{"F":"nvs","P":"Sta/IPMode","H":"Sta/IPMode","T":"B","V":"0","O":[{"DHC]
[MSG:ERR: Device not responding]
```
