### ISSUE TITLE
Problem: macrocfg.json not found und Spiffs mount failed: ESP_FAIL

### ISSUE THREAD

**Issue by luft-post** [bdring/FluidNC#1145]
### Wiki Search Terms

macrocfg.json not found, Spiffs mount failed: ESP_FAIL, 

### Controller Board

OPEN-CNC-Shield 2.x von [https://docs.timos-werkstatt.de/open-cnc-shield-2/controllermodules/fluidnc](https://docs.timos-werkstatt.de/open-cnc-shield-2/controllermodules/fluidnc) mit einen ESP32-Controller

### Machine Description

Fräse mit vier externe DM542T (X, Y1, Y2, Z) 

### Configuration file

```yaml
name: "OCS2 FluidNC"
board: "OCS2 FluidNC Controller"
meta: "2"

stepping:
  engine: I2S_STREAM
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 4
  disable_delay_us: 0

axes:
  # shared_stepper_disable_pin: i2so.12    # Wichtig: hier mus die ENA steuerung ausgeschaltet werden 

  x:
    steps_per_mm: 640
    max_rate_mm_per_min: 2500
    acceleration_mm_per_sec2: 80
    max_travel_mm: 470
    soft_limits: true

    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 10.000
      feed_mm_per_min: 60.000
      seek_mm_per_min: 1200.000
      seek_scaler: 1.1
      feed_scaler: 1.1
      
    motor0:
      limit_all_pin: gpio.36:high 
      hard_limits: true
      pulloff_mm: 5
      stepstick:
        direction_pin: i2so.1   
        step_pin: i2so.0        
    motor1:
      null_motor:
      
  y:
    steps_per_mm: 640
    max_rate_mm_per_min: 2500
    acceleration_mm_per_sec2: 80
    max_travel_mm: 600
    soft_limits: true

    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 10.000
      feed_mm_per_min: 60.000
      seek_mm_per_min: 1200.000
      seek_scaler: 1.1
      feed_scaler: 1.1

    motor0:     
      limit_all_pin: gpio.39:high   
      hard_limits: true
      pulloff_mm: 5
      stepstick:
        direction_pin: i2so.3:low   
        step_pin: i2so.2        
    motor1:     
      limit_neg_pin: gpio.35:high   
      hard_limits: true
      pulloff_mm: 5
      stepstick:
        direction_pin: i2so.9:low   
        step_pin: i2so.8        

  z:
    steps_per_mm: 1600
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 100
    
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 10.000
      feed_mm_per_min: 60.000
      seek_mm_per_min: 500.000
      seek_scaler: 1.1
      feed_scaler: 1.1
    
    motor0: 
      limit_all_pin: gpio.34 
      hard_limits: true
      pulloff_mm: 5
      stepstick:
        direction_pin: i2so.5   
        step_pin: i2so.4
        
    motor1:
      null_motor:
      
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

i2c0:
  sda_pin: gpio.14
  scl_pin: gpio.13

oled:
  i2c_num: 0
  i2c_address: 60
  width: 128
  height: 64
  radio_delay_ms: 1000


Laser:    
  pwm_hz: 5000      
  output_pin: gpio.25:high  
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: true

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN        
  feed_hold_pin: gpio.4:low:pu     
  cycle_start_pin: gpio.15:low:pu   
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
```

### Startup Messages

```text
rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4
[MSG:INFO: uart_channel0 created]
[MSG:RST]
[MSG:INFO: FluidNC 3.7.14-webui3-test https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:DBG: Spiffs mount failed: ESP_FAIL]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:FluidNCconf_4.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine OCS2 FluidNC]
[MSG:INFO: Board OCS2 FluidNC Controller]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: I2C SDA: gpio.14, SCL: gpio.13, Freq: 100000, Bus #: 0]
[MSG:INFO: OLED I2C address: 0x3c width: 128 height: 64]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (10.000,480.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.0 Dir:I2SO.1 Disable:NO_PIN]
[MSG:INFO:  X All Limit gpio.36]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (10.000,610.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.2 Dir:I2SO.3:low Disable:NO_PIN]
[MSG:INFO:  Y All Limit gpio.39]
[MSG:INFO:   Motor1]
[MSG:INFO:     stepstick Step:I2SO.8 Dir:I2SO.9:low Disable:NO_PIN]
[MSG:INFO:  Y2 Neg Limit gpio.35]
[MSG:INFO: Axis Z (-90.000,10.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.4 Dir:I2SO.5 Disable:NO_PIN]
[MSG:INFO:  Z All Limit gpio.34]
[MSG:INFO:   Motor1]
[MSG:INFO: feed_hold_pin gpio.4:low:pu]
[MSG:INFO: cycle_start_pin gpio.15:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.25 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Connecting to STA SSID:laserbrenner]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 192.168.2.180]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:DBG:  Y All Limit 0]

[MSG:DBG:  X All Limit 0]
Grbl 3.7 [FluidNC 3.7.14-webui3-test (wifi) '$' for help]
[MSG:INFO: ALARM: Unhomed]
ALARM:14
[MSG:DBG:  Y2 Neg Limit 0]
[MSG:DBG:  Z All Limit 0]
[MSG:DBG: cycle_start_pin 0]
[MSG:DBG: feed_hold_pin 0]
[MSG:INFO: WebUI: Request from 192.168.2.157]
[MSG:DBG: index.html is cached]
[MSG:DBG: /favicon.ico is cached]
[MSG:DBG: WebSocket 0 from 192.168.2.157 uri /]
[MSG:DBG: /macrocfg.json not found]
[MSG:DBG: 404.htm not found]
[MSG:DBG: /preferences.json is cached]
```

### User Interface Software

ESP3D for FluidNC, 

### What happened?

1. Problem:
Es wird die macrocfg.json nicht gefunden, finde aber dazu keine genaue Info was diese genau ist bzw. was der Inhalt ist. Auf den "FluidNC Local Filesystem" ist diese Datei auch nicht enthalten. Könnt Ihr mir sagen, ob diese wichtig ist bzw. wofür diese gut ist? Reicht es einfach eine leere macrocfg.json Datei zu erstellen und ins Filesystem hochzuladen?

2. Problem:
Beim Booten des ESP32 bekomme ich eine Meldung  "WebSocket 0 from 192.168.2.157 uri /]" und "[MSG:DBG: 404.htm not found]"
Dabei habe ich unter "FluidNC Settings" eine statische IP (192.168.2.180) angegeben.

![Unbenannt](https://github.com/bdring/FluidNC/assets/40865649/5db60e4d-4910-4892-8439-78c258d8dea4)

Auch das angeschlossene Display zeigt mir die 192.168.2.157 an. Wo kommt die 192.168.2.157 her? bzw. wo ist diese Konfiguriert? Das WebUI lässt dich unter 192.168.2.180 öffnen und normal bedienen.

3. Problem:
Es wird die Meldung [MSG:DBG: Spiffs mount failed: ESP_FAIL] ausgegeben, scheint ein Problem mit den von mir eingesetzten Controller zu sein (ESP32-WROOM-32), könnt Ihr mir hierzu was sagen? 

Ich hoffe, dass die Problem Beschreibung und Informationen soweit ausreichen sind. Grundsätzlich kann ich noch sagen das meine CNC auch mit den angezeigten Warnungen über das ESP3D for FluidNC WebUI augenscheinlich normal funktioniert. Sprich die Achsen lassen sich alle verfahren, Endschalter werden erkannt und Homing lässt sich ausführen.

Noch kurz ein Wort und Dank zu FluidNC und den Leuten dahinter. Ich finde es klasse was Ihr auf die Beine gestellt habt, auch wenn ich glaube das ich noch gar nicht genau begriffen habe wie umfangreich FluidNC ist (bin noch neu in der CNC Welt).
Ich finde FluidCN hat einen sehr professionellen Auftritt: eine sehr umfangreiches gut aufgebautes WIKI, eine super einfache Installation Möglichkeit und auch diese (ich nenne es einfach mal so...) Problem Annahmestelle sehr Zielführend aufgebaut.

Also nochmal vielen Herzlichen dank für eure Arbeit :)

Viele Gruß und Dank
Matthias
