### ISSUE TITLE
Machine is not homing X

### ISSUE THREAD

**Issue by alphaonex86** [bdring/FluidNC#1158]
### Wiki Search Terms

Machine homing

### Controller Board

ESP32 DEVKIT V1

### Machine Description

just ESP32 DEVKIT V1, 1 AXIS, 2 optical end stop, stepper from DVD

### Input Circuits

Optical end stop

### Configuration file

```yaml
name: Test X
board: ESP32 DEVKIT V1
meta: cfg
start:
  must_home: false
  check_limits: true
  deactivate_parking: true
axes:
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    homing:
      cycle: -1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.26:pu
      limit_pos_pin: gpio.27:pu
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        step_pin: gpio.32
        direction_pin: gpio.33
        disable_pin: NO_PIN
stepping:
  engine: RMT
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0
```

### Startup Messages

```text
<Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:0.000,0.000,0.000>
```

### What happened?

Do nothing wuth $HX, no move

### GCode File

$Message/Level=Debug
$HX
ok

### Other Information

I can move, stop correctly when reach end stop
