### ISSUE TITLE
OTA update to v3.7.15 failed at 36%, threw an error in the WebUI. Rebooting then failed.

### ISSUE THREAD

**Issue by shampeon** [bdring/FluidNC#1165]
### Wiki Search Terms

OTA
update failed

### Controller Board

MKS TinyBee

### Machine Description

Workbee 1500x1500 CNC router, dual Y, G-Penny 1.5kw spindle, Huanyang VFD connected by RS485

### Configuration file

```yaml
~~~
board: MKS TinyBee V1.0 XXYYZ
name:

kinematics:
  Cartesian:

i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  # uses TH2 IO34 active low - MAKE SURE jumper J2 is set to SDDET!!!
  card_detect_pin: gpio.34:low

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 5
  dir_delay_us: 1
  disable_delay_us: 2

axes:
  x:
    steps_per_mm: 31.965
    max_rate_mm_per_min: 8000.000
    acceleration_mm_per_sec2: 250.000
    max_travel_mm: 1300.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.33:high:pd
      hard_limits: true
      pulloff_mm: 4.000
      standard_stepper:
        step_pin: I2SO.1
        direction_pin: I2SO.2
        disable_pin: I2SO.0

    # use E0 driver for 2nd X axis motor
    motor1:
      hard_limits: true
      pulloff_mm: 4.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.11
        disable_pin: I2SO.9

  y:
    steps_per_mm: 32.046
    max_rate_mm_per_min: 8000.000
    acceleration_mm_per_sec2: 250.000
    max_travel_mm: 1320.000
    soft_limits: false
    homing:
      cycle: 3
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.32:high:pd
      hard_limits: false
      pulloff_mm: 4.000
      standard_stepper:
        step_pin: I2SO.4
        direction_pin: I2SO.5
        disable_pin: I2SO.3

    # use E1 driver for 2nd Y axis motor
    motor1:
      limit_neg_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 4.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.14
        disable_pin: I2SO.12

  z:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 3500.000
    acceleration_mm_per_sec2: 250.000
    max_travel_mm: 110.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.22:high:pd
      hard_limits: true
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.7
        direction_pin: I2SO.8
        disable_pin: I2SO.6

control:
  safety_door_pin: gpio.16:low:pu
  # on MT_DET connector
  # reset_pin: gpio.35:low
  reset_pin: gpio.17:low:pu
  # on TH1 connector
  feed_hold_pin: gpio.36:low
  # on TB connector
  cycle_start_pin: gpio.39:low
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

# coolant:
#   # Heated Bed Terminal Block
#   flood_pin: i2so.16
#   # HE0 Terminal Block
#   mist_pin: i2so.17
#   delay_ms: 0

# spindle PWM signal
PWM:
  pwm_hz: 2500
  # on EXP1 IO15 connector.
  # note IO15 will give some short pulses on boot, which may activate spindle
  # use IO17 on EXP1 to avoid
  output_pin: gpio.15:high
  s0_with_disable: true
  tool_num: 100
  spinup_ms: 4000
  spindown_ms: 4000
  speed_map: 8000=0.000% 18000=100.000%

Laser:
  pwm_hz: 5000
  # on 3D Touch connector (has pdwn + PWM)
  output_pin: gpio.2:high:pd
  s0_with_disable: true
  tool_num: 1
  speed_map: 0=0.000% 1000=100.000%

probe:
  pin: gpio.35:pu:low
  check_mode_start: true

start:
  must_home: false

uart2:
  txd_pin: gpio.4
  rxd_pin: gpio.13
  rts_pin: NO_PIN
  baud: 9600
  mode: 8N1

Huanyang:
  uart_num: 2
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 7200=40% 18000=100%
  off_on_alarm: false
~~~
```

### Startup Messages

```text
Couldn't access it, board was unresponsive
```

### What happened?

I attempted to update to v3.7.15 OTA using the web UI. My machine is standalone, so OTA is the only reasonable way for me to update.

The update progress went in bursts, first to 15% before stalling for a bit, then up to 35% before another stall, then 36%. At that point, it stalled for a long time. An error modal popped up, which I clicked OK on to close.

Thinking it was potentially caused by low memory as it had been running since yesterday, I clicked Restart FluidNC within the web UI. The WebUI showed the board rebooting, but stopped responding. After a few minutes, the reboot modal closed on its own, but the board was unresponsive. I had to hard reboot the board by cutting and restoring power to get it back.

Updating the firmware a second time succeeded.

But there was clearly some state that FluidNC was in before the first firmware update that caused the firmware and reboot failure. If my suspicion is correct that there was low memory, maybe there should be some check before performing a firmware update.

### Other Information

~~~
[MSG:INFO: Update Firmware]
[MSG:INFO: Update 0%]
[MSG:INFO: Update 1%]
[MSG:INFO: Update 2%]
[MSG:INFO: Update 3%]
[MSG:INFO: Update 4%]
[MSG:INFO: Update 5%]
[MSG:INFO: Update 6%]
[MSG:INFO: Update 7%]
[MSG:INFO: Update 8%]
[MSG:INFO: Update 9%]
[MSG:INFO: Update 10%]
[MSG:INFO: Update 11%]
[MSG:INFO: Update 12%]
[MSG:INFO: Update 13%]
[MSG:INFO: Update 14%]
[MSG:INFO: Update 15%]
[MSG:INFO: Update 16%]
[MSG:INFO: Update 17%]
[MSG:INFO: Update 18%]
[MSG:INFO: Update 19%]
[MSG:INFO: Update 20%]
[MSG:INFO: Update 21%]
[MSG:INFO: Update 22%]
[MSG:INFO: Update 23%]
[MSG:INFO: Update 24%]
[MSG:INFO: Update 25%]
[MSG:INFO: Update 26%]
[MSG:INFO: Update 27%]
[MSG:INFO: Update failed]
~~~
