### ISSUE TITLE
Problem:  Issues with uploading *.yaml to FluidNC (latest version)

### ISSUE THREAD

**Issue by PST75** [bdring/FluidNC#1172]
### Wiki Search Terms

Root controller, Huanyang VFD, Yaml indentations etc.

### Controller Board

Root Controller ISO. The config should be an exact copy when it comes to sections described in the root controller WIKI (base config, axes (common cathode), rs485 etc. etc.)

### Machine Description

Gantry milling machine (QueenBee Pro) with dual y steppers (X,Y,Y, Z) and Huanyang VFD and 2.2 kW spindle. Controller is Root Controller ISO
![error3](https://github.com/bdring/FluidNC/assets/114349329/85ac6cf0-7abf-4ecd-8eb0-228f241be6e7)
![error5](https://github.com/bdring/FluidNC/assets/114349329/0aae0530-bb32-47d5-b24f-9834b361807f)
![error4](https://github.com/bdring/FluidNC/assets/114349329/04142a32-1a42-4de1-aeea-0f831cd28c38)

### Configuration file

```yaml
board: Root Controller ISO
name: QBCNC v.1.2

stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 3

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 398.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 1242.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.00
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.7:low
        direction_pin: I2SO.5:low
        disable_pin: I2SO.3:high

  y:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 1277.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.0
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.12:low
        direction_pin: I2SO.10:low
        disable_pin: I2SO.8:high

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.13:low
        direction_pin: I2SO.11:low
        disable_pin: I2SO.9:high

  z:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 80.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.0
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.18:low
        direction_pin: I2SO.16:low
        disable_pin: I2SO.14:high

i2so:
  bck_pin: gpio.22
  data_pin: gpio.12
  ws_pin: gpio.21

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.34
  cycle_start_pin: gpio.36
  macro0_pin: gpio.39
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: gpio.33
  mist_pin: gpio.13
  delay_ms: 0

probe:
  pin: gpio.27
  check_mode_start: true

macros:
  startup_line0:
  startup_line1:
  macro0: 
  macro1: 
  macro2: 
  macro3:

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: i2so.15


start:
  must_home: true

Huanyang:
  uart:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: gpio.4
  baud: 9600
  mode: 8N1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%

Laser:
  pwm_hz: 5000
  output_pin: gpio.25
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 1
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: false
```

### Startup Messages

```text
Please see pict shared in Machine Description.

I have also encountered a different error when trying to upload a different config se picture uploaded in machine description.

Also I get some strange characters within the FluidTerm after powering on / of the controller (picture also included above)
```

### User Interface Software

FluidTerm

### What happened?

Nothing. No movement or sound of power to steppers etc.  The steppers are wired to the controller as common cathode and acc. to wiring instructions on the controller.

No comms with the VFD although I cheked the wiring and parameter settings in FluidNc Wiki....

![IMG20240317210107-min](https://github.com/bdring/FluidNC/assets/114349329/12a7bbf1-3f3b-4c29-8042-b9533776bbdc)
![IMG20240317210114-min](https://github.com/bdring/FluidNC/assets/114349329/a2e7e962-add9-4f15-9278-0083925134de)
![IMG20240317210202-min](https://github.com/bdring/FluidNC/assets/114349329/46be4ea7-80f9-4c71-9ae9-18b39636aa3a)

**Comment by PST75** [comment]
Added note...the steppers powered on with an green LED and the power led etc. on the root controller was indicating "on", VFD powered as well

**Comment by bdring** [comment]
Let's fix the start errors first.

I see an error in your config file. For the Huanyang, the uart parameters are not indented under the uart: line. This causes all the uart parameters to issue warnings.

```yaml
Huanyang:
  uart:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: gpio.4
  baud: 9600
  mode: 8N1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%
  ```

I suggest using the new style separate uart section as described here.  

http://wiki.fluidnc.com/en/config/config_spindles#huanyang-vfd-with-rs485

```yaml
uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: gpio.4
  baud: 9600
  mode: 8N1

Huanyang:
  uart_num: 1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%

**Comment by PST75** [comment]
Thank you very much. Please see my updated file below and I will test ASAP. What about the error I got when trying to upload a new config (ref in picture incl. in my post). It was written as Returned -2 and if it happens again I will not be able to upload the corrected yaml :(


Also could this "double enter" become an issue for the config?

![Codesnip1](https://github.com/bdring/FluidNC/assets/114349329/e1871f07-3ca7-4e2e-bed8-32ac4e77a9c0)

Corrected yaml:


board: Root Controller ISO
name: QBCNC v.1.2

stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 3

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 398.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 1242.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.00
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.7:low
        direction_pin: I2SO.5:low
        disable_pin: I2SO.3:high

  y:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 1277.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.0
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.12:low
        direction_pin: I2SO.10:low
        disable_pin: I2SO.8:high

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.13:low
        direction_pin: I2SO.11:low
        disable_pin: I2SO.9:high

  z:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 80.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.0
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.18:low
        direction_pin: I2SO.16:low
        disable_pin: I2SO.14:high

i2so:
  bck_pin: gpio.22
  data_pin: gpio.12
  ws_pin: gpio.21

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.34
  cycle_start_pin: gpio.36
  macro0_pin: gpio.39
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: gpio.33
  mist_pin: gpio.13
  delay_ms: 0

probe:
  pin: gpio.27
  check_mode_start: true

macros:
  startup_line0:
  startup_line1:
  macro0: 
  macro1: 
  macro2: 
  macro3:

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: i2so.15


start:
  must_home: true

uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: gpio.4
  baud: 9600
  mode: 8N1
  
Huanyang:
  uart_num: 1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%

Laser:
  pwm_hz: 5000
  output_pin: gpio.25
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 1
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: false

**Comment by MitchBradley** [comment]
The Root Controller people told us [here](https://github.com/bdring/FluidNC/issues/1163#issuecomment-2005120039) that they offer support via email at root@rootcnc.com and Discord at https://discord.gg/93Ue5SwthW

**Comment by PST75** [comment]
@MitchBradley 

Thanks...as I'm unsure how to add the three back tics correctly (should it be both in the start and the end of the file) I have renamed the Yaml to a txt file. If possible please have a look if there is something "structually" wrong with the file. and how I have formatted it...most of it is a copy from a config downloaded from the Root Github but maybe I have mad a mess of things in the structure (even if I have not changed much)

Please have a look. Thanks :)

[QBCNCv22.txt](https://github.com/bdring/FluidNC/files/14672549/QBCNCv22.txt)

**Comment by PST75** [comment]
```
board: Root Controller ISO
name: QBCNC v.1.2

stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 3

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 398.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 1242.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.00
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.7:low
        direction_pin: I2SO.5:low
        disable_pin: I2SO.3:high

  y:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 1277.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.0
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.12:low
        direction_pin: I2SO.10:low
        disable_pin: I2SO.8:high

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.13:low
        direction_pin: I2SO.11:low
        disable_pin: I2SO.9:high

  z:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 80.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.0
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.18:low
        direction_pin: I2SO.16:low
        disable_pin: I2SO.14:high

i2so:
  bck_pin: gpio.22
  data_pin: gpio.12
  ws_pin: gpio.21

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.34
  cycle_start_pin: gpio.36
  macro0_pin: gpio.39
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: gpio.33
  mist_pin: gpio.13
  delay_ms: 0

probe:
  pin: gpio.27
  check_mode_start: true

macros:
  startup_line0:
  startup_line1:
  macro0: 
  macro1: 
  macro2: 
  macro3:

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: i2so.15


start:
  must_home: true

uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: gpio.4
  baud: 9600
  mode: 8N1
  
Huanyang:
  uart_num: 1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%

Laser:
  pwm_hz: 5000
  output_pin: gpio.25
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 1
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: false
```
