### ISSUE TITLE
Problem:" $Files/ListGcode error" codes in response UART 1 & 2

### ISSUE THREAD

**Issue by tower-guy** [bdring/FluidNC#1184]
### Wiki Search Terms

$Files/ListGcode
ListGcode

### Controller Board

home made board with bipolar drivers for noise immunity

### Machine Description

Gantry router external drivers localy mounted to steppers, vfd localy mounted to spindle

### Input Circuits

```yaml
Opto inputs
```

### Configuration file

```yaml
name: "ESP32 Dev Controller V4"
board: "ESP32 Dev Controller V4"

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16

start:
  must_home: false
  deactivate_parking: false
  check_limits: false

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 10
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: i2so.3:high
  
  x:
    steps_per_mm: 320
    max_rate_mm_per_min: 4500
    acceleration_mm_per_sec2: 500
    max_travel_mm: 540
    homing:
      cycle: 2
      mpos_mm: 10
      seek_mm_per_min: 1500
      positive_direction: false
  
    motor0:
      limit_all_pin: gpio.35:low
      hard_limits: true
      pulloff_mm: 2.000
      standard_stepper:    
        direction_pin: gpio.12
        step_pin: gpio.26
    motor1:
      null_motor:

  y:
    steps_per_mm: 400
    max_rate_mm_per_min: 4500
    acceleration_mm_per_sec2: 500
    max_travel_mm: 320
    homing:
      cycle: 2
      mpos_mm: 10
      seek_mm_per_min: 1500
      positive_direction: false

    motor0:
      limit_all_pin: gpio.34:low
      hard_limits: true
      pulloff_mm: 2.000
      standard_stepper: 
        direction_pin: gpio.14
        step_pin: gpio.25
    motor1:
      null_motor:

  z:
    steps_per_mm: 640
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 300
    max_travel_mm: 100
    homing:
      cycle: 1
      mpos_mm: 10
      seek_mm_per_min: 500
      positive_direction: true

    motor0:
      limit_all_pin: gpio.39:low
      hard_limits: true
      pulloff_mm: 2.000
      standard_stepper: 
        direction_pin: gpio.27
        step_pin: gpio.33
    motor1:
      null_motor:

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.0
  
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
   
probe:
  pin: gpio.36:low

PWM:
  pwm_hz: 5000
  output_pin: gpio.32
  enable_pin: i2so.1
  direction_pin: i2so.2
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0% 8600=50% 12500=100%

coolant:
  flood_pin: i2so.4
  mist_pin: i2so.5
  delay_ms: 0
  
uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  baud: 115200
  mode: 8N1
  
uart_channel1:
  uart_num: 1
  report_interval_ms: 0
  all_messages: false
```

### Startup Messages

```text
Resetting MCU
[MSG:INFO: uart_channel1 created]
[MSG:RST]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.0 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:10us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable I2SO.3]
[MSG:INFO: Axis X (10.000,550.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.26 Dir:gpio.12 Disable:NO_PIN]
[MSG:INFO:  X All Limit gpio.35:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (10.000,330.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.25 Dir:gpio.14 Disable:NO_PIN]
[MSG:INFO:  Y All Limit gpio.34:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (-90.000,10.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.33 Dir:gpio.27 Disable:NO_PIN]
[MSG:INFO:  Z All Limit gpio.39:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: PWM Spindle Ena:I2SO.1 Out:gpio.32 Dir:I2SO.2 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle PWM]
[MSG:INFO: Flood coolant I2SO.4]
[MSG:INFO: Mist coolant I2SO.5]
[MSG:INFO: Probe Pin: gpio.36:low]
[MSG:INFO: Connecting to STA SSID:Engine House]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.1.48]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC 3.7.13 (wifi) '$' for help]
```

### What happened?

Sent "$Files/ListGcode" to UART 1 the reply randomly indispersed with "[MSG:ERR: Device not responding]" I got the reply below same response from UART 0, 
$SD/List produces a normal response,

It really messed up my state machine I an using to strip out the file names for display on the DRO. I have modified my state machine to work with the reply from $SD/List and is working well.

Thank you for your work it is much appreciated.

reply below :

$Files/ListGcode
[MSG:JSON:{"files":[{"name":"polar_bear 4.nc","size":"212228"},{"name":"circle.txt","size":"178"},{"name":"SD_]
[MSG:ERR: Device not responding]
[MSG:JSON:49 bear(3).gcode","size":"254614"},{"name":"paul.gcode","size":"18696"},{"name":"polar bear 3mm.nc",]
[MSG:ERR: Device not responding]
[MSG:JSON:"size":"92748"},{"name":"polar bear 200mm 3.175.nc","size":"61022"},{"name":"49 polar bear 2.nc","si]
[MSG:ERR: Device not responding]
[MSG:JSON:ze":"85140"}],"path":""}]
ok

### Other Information

$Files/ListGcode
[MSG:JSON:{"files":[{"name":"polar_bear 4.nc","size":"212228"},{"name":"circle.txt","size":"178"},{"name":"SD_]
[MSG:ERR: Device not responding]
[MSG:JSON:49 bear(3).gcode","size":"254614"},{"name":"paul.gcode","size":"18696"},{"name":"polar bear 3mm.nc",]
[MSG:ERR: Device not responding]
[MSG:JSON:"size":"92748"},{"name":"polar bear 200mm 3.175.nc","size":"61022"},{"name":"49 polar bear 2.nc","si]
[MSG:ERR: Device not responding]
[MSG:JSON:ze":"85140"}],"path":""}]
ok

$Files/ListGcode
[MSG:ERR: Device not responding]
[MSG:JSON:{"files":[{"name":"polar_bear 4.nc","size":"212228"},{"name":"circle.txt","size":"178"},{"name":"SD_]
[MSG:ERR: Device not responding]
[MSG:JSON:49 bear(3).gcode","size":"254614"},{"name":"paul.gcode","size":"18696"},{"name":"polar bear 3mm.nc",]
[MSG:ERR: Device not responding]
[MSG:JSON:"size":"92748"},{"name":"polar bear 200mm 3.175.nc","size":"61022"},{"name":"49 polar bear 2.nc","si]
[MSG:ERR: Device not responding]
[MSG:JSON:ze":"85140"}],"path":""}]
ok

$SD/List
[DIR:System Volume Information]
[FILE:  IndexerVolumeGuid|SIZE:76]
[FILE: polar_bear 4.nc|SIZE:212228]
[FILE: circle.txt|SIZE:178]
[FILE: SD_49 bear(3).gcode|SIZE:254614]
[FILE: paul.gcode|SIZE:18696]
[FILE: polar bear 3mm.nc|SIZE:92748]
[FILE: polar bear 200mm 3.175.nc|SIZE:61022]
[FILE: 49 polar bear 2.nc|SIZE:85140]
[/sd/ Free:14.91 GB Used:896.00 KB Total:14.91 GB]
ok
