### ISSUE TITLE
Problem: Probing seems to incorrectly affect machine Coordinates

### ISSUE THREAD

**Issue by nicolas-lang** [bdring/FluidNC#1205]
### Wiki Search Terms

probing

### Controller Board

6-pack

### Machine Description

Gantry CNC XYYZ with external DM556T drivers, X and Y are belt driven, Z is a trapezoidal spindle. The router is a relais switched Kress.

### Input Circuits

```yaml
Touchplate on 6-pack 5v Opto input module. touchplate is 5v, tool is gnd.
Touchplate is a cooper plated FR4
```

### Configuration file

```yaml
board: 6 Pack
name: 6 Pack Ext-DMT-556T XYYZ
meta: by Nicolas Lang
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 10
  dir_delay_us: 0
  disable_delay_us: 0

start:
  must_home: false
  deactivate_parking: false
  check_limits: true

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 66.423
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 844.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.25:low
      limit_all_pin: NO_PIN
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.2:low
        direction_pin: I2SO.1:low
        disable_pin: I2SO.0:low

  y:
    steps_per_mm: 66.423
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 75.000
    max_travel_mm: 1025.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 2000.000
      settle_ms: 500

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.02:low
      limit_all_pin: NO_PIN
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.5:low
        direction_pin: I2SO.4
        disable_pin: I2SO.7:low
    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.36:low
      limit_all_pin: NO_PIN
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.10:low
        direction_pin: I2SO.9:low
        disable_pin: I2SO.8:low

  z:
    steps_per_mm: 1066.664
    max_rate_mm_per_min: 1250.000
    acceleration_mm_per_sec2: 25.000
    max_travel_mm: 100.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: -1.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 500.000
      settle_ms: 500
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.39:low
      limit_all_pin: NO_PIN
      pulloff_mm: 2.0
      standard_stepper:
        step_pin: I2SO.13:low
        direction_pin: I2SO.12
        disable_pin: I2SO.15:low

  # a:
  # steps_per_mm: 1.000
  # max_rate_mm_per_min: 5000.000
  # acceleration_mm_per_sec2: 100.000
  # max_travel_mm: 360.000
  # soft_limits: false
  # motor0:
  # step_pin: I2SO.13
  # direction_pin: I2SO.12
  # disable_pin: I2SO.15

# Input Pins 32-35
probe:
  pin: gpio.32
  #toolsetter_pin: gpio.33:low
  check_mode_start: true
  hard_stop: false

#switch:
#  pin: gpio.35
#unused input pin:
#  pin: gpio.32

# http://wiki.fluidnc.com/en/config/user_outputs
coolant:
  flood_pin: NO_PIN
  mist_pin: gpio.04
  delay_ms: 500

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.020

# M3 M5
relay:
  output_pin: gpio.13:low:pu
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 5000
  spindown_ms: 3000
  tool_num: 0
  speed_map: 0=0.000% 0=100.000% 1=100.000%
  off_on_alarm: true

user_outputs:
  #24V-1 = 26
  #24V-2 = 04
  #24V-3 = 16
  #24V-4 = 27
  #PWM1 M67 E0 Q100.0 M67 E0 Q0
  #analog0_pin: gpio.12
  #PWM2 M67 E1 Q100.0 M67 E1 Q0
  #analog1_pin: gpio.15
  #analog2_pin: NO_PIN
  #analog3_pin: NO_PIN
  #analog0_hz: 5000
  #analog1_hz: 5000
  #analog2_hz: 5000
  #analog3_hz: 5000
  #Pin-Enable M62 P0  M63 P0
  #digital0_pin: gpio.13
  #Pin-Enable M62 P1  M63 P1
  #digital1_pin: gpio.14
  #digital2_pin: NO_PIN
  #digital3_pin: NO_PIN
  #digital4_pin: gpio.26 # N/C
  #digital5_pin: gpio.04 # Mist Coolant
  # gpio.27: ATC-DustOff
  digital6_pin: gpio.27
   # gpio.16: ATC
  digital7_pin: gpio.16
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.7.17 https://github.com/bdring/FluidNC]]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]]
[MSG:INFO: Local filesystem type is littlefs]]
[MSG:INFO: Configuration file:6_Pack_Ext-DMT-556T_XYYZ.yaml]]
[MSG:INFO: Machine 6 Pack Ext-DMT-556T XYYZ]]
[MSG:INFO: Board 6 Pack]]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]]
[MSG:INFO: Stepping:I2S_stream Pulse:10us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]]
[MSG:INFO: User Digital Output:6 on Pin:gpio.27]]
[MSG:INFO: User Digital Output:7 on Pin:gpio.16]]
[MSG:INFO: Axis count 3]]
[MSG:INFO: Axis X (-844.000,0.000)]]
[MSG:INFO:   Motor0]]
[MSG:INFO:     standard_stepper Step:I2SO.2:low Dir:I2SO.1:low Disable:I2SO.0:low]]
[MSG:INFO:  X Pos Limit gpio.25:low]]
[MSG:INFO: Axis Y (-1025.000,0.000)]]
[MSG:INFO:   Motor0]]
[MSG:INFO:     standard_stepper Step:I2SO.5:low Dir:I2SO.4 Disable:I2SO.7:low]]
[MSG:INFO:  Y Pos Limit gpio.2:low]]
[MSG:INFO:   Motor1]]
[MSG:INFO:     standard_stepper Step:I2SO.10:low Dir:I2SO.9:low Disable:I2SO.8:low]]
[MSG:INFO:  Y2 Pos Limit gpio.36:low]]
[MSG:INFO: Axis Z (-101.000,-1.000)]]
[MSG:INFO:   Motor0]]
[MSG:INFO:     standard_stepper Step:I2SO.13:low Dir:I2SO.12 Disable:I2SO.15:low]]
[MSG:INFO:  Z Pos Limit gpio.39:low]]
[MSG:INFO: Kinematic system: Cartesian]]
[MSG:INFO: Relay Spindle Ena:NO_PIN Out:gpio.13:low:pu Dir:NO_PIN]]
[MSG:INFO: Using spindle Relay]]
[MSG:INFO: Mist coolant gpio.4]]
[MSG:INFO: Probe gpio.32]]
[MSG:INFO: Connecting to STA SSID:***]]
[MSG:INFO: Connecting.]]
[MSG:INFO: Connecting..]]
[MSG:INFO: Connecting...]]
[MSG:INFO: Connected - IP is ***]]
[MSG:INFO: WiFi on]]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]]
[MSG:INFO: SSDP Started]]
[MSG:INFO: HTTP started on port 80]]
[MSG:INFO: Telnet started on port 23]]
ok
```

### User Interface Software

WebUI (updated index.html.gz recently)

### What happened?

When Z-probing multiple times at the same spot, the Zm of the touchplate contact drifts.

Step by step using WebUI:
- Homed Z (Top-Z is 0 with coordinates being negative towards the workpiece/touchplate)
- Move near contact
- probe --> Zm -41.498 (OK)
- re-probe --> Zm -41.835 (off by  a bit)
- re-probe --> Zm -42.198 (off by  a bit more, and this drift would go on with repeats)
- re-Homed Z
- Move near contact
- re-probe --> Zm -41.497 (again OK, as we just freshly homed)

**My expectation would be to touch off at always the same machine-coordinates.**

I first thought /probe/hard_stop was the culprit but the issue persisted after I set it to false

to me this makes like no sense... I would assume Machine Coordinates should always be the explicit position of the spindle carrier. This would be independant of tools or tool specific offsets which are only applied to the work coordinate system... or is that assumption incorrect?
I have tired understanding the current probing code but i failed to identify if it applies to machine coordinates or work coordinates

I would appreciate if someone could confirm that probing works correctly "in general", If this it is my personal problem, I would test and debug some more myself first prior to stealing your time.

### Other Information

log:
```gcode
$HZ
<Home|MPos:0.000,0.000,-1.000|FS:165,0|WCO:0.000,0.000,-44.213>
<Home|MPos:0.000,0.000,1.013|FS:0,0|Pn:Z|Ov:100,100,100>
<Home|MPos:0.000,0.000,1.013|FS:100,0|Pn:Z>
<Home|MPos:0.000,0.000,0.687|FS:100,0>
<Home|MPos:0.000,0.000,-0.148|FS:100,0>
<Home|MPos:0.000,0.000,-0.969|FS:0,0>
<Home|MPos:0.000,0.000,-0.986|FS:0,0>
<Home|MPos:0.000,0.000,-0.268|FS:100,0>
<Home|MPos:0.000,0.000,0.564|FS:100,0>
<Home|MPos:0.000,0.000,0.998|FS:0,0|Pn:Z>
<Home|MPos:0.000,0.000,0.998|FS:100,0|Pn:Z|WCO:0.000,0.000,-44.213>
<Home|MPos:0.000,0.000,0.692|FS:100,0|Ov:100,100,100>
<Home|MPos:0.000,0.000,-0.143|FS:100,0>
<Home|MPos:0.000,0.000,-0.972|FS:0,0>
<Home|MPos:0.000,0.000,-1.001|FS:0,0>
[MSG:Homed:Z]
ok
<Idle|MPos:0.000,0.000,-1.000|FS:0,0>
<Idle|MPos:0.000,0.000,-1.000|FS:0,0>
G53 G0 z-39
ok
<Run|MPos:0.000,0.000,-1.000|FS:165,0>
<Run|MPos:0.000,0.000,-4.187|FS:915,0>
<Run|MPos:0.000,0.000,-13.314|FS:1250,0>
<Run|MPos:0.000,0.000,-23.709|FS:1250,0|WCO:0.000,0.000,-44.213>
<Run|MPos:0.000,0.000,-33.754|FS:806,0|Ov:100,100,100>
<Run|MPos:0.000,0.000,-38.740|FS:56,0>
<Idle|MPos:0.000,0.000,-39.000|FS:0,0>
G38.6 Z-40 F100 P2
[GC:G38.2 G54 G17 G21 G90 G94 M5 M9 T0 F100 S0]
<Run|MPos:0.000,0.000,-39.000|FS:100,0>
<Run|MPos:0.000,0.000,-39.781|FS:100,0>
<Run|MPos:0.000,0.000,-40.615|FS:100,0>
<Run|MPos:0.000,0.000,-41.449|FS:100,0>
<Run|MPos:0.000,0.000,-41.500|FS:100,0|Pn:P>
<Run|MPos:0.000,0.000,-41.514|FS:85,0>
<Run|MPos:0.000,0.000,-41.531|FS:70,0|Pn:P|WCO:0.000,0.000,-44.213>
[PRB:0.000,0.000,-41.498:1]
$J=G90 G21 F1000 Z3
[MSG:INFO: Probe offset applied:]
ok
<Idle|MPos:0.000,0.000,-41.733|FS:0,0|Pn:P|WCO:0.000,0.000,-43.498>
ok
<Jog|MPos:0.000,0.000,-41.733|FS:180,0|Pn:P|Ov:100,100,100>
<Jog|MPos:0.000,0.000,-41.352|FS:247,0>
<Idle|MPos:0.000,0.000,-40.497|FS:0,0>
G38.6 Z-40 F100 P2
<Run|MPos:0.000,0.000,-40.497|FS:100,0>
<Run|MPos:0.000,0.000,-41.278|FS:100,0>
<Run|MPos:0.000,0.000,-41.838|FS:100,0|Pn:P>
<Run|MPos:0.000,0.000,-41.851|FS:85,0>
<Run|MPos:0.000,0.000,-41.864|FS:70,0|Pn:P>
[PRB:0.000,0.000,-41.835:1]
$J=G90 G21 F1000 Z3
[MSG:INFO: Probe offset applied:]
ok
<Idle|MPos:0.000,0.000,-42.064|FS:0,0|Pn:P|WCO:0.000,0.000,-43.835>
ok
<Jog|MPos:0.000,0.000,-42.063|FS:180,0|Pn:P>
<Jog|MPos:0.000,0.000,-41.731|FS:260,0|Ov:100,100,100>
<Idle|MPos:0.000,0.000,-40.835|FS:0,0>
G38.6 Z-40 F100 P2
<Run|MPos:0.000,0.000,-40.835|FS:100,0>
<Run|MPos:0.000,0.000,-41.614|FS:100,0>
<Run|MPos:0.000,0.000,-42.201|FS:100,0|Pn:P>
[PRB:0.000,0.000,-42.198:1]
$J=G90 G21 F1000 Z3
[MSG:INFO: Probe offset applied:]
ok
<Idle|MPos:0.000,0.000,-42.434|FS:0,0|Pn:P|WCO:0.000,0.000,-44.198>
ok
<Jog|MPos:0.000,0.000,-42.433|FS:180,0|Pn:P>
<Jog|MPos:0.000,0.000,-42.101|FS:262,0>
<Idle|MPos:0.000,0.000,-41.198|FS:0,0>
G38.6 Z-40 F100 P2
<Run|MPos:0.000,0.000,-41.198|FS:100,0>
<Run|MPos:0.000,0.000,-41.978|FS:100,0|Ov:100,100,100>
<Run|MPos:0.000,0.000,-42.559|FS:85,0|Pn:P>
<Run|MPos:0.000,0.000,-42.573|FS:70,0>
<Run|MPos:0.000,0.000,-42.586|FS:70,0|Pn:P>
[PRB:0.000,0.000,-42.556:1]
$J=G90 G21 F1000 Z3
[MSG:INFO: Probe offset applied:]
ok
<Idle|MPos:0.000,0.000,-42.780|FS:0,0|Pn:P|WCO:0.000,0.000,-44.556>
ok
<Jog|MPos:0.000,0.000,-42.779|FS:180,0|Pn:P>
<Jog|MPos:0.000,0.000,-42.466|FS:259,0>
<Idle|MPos:0.000,0.000,-41.556|FS:0,0>
$HZ
<Home|MPos:0.000,0.000,-41.556|FS:165,0>
<Home|MPos:0.000,0.000,-38.763|FS:500,0>
<Home|MPos:0.000,0.000,-34.597|FS:500,0|Ov:100,100,100>
<Home|MPos:0.000,0.000,-30.425|FS:500,0>
<Home|MPos:0.000,0.000,-26.259|FS:500,0>
<Home|MPos:0.000,0.000,-22.087|FS:500,0>
<Home|MPos:0.000,0.000,-17.914|FS:500,0|WCO:0.000,0.000,-44.556>
<Home|MPos:0.000,0.000,-13.740|FS:500,0>
<Home|MPos:0.000,0.000,-9.576|FS:500,0>
<Home|MPos:0.000,0.000,-5.402|FS:500,0>
<Home|MPos:0.000,0.000,-1.229|FS:500,0>
<Home|MPos:0.000,0.000,0.359|FS:0,0|Pn:Z>
<Home|MPos:0.000,0.000,0.359|FS:100,0|Pn:Z|Ov:100,100,100>
<Home|MPos:0.000,0.000,0.023|FS:100,0>
<Home|MPos:0.000,0.000,-0.812|FS:100,0>
<Home|MPos:0.000,0.000,-1.628|FS:0,0>
<Home|MPos:0.000,0.000,-1.641|FS:0,0|WCO:0.000,0.000,-44.556>
<Home|MPos:0.000,0.000,-0.913|FS:100,0>
<Home|MPos:0.000,0.000,-0.078|FS:100,0>
<Home|MPos:0.000,0.000,0.331|FS:0,0|Pn:Z>
<Home|MPos:0.000,0.000,0.331|FS:100,0|Pn:Z>
<Home|MPos:0.000,0.000,0.033|FS:100,0>
<Home|MPos:0.000,0.000,-0.800|FS:100,0|Ov:100,100,100>
<Home|MPos:0.000,0.000,-1.632|FS:0,0>
<Home|MPos:0.000,0.000,-1.669|FS:0,0>
[MSG:Homed:Z]
ok
<Idle|MPos:0.000,0.000,-1.000|FS:0,0>
<Idle|MPos:0.000,0.000,-1.000|FS:0,0|WCO:0.000,0.000,-44.556>
G53 G0 z-39
ok
<Run|MPos:0.000,0.000,-1.000|FS:180,0>
<Run|MPos:0.000,0.000,-4.212|FS:915,0>
<Run|MPos:0.000,0.000,-13.357|FS:1250,0>
<Run|MPos:0.000,0.000,-23.793|FS:1250,0>
<Run|MPos:0.000,0.000,-33.787|FS:806,0>
<Run|MPos:0.000,0.000,-38.748|FS:56,0|Ov:100,100,100>
<Idle|MPos:0.000,0.000,-39.000|FS:0,0>
G38.6 Z-40 F100 P2
[GC:G38.2 G54 G17 G21 G90 G94 M5 M9 T0 F100 S0]
<Run|MPos:0.000,0.000,-39.000|FS:100,0>
<Run|MPos:0.000,0.000,-39.783|FS:100,0>
<Run|MPos:0.000,0.000,-40.615|FS:100,0|WCO:0.000,0.000,-44.556>
<Run|MPos:0.000,0.000,-41.448|FS:100,0>
<Run|MPos:0.000,0.000,-41.499|FS:100,0|Pn:P>
<Run|MPos:0.000,0.000,-41.513|FS:85,0>
<Run|MPos:0.000,0.000,-41.529|FS:70,0|Pn:P>
[PRB:0.000,0.000,-41.497:1]
$J=G90 G21 F1000 Z3
[MSG:INFO: Probe offset applied:]
ok
<Idle|MPos:0.000,0.000,-41.733|FS:0,0|Pn:P|WCO:0.000,0.000,-43.497>
ok
<Jog|MPos:0.000,0.000,-41.732|FS:180,0|Pn:P|Ov:100,100,100>
<Jog|MPos:0.000,0.000,-41.368|FS:247,0>
<Idle|MPos:0.000,0.000,-40.496|FS:0,0>
```
