### ISSUE TITLE
Problem: Homing X in >3.7.10 not working on ESP32

### ISSUE THREAD

**Issue by jkeating732** [bdring/FluidNC#1224]
### Wiki Search Terms

Not homing X axis

### Controller Board

MKS Tinybee v1.0 

### Machine Description

MPCNC Primo

### Configuration file

```yaml
board: MKS TinyBee V1.0 XXYYZ
name:
 
kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

#fan
# user_outputs:
#   digital0_pin: i2so.19

axes:
  x:
    steps_per_mm: 100
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 325.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33
      hard_limits: true
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2
        disable_pin: I2SO.0

    # use E0 driver for 2nd X axis motor
    motor1:
      limit_neg_pin: gpio.32
      hard_limits: true
      pulloff_mm: 2.000
      stepstick:
        # step_pin: I2SO.10
        # direction_pin: I2SO.11
        # disable_pin: I2SO.9
        step_pin: I2SO.4
        direction_pin: I2SO.5
        disable_pin: I2SO.3

  y:
    # steps_per_mm: 40
    # max_rate_mm_per_min: 8000.000
    # acceleration_mm_per_sec2: 70.000
    # max_travel_mm: 1250.000
    steps_per_mm: 100
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 220.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.22
      hard_limits: true
      pulloff_mm: 2.000
      stepstick:
        # step_pin: I2SO.4
        # direction_pin: I2SO.5
        # disable_pin: I2SO.3
        step_pin: I2SO.7
        direction_pin: I2SO.8
        disable_pin: I2SO.6

    # use E1 driver for 2nd Y axis motor
    motor1:
      limit_neg_pin: gpio.35
      hard_limits: true
      pulloff_mm: 2.000
      stepstick:
        # step_pin: I2SO.13
        # direction_pin: I2SO.14
        # disable_pin: I2SO.12
        step_pin: I2SO.10
        direction_pin: I2SO.11
        disable_pin: I2SO.9

  z:
    steps_per_mm: 1400.000
    max_rate_mm_per_min: 200.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 80.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      # limit_pos_pin: gpio.22:low:pu
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        # step_pin: I2SO.7
        # direction_pin: I2SO.8
        # disable_pin: I2SO.6
        step_pin: I2SO.13
        direction_pin: I2SO.14
        disable_pin: I2SO.12

i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  # uses TH2 IO34 active low - MAKE SURE jumper J2 is set to SDDET!!!
  card_detect_pin: NO_PIN

control:
  safety_door_pin: NO_PIN
  # on MT_DET connector
  reset_pin: NO_PIN
  # on TH1 connector
  feed_hold_pin: NO_PIN
  # on TB connector
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.4:low:pu
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0: $SD/Run=lasertest.gcode
  macro1: $SD/Run=home.gcode
  macro2:
  macro3:

coolant:
  # Heated Bed Terminal Block
  flood_pin: NO_PIN
  # HE0 Terminal Block
  mist_pin: NO_PIN
  delay_ms: 0

Laser:
  pwm_hz: 5000
  # Add 10K resistor between GND & Signal —> Stop laser power on at boot
  # on 3D Touch connector (has pdwn + PWM)
  output_pin: gpio.2:high:pd
  s0_with_disable: true
  disable_with_s0: true
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: true
# 135=0mA 270=5mA 400=10mA 700=16mA

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

# # spindle PWM signal
# PWM:
#   pwm_hz: 2500
#   # on EXP1 IO15 connector.
#   # note IO15 will give some short pulses on boot, which may activate spindle
#   # use IO17 on EXP1 to avoid
#   output_pin: gpio.15:high
#   s0_with_disable: true
#   tool_num: 0
#   spinup_ms: 4000
#   spindown_ms: 4000
#   speed_map: 0=0.000% 12000=100.000%

start:
  must_home: false
```

### Startup Messages

```text
Grbl 3.0 [FluidNC v3.0.x (noGit) (wifi) '$' for help]
ets Jun  8 2��00:22:57C�HH���0x1 (�]ERON_RESEU�I����0x13B�A%}MQ}1M!}BOOT)
conV�ͥ�� 0, *�]A�0xee
,k�E���0x00,\E���0x00,dE�v:0x00,cs�����0x00,h�E���0x00,wp_��:0x00
modY'T������div:1
load:0�fff0030,leK��84
!�a����0078000����13220
������1&�����4
load'��0080400,���3028
e��y 0x40080MYSH�
[MSG:INFO: FluidNC v3.0.x (noGit)  (noGit)]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine ]
[MSG:INFO: Board MKS TinyBee V1.0 XXYYZ]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33]
[MSG:INFO:   Motor1]
[MSG:INFO:     stepstick Step:I2SO.4 Dir:I2SO.5 Disable:I2SO.3]
[MSG:INFO:  X2 Neg Limit gpio.32]
[MSG:INFO: Axis Y (-220.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.7 Dir:I2SO.8 Disable:I2SO.6]
[MSG:INFO:  Y Neg Limit gpio.22]
[MSG:INFO:   Motor1]
[MSG:INFO:     stepstick Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Y2 Neg Limit gpio.35]
[MSG:INFO: Axis Z (0.000,80.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: macro0_pin gpio.4:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.2:pd Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Connecting to STA SSID:myWIFI]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.50.63]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.0 [FluidNC v3.0.x (noGit) (wifi) '$' for help]
ok
[VER:3.0 FluidNC v3.0.x (noGit):]
[OPT:PHS]
[MSG: Machine: ]
[MSG: Mode=STA:SSID=myWIFI:Status=Connected:IP=192.168.50.63:MAC=0C-8B-95-EF-B4-D0]
ok

Grbl 3.0 [FluidNC v3.0.x (noGit) (wifi) '$' for help]
```

## Summary
I have tried the latest version of the software with no luck on homing the X axis, I reverted back to 3.7.10 which was working for me and it homed as expected. I then tried the incremental release update to determine where homing broke which is with 3.7.11 and onwards.

### Commands Window
```
$G
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]
ok
<Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:0.000,0.000,0.000>
$HY
ok
<Idle|MPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100>
$HX
ok
<Idle|MPos:0.000,0.000,0.000|FS:0,0>
```
### Boot
```

Grbl 3.0 [FluidNC v3.0.x (noGit) (wifi) '$' for help]
ets Jun  8 2��00:22:57C�HH���0x1 (�]ERON_RESEU�I����0x13B�A%}MQ}1M!}BOOT)
conV�ͥ�� 0, *�]A�0xee
,k�E���0x00,\E���0x00,dE�v:0x00,cs�����0x00,h�E���0x00,wp_��:0x00
modY'T������div:1
load:0�fff0030,leK��84
!�a����0078000����13220
������1&�����4
load'��0080400,���3028
e��y 0x40080MYSH�
[MSG:INFO: FluidNC v3.0.x (noGit)  (noGit)]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine ]
[MSG:INFO: Board MKS TinyBee V1.0 XXYYZ]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33]
[MSG:INFO:   Motor1]
[MSG:INFO:     stepstick Step:I2SO.4 Dir:I2SO.5 Disable:I2SO.3]
[MSG:INFO:  X2 Neg Limit gpio.32]
[MSG:INFO: Axis Y (-220.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.7 Dir:I2SO.8 Disable:I2SO.6]
[MSG:INFO:  Y Neg Limit gpio.22]
[MSG:INFO:   Motor1]
[MSG:INFO:     stepstick Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Y2 Neg Limit gpio.35]
[MSG:INFO: Axis Z (0.000,80.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: macro0_pin gpio.4:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.2:pd Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Connecting to STA SSID:myWIFI]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.50.63]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.0 [FluidNC v3.0.x (noGit) (wifi) '$' for help]
ok
[VER:3.0 FluidNC v3.0.x (noGit):]
[OPT:PHS]
[MSG: Machine: ]
[MSG: Mode=STA:SSID=myWIFI:Status=Connected:IP=192.168.50.63:MAC=0C-8B-95-EF-B4-D0]
ok

Grbl 3.0 [FluidNC v3.0.x (noGit) (wifi) '$' for help]
```

### Commands
```
$G
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]
ok
<Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:0.000,0.000,0.000>
$HY
ok
<Idle|MPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100>
$HX
ok
<Idle|MPos:0.000,0.000,0.000|FS:0,0>
```

### Boot
```
ets Jun�2016 00:2&��SH
rst:�� (POWERON%UMQ�,boot:0�3 (SPI_FAS�e1M!}    ==Q�
configsip: b�A%]A�0xeYC�,k�E���0x�b�}����0x0b"}����0x00i�0_drv:0x00,h�E���0x00,w}�rv:0x00
m��:DIO, clock V��1
load:��fff0030,lYK�184
load'��0078000,��:13220
�
������1&�����4
l+��0x40080�blen:3028C������0x4�5e4

[MSG:INFO: FluidNC v3.0.x (noGit)  (noGit)]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine ]
[MSG:INFO: Board MKS TinyBee V1.0 XXYYZ]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33]
[MSG:INFO:   Motor1]
[MSG:INFO:     stepstick Step:I2SO.4 Dir:I2SO.5 Disable:I2SO.3]
[MSG:INFO:  X2 Neg Limit gpio.32]
[MSG:INFO: Axis Y (-220.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.7 Dir:I2SO.8 Disable:I2SO.6]
[MSG:INFO:  Y Neg Limit gpio.22]
[MSG:INFO:   Motor1]
[MSG:INFO:     stepstick Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Y2 Neg Limit gpio.35]
[MSG:INFO: Axis Z (0.000,80.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: macro0_pin gpio.4:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.2:pd Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Connecting to STA SSID:myWIFI]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.50.63]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.0 [FluidNC v3.0.x (noGit) (wifi) '$' for help]
ok
[VER:3.0 FluidNC v3.0.x (noGit):]
[OPT:PHS]
[MSG: Machine: ]
[MSG: Mode=STA:SSID=myWIFI:Status=Connected:IP=192.168.50.63:MAC=0C-8B-95-EF-B4-D0]
```
