### ISSUE TITLE
Problem: CL86T v4.1 external driver Timing config, Startup error using ":pu" or the CNC will not move. 

### ISSUE THREAD

**Issue by Red5-3D** [bdring/FluidNC#1238]
### Wiki Search Terms

Controller timings, Controller enable, MKS tiny bee external controllers. 

### Controller Board

MKS TinyBee 

### Machine Description

CNC conversion to an import mill. Same size and most of the parts as a Grizzly G0704 mill. 3 axis, 3 stepperonline closed loop Nema 34 motors with Stepperonline CL86T V4.1 closed loop drivers. Each stepper/controller came as a kit from stepperonline. I am using the external stepper pins on the MKS tinybee board where all share a common ground.   Steppers are direct drive to ballscrews.

### Configuration file

```yaml
: MKS TinyBee V1.0_001
name: Mill
meta: (6.7.2024) by Red5
kinematics:
  cartesian:


#uart1:
  #txd_pin: gpio.17
  #rxd_pin: gpio.16
  #rts_pin: NO_PIN
  #cts_pin: NO_PIN
  #baud: 1000000
  #mode: 8N1

#uart_channel1:
  #report_interval_ms: 75
  #uart_num: 1

stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 2
  disable_delay_us: 200000
  segments: 12

axes:
  x:
    steps_per_mm: 640
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 39
    max_travel_mm: 465
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 300
      seek_mm_per_min: 1200
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1

    motor0:
      limit_neg_pin: gpio.33:high:pd
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2
      standard_stepper:
        step_pin: i2so.1
        direction_pin: i2so.2
        disable_pin: i2so.0:low:pu
      

  y:
    steps_per_mm: 640
    max_rate_mm_per_min: 1200
    acceleration_mm_per_sec2: 39
    max_travel_mm: 130
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0
      feed_mm_per_min: 300
      seek_mm_per_min: 1000
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.32:high:pd
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3
      standard_stepper:
        step_pin: i2so.4:low
        direction_pin: i2so.5
        disable_pin: i2so.3:low:pu


  z:
    steps_per_mm: 640
    max_rate_mm_per_min: 800
    acceleration_mm_per_sec2: 25
    max_travel_mm: 150
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0
      feed_mm_per_min: 300
      seek_mm_per_min: 900
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.22:high:pd
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      standard_stepper:
        step_pin: i2so.7:low
        direction_pin: i2so.8
        disable_pin: i2so.6:low:pu
probe:
  pin: gpio.35:low
  toolsetter_pin: NO_PIN
  check_mode_start: true
  hard_stop: true

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16

i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: gpio.34:low
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.4:pu:low
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: NO_PIN
macros:
  macro0: $SD/Run=lasertest.gcode
  macro1: $SD/Run=home.gcode
coolant:
  # Heated Bed Terminal Block
  flood_pin: i2so.16
  # HE0 Terminal Block
  mist_pin: i2so.17
  delay_ms: 0

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
start:
  must_home: true
#PWM:
  #pwm_hz: 5000
  #direction_pin: NO_PIN
  #output_pin: gpio.32
  #enable_pin: gpio.27
  #disable_with_s0: false
  #s0_with_disable: true
  #spinup_ms: 0
  #spindown_ms: 0
  #tool_num: 0
  #speed_map: 0=0.000% 10000=100.000%
```

### Startup Messages

```text
$Report/Interval=50
$G
[MSG:INFO: websocket auto report interval set to 50 ms]
ok
<Alarm|MPos:0.000,0.000,0.000|FS:0,0|WCO:330.300,-105.300,-109.600>
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]
ok
<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100|A:>
$ss
[MSG:INFO: FluidNC v3.7.17 https://github.com/bdring/FluidNC]]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]]
[MSG:INFO: Local filesystem type is littlefs]]
[MSG:INFO: Configuration file:Bees_active.yaml]]
[MSG:ERR: ERR: i2so.0:low:pu - Unsupported I2SO option 'pu]
  y:
    steps_per_mm: 640
      positive_direction: true
      mpos_mm: 0
[MSG:INFO: UART1 Tx:gpio.17 Rx:gpio.16 RTS:NO_PIN Baud:1000000]]
[MSG:INFO: uart_channel1 created at report interval: 75]]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:gpio.34:low freq:8000000]]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:200000us Dir Delay:2us Idle Delay:250ms]]
[MSG:INFO: Axis count 3]]
[MSG:INFO: Axis X (0.000,465.000)]]
[MSG:INFO:   Motor0]]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2 Disable:NO_PIN]]
[MSG:INFO:  X Neg Limit gpio.33:pd]]
[MSG:INFO: Axis Y (-130.000,0.000)]]
[MSG:INFO:   Motor0]]
[MSG:INFO:     standard_stepper Step:I2SO.4:low Dir:I2SO.5 Disable:I2SO.3:low]]
[MSG:INFO:  Y Pos Limit gpio.32:pd]]
[MSG:INFO: Axis Z (-150.000,0.000)]]
[MSG:INFO:   Motor0]]
[MSG:INFO:     standard_stepper Step:I2SO.7:low Dir:I2SO.8 Disable:I2SO.6:low]]
[MSG:INFO:  Z Pos Limit gpio.22:pd]]
[MSG:INFO: macro0_pin gpio.4:low:pu]]
[MSG:INFO: Kinematic system: Cartesian]]
[MSG:INFO: Connecting to STA SSID:Dockingbay94]]
[MSG:INFO: Connecting.]]
[MSG:INFO: Connecting..]]
[MSG:INFO: Connected - IP is 192.168.50.40]]
[MSG:INFO: WiFi on]]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]]
[MSG:INFO: SSDP Started]]
[MSG:INFO: HTTP started on port 80]]
[MSG:INFO: Telnet started on port 23]]
```

### User Interface Software

Web Ui, also G sender

### What happened?

I had problems getting the .yaml file setup to make the mill move.  At first all the CNC would do nothing trying to jog. I had no limit switches set up at that time.  I could double click on a movement and it would move but not consistently. Sometimes when choosing 30mm jog it would move with one click. I worked on the stepping: section setup to my external controller specs and that seemed to help but did not resolve the issue. I tried many things and the one that seemed to work was the disable_pin: set to :low and :pu.  
Having "pu gives me at startup error but without it jogging or now that I have endstops homing doesn't work.  
If I have only one axis with :pu  and not on the others only the axis with "pu will Jog.   
The CNC mill will run gcode and cut parts as expected. Over the last couple weeks I needed to make hundreds of profile cuts on parts and the code runs fine.  Every time I start it up I just have to clear the start error in the "Tablet" tab >menu>Reset then Unlock. 

https://www.omc-stepperonline.com/index.php?route=product/product/get_file&file=3130/CL86T-V4.1%20Manual.pdf  

Controller manual pdf link. 

One option presented on Discord was to leave the enables unconnected on the drivers. Will this limit an E-stop function?
