### ISSUE TITLE
Error Message: Ignored key SingleArmScara

### ISSUE THREAD

**Issue by neurg** [bdring/FluidNC#1260]
### Wiki Search Terms

scara, SingleArmScara, kinematics

### Controller Board

ESP32Duino

### Machine Description

two stepper motors nema17 with arduino cnc shield and A4988 drivers.

### Configuration file

```yaml
board: ESPDUINO-32
name: PANT.S.

kinematics:
  SingleArmScara:
    upper_arm_mm: 120.000000
    forearm_mm: 120.000000
    segment_mm: 1.000000
    elbow_motor: false
    orientation: 0.000000

axes:
  shared_stepper_disable_pin: gpio.12:high
  
  x:
    steps_per_mm: 17.778
    max_rate_mm_per_min: 100000
    acceleration_mm_per_sec2: 5000
    max_travel_mm: 1000
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false
    
    motor0:
      stepstick:
        direction_pin: gpio.16
        step_pin: gpio.26

  y:
    steps_per_mm: 17.778
    max_rate_mm_per_min: 100000
    acceleration_mm_per_sec2: 5000
    max_travel_mm: 1000
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
      stepstick:
        direction_pin: gpio.27
        step_pin: gpio.25

  z:
    steps_per_mm: 17.778
    max_rate_mm_per_min: 100000
    acceleration_mm_per_sec2: 5000
    max_travel_mm: 1000
    homing:
      cycle: 1
      mpos_mm: 10
      positive_direction: true

    motor0:
      stepstick:
        direction_pin: gpio.14
        step_pin: gpio.17

  a:
    steps_per_mm: 17.778
    max_rate_mm_per_min: 100000
    acceleration_mm_per_sec2: 5000
    max_travel_mm: 1000
    homing:
      cycle: 1
      mpos_mm: 10
      positive_direction: true

    motor0:
      stepstick:
        direction_pin: gpio.18
        step_pin: gpio.19
```

### Startup Messages

```text
[MSG:INFO: uart_channel0 created]
[MSG:RST]
[MSG:INFO: FluidNC v3.7.18 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:ERR: Ignored key SingleArmScara]
[MSG:ERR: Skipping key upper_arm_mm indent 4 this indent 2]
[MSG:ERR: Skipping key forearm_mm indent 4 this indent 2]
[MSG:ERR: Skipping key segment_mm indent 4 this indent 2]
[MSG:ERR: Skipping key elbow_motor indent 4 this indent 2]
[MSG:ERR: Skipping key orientation indent 4 this indent 2]
[MSG:INFO: Machine PANT.S.]
[MSG:INFO: Board ESPDUINO-32]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 4]
[MSG:INFO: Shared stepper disable gpio.12]
[MSG:INFO: Axis X (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.26 Dir:gpio.16 Disable:NO_PIN]
[MSG:INFO: Axis Y (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.25 Dir:gpio.27 Disable:NO_PIN]
[MSG:INFO: Axis Z (-990.000,10.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.17 Dir:gpio.14 Disable:NO_PIN]
[MSG:INFO: Axis A (-990.000,10.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.19 Dir:gpio.18 Disable:NO_PIN]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

FluidTerm

### What happened?

Hi there.
I am new with fluidnc. I would like to control an elbow and shoulder with two stepper motors, similar to documentation link [here](http://wiki.fluidnc.com/en/features/kinematics/single_arm_scara). I used the Kinematic mentioned in that link. Using ESP32Duino with Nema17 and A4988 drivers on a cnc shield, I setup fluidnc v3.7.18 in Mac OS. When loading the yaml file I get the error:

 [MSG:ERR: Ignored key SingleArmScara]

It seems that SingleArmScara method is missing in the code. Is this feature under development? Would you recommend I proceed using fluidnc with this functionality?
