### ISSUE TITLE
Problem: config. yaml file

### ISSUE THREAD

**Issue by Hooks321** [bdring/FluidNC#1275]
### Wiki Search Terms

yaml file help.

### Controller Board

6 pack controller esp-wroom-32

### Machine Description

Gantry laser 1300x900 diode 10w output.

### Input Circuits

```yaml
?
```

### Configuration file

```yaml
Wont paste.
```

### Startup Messages

```text
machine won't move.
```

### What happened?

Machine won't move.

### Other Information

Just need a standard laser config.yaml file/ 3 axis suit 10w diode laser/ motor steps-533.366616 . used for cutting and engraving.

**Comment by bdring** [comment]
We need to see your existing config file to be able to help.

Please cut and paste on a reply.

**Comment by Hooks321** [comment]
[Laser Home XYZ.txt](https://github.com/user-attachments/files/16401896/Laser.Home.XYZ.txt)

**Comment by Hooks321** [comment]
![20240728_111753](https://github.com/user-attachments/assets/80b2d064-60e7-45ce-97ac-cf91619407be)
This is the boardThat I am trying to use.

**Comment by bdring** [comment]
I have no knowledge of that controller. It is not on our [known hardware](http://wiki.fluidnc.com/en/hardware/existing_hardware) list.

Can you provide links to the schematic, datasheet and where you got it. Have you contacted the supplier for help?

I am pasting your file here. It has a lot of NO_PIN values, that we cannot help you with.

```yaml
board: 6 Pack
name:Laser Home XYZ
meta: 2024 Gary
stepping:
  engine: I2S_stream
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
  segments: 12

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 533.366616
    max_rate_mm_per_min: 4000.000
    acceleration_mm_per_sec2: 80.000
    max_travel_mm: 900.000
    soft_limits: true
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 3.000
      stepstick:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: I2SO.3
        reset_pin: NO_PIN

  y:
    steps_per_mm: 533.366616
    max_rate_mm_per_min: 4000.000
    acceleration_mm_per_sec2: 80.000
    max_travel_mm: 1300.000
    soft_limits: true
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: I2SO.6
        reset_pin: NO_PIN

  z:
    steps_per_mm: 533.366616
    max_rate_mm_per_min: 4000.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 20.000
    soft_limits: true
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

start:
  must_home: false

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
NoSpindle:
```
