### ISSUE TITLE
 Jaki czytnik karta micro SD  działa prawidłowo  na gołym ESP32 38 PIN

### ISSUE THREAD

**Issue by qulet** [bdring/FluidNC#1304]
### Wiki Search Terms

Karta SD 
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
  

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  # frequency hz: 10000000 różne wartości tego parametru  nie rozwiązują problemu....

### Controller Board

ESP 32 38 PIN

### Machine Description

Sterowanie routerem  4osiowym sterowniki TB6600 wszystkie funkcje działają - ale karta SD stanowi problem.

### Input Circuits

```yaml
nie stanowią problemu
```

### Configuration file

```yaml
ame: "ESP32 V4"
board: "ESP32"
meta: "N_ver"

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN

  x:
    steps_per_mm: 214
    max_rate_mm_per_min: 200.000
    acceleration_mm_per_sec2: 20.000
    max_travel_mm: 190.000
    homing:
      cycle: 2
      mpos_mm: -3.000
      feed_mm_per_min: 100.000
      positive_direction: false
    
    motor0:
      limit_all_pin: gpio.34:low
      hard_limits: false
      pulloff_mm: 3.000
      stepstick:
        direction_pin: gpio.14
        step_pin: gpio.15

  y:
    steps_per_mm: 214
    max_rate_mm_per_min: 200
    acceleration_mm_per_sec2: 20
    max_travel_mm: 120
    homing:
      cycle: 2
      mpos_mm: -3
      positive_direction: false
    
    motor0:
      limit_all_pin: gpio.39:low
      hard_limits: false
      pulloff_mm: 3
      stepstick:
        direction_pin: gpio.27
        step_pin: gpio.13

  z:
    steps_per_mm: 319
    max_rate_mm_per_min: 200
    acceleration_mm_per_sec2: 25
    max_travel_mm: 75
    homing:
      cycle: 1
      mpos_mm: 3
      positive_direction: true
    
    motor0:
      limit_all_pin: gpio.36:low
      hard_limits: false
      pulloff_mm: 3
      stepstick:
        direction_pin: gpio.26
        step_pin: gpio.12

  a:
    steps_per_mm: 89
    max_rate_mm_per_min: 200
    acceleration_mm_per_sec2: 25
    max_travel_mm: 365
    
    motor0:
      stepstick:
        direction_pin: gpio.32
        step_pin: gpio.33

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
  

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  # frequency_hz: 10000000

coolant:
  flood_pin: gpio.4

probe:
  pin: gpio.16:low:pu

user_outputs:
  digital0_pin: gpio.25

PWM:
  pwm_hz:10000
  output_pin: gpio.2
  enable_pin: gpio.17
  disable_with_s0: false
  s0_with_disable: true
  speed_map: 0=0% 0=25% 6000=25% 24000=100%
```

### Startup Messages

```text
mands
$G
$SS
$SS
[MSG:INFO: FluidNC v3.8.2-pre https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:4axis_v4.yaml]
[MSG:INFO: Machine ESP32 V4]
[MSG:INFO: Board ESP32]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: User Digital Output:0 on Pin:gpio.25]
[MSG:INFO: Axis count 4]
[MSG:INFO: Axis X (-3.000,187.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.15 Dir:gpio.14 Disable:NO_PIN]
[MSG:INFO:  X All Limit gpio.34:low]
[MSG:INFO: Axis Y (-3.000,117.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.13 Dir:gpio.27 Disable:NO_PIN]
[MSG:INFO:  Y All Limit gpio.39:low]
[MSG:INFO: Axis Z (-72.000,3.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.12 Dir:gpio.26 Disable:NO_PIN]
[MSG:INFO:  Z All Limit gpio.36:low]
[MSG:INFO: Axis A (-365.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.33 Dir:gpio.32 Disable:NO_PIN]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:Orange_Swiatlowod_D290]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.1.22]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: PWM Spindle Ena:gpio.17 Out:gpio.2 Dir:NO_PIN Freq:10000Hz Period:4095]
[MSG:INFO: Flood coolant gpio.4]
[MSG:INFO: Probe gpio.16:low:pu]
```

### User Interface Software

webui

### What happened?

Na kartę mogę wgrywać programy *.NC  ale nie mogę ich uuchamiać :
ERROR:66
Failed to open file

### Other Information

wyprubowałem już dwa czytniki:
![IMG20240831215117](https://github.com/user-attachments/assets/ffd2b966-def1-4b25-b220-3154b83b2806)
![IMG20240831215208](https://github.com/user-attachments/assets/ab280c3b-7139-4cba-8362-54955687d052)
Jeden i drugi nie pozwala odczytać pliku *.Nc
