### ISSUE TITLE
Problem: GCode Logic has problems and throes errors

### ISSUE THREAD

**Issue by projecjeff** [bdring/FluidNC#1312]
### Wiki Search Terms

I am using the egsamles you supplied on the wiki page of the manual

### Controller Board

My own board using latese Ver 3.8.2  installed via Web installer

### Machine Description

3 Axis Router

### Configuration file

```yaml
board: Projec
name: PRJ XYZABC DEV ATC V4PCB

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false

start:
  must_home: false
  deactivate_parking: false
  check_limits: false


stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 10
  dir_delay_us: 5
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 180.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1:low		
        disable_pin: I2SO.0

  y:
    steps_per_mm: 180.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.32
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7

  z:
    steps_per_mm: 180.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8

  a:
    steps_per_mm: 180.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15     

  b:
    steps_per_mm: 180.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.18
        direction_pin: I2SO.17
        disable_pin: I2SO.16   

  c:
    steps_per_mm: 180.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.21
        direction_pin: I2SO.20
        disable_pin: I2SO.23          

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

# CH 1 is generaly used for Remote I/O ETC
uart1:
  txd_pin: gpio.14
  rxd_pin: gpio.13
  rts_pin: gpio.12
  baud: 115200
  mode: 8N1
  
uart_channel1:
  uart_num: 1
  report_interval_ms: 75
  message_level: info
  
# CH 2 is generaly used for BT Module and Pendant
uart2:
  txd_pin: gpio.25
  rxd_pin: gpio.26
  baud: 115200
  mode: 8N1
  
uart_channel2:
   uart_num: 2
   report_interval_ms: 75
   message_level: info


control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN


probe:
  pin: NO_PIN
  check_mode_start: false


macros:
  startup_line0:
  startup_line1:
  macro0: $H&g10 P1 L20 x-2 y1200 z5
  macro1: g53 g0 x0 y-5 z-10
  macro2: g53 g0 x0 y-1205 z-10
  macro3: g53 g0 z-10

  
coolant:
#First Relay O/P RL1 Pin 1
  flood_pin: I2SO.28
  mist_pin:  NO_PIN
  delay_ms: 0


user_outputs:
#Fet Outputs  M62 P0  turn ON Digital0  , M63 P0  turn OFF Digital0  
  digital0_pin: I2SO.24
  digital1_pin: I2SO.25
  digital2_pin: I2SO.26
  digital3_pin: I2SO.27
#Relay Outputs First Used for Coolant .. So below Relays 2 to 4  M62 P4  turn ON Digital4  , M63 P4  turn OFF Digital4  
  digital4_pin: I2SO.29
  digital5_pin: I2SO.30
  digital6_pin: I2SO.31
  
  
# 16 is used for PWM D/A 0 to 10v
# 15 is used for Fowward , is2o.22 for Rev
10V:
  pwm_hz: 5000
  output_pin: gpio.16
  forward_pin: gpio.15
  reverse_pin: I2SO.22
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 1000
  spindown_ms: 1000
  tool_num: 0
  speed_map: 0=0.000% 1000=5.600% 21300=100.000%
```

### Startup Messages

```text
> $bye
> $J=G21G91X20F4000
[MSG:INFO: Restarting]
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13260
load:0x40080400,len:3028
entry 0x400805e4
[MSG:INFO: uart_channel0 created]
[MSG:RST]
[MSG:INFO: FluidNC v3.8.2 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine PRJ XYZABC DEV ATC V4PCB]
[MSG:INFO: Board Projec]
[MSG:INFO: UART1 Tx:gpio.14 Rx:gpio.13 RTS:gpio.12 Baud:115200]
[MSG:INFO: UART2 Tx:gpio.25 Rx:gpio.26 RTS:NO_PIN Baud:115200]
[MSG:INFO: uart_channel1 created at report interval: 75]
[MSG:INFO: uart_channel2 created at report interval: 75]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_stream Pulse:10us Dsbl Delay:0us Dir Delay:5us Idle Delay:255ms]
[MSG:INFO: User Digital Output:0 on Pin:I2SO.24]
[MSG:INFO: User Digital Output:1 on Pin:I2SO.25]
[MSG:INFO: User Digital Output:2 on Pin:I2SO.26]
[MSG:INFO: User Digital Output:3 on Pin:I2SO.27]
[MSG:INFO: User Digital Output:4 on Pin:I2SO.29]
[MSG:INFO: User Digital Output:5 on Pin:I2SO.30]
[MSG:INFO: User Digital Output:6 on Pin:I2SO.31]
[MSG:INFO: Axis count 6]
[MSG:INFO: Axis X (-150.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.1:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33]
[MSG:INFO: Axis Y (-150.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.5 Dir:I2SO.4 Disable:I2SO.7]
[MSG:INFO:  Y Neg Limit gpio.32]
[MSG:INFO: Axis Z (-150.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.9 Disable:I2SO.8]
[MSG:INFO:  Z Neg Limit gpio.35]
[MSG:INFO: Axis A (-150.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.12 Disable:I2SO.15]
[MSG:INFO: Axis B (-150.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.18 Dir:I2SO.17 Disable:I2SO.16]
[MSG:INFO: Axis C (-150.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.21 Dir:I2SO.20 Disable:I2SO.23]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.1.200 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: 10V Spindle Ena:NO_PIN Out:gpio.16 Dir:NO_PIN Fwd:gpio.15 Rev:I2SO.22 Freq:5000Hz Period:8191]
[MSG:INFO: Flood coolant I2SO.28]

Grbl 3.8 [FluidNC v3.8.2 (noradio) '$' for help]
ok
```

### User Interface Software

Universal Gcode sender UGS V2.1.6

### What happened?

I am testing the new Flow control options. and if I try the egsamples supplyed on the wiki.fluidnc.com  most dont work or through errors only a couple do work.

All outher functionalaty works OK

Am i doing somthing wrong or is there some bugs
I am trying to use a mix of the logic commands.

The work you are doing is amazing thanks

### GCode File

Looping test..
Gcode..
#<_times>=4
o101 repeat[#<_times>]
  G91 G1 X5 F500
o101 endrepeat

Result ..
> #<_times>=4
> o101repeat[#<_times>]
> G91G1X5F500
> o101endrepeat
ok
*** The communicator has been paused
error:177
[MSG:ERR: Flow Control Not Executing Macro]
ok
error:177

**** Finished sending file in 00:00:00 ****

ERR: Flow Control Not Executing Macro

------- This on also --
G91
F500
#<_x> = 0
o101 while [#<_x> LT 10]
  G1 X5
  #<_x> = [#<-x>+1]
o101 endwhile

Result..
> G91
> F500
> #<_x>=0
> o101while[#<_x>LT10]
> G1X5
> #<_x>=[#<-x>+1]
> o101endwhile
ok
ok
*** The communicator has been paused
error:180
*** The communicator has been paused
[MSG:ERR: Parameter Assignment Failed]
error:177
[MSG:ERR: Flow Control Not Executing Macro]
ok
*** The communicator has been paused
error:2
[MSG:ERR: Bad GCode number format]
error:177

**** Finished sending file in 00:00:00 ****

ERR: Flow Control Not Executing Macro
