### ISSUE TITLE
Problem: Crash/stalling during Web UI page reload

### ISSUE THREAD

**Issue by J3olk** [bdring/FluidNC#1315]
### Wiki Search Terms

Stalling, backtrace, $HTTP/BlockDuringMotion

### Controller Board

Custom Board

### Machine Description

4 axis, pwm spindle

### Configuration file

```yaml
board: Custom
name: Machine
meta: Machine

arc_tolerance_mm: 0.005
junction_deviation_mm: 0.02
verbose_errors: true
report_inches: false
use_line_numbers: true

stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 640.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 225.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 400.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.0
        direction_pin: I2SO.1
        disable_pin: NO_PIN

  y:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 140.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 400.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.3:low
        disable_pin: NO_PIN

  z:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 35.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 400.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.4
        direction_pin: I2SO.5
        disable_pin: NO_PIN
        
  a:
    steps_per_mm: 28.444
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 720.000
    soft_limits: false
    homing:
      cycle: -1
      allow_single_axis: false
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: I2SO.6
        direction_pin: I2SO.7
        disable_pin: NO_PIN

kinematics:
  Cartesian:

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

i2c0:
   sda_pin: gpio.15
   scl_pin: gpio.4

oled:
   i2c_num: 0
   i2c_address: 60
   width: 128
   height: 64
   radio_delay_ms: 3000
   
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5
  frequency_hz: 20000000

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN

status_outputs:
  report_interval_ms: 100
  idle_pin: NO_PIN
  run_pin: NO_PIN
  hold_pin: NO_PIN
  alarm_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

probe:
  pin: gpio.39:low
  check_mode_start: false

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

start:
  must_home: true
  deactivate_parking: false
  check_limits: false

PWM:
  pwm_hz: 5000
  output_pin: gpio.26
  enable_pin: gpio.25
  direction_pin: NO_PIN
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 1000
  spindown_ms: 1000
  tool_num: 0
  speed_map: 0=0.000% 10000=100.000%
  off_on_alarm: true

parking:
  enable: false
  axis: Z
  pullout_distance_mm: 5.000
  pullout_rate_mm_per_min: 300.000
  target_mpos_mm: -5.000
  rate_mm_per_min: 800.000
```

### Startup Messages

```text
$SS
[MSG:INFO: FluidNC v3.8.2 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine Machine]
[MSG:INFO: Board Custom]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:20000000]
[MSG:INFO: I2C SDA: gpio.15, SCL: gpio.4, Freq: 100000, Bus #: 0]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 4]
[MSG:INFO: Axis X (0.000,225.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.0 Dir:I2SO.1 Disable:NO_PIN]
[MSG:INFO: Axis Y (0.000,140.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.3:low Disable:NO_PIN]
[MSG:INFO: Axis Z (-35.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5 Disable:NO_PIN]
[MSG:INFO: Axis A (0.000,720.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.6 Dir:I2SO.7 Disable:NO_PIN]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:POCO]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.162.99]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: OLED I2C address: 0x3c width: 128 height: 64]
[MSG:ERR: OLED is not responding]
[MSG:INFO: Status outputs Interval:100 Idle:NO_PIN Cycle:NO_PIN Hold:NO_PIN Alarm:NO_PIN]
[MSG:INFO: PWM Spindle Ena:gpio.25 Out:gpio.26 Dir:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Probe gpio.39:low]
ok
```

### User Interface Software

WebUI, FluidTerm

### What happened?

Reloading the Web UI page while job is running from SD card leads to a crash when the setting `$HTTP/BlockDuringMotion=ON` is enabled.
The reload page is not displayed, so I can't set the hold status before load a file from the local FLASH filesystem. After restart esp32 skipping config file.

### Other Information

```
[MSG:INFO: Caution: Unlocked]
<Run|MPos:-8.863,21.266,2.000,0.000|FS:822,9000|Pn:P|WCO:0.000,0.000,0.000,0.000|SD:0.47,/sd/Work.tap>
[MSG:INFO: WebUI: Request from 192.168.162.81]
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400f9f23  PS      : 0x00060430  A0      : 0x80107f9f  A1      : 0x3ffb2130
A2      : 0x00000000  A3      : 0x49489d35  A4      : 0x00000000  A5      : 0x00000004
A6      : 0x00000000  A7      : 0x00060023  A8      : 0x00000001  A9      : 0x00000001
A10     : 0x00000001  A11     : 0x00800000  A12     : 0x3ffc84bc  A13     : 0x00060423
A14     : 0x00060420  A15     : 0x00000001  SAR     : 0x0000001d  EXCCAUSE: 0x0000001c
EXCVADDR: 0x0000001d  LBEG    : 0x4008c074  LEND    : 0x4008c07f  LCOUNT  : 0x00000000


Backtrace: 0x400f9f20:0x3ffb2130 0x40107f9c:0x3ffb2150 0x400fd587:0x3ffb21b0 0x400fdbee:0x3ffb21d0 0x400fdebf:0x3ffb2210 0x400ee050:0x3ffb2250 0x40129151:0x3ffb2290




ELF file SHA256: 0828a1989017003c

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13260
load:0x40080400,len:3028
entry 0x400805e4
[MSG:INFO: uart_channel0 created]
[MSG:RST]
[MSG:INFO: FluidNC v3.8.2 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:ERR: Skipping configuration file due to panic]
[MSG:INFO: Using default configuration]
[MSG:INFO: Axes: using defaults]
[MSG:INFO: Machine Default (Test Drive)]
[MSG:INFO: Board None]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:POCO]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.162.99]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.8 [FluidNC v3.8.2 (noradio) '$' for help]
[MSG:ERR: Configuration is invalid. Check boot messages for ERR's.]

```
