### ISSUE TITLE
Problem: Curious Axis Behavior (FluidNC 3.9.1)

### ISSUE THREAD

**Issue by KarglFeinmechanik** [bdring/FluidNC#1385]
### Wiki Search Terms

motor, stepper, limit, stallguard, config, configuration, tmc2130, Enable, Disable

### Controller Board

6-pack V1p8

### Machine Description

6 Individual Axis (Nema 17's, Nema 8's) 6x TMC2130 in SPI Configuration 
Firmware before, where everything was ok: 3.7.11

### Input Circuits

```yaml
n.A. Stallguard Hardware Jumpers Installed
```

### Configuration file

```yaml
board: 6 Pack V1p8
name: KRAgilus
stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 8000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 800.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 3.000

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.33:low:pu
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2.000
      tmc_2130:
        cs_pin: i2so.3
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0
        spi_index: -1
        r_sense_ohms: 0.110
        run_amps: 1.000
        hold_amps: 0.250
        microsteps: 16
        stallguard: 0
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: false

  y:
    steps_per_mm: 800.000
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 180.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 90.000
      feed_mm_per_min: 800.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 3.000

    motor0:
      limit_neg_pin: gpio.32:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      tmc_2130:
        cs_pin: i2so.6
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7
        spi_index: -1
        r_sense_ohms: 0.110
        run_amps: 1.000
        hold_amps: 0.250
        microsteps: 16
        stallguard: 0
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: false

  z:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 75.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 2.000

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.35:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2.000
      tmc_2130:
        cs_pin: i2so.11
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8
        spi_index: -1
        r_sense_ohms: 0.110
        run_amps: 0.800
        hold_amps: 0.250
        microsteps: 16
        stallguard: 0
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: false
        
  a:
    steps_per_mm: 200
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 120.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 600.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.34:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 0.100
      tmc_2130:
        cs_pin: i2so.14
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15
        spi_index: -1
        r_sense_ohms: 0.110
        run_amps: 0.600
        hold_amps: 0.050
        microsteps: 16
        stallguard: 0
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: false

  b:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 190.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 95.000
      feed_mm_per_min: 400.000
      seek_mm_per_min: 400.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: gpio.39:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 0.100
      tmc_2130:
        cs_pin: i2so.19
        step_pin: I2SO.18
        direction_pin: I2SO.17
        disable_pin: I2SO.16
        spi_index: -1
        r_sense_ohms: 0.110
        run_amps: 0.250
        hold_amps: 0.050
        microsteps: 16
        stallguard: 0
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: false
        
  c:      
    steps_per_mm: 90.000
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 720.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 360.000
      feed_mm_per_min: 800.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: gpio.36:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 0.100
      tmc_2130:
        cs_pin: i2so.22
        step_pin: I2SO.21
        direction_pin: I2SO.20
        disable_pin: I2SO.23
        spi_index: -1
        r_sense_ohms: 0.110
        run_amps: 0.250
        hold_amps: 0.050
        microsteps: 16
        stallguard: 0
        stallguard_debug: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: false
        

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: i2so.24
  mist_pin: i2so.27
  delay_ms: 0

probe:
  pin: NO_PIN
  check_mode_start: true


macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:


start:
  must_home: false
  deactivate_parking: true
  check_limits: false

PWM:
  pwm_hz: 5000
  output_pin: gpio.14
  enable_pin: gpio.13
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 1000
  spindown_ms: 1000
  tool_num: 0
  speed_map: 0=0.000% 5000=100.000%
```

### Startup Messages

```text
$SS
[MSG:INFO: FluidNC v3.9.1 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:AgilusV2.yaml]
[MSG:INFO: Machine KRAgilus]
[MSG:INFO: Board 6 Pack V1p8]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_STREAM Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 6]
[MSG:INFO: Axis X (150.000,450.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.2 Dir:I2SO.1 CS:I2SO.3 Disable:I2SO.0 Index:-1 R:0.110]
[MSG:INFO: X Pos Limit gpio.33:low:pu]
[MSG:INFO: Axis Y (-90.000,90.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.5 Dir:I2SO.4 CS:I2SO.6 Disable:I2SO.7 Index:-1 R:0.110]
[MSG:INFO: Y Neg Limit gpio.32:low:pu]
[MSG:INFO: Axis Z (-225.000,75.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.10 Dir:I2SO.9 CS:I2SO.11 Disable:I2SO.8 Index:-1 R:0.110]
[MSG:INFO: Z Pos Limit gpio.35:low]
[MSG:INFO: Axis A (0.000,120.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.13 Dir:I2SO.12 CS:I2SO.14 Disable:I2SO.15 Index:-1 R:0.110]
[MSG:INFO: A Pos Limit gpio.34:low]
[MSG:INFO: Axis B (95.000,285.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.18 Dir:I2SO.17 CS:I2SO.19 Disable:I2SO.16 Index:-1 R:0.110]
[MSG:INFO: B Neg Limit gpio.39:low]
[MSG:INFO: Axis C (360.000,1080.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.21 Dir:I2SO.20 CS:I2SO.22 Disable:I2SO.23 Index:-1 R:0.110]
[MSG:INFO: C Neg Limit gpio.36:low]
[MSG:ERR: X Axis TMC driver not detected - expected 0x11 got 0x0]
[MSG:INFO: Y Axis driver test passed]
[MSG:INFO: Z Axis driver test passed]
[MSG:INFO: A Axis driver test passed]
[MSG:ERR: B Axis TMC driver not detected - expected 0x11 got 0xff]
[MSG:ERR: C Axis TMC driver not detected - expected 0x11 got 0xff]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:WLAN]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.178.111]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://KFAgilusV2.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: PWM Spindle Ena:gpio.13 Out:gpio.14 Dir:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Flood coolant I2SO.24]
[MSG:INFO: Mist coolant I2SO.27]
ok



OR (5min Later after a cold start)

$SS
[MSG:INFO: FluidNC v3.9.1 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:AgilusV2.yaml]
[MSG:INFO: Machine KRAgilus]
[MSG:INFO: Board 6 Pack V1p8]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_STREAM Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 6]
[MSG:INFO: Axis X (150.000,450.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.2 Dir:I2SO.1 CS:I2SO.3 Disable:I2SO.0 Index:-1 R:0.110]
[MSG:INFO: X Pos Limit gpio.33:low:pu]
[MSG:INFO: Axis Y (-90.000,90.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.5 Dir:I2SO.4 CS:I2SO.6 Disable:I2SO.7 Index:-1 R:0.110]
[MSG:INFO: Y Neg Limit gpio.32:low:pu]
[MSG:INFO: Axis Z (-225.000,75.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.10 Dir:I2SO.9 CS:I2SO.11 Disable:I2SO.8 Index:-1 R:0.110]
[MSG:INFO: Z Pos Limit gpio.35:low]
[MSG:INFO: Axis A (0.000,120.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.13 Dir:I2SO.12 CS:I2SO.14 Disable:I2SO.15 Index:-1 R:0.110]
[MSG:INFO: A Pos Limit gpio.34:low]
[MSG:INFO: Axis B (95.000,285.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.18 Dir:I2SO.17 CS:I2SO.19 Disable:I2SO.16 Index:-1 R:0.110]
[MSG:INFO: B Neg Limit gpio.39:low]
[MSG:INFO: Axis C (360.000,1080.000)]
[MSG:INFO: Motor0]
[MSG:INFO: tmc_2130 Step:I2SO.21 Dir:I2SO.20 CS:I2SO.22 Disable:I2SO.23 Index:-1 R:0.110]
[MSG:INFO: C Neg Limit gpio.36:low]
[MSG:ERR: X Axis TMC driver not detected - expected 0x11 got 0xfe]
[MSG:ERR: Y Axis TMC driver not detected - expected 0x11 got 0xff]
[MSG:INFO: Z Axis driver test passed]
[MSG:ERR: A Axis TMC driver not detected - expected 0x11 got 0xff]
[MSG:INFO: B Axis driver test passed]
[MSG:INFO: C Axis driver test passed]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:WLAN]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connecting....]
[MSG:INFO: Connected - IP is 192.168.178.111]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://KFAgilusV2.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: PWM Spindle Ena:gpio.13 Out:gpio.14 Dir:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Flood coolant I2SO.24]
[MSG:INFO: Mist coolant I2SO.27]
ok
```

### User Interface Software

WebUI

### What happened?

Updated the Firmware since 1 Year now i have Problems with Axis Movements.
After Startup: JOG Mode: X,Z,B axis won't move in any Direction (Log Console showing normal)
Y,A and C Axis Move normally
.
Switched off Powersupply for 6 pack board, waited 1 min,

Switched it back on: X, A, C Axis are Moving without problems (Jog-Mode), 
previous Problem shifted to Axis Y,Z,B...

Test:
Reconfiguration from StealthChop to Stallguard on all 6 Axes (Run Mode):
same Test revealed that all Axis wanted to move, but the Axes with the Problem are just "squeeking" the Time the jog signal is on.

### GCode File

n.A.

### Other Information

before Updating to 3.9.1, everything seemed ok.

TMC Drivers Swapped without any change of the Issue.
in StealthChop Mode, Axis that will not move are silent.
in Stallguard Mode, Axis that will not move are "squeeking" during movement tests.

Axis Behavior is different, sometimes X,Z,A are not moving... sometimes Just Y,B are not moving

Axis that move are perfectly fine, no mechanical issue.
