### ISSUE TITLE
Problem: folders nor working

### ISSUE THREAD

**Issue by Ams-Laser** [bdring/FluidNC#1394]
### Wiki Search Terms

sd folders

### Controller Board

mks tinybee

### Machine Description

gantry laser diode

### Input Circuits

```yaml
na
```

### Configuration file

```yaml
name: diode
meta: AMS 18/09/2024
planner_blocks: 120
kinematics: {}
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: gpio.34:low
start:
  must_home: false
axes:
  homing_runs: 1
  x:
    steps_per_mm: 20
    max_rate_mm_per_min: 9000
    acceleration_mm_per_sec2: 1200
    max_travel_mm: 340
    homing:
      cycle: 1
      positive_direction: false
      feed_mm_per_min: 1500
      seek_mm_per_min: 1500
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.33:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.1
        direction_pin: i2so.2:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
  y:
    steps_per_mm: 20
    max_rate_mm_per_min: 9000
    acceleration_mm_per_sec2: 900
    max_travel_mm: 420
    homing:
      cycle: 1
      positive_direction: false
      feed_mm_per_min: 1500
      seek_mm_per_min: 1500
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.32:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.4
        direction_pin: i2so.5
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
    motor1:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.22:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.7
        direction_pin: i2so.8:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
  z:
    steps_per_mm: 40
    max_rate_mm_per_min: 500
    acceleration_mm_per_sec2: 100
    max_travel_mm: 10000
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      stepstick:
        step_pin: i2so.10
        direction_pin: i2so.11:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
Laser:
  output_pin: gpio.2:pd
  disable_with_s0: true
  s0_with_disable: true
  off_on_alarm: true
```

### Startup Messages

```text
name: diode
meta: AMS 18/09/2024
planner_blocks: 120
kinematics: {}
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: gpio.34:low
start:
  must_home: false
axes:
  homing_runs: 1
  x:
    steps_per_mm: 20
    max_rate_mm_per_min: 9000
    acceleration_mm_per_sec2: 1200
    max_travel_mm: 340
    homing:
      cycle: 1
      positive_direction: false
      feed_mm_per_min: 1500
      seek_mm_per_min: 1500
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.33:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.1
        direction_pin: i2so.2:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
  y:
    steps_per_mm: 20
    max_rate_mm_per_min: 9000
    acceleration_mm_per_sec2: 900
    max_travel_mm: 420
    homing:
      cycle: 1
      positive_direction: false
      feed_mm_per_min: 1500
      seek_mm_per_min: 1500
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.32:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.4
        direction_pin: i2so.5
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
    motor1:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.22:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.7
        direction_pin: i2so.8:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
  z:
    steps_per_mm: 40
    max_rate_mm_per_min: 500
    acceleration_mm_per_sec2: 100
    max_travel_mm: 10000
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      stepstick:
        step_pin: i2so.10
        direction_pin: i2so.11:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
Laser:
  output_pin: gpio.2:pd
  disable_with_s0: true
  s0_with_disable: true
  off_on_alarm: true
```

### User Interface Software

webui

### What happened?

tried to start a job from a folder that previously worked and shows error 
ERROR:66
Failed to open file
[MSG:ERR: Failed to open file]
$SD/Run=/Diseño Jano/Todos Grabado Jano/T25 Grabado Jano.gco
<Idle|MPos:187.950,189.600,0.000|FS:0,0|Ov:100,100,100>
ERROR:66
Failed to open file
Error : error:66 :undefined
[MSG:ERR: Failed to open file]

### GCode File

[SD_Diseño Jano_Todos Grabado Jano_T25 Grabado Jano.txt](https://github.com/user-attachments/files/18043176/SD_Diseno.Jano_Todos.Grabado.Jano_T25.Grabado.Jano.txt)

### Other Information

while creating issue found the problem a latin-america character on path "Ñ" causes error
