### ISSUE TITLE
Problem: Unable to access Fluid WebUI

### ISSUE THREAD

**Issue by CMarkussen** [bdring/FluidNC#1415]
### Wiki Search Terms

webui access
webui trouble
webui Q&A
http://wiki.fluidnc.com/en/features/webui

### Controller Board

6-pack

### Machine Description

3-axis gantry router with Makerbase MKS SERVO57D NEMA23 closed loop stepper motors, inductive end-stops, 1.5kW spindle with Huanyang VFD

### Input Circuits

```yaml
# Connections
######################################################
# Function        Motor       End-stop pin
# X-axis        : Motor1      gpio.35
# Y-axis left   : Motor2      gpio.34
# Y-axis right  : Motor3      gpio.39
# Z-axis        : Motor4      gpio.36
# Rotary        : Motor5      gpio.????
# Free          : Motor6      

# Enable - yellow
# Step - Green
# direction - White

# RS485 / UART1 : Pin 15 (TX), 16 (RX), 14(RTS)
# Expansion port: Pin 25 (RX), 27 (TX)

# Input           Pin
# Touch probe   : gpio.2
# Start button  : gpio.26
# Pause button  : gpio.33 
# Fault		: gpio.32

# Outputs         Pin
# Cooling pump  : gpio.12
# Cooling Fan   : gpio.4
# Alarm pin     : gpio.13
# RTS (?)       : gpio.14
```

### Configuration file

```yaml
I have been testing with a minimal configuration file with only one stepper motor:
board: 6 Pac
name: Test
verbose_errors: true
start:
  must_home: false
  deactivate_parking: false
  check_limits: false
axes:
  x:
    steps_per_mm: 400
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 300
    soft_limits: true
    homing:
      cycle: 2
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.34
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.5
        direction_pin: i2so.4
        disable_pin: i2so.7
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
probe:
  pin: gpio.2:pu:low
  toolsetter_pin: NO_PIN
  check_mode_start: true
  hard_stop: false
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  frequency_hz: 8000000
control:
  feed_hold_pin: NO_PIN
  cycle_start_pin: gpio.26:pu:low
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: NO_PIN
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17
uart1:
  txd_pin: gpio.15
  rxd_pin: gpio.16
  baud: 9600
  mode: 8N1
uart2:
  txd_pin: gpio.27
  rxd_pin: gpio.25
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 1000000
  mode: 8N1
uart_channel1:
  uart_num: 2
  report_interval_ms: 75
  message_level: Verbose
```

### Startup Messages

```text
$Startup/Show
[MSG:INFO: FluidNC v3.9.3 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:test config.yaml]
[MSG:INFO: Machine Test]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: UART1 Tx:gpio.15 Rx:gpio.16 RTS:NO_PIN Baud:9600]
[MSG:INFO: UART2 Tx:gpio.27 Rx:gpio.25 RTS:NO_PIN Baud:1000000]
[MSG:INFO: uart_channel2 created at report interval: 75]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_STREAM Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.5 Dir:I2SO.4 Disable:I2SO.7]
[MSG:INFO:  X Pos Limit gpio.34]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: cycle_start_pin gpio.26:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:Jonas]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.86.29]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: Probe gpio.2:low:pu]
ok
```

### User Interface Software

WebUI and FluidNC web installer

### What happened?

I have connected the board to the inputs and outputs signal wires. The WebUI was working, I was exploring the UI and setting up my preferences. I made some changes to the fluid configuration file and after rebooting the board, it would not load the WebUI using address fluidnc.local. I have performed a complete re-install of Fluid using the Fluid web installer. Everything seems to work as expected but the WebUI will not load. I have also tried to access it directly through the IP address as reported through the Configure WiFi tab in the web installer but this presents a different user interface (see attached screen shot). I have used a minimal configuration for testing purposes but this has not helped. How can I fix this so I get access to the WebUI through the fluidnc.local address? 
![WIFI config](https://github.com/user-attachments/assets/26b472f9-d154-4828-afa7-0334574abd24)
![WebUI](https://github.com/user-attachments/assets/c28f75b8-9116-4ff1-9a76-41ef637a68fd)
![Calibrate](https://github.com/user-attachments/assets/319e745d-a0c7-4d52-a150-8493df274175)
![Fluid install](https://github.com/user-attachments/assets/c4bbba64-9431-49d0-8a0b-d288fe899430)
![File browser](https://github.com/user-attachments/assets/ed3d4f8c-dfda-4272-aac7-b0942a17f353)

### GCode File

NA
