### ISSUE TITLE
Problem:  How to implement a potentiometer in config.yaml to override feed speed on a anaolog input of the ESP32 ?

### ISSUE THREAD

**Issue by MirkoCNC** [bdring/FluidNC#1424]
### Wiki Search Terms

Analog input via potentiometer on the ESP32 in order to override feed speed 

### Controller Board

ESP32 board connected with Mach3 driver board

### Machine Description

XA axis to control a winding machine to make coils

### Input Circuits

```yaml
It is just the potentionmeter on ADC1_CH0
```

### Configuration file

```yaml
name: CNC-Winder
board: ESP32-MACH3

start:
  must_home: False

axes:
  x:
# Steps per 5mm (one turn) 400 x 16 / 5 (0.9 degree, 16 microsteps, 5mm spindle)
    steps_per_mm: 1280.000       
    max_rate_mm_per_min: 500.000
    acceleration_mm_per_sec2: 20.000

    motor0:
      standard_stepper:
        step_pin: gpio.32
        direction_pin: gpio.5
        disable_pin: gpio.33:low

  z:
# Steps per one degree 200 x 8 / 360 (1.8 degree, 8 micosteps)
    steps_per_mm: 4.444
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 2.000

    motor0:
      standard_stepper:
        step_pin: gpio.19
        direction_pin: gpio.21
        disable_pin: gpio.18:low

control:
  feed_hold_pin: gpio.14:low
  cycle_start_pin: gpio.35:low
  estop_pin: gpio.15:low
```

### Startup Messages

```text
Everthing is OK and works. I just want to add the additional feature of overriding feed speed with a potentiometer.
```

### User Interface Software

WebUI or Universal GCode Sender

### What happened?

I cannot find any information in the Wiki to achieve implementing the analog potentiometer.

### GCode File

No problem with GCode
