### ISSUE TITLE
Problem: Probing was skipped randomly, for the 1st tool change, before going for tool change in atc_manual macro.

### ISSUE THREAD

**Issue by ikhwan-ma** [bdring/FluidNC#1427]
### Wiki Search Terms

probing skipped atc manual

### Controller Board

6-pack external

### Machine Description

Gantry router with external HBS860H all closed loop, dual X motor, single Y, single Z, Fuling/Fohlinn DB600 VFD 3.7KW, 3.5KW 1200Hz 8pole ATC spindle.

### Configuration file

```yaml
board: 6 Pack External
name: 6 Pack Ext XXYZ Fuling ATC
meta: Last changed 23/11/2024
use_line_numbers: true

stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 850.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.34
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

    motor1:
      limit_neg_pin: gpio.39
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7

  y:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 650.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.32
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8
    
    
  z:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 90.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 250.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.33
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15
        
probe:
  pin: gpio.36:low
  toolsetter_pin: gpio.14:low
  check_mode_start: true
  hard_stop: false
  
control:
  safety_door_pin: gpio.13:low
  # safety_door_pin pair with probe overtravel sw
  cycle_start_pin: gpio.12
  feed_hold_pin: gpio.15
        
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

start:
  must_home: true
  
coolant:
  flood_pin: i2so.25
  mist_pin: i2so.24
  delay_ms: 0

user_outputs:
  #P0 - ATC tool release
  digital0_pin: i2so.27
  #P1 - TLO Probe Blower
  digital1_pin: i2so.26

10V:
  output_pin: gpio.26
  forward_pin: gpio.4
  reverse_pin: gpio.16
  pwm_hz: 5000
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 10000
  spindown_ms: 10000
  tool_num: 0
  speed_map: 0=0.000% 1800=10.000% 18000=100.000%
  off_on_alarm: false
  atc: atc_manual

atc_manual:
  safe_z_mpos_mm: -1.0000
  probe_seek_rate_mm_per_min: 300.0000
  probe_feed_rate_mm_per_min: 100.0000
  change_mpos_mm: -775.000 -315.000 -1.000
  ets_mpos_mm: 0.000 -75.000 -85.000
  ets_rapid_z_mpos_mm: -10.0000
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.9.4 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:6P Ext XXYZ FUL.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine 6 Pack Ext XXYZ Fuling ATC]
[MSG:INFO: Board 6 Pack External]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21Min Pulse:2us]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_STREAM Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: User Digital Output: 0 on Pin:I2SO.27]
[MSG:INFO: User Digital Output: 1 on Pin:I2SO.26]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-850.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.1 Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.34]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.5 Dir:I2SO.4 Disable:I2SO.7]
[MSG:INFO:  X2 Neg Limit gpio.39]
[MSG:INFO: Axis Y (-650.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.9 Disable:I2SO.8]
[MSG:INFO:  Y Pos Limit gpio.32]
[MSG:INFO: Axis Z (-90.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.12 Disable:I2SO.15]
[MSG:INFO:  Z Pos Limit gpio.33]
[MSG:INFO: safety_door_pin gpio.13:low]
[MSG:INFO: feed_hold_pin gpio.15]
[MSG:INFO: cycle_start_pin gpio.12]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:ASF]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.1.201]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://ASFRouter.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: ATC:atc_manual]
[MSG:INFO: 10V Spindle Ena:NO_PIN Out:gpio.26 Dir:NO_PIN Fwd:gpio.4 Rev:gpio.16 Freq:5000Hz Period:8191 with atc_manual]
[MSG:INFO: Flood coolant I2SO.25]
[MSG:INFO: Mist coolant I2SO.24]
[MSG:INFO: Probe gpio.36:low]
[MSG:INFO: Toolsetter gpio.14:low]
ok
```

### User Interface Software

UGS 2.1.9

### What happened?

** All axes homed **
1- load my nc file.
2- typed in G56 - my work offset
3- M61 Q10 - load the 1st tool used in the program
4- Hit Start button
5- Reached next tool change. Program paused, spindle turning down.

 **++normal case++**
**6- Z moves up, spindle move on to fixed probe for tool length offset probing, and then go to tool change location.**
7- Insert new tool, hit cycle start button, spindle goes to fixed probe to complete tool length offset probing.
8- Comes back to the last location at the last tool height, and continue with the rest of the program. I smiled.
9- Subsequent tool changes exhibit no problems at all.

**<<abnormal case>>**
**6- Z moves up, spindle move on to tool change location.**
7- Insert new tool, hit cycle start button, spindle goes to fixed probe to complete tool length offset probing.
8- Comes back to the last location at the wrong tool height, and crashed on the work piece. I died.

This <<abnormal case>> almost always happen when you ran the same program for the next part (2nd, 3rd.. on), regardless if you hit the soft reset button or not. But a power cycle will confirm the ++normal case++ to happen on the fresh run of the program, but not on the subsequent run of the program. Not without a power cycle.
