### ISSUE TITLE
10 volts inoperative output (spindle )

### ISSUE THREAD

**Issue by DVA85** [bdring/FluidNC#1434]
### Wiki Search Terms

show file .yaml below

### Controller Board

nothing here

### Machine Description

nothing here

### Input Circuits

```yaml
nothing here
```

### Configuration file

```yaml
board: 6 Pack
name: 5 Pack External Router XYYZR 10V Spindle
meta: Pilou 27/12/2024 V1

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false

start:
  must_home: true
  deactivate_parking: false

stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 319.027
    max_rate_mm_per_min: 1500.000
    acceleration_mm_per_sec2: 25.000
    max_travel_mm: 806.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 50.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.26:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

  y:
    steps_per_mm: 798.005
    max_rate_mm_per_min: 1500.000
    acceleration_mm_per_sec2: 25.000
    max_travel_mm: 1080.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 50.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8    
    
  z:
    steps_per_mm: 1926.453
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 25.000
    max_travel_mm: 226.700
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.32:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15

 a:
    steps_per_mm: 53.333
    max_rate_mm_per_min: 10000.0
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 400.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.18
        direction_pin: I2SO.17
        disable_pin: I2SO.16

probe:
  pin: gpio.35:low
  check_mode_start: true

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

RapidChange:
  alignment: Y_AXIS
  direction: POSITIVE
  number_of_pockets: 4
  pocket_offset: 38.000
  x_pocket_1: -439.720
  y_pocket_1: -150.170
  z_engage: -80.000
  z_traverse: -10.000
  z_safe_clearance: 0.000
  engage_feed_rate: 1600
  load_rpm: 1600
  unload_rpm: 1600
  dust_cover_enabled: False
  tool_recognition_enabled: False
  tool_setter_enabled: True
  x_tool_setter: -439.730
  y_tool_setter: -212.000
  z_seek_start: 0.000
  z_safe_tool_setter: 0
  set_tool_offset: 43
  seek_feed_rate: 300
  seek_retreat: 5
  set_feed_rate: 100
  set_tool_max_travel: 50.000
  dust_cover_axis: A_AXIS
  dust_cover_open_position: 0.000
  dust_cover_closed_position: 0.000
  dust_cover_use_output: False
  z_tool_recognition_zone_1: 0.000
  z_tool_recognition_zone_2: 0.000
  dust_cover_pin: NO_PIN
  tool_recognition_pin: NO_PIN

coolant:
  mist_pin: gpio.12
  delay_ms: 0

parking:
  enable: true
  axis: Z
  target_mpos_mm: -5.0
  rate_mm_per_min: 800.0
  pullout_distance_mm: 5.0
  pullout_rate_mm_per_min: 250.0

macros:
  startup_line0:
  startup_line1:
  macro0: G54G0Z0&G54G0X0Y0
  macro1: 
  macro2:
  macro3:
  after_reset: G20
  after_unlock: G91

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.2:low:pu
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

10V:
  forward_pin: gpio.15
  reverse_pin: gpio.14
  pwm_hz: 5000
  output_pin: gpio.13
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 6000=25%.000 12000=50.000% 24000=100.000%
  off_on_alarm: true
```

### Startup Messages

```text
no message when start to run
```

### User Interface Software

Fluidnc

### What happened?

nothing here

### GCode File

nothing here

### Other Information

nothing here
