### ISSUE TITLE
Problem: DAC Spindle mis-handles enable_pin

### ISSUE THREAD

**Issue by MitchBradley** [bdring/FluidNC#1435]
### Wiki Search Terms

DAC

### Controller Board

 ESP32 Dev Kit V4 Controller

### Machine Description

Vertical Metal CNC Mill

### Input Circuits

```yaml
N/A
```

### Configuration file

```yaml
name: "Vertical Metal CNC Mill"
board: "ESP32 Dev Kit V4 Controller"

start:
  must_home: false
  deactivate_parking: true
  check_limits: true

stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 3
  dir_delay_us: 1
  disable_delay_us: 10

axes:
  homing_runs: 2
  x:
    steps_per_mm: 1280.000
    max_rate_mm_per_min: 4500.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 500.000
    soft_limits: false
    motor0:
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: gpio.32
        direction_pin: gpio.4
  y:
    steps_per_mm: 1280.000
    max_rate_mm_per_min: 4500.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 230.000
    soft_limits: false
    motor0:
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: gpio.33
        direction_pin: gpio.27
  z:
    steps_per_mm: 1280.000
    max_rate_mm_per_min: 1200.000
    acceleration_mm_per_sec2: 20.000
    max_travel_mm: 370.000
    soft_limits: false
    motor0:
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: gpio.25
        direction_pin: gpio.14

DAC:
  output_pin: gpio.26
  enable_pin: gpio.15
  direction_pin: NO_PIN
  disable_with_s0: true
  s0_with_disable: false
  spinup_ms: 3000
  spindown_ms: 3000
  tool_num: 0
  speed_map: 0=0.000% 18000=100.000%
  off_on_alarm: true
```

### Startup Messages

```text
[MSG:INFO: uart_channel0 created]
[MSG:RST]
[MSG:INFO: FluidNC v3.9.4 (GenericVFDImprovements-72e73379-dirty) https://github.com/bdring/FluidNC.git]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:dac.flnc]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine Vertical Metal CNC Mill]
[MSG:INFO: Board ESP32 Dev Kit V4 Controller]
[MSG:DBG: SPI not defined]
[MSG:DBG: See http://wiki.fluidnc.com/en/config/sd_card#sdfallbackcs-access-sd-without-a-config-file]
[MSG:INFO: Stepping:RMT Pulse:3us Dsbl Delay:10us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-500.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.32 Dir:gpio.4 Disable:NO_PIN]
[MSG:INFO: Axis Y (-230.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.33 Dir:gpio.27 Disable:NO_PIN]
[MSG:INFO: Axis Z (-370.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.25 Dir:gpio.14 Disable:NO_PIN]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:CampOlindaHS]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.4.51]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: DAC Spindle Out:gpio.26 Dir:NO_PIN Res:8bits]

Grbl 3.9 [FluidNC v3.9.4 (GenericVFDImprovements-72e73379-dirty) (wifi) '$' for help]
```

### User Interface Software

FluidTerm

### What happened?

ok
m3s18000
[MSG:ERR: gpio.15]
[MSG:ERR: Critical error in run_once: Pin gpio.15 cannot be written]
[MSG:ERR: Stacktrace: _attributes.has(PinAttributes::Output) (@line 141): Pin gpio.15 cannot be written]
error:9
[MSG:ERR: GCode cannot be executed in lock or alarm state]

### Other Information

The error appears to be related to the use of enable_pin
