### ISSUE TITLE
Problem: Homing intermitent issues with optical endstops (bounce ?)

### ISSUE THREAD

**Issue by Ams-Laser** [bdring/FluidNC#1447]
### Wiki Search Terms

debounce limit switch

### Controller Board

MKS tinybee 1.0

### Machine Description

gantry machine, laser and embroidery machine

### Input Circuits

```yaml
https://reprapproject.nl/images/optical%20endstop.jpg
```

### Configuration file

```yaml
name: Bordadora
meta: AMS 05/02/25
planner_blocks: 120
kinematics: {}
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: gpio.34:low
start:
  must_home: false
axes:
  homing_runs: 1
  x:
    steps_per_mm: 20
    max_rate_mm_per_min: 9000
    acceleration_mm_per_sec2: 900
    max_travel_mm: 500
    homing:
      cycle: 1
      positive_direction: false
      feed_mm_per_min: 1500
      seek_mm_per_min: 1500
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.33:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.1
        direction_pin: i2so.2
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
  y:
    steps_per_mm: 20
    max_rate_mm_per_min: 9000
    acceleration_mm_per_sec2: 900
    max_travel_mm: 500
    homing:
      cycle: 1
      positive_direction: false
      feed_mm_per_min: 1500
      seek_mm_per_min: 1500
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.32:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.4
        direction_pin: i2so.5
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
  z:
    steps_per_mm: 40
    max_rate_mm_per_min: 500
    acceleration_mm_per_sec2: 100
    max_travel_mm: 10000
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      stepstick:
        step_pin: i2so.13
        direction_pin: i2so.14:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
PWM:
  output_pin: gpio.2:pd
  tool_num: 1
```

### Startup Messages

```text
name: Bordadora
meta: AMS 05/02/25
planner_blocks: 120
kinematics: {}
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: gpio.34:low
start:
  must_home: false
axes:
  homing_runs: 1
  x:
    steps_per_mm: 20
    max_rate_mm_per_min: 9000
    acceleration_mm_per_sec2: 900
    max_travel_mm: 500
    homing:
      cycle: 1
      positive_direction: false
      feed_mm_per_min: 1500
      seek_mm_per_min: 1500
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.33:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.1
        direction_pin: i2so.2
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
  y:
    steps_per_mm: 20
    max_rate_mm_per_min: 9000
    acceleration_mm_per_sec2: 900
    max_travel_mm: 500
    homing:
      cycle: 1
      positive_direction: false
      feed_mm_per_min: 1500
      seek_mm_per_min: 1500
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.32:pd
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 10
      stepstick:
        step_pin: i2so.4
        direction_pin: i2so.5
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
  z:
    steps_per_mm: 40
    max_rate_mm_per_min: 500
    acceleration_mm_per_sec2: 100
    max_travel_mm: 10000
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      stepstick:
        step_pin: i2so.13
        direction_pin: i2so.14:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
PWM:
  output_pin: gpio.2:pd
  tool_num: 1
```

### User Interface Software

webui

### What happened?

on homing, the endstop is triggered but sometimes is kept "floating" (due to bounce on input line)
$Message/Level=Debug

![Image](https://github.com/user-attachments/assets/9bc4d9f6-3d34-48ac-b328-d7e5babae88d)

### Other Information

![Image](https://github.com/user-attachments/assets/f71413c0-a49e-46d7-8b84-35a27974e0c7)
