### ISSUE TITLE
Problem: gpio.14 (integrated esp32) does not change state. Plasma branch f/w.

### ISSUE THREAD

**Issue by jusbo20** [bdring/FluidNC#1453]
### Wiki Search Terms

Created Discord post with same-ish heading. Was told to submit github issue by Mr. Dring
"Plasma" was then used as a search term on the wiki to recall specific plasma page.

### Controller Board

6x CNC Controller board v1.2 integrated ESP32, external stepper drivers with base config of xyyz yaml official.
Wiring is shown on picture attached.
![Image](https://github.com/user-attachments/assets/9840f332-d9ac-4044-b2bd-22233ca94252)
![Image](https://github.com/user-attachments/assets/d1afcb01-0f1c-4b4e-b72d-fb9ea7011ed2)

### Machine Description

Plasma firmware branch on 6x CNC Controller Board v1.2. Using DMM to test output of gpio.14.
The firmware was a drop? Artifact? I don't recall the verbiage used....I did not compile it myself. The file was for windows.

### Input Circuits

```yaml
N/A
```

### Configuration file

```yaml
board: 6 Pack
name: 6 Pack External XYYZ
meta: 2023-01-29 B. Dring
stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 199.64
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 300
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0
      feed_mm_per_min: 100
      seek_mm_per_min: 200
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_neg_pin: gpio.2:pu:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.10
        direction_pin: i2so.9
        disable_pin: NO_PIN
  y:
    steps_per_mm: 199.64
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 300
    soft_limits: false
    homing:
      cycle: 3
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 100
      seek_mm_per_min: 200
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_neg_pin: gpio.26:pu:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.2
        direction_pin: i2so.1
        disable_pin: NO_PIN
    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.5
        direction_pin: i2so.4
        disable_pin: NO_PIN
  z:
    steps_per_mm: 197.78
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 150
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150
      feed_mm_per_min: 100
      seek_mm_per_min: 800
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.13
        direction_pin: i2so.12:low
        disable_pin: NO_PIN
probe:
  pin: gpio.33:pu:low
  check_mode_start: true
  toolsetter_pin: NO_PIN
PlasmaSpindle:
  enable_pin: gpio.14
  arc_ok_pin: gpio.36:low
  arc_wait_ms: 1200
  tool_num: 0
  off_on_alarm: true
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5
start:
  must_home: false
```

### Startup Messages

```text
Grbl 3.0 [FluidNC v3.0.x (HEAD-ef4b1c4) (wifi) '$' for help]
$Startup/Show
[MSG:INFO: FluidNC v3.0.x (HEAD-ef4b1c4) https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine 6 Pack External XYYZ]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21Min Pulse:2us]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_STREAM Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.9 Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.2:low:pu]
[MSG:INFO: Axis Y (0.000,300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.1 Disable:NO_PIN]
[MSG:INFO:  Y Neg Limit gpio.26:low:pu]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.5 Dir:I2SO.4 Disable:NO_PIN]
[MSG:INFO: Axis Z (0.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.12:low Disable:NO_PIN]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:Unifi]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.99.88]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://6pack.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: ArcOK gpio.36:low]
[MSG:INFO: PlasmaSpindle Ena:gpio.14 Arc OK:gpio.36:low]
[MSG:INFO: Probe gpio.33:low:pu]
ok
```

### User Interface Software

WebUi via usb and or wifi

### What happened?

Before hooking up to my plasma machine I am trying to verify that gpio.14 is either

1. Putting out voltage
2. Dry open/closure 

No voltage readings between gpio.14&GND. Continuity is closed no matter what command (M3, M3s1, M3S1000, M5) is inputted into the command box of the webUI.

### GCode File

No GCode file available issued single commands 1 at a time. They are M3, M3s1, M3S1000, M5

### Other Information

I have provided pictures of my wiring and my enclosure of my actual wiring accurately depicted on the piece of paper.
