### ISSUE TITLE
Problem: (Generic) ModbusVFD (RS485) does not transmit frequency setting command

### ISSUE THREAD

**Issue by borisov-py** [bdring/FluidNC#1454]
### Wiki Search Terms

(Generic) ModbusVFD (RS485)

### Controller Board

An unknown ESP 32 board was included with the machine.
![Image](https://github.com/user-attachments/assets/3f02aa71-a376-4adf-9fe1-217fd68732ee)
![Image](https://github.com/user-attachments/assets/0e78bac1-d567-4d8e-bee9-1fb43f480a7a)
![Image](https://github.com/user-attachments/assets/4f3ca58a-f654-499e-bf87-5f110890442a)

### Machine Description

Portal CNC milling machine size 30x40cm

![Image](https://github.com/user-attachments/assets/219ac59e-48d5-41bb-92ee-3f82a14b2538)
![Image](https://github.com/user-attachments/assets/0458c3fd-7d88-4b91-8263-67b32fccc01b)

### Input Circuits

```yaml

```

### Configuration file

```yaml
board: None
name: KJBJ
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 10
  dir_delay_us: 10
  disable_delay_us: 0
  segments: 12
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
kinematics: {}
axes:
  shared_stepper_disable_pin: gpio.13
  shared_stepper_reset_pin: NO_PIN
  homing_runs: 1
  x:
    steps_per_mm: 639.9
    max_rate_mm_per_min: 3000
    acceleration_mm_per_sec2: 40
    max_travel_mm: 280
    soft_limits: true
    motor0:
      limit_neg_pin: gpio.17:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      stepstick:
        step_pin: gpio.12
        direction_pin: gpio.14:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: -1
  y:
    steps_per_mm: 640.2
    max_rate_mm_per_min: 3000
    acceleration_mm_per_sec2: 40
    max_travel_mm: 400
    soft_limits: true
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.4:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3
      stepstick:
        step_pin: gpio.26
        direction_pin: gpio.15
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
    homing:
      cycle: 2
      mpos_mm: -1
      positive_direction: true
  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 30
    max_travel_mm: 120
    soft_limits: true
    motor0:
      limit_neg_pin: gpio.33:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      stepstick:
        step_pin: gpio.27
        direction_pin: gpio.16
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
    homing:
      cycle: 2
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.36:low
  cycle_start_pin: gpio.34:low
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: gpio.39:low
coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0
probe:
  pin: gpio.32:low
  toolsetter_pin: NO_PIN
  check_mode_start: true
  hard_stop: false
macros: {}
start:
  must_home: false
  deactivate_parking: false
  check_limits: false
parking:
  enable: false
  axis: Z
  target_mpos_mm: -5
  rate_mm_per_min: 800
  pullout_distance_mm: 5
  pullout_rate_mm_per_min: 250
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN
user_inputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.01
verbose_errors: true
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5:pd
uart2:
  txd_pin: gpio.25
  rxd_pin: gpio.22
  rts_pin: NO_PIN
  baud: 9600
  mode: 8N1
ModbusVFD:
  uart_num: 2
  modbus_id: 1
  model: VFD-M+
  cw_cmd: 06 20 00 00 12 > echo
  ccw_cmd: 06 20 00 00 22 > echo
  off_cmd: 06 20 00 00 01 > echo
  set_rpm_cmd: 06 20 01 rpm% > echo
  min_RPM: 0
  max_RPM: 24000
  debug: 3
```

### Startup Messages

```text
rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13260
load:0x40080400,len:3028
entry 0x400805e4
[MSG:INFO: uart_channel0 created]
[MSG:RST]
[MSG:INFO: FluidNC 3.9.5-pre1 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config (4).yaml]
[MSG:WARN: min_RPM value 0 constrained to range (4294967295,4294967295)]
[MSG:WARN: max_RPM value 24000 constrained to range (4294967295,4294967295)]
[MSG:INFO: Machine KJBJ]
[MSG:INFO: Board None]
[MSG:INFO: UART2 Tx:gpio.25 Rx:gpio.22 RTS:NO_PIN Baud:9600]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5:pd detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:10us Dsbl Delay:0us Dir Delay:10us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13]
[MSG:INFO: Axis X (-1.000,279.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.12 Dir:gpio.14:low Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.17:low]
[MSG:INFO: Axis Y (-401.000,-1.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.26 Dir:gpio.15 Disable:NO_PIN]
[MSG:INFO:  Y Pos Limit gpio.4:low]
[MSG:INFO: Axis Z (-120.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.27 Dir:gpio.16 Disable:NO_PIN]
[MSG:INFO:  Z Neg Limit gpio.33:low]
[MSG:INFO: feed_hold_pin gpio.36:low]
[MSG:INFO: cycle_start_pin gpio.34:low]
[MSG:INFO: estop_pin gpio.39:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:ORASZ]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.3.166]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: ModbusVFD Spindle Tx:gpio.25 Rx:gpio.22 RTS:NO_PIN Baud:9600]
[MSG:INFO: Probe gpio.32:low]

Grbl 3.9 [FluidNC 3.9.5-pre1 (wifi) '$' for help]

Grbl 3.9 [FluidNC 3.9.5-pre1 (wifi) '$' for help]
[MSG:INFO: RS485 Tx:  01 06 20 00 00 01 43 CA]
[MSG:INFO: RS485 Rx:  01 06 20 00 00 01 43 CA]
ok
[VER:3.9 FluidNC 3.9.5-pre1:]
[OPT:PHS]
[MSG:Machine: KJBJ]
[MSG:Mode=STA:SSID=ORASZ:Status=Connected:IP=192.168.3.166:MAC=10-06-1C-68-11-84]
ok
```

### What happened?

I studied the machine diagram and made a table of conclusions. Additionally installed an SD card module. Everything works. I wanted to connect a VFD via RS485. My VFD controller does not have an RS485 interface on the converter board. I connected directly Uart VFD to UART ESP32 via ADUM1201 chip. I checked the functionality of the interface through the terminal on the computer.  Initially, I tried various VFD models in the configuration, but they did not fit the parameters. The closest VFD in terms of parameters is YL620. But it transmits frequency, and I need % of the maximum frequency.I found that the universal VFD controller is in the new firmware. I installed new firmware. Configured, but doesn't work. When I try to set the frequency, it does not issue a command.

![Image](https://github.com/user-attachments/assets/097234c8-d6a0-441c-a052-d7124b525d55)
If you just specify the model YL620. the frequency is set to a maximum of 1.6 Hz.
if I copy the settings for the YL620 universal from WIKI, it also does not transmit the 2001 command. I am not a programmer, I could not figure out what was wrong. Please help me figure it out/
There is a Chinese manual for the VFD. I found an analogue in English with modbus commands -hs350-1. 5

![Image](https://github.com/user-attachments/assets/eb806ddf-0dec-4863-8917-cc79f5b1ab25)

![Image](https://github.com/user-attachments/assets/82fe6555-13a5-4f16-b7b8-4b185959ced1)

![Image](https://github.com/user-attachments/assets/a4f5523a-0370-4d1a-b5ac-442f3c1bb234)

![Image](https://github.com/user-attachments/assets/b796d7b6-ab2b-443f-8920-9ef2d189265f)

![Image](https://github.com/user-attachments/assets/9ce8bb49-6f78-4a17-9725-93a09bc832ab)
