### ISSUE TITLE
Working  config.yaml  for  Aliexpress    Macrobase 4-axis Pro cnc ESP32 controller with FluidNC

### ISSUE THREAD

**Issue by jezisvole** [bdring/FluidNC#1467]
### Wiki Search Terms

config.yaml 

### Controller Board

Macrobase 4-axis Pro - FluidNC

### Machine Description

No machine yet - just test electronics

Hi.   I have been working with this board and it now seems to be working fine with a config.yaml I have been adjusting.   If anyone wants it, feel free.

### Input Circuits

```yaml

```

### Configuration file

```yaml
board: 4 Axis Pro
name: 4 Axis StepStick XYZ + A
stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 6
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN

  x:
    steps_per_mm: 38.000         
    max_rate_mm_per_min: 5000.000  
    acceleration_mm_per_sec2: 100.000  
    max_travel_mm: 1000.000   
    soft_limits: false       
    homing:
      cycle: 1          
      positive_direction: false 
      mpos_mm: 0.000    
      feed_mm_per_min: 100.000   
      seek_mm_per_min: 200.000   
      settle_ms: 500           
      seek_scaler: 1.100 
      feed_scaler: 1.100 

    motor0:
      limit_neg_pin: NO_PIN   
      limit_pos_pin: NO_PIN  
      limit_all_pin: gpio.33:low:pu 
      hard_limits: false 
      pulloff_mm: 5.000 
      stepstick:
        ms3_pin: i2so.3
        step_pin: I2SO.2 
        direction_pin: I2SO.1 
        disable_pin: I2SO.0  

  y:
    steps_per_mm: 38.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 1000.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.32:low
      hard_limits: false
      pulloff_mm: 5.000
      stepstick:
        ms3_pin: i2so.6
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7

  z:
    steps_per_mm: 38.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.35:low
      hard_limits: false
      pulloff_mm: 5.000
      stepstick:
        ms3_pin: i2so.11
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8
        
  a:
    steps_per_mm: 38.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 1000.000
    soft_limits: false
    homing:
      cycle: -1
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      stepstick:
        ms3_pin: i2so.14
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.36
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.16:low:pu 
  macro1_pin: gpio.14:low:pu 
  macro2_pin: gpio.25:low:pu 
  macro3_pin: gpio.26:low:pu 

coolant:
  flood_pin: i2so.24
  mist_pin: gpio.4
  delay_ms: 0

probe:
  pin: gpio.34:low
  check_mode_start: true

macros:
  startup_line0:
  startup_line1:
  macro0: $SD/Run=test.nc
  macro1: $SD/Run=test.nc
  macro2: $SD/Run=test.nc
  macro3: $SD/Run=test.nc

start:
  must_home: false

PWM:
  pwm_hz: 5000
  output_pin: gpio.27
  enable_pin: gpio.12
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 1000
  spindown_ms: 1000
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
```

### Startup Messages

```text
OK
```

### User Interface Software

FluidNC web

### What happened?

Resolved  config.yaml
