### ISSUE TITLE
Problem: Tool setter not working.

### ISSUE THREAD

**Issue by MadeInRu** [bdring/FluidNC#1497]
### Wiki Search Terms

I've searched online for possible solutions and tried a few. The biggest problem for me is that I don’t know whether there’s a hardware issue or not. If you guys can advise on a solution, it would be much appreciated! Thanks a lot in advance.

### Controller Board

[6-pack](https://us.ratrig.com/bigtreetech-rat-rig-rodent-cnc-controller-tmc2160.html)

### Machine Description

https://ratrig.com/cnc-kits/mills-coming-soon/rat-rig-mill.html

Beginner bundle

### Input Circuits

```yaml
https://us.ratrig.com/bigtreetech-rat-rig-rodent-cnc-controller-tmc2160.html
```

### Configuration file

```yaml
board: BTT Rodent-Z V1.0
name: Rat Rig Mill
meta: (19.12.2024) by MCruz Rat Rig PWM Spindle Config

kinematics:
  Cartesian:

# stepping:
#   engine: RMT
#   idle_ms: 250
#   dir_delay_us: 1
#   pulse_us: 2
#   disable_delay_us: 0
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 340.000
    soft_limits: True
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 400.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.35
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      tmc_5160:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0
        cs_pin: gpio.5
        spi_index: 1
        r_sense_ohms: 0.075
        run_amps: 2.0
        hold_amps: 1.5
        microsteps: 16
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        run_mode: CoolStep
        homing_mode: CoolStep
        stallguard: 16
        stallguard_debug: false
        toff_coolstep: 3
        tpfd: 4

  y:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 160
    soft_limits: True
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 400.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.34
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      tmc_5160:
        step_pin: I2SO.5
        direction_pin: I2SO.4:high
        disable_pin: I2SO.7
        cs_pin: NO_PIN
        spi_index: 2
        r_sense_ohms: 0.075
        run_amps: 2.0
        hold_amps: 1.5
        microsteps: 16
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        run_mode: CoolStep
        homing_mode: CoolStep
        stallguard: 16
        stallguard_debug: false
        toff_coolstep: 3
        tpfd: 4

  z:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 1500.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 105.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0
      feed_mm_per_min: 400.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.33
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      tmc_5160:
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8
        cs_pin: NO_PIN
        spi_index: 3
        r_sense_ohms: 0.075
        run_amps: 2.0
        hold_amps: 1.5
        microsteps: 16
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        run_mode: CoolStep
        homing_mode: CoolStep
        stallguard: 16
        stallguard_debug: false
        toff_coolstep: 3
        tpfd: 4

  a:  #Not Used in the Mill
    # E0
    steps_per_mm: 157.750
    max_rate_mm_per_min: 18000.000
    acceleration_mm_per_sec2: 1500.000
    max_travel_mm: 325.000
    soft_limits: false
    homing:
      cycle: -1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      tmc_5160:
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15
        cs_pin: NO_PIN
        spi_index: 4
        r_sense_ohms: 0.022
        run_amps: 0.5
        hold_amps: 0.5
        microsteps: 16
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        run_mode: CoolStep
        homing_mode: CoolStep
        stallguard: 16
        stallguard_debug: false
        toff_coolstep: 3
        tpfd: 4


probe:
  toolsetter_pin: gpio.37:low

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.0
  card_detect_pin: NO_PIN
  frequency_hz: 8000000
# I2SO.3

# coolant:
#   flood_pin: gpio.2:high
#   mist_pin:  gpio.3:low
# gpio.4 # HB MOS

# probe:
#   pin: gpio.5:low:pu
#   toolsetter_pin: gpio.14:low

# Begin Huanyang
#uart1:
#  txd_pin: gpio.15
#  rxd_pin: gpio.16
#  rts_pin: gpio.14
#  baud: 9600
#  mode: 8N1

# Huanyang:
#  uart_num: 1
#  modbus_id: 1
#  tool_num: 0
#  speed_map: 0=0% 8000=22% 10000=27% 15000=40% 2000=54% 24000=63%   
#  off_on_alarm: false

PWM:
   pwm_hz: 5000
   output_pin: gpio.13
   enable_pin: NO_PIN
   direction_pin: NO_PIN
   disable_with_s0: false
   s0_with_disable: true
   spinup_ms: 0
   spindown_ms: 0
   tool_num: 0
   speed_map: 0=0% 8000=29% 15000=54% 2000=69% 24000=85%  
   off_on_alarm: false

i2c0:
   sda_pin: gpio.27
   scl_pin: gpio.26

status_outputs:
  report_interval_ms: 500
  idle_pin: I2SO.11:low
  run_pin: I2SO.14:low
  alarm_pin: I2SO.3:low
# hold_pin: gpio.16
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.9.7 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine Rat Rig Mill]
[MSG:INFO: Board BTT Rodent-Z V1.0]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21Min Pulse:2us]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.0 detect:NO_PIN freq:8000000]
[MSG:INFO: I2C SDA: gpio.27, SCL: gpio.26, Freq: 100000, Bus #: 0]
[MSG:INFO: Stepping:I2S_STREAM Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 4]
[MSG:INFO: Axis X (0.000,340.000)]
[MSG:INFO:   Motor0]
[MSG:DBG: TMCStepper Library Ver. 0x703]
[MSG:INFO:     tmc_5160 Step:I2SO.2 Dir:I2SO.1 CS:gpio.5 Disable:I2SO.0 Index:1 R:0.075]
[MSG:INFO:  Pos Limit gpio.35]
[MSG:INFO: Axis Y (0.000,160.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:I2SO.5 Dir:I2SO.4 CS:NO_PIN Disable:I2SO.7 Index:2 R:0.075]
[MSG:INFO:  Pos Limit gpio.34]
[MSG:INFO: Axis Z (-105.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:I2SO.10 Dir:I2SO.9 CS:NO_PIN Disable:I2SO.8 Index:3 R:0.075]
[MSG:INFO:  Pos Limit gpio.33]
[MSG:INFO: Axis A (-175.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:I2SO.13 Dir:I2SO.12 CS:NO_PIN Disable:I2SO.15 Index:4 R:0.022]
[MSG:INFO: X Axis driver test passed]
[MSG:DBG: X Axis Coolstep]
[MSG:INFO: Y Axis driver test passed]
[MSG:DBG: Y Axis Coolstep]
[MSG:INFO: Z Axis driver test passed]
[MSG:DBG: Z Axis Coolstep]
[MSG:INFO: A Axis driver test passed]
[MSG:DBG: A Axis Coolstep]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: AP SSID Mill IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: Status outputs Interval:500 Idle:I2SO.11:low Cycle:I2SO.14:low Hold:NO_PIN Alarm:I2SO.3:lowDoor:NO_PIN]
[MSG:INFO: PWM Spindle Ena:NO_PIN Out:gpio.13 Dir:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Toolsetter gpio.37]
```

### What happened?

Good time of the day. I’m having trouble connecting the tool setter to my RatRig Mill. I’m using the Rodent board version 1.1. I’ve tried all possible wiring combinations with the four wires, but none seem to work.

I mistakenly posted a photo of an error message saying the text couldn’t be found, but I can now confirm that message is unrelated. There’s no reaction from the tool setter in debug mode when I press it. Meanwhile, the endstops for X, Y, and Z respond immediately.

I’ve checked the tool setter with a multimeter and identified the correct wire pairs. In my configuration, I'm only using the pin for the tool setter because the 3D probe isn’t working (or isn’t working properly), so I can’t confirm its behavior.

I’m new to this, so I’m not entirely sure how to check whether the Rodent board might be faulty. However, all endstops and motors function correctly. I’ve also noticed that if I set the tool setter pin to low, the "P" icon in the dashboard turns dark blue — as if it’s permanently activated.

### Other Information

![Image](https://github.com/user-attachments/assets/67f23e62-5408-4079-bebd-c0f36d55cca4)
![Image](https://github.com/user-attachments/assets/798ee448-b683-470b-96c1-8186495bcdee)
![Image](https://github.com/user-attachments/assets/40996ecc-6600-4062-81d4-7399bf5275a3)
![Image](https://github.com/user-attachments/assets/825bf782-e9e5-4268-bbf3-811acf971c65)
![Image](https://github.com/user-attachments/assets/12587c9a-85ac-46aa-a704-b39b191b173d)
