### ISSUE TITLE
Problem: Jogging a servo with soft limits from UGS Platform

### ISSUE THREAD

**Issue by Liizam** [bdring/FluidNC#1504]
### Wiki Search Terms

 Servo issues, servo jerk, servo smooth movement

### Controller Board

TMC2209 Pen/Laser CNC Controller

### Machine Description

The wall drawing XY-plotter- BOTSY with a micro servo motor. 

### Input Circuits

```yaml

```

### Configuration file

```yaml
z:
    steps_per_mm: 400
    max_rate_mm_per_min: 8000
    acceleration_mm_per_sec2: 3000
    max_travel_mm: 30
    soft_limits: true
    homing:
      cycle: 0
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 2000
      seek_mm_per_min: 2000
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 0.1
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.21
        min_pulse_us: 2000
        max_pulse_us: 1000
        timer_ms: 5
```

### Startup Messages

```text
>>> $ss
[MSG:INFO: FluidNC v3.9.6 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:BOTSYART_v4A_macros2.yaml]
[MSG:WARN: X Axis tmc_2209 homing current not in config. Using run current]
[MSG:WARN: Y Axis tmc_2209 homing current not in config. Using run current]
[MSG:INFO: Machine BOTSY Apr 17, 2025]
[MSG:INFO: Board FluidNC Pen/Laser 2209 V2]
[MSG:INFO: UART1 Tx:gpio.17 Rx:gpio.16 RTS:NO_PIN Baud:115200]
[MSG:INFO: UART2 Tx:gpio.4 Rx:gpio.15 RTS:NO_PIN Baud:5000000]
[MSG:INFO: uart_channel2 created at report interval: 75]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:3us Dsbl Delay:0us Dir Delay:1us Idle Delay:5ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13]
[MSG:INFO: Axis X (-1220.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 UART1 Addr:0 CS:NO_PIN Step:gpio.14 Dir:gpio.12 Disable:NO_PIN R:0.110]
[MSG:INFO:  Neg Limit gpio.36:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (-2000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 UART1 Addr:1 CS:NO_PIN Step:gpio.25 Dir:gpio.26 Disable:NO_PIN R:0.110]
[MSG:INFO:  Neg Limit gpio.39:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (0.000,30.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     rc_servo Pin:gpio.21 Pulse Len(2000,1000 period:1048575)]
[MSG:INFO:     Update timer for rc_servo at 5 ms]
[MSG:INFO: X Axis driver test passed]
[MSG:INFO: Y Axis driver test passed]
[MSG:INFO: safety_door_pin gpio.33:low]
[MSG:INFO: feed_hold_pin gpio.35:low]
[MSG:INFO: cycle_start_pin gpio.34:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: BT Started with FluidNC]
[MSG:INFO: Laser Ena:gpio.2 Out:gpio.27 Freq:5000Hz Period:8191]
ok
```

### User Interface Software

UGS Platform, step size Z: 3 inch, feed rate: 8,000 

### What happened?

Bart, 
Using Z-jog from the UGS Platform, I'm experiencing a servo glitch—please see the attached video.

The servo PWM normally switches between two values: 1ms (two columns) and 2ms (four columns). I press Z+ and Z– from the UGS Platform, and the servo executes the jog commands correctly a few times times. Then suddenly, the PWM signal becomes incorrect—either 0.5ms or 1.5ms. This happens if I press Z+/- quickly and slowly.

I've tested three different mini-servo models with different operating currents, including a brand-name Futaba, and the glitch occurs with all of them.
Also, I’ve noticed that the servo arm often jerks slightly in the opposite direction before beginning its movement.

Any suggestions would be greatly appreciated.

https://github.com/user-attachments/assets/70a1ccdc-81e6-439d-b575-1ae1eb03238e

### GCode File

Z-Jog commands:

Z+:  $J=G20G91Z3F8000
Z-:  $J=G20G91Z-3F8000

**Comment by bdring** [comment]
the update interval set by `timer_ms` looks really fast at 5ms. That is just a fraction of the PWM period of 20ms. (50Hz).

Try changing it to `timer_ms: 100`. 

We might want to change the code to add a lower limit or something based on the frequency. The default is 20. I am not sure how the PWM period is affected when it is changed so fast.

**Comment by Liizam** [comment]
I've been testing servo behavior using various `timer_ms` settings. I measured the number of **correct arm movements**** (from 0° to 90° and back) versus **glitch actions**. The most reliable performance occurred at:

* `timer_ms = 5`, with a **Z step = 1 inch** and **Z feed rate = 8000**. I achieved over **100 successful Z-jogs** in UGS.
* `timer_ms = 10`, same Z step and feed rate. Success ratios were approximately **62:1**, **51:1**, and **24:1** (correct\:glitch).
* `timer_ms = 100` produced unreliable results, with ratios around **1:1** or **2:1**.

Additionally, I noticed that the **servo movement range** is affected by the **Z step** and **Z feed rate** settings in the UGS Jog Controller.

From a mechanical design perspective, I expected the servo's motion to depend solely on PWM signal parameters (e.g., `min_pulse_us` to `max_pulse_us` defining the arm angles). During Z-jog commands in UGS (e.g., Z+: `$J=G20G91Z2F500` or Z-: `$J=G20G91Z-2F500`), the servo moves only when the jog direction (Z+ or Z-) changes. The wall limits the pen/marker move.

**Suggested YAML Features for FluidNC**:
These features relate specifically to **drawing plotters**, where the **physical limits**—such as the wall or drawing surface—constrain pen/marker movement, not the precise servo angle itself.

* Add a **transition time** for the PWM signal to move from `min_pulse_us` to `max_pulse_us`. This softens the servo motion, so the pen or marker doesn’t slam into the drawing surface.
* Include a **servo dwell time** (a configurable delay) after the PWM signal changes, to allow the motion to complete before the next G-code command executes. This accounts for the actual speed and mechanics of the servo.

I may be stuck in my current logic about how drawing plotters behave, especially when it comes to servo control. Open to corrections or suggestions. I'm happy to test any proposed changes or take additional measurements.

**Comment by bdring** [comment]
Edit your first post to show your complete config file. I assume there is more to it.

**Comment by bdring** [comment]
I have made many plotters using FluidNC.

The timer_ms is the time between updates of the PWM value as it is tracking the virtual Z axis. If you have a frequency of 50Hz, that is a 20ms period. If you have a timer_ms less than 20, then it is trying to update the PWM faster than the period. That is not good. 

- Add a transition time for the PWM signal to move from min_pulse_us to max_pulse_us. This softens the servo motion, so the pen or marker doesn’t slam into the drawing surface.

The PWM range is mapped the the range of travel for the axis. The axis will move through the range of travel per your `max_rate_mm_per_min` value. You have a very high rate of travel so the servo will move quicky. If you did a G01 Z30 F30 it would take a full minute to do the move from Z0 to Z30

 - Include a servo dwell time (a configurable delay) after the PWM signal changes, to allow the motion to complete before the next G-code command executes. This accounts for the actual speed and mechanics of the servo.

If you properly give `max_rate_mm_per_min` the true rate of travel it will work fine.

**Comment by bdring** [comment]
Here it is running at 2 different speeds.

Post your full config!

https://github.com/user-attachments/assets/45a84e82-9efb-4b3e-94cf-3804ec8b2700

**Comment by Liizam** [comment]
Thank you very much for your attention to my issue. Here is my config.
 
name: 
board: FluidNC Pen/Laser 2209 V2
meta: 
arc_tolerance_mm: 0.1
junction_deviation_mm: 0.1
stepping:
  engine: RMT
  idle_ms: 5
  dir_delay_us: 1
  pulse_us: 3
  disable_delay_us: 0
start:
  must_home: false
  deactivate_parking: false
  check_limits: false
uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 115200
  mode: 8N1
uart2:
  txd_pin: gpio.4
  rxd_pin: gpio.15
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 5000000
  mode: 8N1
uart_channel2:
  uart_num: 2
  report_interval_ms: 75
axes:
  shared_stepper_disable_pin: gpio.13:high
  x:
    steps_per_mm: 40.18
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 40
    max_travel_mm: 1220
    soft_limits: false
    homing: false
    motor0:
      limit_neg_pin: gpio.36:low
      hard_limits: false
      pulloff_mm: 5
      tmc_2209:
        uart_num: 1
        addr: 0
        r_sense_ohms: 0.11
        run_amps: 0.7
        hold_amps: 0.05
        microsteps: 8
        stallguard: 5
        stallguard_debug: false
        toff_disable: 1
        toff_stealthchop: 6
        toff_coolstep: 4
        run_mode: SpreadCycle
        homing_mode: SpreadCycle
        use_enable: false
        direction_pin: gpio.12
        step_pin: gpio.14
    motor1:
      null_motor: null
  y:
    steps_per_mm: 40.08
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 2000
    soft_limits: false
    homing: false
    motor0:
      limit_neg_pin: gpio.39:low
      tmc_2209:
        uart_num: 1
        addr: 1
        r_sense_ohms: 0.11
        run_amps: 0.7
        hold_amps: 0.05
        microsteps: 8
        stallguard: 5
        stallguard_debug: false
        toff_disable: 1
        toff_stealthchop: 6
        toff_coolstep: 4
        run_mode: SpreadCycle
        homing_mode: StallGuard
        use_enable: false
        direction_pin: gpio.26
        step_pin: gpio.25
    motor1:
      null_motor: null
  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 8000
    acceleration_mm_per_sec2: 3000
    max_travel_mm: 30
    soft_limits: true
    homing:
      cycle: 0
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 2000
      seek_mm_per_min: 2000
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 0.1
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.21
        min_pulse_us: 2000
        max_pulse_us: 1000
        timer_ms: 5
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
probe:
  pin: NO_PIN
control:
  feed_hold_pin: gpio.35:low
  cycle_start_pin: gpio.34:low
  safety_door_pin: gpio.33:low
laser:
  pwm_hz: 5000
  output_pin: gpio.27
  enable_pin: gpio.2
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 255=100.000%
macros:
  startup_line0: G4 P0.2
  startup_line1: G21&G90&G92 Z0&G0 Z30

**Comment by Liizam** [comment]
Thank you very much for your attention to my issue. Here is my config.

name: 
board: FluidNC Pen/Laser 2209 V2
meta: 
arc_tolerance_mm: 0.1
junction_deviation_mm: 0.1
stepping:
  engine: RMT
  idle_ms: 5
  dir_delay_us: 1
  pulse_us: 3
  disable_delay_us: 0
start:
  must_home: false
  deactivate_parking: false
  check_limits: false
uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 115200
  mode: 8N1
uart2:
  txd_pin: gpio.4
  rxd_pin: gpio.15
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 5000000
  mode: 8N1
uart_channel2:
  uart_num: 2
  report_interval_ms: 75
axes:
  shared_stepper_disable_pin: gpio.13:high
  x:
    steps_per_mm: 40.18
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 40
    max_travel_mm: 1220
    soft_limits: false
    homing: false
    motor0:
      limit_neg_pin: gpio.36:low
      hard_limits: false
      pulloff_mm: 5
      tmc_2209:
        uart_num: 1
        addr: 0
        r_sense_ohms: 0.11
        run_amps: 0.7
        hold_amps: 0.05
        microsteps: 8
        stallguard: 5
        stallguard_debug: false
        toff_disable: 1
        toff_stealthchop: 6
        toff_coolstep: 4
        run_mode: SpreadCycle
        homing_mode: SpreadCycle
        use_enable: false
        direction_pin: gpio.12
        step_pin: gpio.14
    motor1:
      null_motor: null
  y:
    steps_per_mm: 40.08
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 2000
    soft_limits: false
    homing: false
    motor0:
      limit_neg_pin: gpio.39:low
      tmc_2209:
        uart_num: 1
        addr: 1
        r_sense_ohms: 0.11
        run_amps: 0.7
        hold_amps: 0.05
        microsteps: 8
        stallguard: 5
        stallguard_debug: false
        toff_disable: 1
        toff_stealthchop: 6
        toff_coolstep: 4
        run_mode: SpreadCycle
        homing_mode: StallGuard
        use_enable: false
        direction_pin: gpio.26
        step_pin: gpio.25
    motor1:
      null_motor: null
  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 8000
    acceleration_mm_per_sec2: 3000
    max_travel_mm: 30
    soft_limits: true
    homing:
      cycle: 0
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 2000
      seek_mm_per_min: 2000
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 0.1
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.21
        min_pulse_us: 2000
        max_pulse_us: 1000
        timer_ms: 5
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
probe:
  pin: NO_PIN
control:
  feed_hold_pin: gpio.35:low
  cycle_start_pin: gpio.34:low
  safety_door_pin: gpio.33:low
laser:
  pwm_hz: 5000
  output_pin: gpio.27
  enable_pin: gpio.2
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 255=100.000%
macros:
  startup_line0: G4 P0.2
  startup_line1: G21&G90&G92 Z0&G0 Z30

**Comment by Liizam** [comment]
Thank you very much for your attention to my issue.

```
name: 
board: FluidNC Pen/Laser 2209 V2
meta: 
arc_tolerance_mm: 0.1
junction_deviation_mm: 0.1
stepping:
  engine: RMT
  idle_ms: 5
  dir_delay_us: 1
  pulse_us: 3
  disable_delay_us: 0
start:
  must_home: false
  deactivate_parking: false
  check_limits: false
uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 115200
  mode: 8N1
uart2:
  txd_pin: gpio.4
  rxd_pin: gpio.15
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 5000000
  mode: 8N1
uart_channel2:
  uart_num: 2
  report_interval_ms: 75
axes:
  shared_stepper_disable_pin: gpio.13:high
  x:
    steps_per_mm: 40.18
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 40
    max_travel_mm: 1220
    soft_limits: false
    homing: false
    motor0:
      limit_neg_pin: gpio.36:low
      hard_limits: false
      pulloff_mm: 5
      tmc_2209:
        uart_num: 1
        addr: 0
        r_sense_ohms: 0.11
        run_amps: 0.7
        hold_amps: 0.05
        microsteps: 8
        stallguard: 5
        stallguard_debug: false
        toff_disable: 1
        toff_stealthchop: 6
        toff_coolstep: 4
        run_mode: SpreadCycle
        homing_mode: SpreadCycle
        use_enable: false
        direction_pin: gpio.12
        step_pin: gpio.14
    motor1:
      null_motor: null
  y:
    steps_per_mm: 40.08
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 2000
    soft_limits: false
    homing: false
    motor0:
      limit_neg_pin: gpio.39:low
      tmc_2209:
        uart_num: 1
        addr: 1
        r_sense_ohms: 0.11
        run_amps: 0.7
        hold_amps: 0.05
        microsteps: 8
        stallguard: 5
        stallguard_debug: false
        toff_disable: 1
        toff_stealthchop: 6
        toff_coolstep: 4
        run_mode: SpreadCycle
        homing_mode: StallGuard
        use_enable: false
        direction_pin: gpio.26
        step_pin: gpio.25
    motor1:
      null_motor: null
  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 8000
    acceleration_mm_per_sec2: 3000
    max_travel_mm: 30
    soft_limits: true
    homing:
      cycle: 0
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 2000
      seek_mm_per_min: 2000
      settle_ms: 500
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 0.1
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.21
        min_pulse_us: 2000
        max_pulse_us: 1000
        timer_ms: 5
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
probe:
  pin: NO_PIN
control:
  feed_hold_pin: gpio.35:low
  cycle_start_pin: gpio.34:low
  safety_door_pin: gpio.33:low
laser:
  pwm_hz: 5000
  output_pin: gpio.27
  enable_pin: gpio.2
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 255=100.000%
macros:
  startup_line0: G4 P0.2
  startup_line1: G21&G90&G92 Z0&G0 Z30


```
