### ISSUE TITLE
Problem:  cycle: 0 can not home by $H<axis>

### ISSUE THREAD

**Issue by favoritewky** [bdring/FluidNC#1511]
### Wiki Search Terms

http://wiki.fluidnc.com/en/config/axes
cycle:

    Type: [Integer](http://wiki.fluidnc.com/en/config/overview#integer)
    Range: -1 to 6
    Default: -1
    Interactions: multi-axis homing cannot be used with CoreXY, because 2 motors are used for each axis move.
    Details:

        Homing cycles determine each axis home. Cycles allow you to home axes one at a time or group a few axes into a single cycle for multi-axis homing. Assign the same number to multiple axes to home them in the same cycle. Many people would home the Z first (cycle: 1) and then might home X and Y at the same time (cycle: 2)

        A setting of 1 or greater enables the axis for homing with $H. Anything lower than 1 will be an inactive cycle and no physical homing will occur for that axis.

        **A setting of 0 means it will not home with $H, but you can still home it with $H<axis>**

        A value of -1 means the machine will not move, but the current machine position (mpos) position of the axis will be set to the mpos_mm value for the axis. This can be used for axes that don't have any switches.

        Typically you would put the Z axis on cycle: 1 and the other axes on higher cycles.

### Controller Board

 MKS-DLC32

### Machine Description

Coryxy voron v0.

### Input Circuits

```yaml

```

### Configuration file

```yaml
board: MKS-DLC32
name: Laser

kinematics:
  corexy:

stepping:
  engine: I2S_STATIC
#Static only, Stream Produces a second "ghost line" when doing engraving/Filling
  idle_ms: 254
  pulse_us: 6
  dir_delay_us: 10
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 150.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_pos_pin: gpio.36
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6:high
    

  y:
    steps_per_mm: 80
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 150.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_pos_pin: gpio.35
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2:high
 

  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 12000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 100.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.34
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4:low

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17
```

### Startup Messages

```text
[MSG:INFO: FluidNC 3.7.13 https://github.com/bdring/FluidNC]]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]]
[MSG:DBG: Spiffs mount failed: ESP_FAIL]]
[MSG:INFO: Local filesystem type is littlefs]]
[MSG:INFO: Configuration file:config.yaml]]
[MSG:DBG: Running after-parse tasks]]
[MSG:DBG: Checking configuration]]
[MSG:INFO: Machine Laser]]
[MSG:INFO: Board MKS-DLC32]]
[MSG:INFO: I2SO BCK:gpio.16 WS:gpio.17 DATA:gpio.21]]
[MSG:INFO: SPI SCK:gpio.14 MOSI:gpio.13 MISO:gpio.12]]
[MSG:DBG: See http://wiki.fluidnc.com/en/config/sd_card#sdfallbackcs-access-sd-without-a-config-file]]
[MSG:INFO: Stepping:I2S_static Pulse:6us Dsbl Delay:0us Dir Delay:10us Idle Delay:254ms]]
[MSG:INFO: Axis count 3]]
[MSG:INFO: Shared stepper disable I2SO.0]]
[MSG:INFO: Axis X (0.000,150.000)]]
[MSG:INFO:   Motor0]]
[MSG:INFO:     stepstick Step:I2SO.5 Dir:I2SO.6 Disable:NO_PIN]]
[MSG:INFO:  X Pos Limit gpio.36]]
[MSG:INFO: Axis Y (0.000,150.000)]]
[MSG:INFO:   Motor0]]
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:NO_PIN]]
[MSG:INFO:  Y Pos Limit gpio.35]]
[MSG:INFO: Axis Z (0.000,100.000)]]
[MSG:INFO:   Motor0]]
[MSG:INFO:     stepstick Step:I2SO.3 Dir:I2SO.4:low Disable:NO_PIN]]
[MSG:INFO:  Z Neg Limit gpio.34]]
[MSG:INFO: macro0_pin gpio.33:low:pu]]
[MSG:INFO: Kinematic system: CoreXY]]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.32 Freq:5000Hz Period:8191]]
[MSG:INFO: Using spindle Laser]]
[MSG:INFO: Probe Pin: gpio.22]]
[MSG:INFO: Connecting to STA SSID:]]
[MSG:INFO: Connecting.]]
[MSG:INFO: Connecting..]]
[MSG:INFO: Connected - IP is ]]
[MSG:INFO: WiFi on]]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]]
[MSG:INFO: SSDP Started]]
[MSG:INFO: HTTP started on port 80]]
[MSG:INFO: Telnet started on port 23]]
```

### User Interface Software

Webui

### What happened?

Grbl 3.7 [FluidNC 3.7.13 (wifi) '$' for help]
[MSG:ERR: Not a homed axis:]
[MSG:ERR: Macro can only be used in idle state]
[MSG:DBG: Homing Cycle X]
[MSG:DBG: Homing nextPhase FastApproach]
[MSG:DBG: Starting from 150.456,150.006,50.000]
[MSG:DBG: Planned move to 315.456,150.006,50.000 @ 600.000]
[MSG:DBG:  X Pos Limit 1]
[MSG:DBG: Homing limited X]
[MSG:DBG: Homing nextPhase Pulloff0]
[MSG:DBG: Starting from 150.806,150.006,50.000]
[MSG:DBG: Planned move to 149.806,150.006,50.000 @ 300.000]
[MSG:DBG:  X Pos Limit 0]
[MSG:DBG: CycleStop Pulloff0]
[MSG:DBG: Homing nextPhase SlowApproach]
[MSG:DBG: Starting from 150.150,149.663,50.000]
[MSG:DBG: Planned move to 151.250,149.663,50.000 @ 300.000]
[MSG:DBG:  X Pos Limit 1]
[MSG:DBG: Homing limited X]
[MSG:DBG: Homing nextPhase Pulloff1]
[MSG:DBG: Starting from 150.725,149.663,50.000]
[MSG:DBG: Planned move to 149.725,149.663,50.000 @ 300.000]
[MSG:DBG:  X Pos Limit 0]
[MSG:DBG: CycleStop Pulloff1]
[MSG:DBG: Homing nextPhase Pulloff2]
[MSG:DBG: mpos was 149.994,149.394,50.000]
[MSG:DBG: mpos becomes 150.000,149.394,50.000]
[MSG:DBG: mpos transformed 150.000,149.400,50.000]
[MSG:DBG: Homing Cycle Y]
[MSG:DBG: Homing nextPhase FastApproach]
[MSG:DBG: Starting from 150.000,149.400,50.000]
[MSG:DBG: Planned move to 150.000,314.400,50.000 @ 600.000]
[MSG:DBG:  Y Pos Limit 1]
[MSG:DBG: Homing limited Y]
[MSG:DBG: Homing nextPhase Pulloff0]
[MSG:DBG: Starting from 150.000,150.825,50.000]
[MSG:DBG: Planned move to 150.000,149.825,50.000 @ 300.000]
[MSG:DBG:  Y Pos Limit 0]
[MSG:DBG: CycleStop Pulloff0]
[MSG:DBG: Homing nextPhase SlowApproach]
[MSG:DBG: Starting from 150.237,150.062,50.000]
[MSG:DBG: Planned move to 150.237,151.163,50.000 @ 300.000]
[MSG:DBG:  Y Pos Limit 1]
[MSG:DBG: Homing limited Y]
[MSG:DBG: Homing nextPhase Pulloff1]
[MSG:DBG: Starting from 150.238,150.800,50.000]
[MSG:DBG: Planned move to 150.238,149.800,50.000 @ 300.000]
[MSG:DBG:  Y Pos Limit 0]
[MSG:DBG: CycleStop Pulloff1]
[MSG:DBG: Homing nextPhase Pulloff2]
[MSG:DBG: mpos was 150.450,150.012,50.000]
[MSG:DBG: mpos becomes 150.450,150.000,50.000]
[MSG:DBG: mpos transformed 150.450,150.000,50.000]
[MSG:DBG: Homing done]
[MSG:DBG: Jog constrained to axis range]
[MSG:DBG: Jog constrained to axis range]
[MSG:DBG: Jog constrained to axis range]
[MSG:DBG: Jog constrained to axis range]
$HZ
[MSG:ERR: Not a homed axis:]
[MSG:ERR: Macro can only be used in idle state]
ok
$Hz
[MSG:ERR: Not a homed axis:]
[MSG:ERR: Macro can only be used in idle state]
ok

I can't home z by $HZ.
