### ISSUE TITLE
Problem: G0 is turning off the spindle PWM

### ISSUE THREAD

**Issue by AntonioFromBrazil** [bdring/FluidNC#1513]
### Wiki Search Terms

G0 command is turning off the spindle PWM. This is boring since some softwares such inkscape/lasertools generate G0 commands to move axis... Is there anyway to avoid that ? Thanks 

### Controller Board

I am using a custom controller with ESP32 wroom. The spindle PWM is working ok. The problem is only that it is undesired turned off with G0 move axes command...

### Machine Description

The apllication is a homemade styrofoam cutter. The spindle PWM is used to warm up the niquelcrome wire

### Input Circuits

```yaml

```

### Configuration file

```yaml
name: styrofoam cutter
board: ESP32 Dev Controller V4
stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 0
  pulse_us: 30
  disable_delay_us: 0
axes:
  x:
    steps_per_mm: 200
    max_rate_mm_per_min: 600
    acceleration_mm_per_sec2: 10
    max_travel_mm: 300
    homing:
      cycle: 1
      mpos_mm: 5
      positive_direction: false
    motor0:
      limit_all_pin: gpio.17:pu
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      pulloff_mm: 5
      stepstick:
        step_pin: gpio.12
        direction_pin: gpio.14
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
      hard_limits: false
  y:
    steps_per_mm: 200
    max_rate_mm_per_min: 600
    acceleration_mm_per_sec2: 10
    max_travel_mm: 200
    homing:
      cycle: 1
      mpos_mm: 5
      positive_direction: false
    motor0:
      limit_all_pin: gpio.4:pu
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      pulloff_mm: 5
      stepstick:
        step_pin: gpio.26
        direction_pin: gpio.15
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
      hard_limits: false
  z:
    steps_per_mm: 200
    max_rate_mm_per_min: 600
    acceleration_mm_per_sec2: 10
    max_travel_mm: 200
    homing:
      cycle: 1
      mpos_mm: -5
      positive_direction: true
    motor0:
      limit_all_pin: gpio.16:pu
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      stepstick:
        step_pin: gpio.27
        direction_pin: gpio.33
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5
  homing_runs: 1
  shared_stepper_disable_pin: gpio.13:pu
  shared_stepper_reset_pin: NO_PIN
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
coolant:
  flood_pin: gpio.25
  mist_pin: gpio.21
start:
  must_home: false
  deactivate_parking: false
Laser:
  pwm_hz: 1000
  disable_with_s0: true
  s0_with_disable: true
  output_pin: gpio.2
  enable_pin: gpio.0
  off_on_alarm: true
  speed_map: 0=0.000% 0=0.0% 100=100.000%
```

### Startup Messages

```text
$SS
[MSG:INFO: FluidNC v3.9.7 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:configCortadorV3.yaml]
[MSG:INFO: Machine Controlador do cortador de isopor VersÃ£o 3]
[MSG:INFO: Board ESP32 Dev Controller V4]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5:pd detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:30us Dsbl Delay:0us Dir Delay:0us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13:pu]
[MSG:INFO: Axis X (5.000,175.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.12 Dir:gpio.14 Disable:NO_PIN]
[MSG:INFO:  All Limit gpio.17:pu]
[MSG:INFO: Axis Y (5.000,185.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.26 Dir:gpio.15 Disable:NO_PIN]
[MSG:INFO:  All Limit gpio.4:pu]
[MSG:INFO: Axis Z (-15.000,-5.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.27 Dir:gpio.33 Disable:NO_PIN]
[MSG:INFO:  All Limit gpio.16:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Connecting to STA SSID:Hortencia148]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.15.99]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: Laser Ena:gpio.0 Out:gpio.2 Freq:1000Hz Period:255]
[MSG:INFO: Flood coolant gpio.25]
[MSG:INFO: Mist coolant gpio.21]
ok
```

### User Interface Software

Candle

### What happened?

na

### GCode File

na

### Other Information

na
