### ISSUE TITLE
Problem: PlasmaSpindle, M3 code does not change GPIO state, until there is no arc OK signal.

### ISSUE THREAD

**Issue by mmt8284** [bdring/FluidNC#1519]
### Wiki Search Terms

PlasmaSpindle

### Controller Board

ESP32 DevKitC ESP-WROOM-32U

### Machine Description

Only esp32 board. I have working setup that executes gcode without actual cutting but that's not the case.
For recreating this problem only esp32 board is needed.

### Input Circuits

```yaml
https://crcit.net/c/f29ecf7ff51f4f9a8ecea863c68f276a
```

### Configuration file

```yaml
name: "ESP32 Dev Controller V4"
board: "ESP32 Dev Controller V4"

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0
  
start:
  must_home: false
  

axes:
  shared_stepper_disable_pin: gpio.14:high
  
  x:
    steps_per_mm: 14.0097
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 1330
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 2
      seek_mm_per_min: 1500
      feed_mm_per_min: 800
      positive_direction: true
    
    motor0:
      limit_neg_pin: gpio.4:low
      stepstick:
        direction_pin: gpio.25
        step_pin: gpio.33
      pulloff_mm: 10.0
    motor1:
      null_motor:

  y:
    steps_per_mm: 14.0097
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 880
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 10
      seek_mm_per_min: 1500
      feed_mm_per_min: 800
      positive_direction: false
    motor0:
      limit_neg_pin: gpio.35:low
      stepstick:
        direction_pin: gpio.27
        step_pin: gpio.26
      pulloff_mm: 10.0
    motor1:
      limit_neg_pin: gpio.34:low
      stepstick:
        direction_pin: gpio.18
        step_pin: gpio.19
      pulloff_mm: 10.0

  z:
    steps_per_mm: 96.7741
    max_rate_mm_per_min: 1500
    acceleration_mm_per_sec2: 30
    max_travel_mm: 50
    homing:
      cycle: 1
      mpos_mm: 40
      positive_direction: false
      seek_mm_per_min: 400
      feed_mm_per_min: 200

    motor0:
      limit_neg_pin: gpio.5:low
      stepstick:
        direction_pin: gpio.21
        step_pin: gpio.22
      pulloff_mm: 10
    motor1:
      null_motor:
probe:
  pin: gpio.17:low
  

PlasmaSpindle:
  enable_pin: gpio.13:high
  arc_ok_pin: gpio.23:high
  arc_wait_ms: 3000
  tool_num: 0
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.9.7 https://github.com/bdring/FluidNC]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:test107.yml]
[MSG:INFO: Machine ESP32 Dev Controller V4]
[MSG:INFO: Board ESP32 Dev Controller V4]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.14]
[MSG:INFO: Axis X (-1328.000,2.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.33 Dir:gpio.25 Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.4:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (10.000,890.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.26 Dir:gpio.27 Disable:NO_PIN]
[MSG:INFO:  Y Neg Limit gpio.35:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     stepstick Step:gpio.19 Dir:gpio.18 Disable:NO_PIN]
[MSG:INFO:  Y2 Neg Limit gpio.34:low]
[MSG:INFO: Axis Z (40.000,90.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.22 Dir:gpio.21 Disable:NO_PIN]
[MSG:INFO:  Z Neg Limit gpio.5:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: ArcOK gpio.23]
[MSG:INFO: PlasmaSpindle Ena:gpio.13:high Arc OK:gpio.23]
[MSG:INFO: Probe gpio.17:low]
ok
```

### What happened?

Basically same problem, different setup. https://github.com/bdring/FluidNC/issues/1453)

From what I understand, when sending the M3 command, the state of GPIO.13 should change. This should trigger the relay, which, in turn, should allow the plasma to fire. After successfully igniting the arc (within the arc_wait_ms time), the plasma should return an 'arc OK' signal, and cutting should proceed.

The problem is that the M3 command doesn’t change the GPIO.13 signal until the 'arc OK' signal is returned, which is the wrong order and indicates a bug.

After changing the order and shorting the wires responsible for the 'arc OK' signal, and only then sending the M3 command, the plasma fires.

The 'arc OK' signal should be a response and a requirement to allow cutting, not to ignite the arc.

Please help me solve the problem.
