### ISSUE TITLE
Option to lock out single axis homing.

### ISSUE THREAD

**Issue by MitchBradley** [bdring/FluidNC#167]
POG had an option to prevent single axis homing. Some people see single axis homing as dangerous because you can unlock the homing alarm by homing only one axis.

**Comment by MitchBradley** [comment]
Another idea - instead of locking out single axis homing, have a list of axes that must be homed before the alarm goes off.

**Comment by MitchBradley** [comment]
It could be structured as a per-axis "must_home:" item.

**Comment by bdring** [comment]
I doubt this is a high priority. I added it to Trello as reminder that we left an old feature unresolved.

POG allows you to lock out single axis homing, but you can still $X to clear the homing alarm.

Here is an idea to allow a basic mimic of POG.

```yaml
axes:
  shared_stepper_disable_pin: gpio.13:high
  allow_single_axis_homing: true 
  
  x:
  ...
 ```
