### ISSUE TITLE
Axes do not work correctly.

### ISSUE THREAD

**Issue by IgorPack** [bdring/FluidNC#210]
Fixed (thanks Bart!). 

Installed FluidNC 3.2.8 firmware, Wemos D1 R32 ESP32 board (ESPDUINO-32 HW -729), wifi and WebUI starts instantly. Everything is fine! When connecting motors (NEMA23 2.8A) and connecting (top) with CNC Shield v3.0, the X axis moves normally in only one direction, when I try to return it in the opposite direction, the axis moves in the original direction. The Y and Z axes do not react at all. Changing the pins on the X-axis from the Y-axis and vice versa does not change anything. Perhaps this is due to a different pinout on the CNC Shield v3.0. 

I'm new to this and did't find any available instructions on how to check and configure it. Can someone tell me how to set up the car correctly? 

I would be grateful for any help. 

Thanks.

![Wemos D1 R3 ESP32   Shield v3 0](https://user-images.githubusercontent.com/96005179/147589977-468b9008-c993-498f-93e9-cbd0e1acc225.jpg)

![Config_1](https://user-images.githubusercontent.com/96005179/147592053-a88b502d-8ada-4719-8544-054ddae5fa60.PNG)

![Config_2](https://user-images.githubusercontent.com/96005179/147592063-bdc3c57d-177a-4b92-aa8a-53c40f1dd40d.PNG)

![Config_3](https://user-images.githubusercontent.com/96005179/147592074-634b64fc-62db-4b32-b6e3-8a542cf34202.PNG)

![Config_4](https://user-images.githubusercontent.com/96005179/147592083-fd5fee17-d03e-4df5-b556-c2cfb96a5aa2.PNG)

![Config_5](https://user-images.githubusercontent.com/96005179/147592095-4828cb67-4e1b-40b7-8800-de9fc0072449.PNG)

![Config_6](https://user-images.githubusercontent.com/96005179/147592105-257e84fc-0b51-43f4-bda4-fb59cb95797d.PNG)

![Config_7](https://user-images.githubusercontent.com/96005179/147592117-fd23d71a-fe9b-4d1a-a5d7-27b3e979bf2b.PNG)

![Config_8](https://user-images.githubusercontent.com/96005179/147592131-8b641cf8-18ab-4c18-800e-3c90cde45743.PNG)

![Config_9](https://user-images.githubusercontent.com/96005179/147592144-68c49225-a0a4-4c98-b244-857f9647a2fe.PNG)

![Config_10](https://user-images.githubusercontent.com/96005179/147592151-35bec540-0ea7-441b-87a8-367911776b9c.PNG)

**Comment by bdring** [comment]
Please paste your [startup messages](https://github.com/bdring/FluidNC/wiki/Requesting-Help#fluidnc-boot-messages) in a reply. Also, insert a photo of your electronics.

**Comment by chron0** [comment]
@IgorPack - I have the same hardware but checking my yml I use different pins as it was kind of a pain to find correct schematics for the shield and the esp32/arduino pin remapping:

Here's my config, your mileage may vary but it may help you:

```
axes:
  shared_stepper_disable_pin: gpio.12:low
  
  x:
    steps_per_mm: 100
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 900
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false
    
    motor0:
      limit_all_pin: gpio.39:low:pu
      stepstick:
        direction_pin: gpio.16
        step_pin: gpio.26

  y:
    steps_per_mm: 100
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 900
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
      limit_all_pin: gpio.4:low:pu
      stepstick:
        direction_pin: gpio.27
        step_pin: gpio.25

  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    homing:
      cycle: 1
      mpos_mm: 10
      positive_direction: true

    motor0:
      limit_all_pin: gpio.35:low:pu
      stepstick:
        direction_pin: gpio.14
        step_pin: gpio.17
```

**Comment by IgorPack** [comment]
OK, chron0, thanks for the advice, I'll try. Have a good New Year!

**Comment by IgorPack** [comment]
It looks like the problem was in the assignment of pins. Everything worked, the issue is closed, many thanks and good luck in projects to everyone who responded. Special thanks to Bard for everything he does.

**Comment by 4klemo4** [comment]
> @IgorPack - I have the same hardware but checking my yml I use different pins as it was kind of a pain to find correct schematics for the shield and the esp32/arduino pin remapping:
> 
> Here's my config, your mileage may vary but it may help you:
> 
> ```
> axes:
>   shared_stepper_disable_pin: gpio.12:low
>   
>   x:
>     steps_per_mm: 100
>     max_rate_mm_per_min: 6000
>     acceleration_mm_per_sec2: 200
>     max_travel_mm: 900
>     homing:
>       cycle: 2
>       mpos_mm: 10
>       positive_direction: false
>     
>     motor0:
>       limit_all_pin: gpio.39:low:pu
>       stepstick:
>         direction_pin: gpio.16
>         step_pin: gpio.26
> 
>   y:
>     steps_per_mm: 100
>     max_rate_mm_per_min: 6000
>     acceleration_mm_per_sec2: 200
>     max_travel_mm: 900
>     homing:
>       cycle: 2
>       mpos_mm: 10
>       positive_direction: false
> 
>     motor0:
>       limit_all_pin: gpio.4:low:pu
>       stepstick:
>         direction_pin: gpio.27
>         step_pin: gpio.25
> 
>   z:
>     steps_per_mm: 800
>     max_rate_mm_per_min: 2000
>     acceleration_mm_per_sec2: 25
>     max_travel_mm: 1000
>     homing:
>       cycle: 1
>       mpos_mm: 10
>       positive_direction: true
> 
>     motor0:
>       limit_all_pin: gpio.35:low:pu
>       stepstick:
>         direction_pin: gpio.14
>         step_pin: gpio.17
> ```
> 
> ![](https://camo.githubusercontent.com/a0ae94a4c185d2eec0a304a03ccd619446f4fb74a75691a83d4204aeca248baa/68747470733a2f2f63646e2e6c627279706c617965722e78797a2f6170692f76342f73747265616d732f667265652f667269636b696e2d6c617365722d707265766965772d3430772d6475616c2d64696f64652d6c617365722d746573742f623732363233396336636337386335313139636534306634363464376566643630346134373835322f336661303737)

Hi. I have the same hardware as you. Espduino with cnc shield. I have use you settings. I have one problem I can’t get the laser to work with ttl. Can you help me?

**Comment by chron0** [comment]
I had issues with that too, because the pins on the cncshield were mapped to pins on the esp32 which werent suitable for pwm.
I've chosen these ones now:

```
Laser:
  pwm_freq: 5000
  output_pin: gpio.32
  enable_pin: gpio.33
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool: 100
  speed_map: 0=0.000% 1000=100.000%
```

so you wont be using the pins labeled on the cncshield but the pins on the espduino directly. This one gives me good PWM.

**Comment by 4klemo4** [comment]
> I had issues with that too, because the pins on the cncshield were mapped to pins on the esp32 which werent suitable for pwm. I've chosen these ones now:
> 
> ```
> Laser:
>   pwm_freq: 5000
>   output_pin: gpio.32
>   enable_pin: gpio.33
>   direction_pin: NO_PIN
>   disable_with_s0: false
>   s0_with_disable: true
>   tool: 100
>   speed_map: 0=0.000% 1000=100.000%
> ```
> 
> so you wont be using the pins labeled on the cncshield but the pins on the espduino directly. This one gives me good PWM.

Ok tnx for the fast answer. I will try them as soon as I get home. Tnx

**Comment by 4klemo4** [comment]
> 

OK laser is working now but I have 2 problems. When the CNC shield is installed I can't connect via WiFi, only if I remove it I can connect. And I can't get axis to move. I have a4988 drivers in sixteenths steps. Can you share your full config?

**Comment by chron0** [comment]
```
name: "Cutt3r Ghetto Controller V1"
board: "Cutt3r Ghetto Controller V1"

kinematics:
  corexy:

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.12:low
  
  x:
    steps_per_mm: 100
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 900
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false
    
    motor0:
      limit_all_pin: gpio.39:low:pu
      stepstick:
        direction_pin: gpio.16
        step_pin: gpio.26

  y:
    steps_per_mm: 100
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 900
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
      limit_all_pin: gpio.4:low:pu
      stepstick:
        direction_pin: gpio.27
        step_pin: gpio.25

  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    homing:
      cycle: 1
      mpos_mm: 10
      positive_direction: true

    motor0:
      limit_all_pin: gpio.35:low:pu
      stepstick:
        direction_pin: gpio.14
        step_pin: gpio.17


spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: gpio.36
  mist_pin:  gpio.34

Laser:
  pwm_freq: 5000
  output_pin: gpio.32
  enable_pin: gpio.33
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool: 100
  speed_map: 0=0.000% 1000=100.000%
```
