### ISSUE TITLE
Constant speed

### ISSUE THREAD

**Issue by pilotak** [bdring/FluidNC#241]
At the moment when you set to move axis lets say 10cm it starts slowly then it's quick and is slow down in the end. What needs to be done in order to have constant speed?

FW v3.3.0
<details><summary>config</summary>
<p>

```yaml
name: "ESP32 plotter"
board: "ESP32 plotter v1.0"

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

stepping:
  engine: RMT
  idle_ms: 250
  pulse_us: 2
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.17
  x:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 500.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 750.000
      seek_mm_per_min: 350.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.27:high
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5.000
      tmc_2209:
        uart:
          txd_pin: gpio.22
          rxd_pin: gpio.21
          rts_pin: NO_PIN
          cts_pin: NO_PIN
          baud: 115200
          mode: 8N1

        addr: 0
        run_amps: 0.500
        hold_amps: 0.150
        microsteps: 16
        stallguard: 50
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 8
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StallGuard
        use_enable: false
        step_pin: gpio.4
        direction_pin: gpio.16
        disable_pin: NO_PIN

    motor1:
      null_motor:

  y:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false

    motor0:
      limit_neg_pin: gpio.26:high
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      tmc_2209:
        addr: 1
        run_amps: 0.500
        hold_amps: 0.150
        microsteps: 16
        stallguard: 15
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 8
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StallGuard
        use_enable: false
        step_pin: gpio.33
        direction_pin: gpio.32
        disable_pin: NO_PIN

    motor1:
      null_motor:

  z:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 25.000
    max_travel_mm: 200.000
    soft_limits: false

besc:
  pwm_hz: 50
  output_pin: gpio.13
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  speed_map: 0=0.000% 255=100.000%
  spinup_ms: 3
  spindown_ms: 3
  min_pulse_us: 900
  max_pulse_us: 2000

control:
  safety_door: NO_PIN
  reset: NO_PIN
  feed_hold: NO_PIN
  cycle_start: NO_PIN
  macro0: NO_PIN
  macro1: NO_PIN
  macro2: NO_PIN

user_outputs:
  analog0_pin: gpio.12
```
</p>
