### ISSUE TITLE
I2SO_STREAM bug?

### ISSUE THREAD

**Issue by snakescb** [bdring/FluidNC#245]
Hi, 

on v3.3.0 (but also on the previous version), my motor on a TMC5160 driver runs fine using the I2S_STATIC engine. I setup the config to 32 microstepping, 6400 steps per mm, 50mm per minute. When I jog 1 mm, the motor turns exactly 1 revolution as expected, all fine.

When I change nothing but the stepper engine to I2S_stream, jogging 1mm gives a bit more than 2.5 revolutions. I first assumed my controller board is broken, but I think it is more related to the software. Is this issue known? Is there a general recommendation, in which situation to use I2S_STATIC, and when I2S_STREAM?

Regards
Christian

**Comment by bdring** [comment]
I'll look into that tomorrow. If there is an issue it is likely setup or firmware.

The hardware is used the same way in either mode.

**Comment by bdring** [comment]
I tested I2SO_Stream and I2SO_Static on my machine. They both behave the same as far as motion and resolution go.

Can you post the config file you used? Only post the one that works. I will change the I2S type myself.

https://github.com/bdring/FluidNC/wiki/Requesting-Help

**Comment by snakescb** [comment]
Sure, here my config.yaml. Currently on my bench the motor is installed on the x axis. All drivers configured are installed on the board and initialize ok.

```
board: NCMate
name: CNC Maettenwil

start:
  must_home: false
  
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 10
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  
  x:
    steps_per_mm: 6400.000
    max_rate_mm_per_min: 350.000
    acceleration_mm_per_sec2: 50.00
    max_travel_mm: 400.000
    soft_limits: false
    
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000

      tmc_5160:
        cs_pin: i2so.7
        step_pin: i2so.6
        direction_pin: i2so.5
        disable_pin: i2so.4
        r_sense_ohms: 0.075
        run_amps: 0.8
        hold_amps: 0.4
        microsteps: 32
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false

  y:
    steps_per_mm: 640.000
    max_rate_mm_per_min: 1500
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 600.000
    soft_limits: false
    
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000

      tmc_5160:
        cs_pin: i2so.3
        step_pin: i2so.2
        direction_pin: i2so.1
        disable_pin: i2so.0
        r_sense_ohms: 0.075
        run_amps: 2.00
        hold_amps: 1.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      
      tmc_5160:
        cs_pin: i2so.11
        step_pin: i2so.10
        direction_pin: i2so.9
        disable_pin: i2so.8
        r_sense_ohms: 0.075
        run_amps: 2.00
        hold_amps: 1.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false

  z:
    steps_per_mm: 640
    max_rate_mm_per_min: 1500
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 200
    soft_limits: false

    homing:
      cycle: 1
      mpos_mm: 100
      positive_direction: true

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000

      tmc_5160:
        cs_pin: i2so.15
        step_pin: i2so.14
        direction_pin: i2so.13
        disable_pin: i2so.12
        r_sense_ohms: 0.075
        run_amps: 2.00
        hold_amps: 1.50
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: i2so.23
  mist_pin: i2so.20
  delay_ms: 0

probe:
  pin: gpio.4:low
  check_mode_start: true

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

10V:
  forward_pin: i2so.16
  reverse_pin: i2so.17
  pwm_hz: 5000
  output_pin: gpio.16
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 10000=100.000%
```
