### ISSUE TITLE
Multiple spindles of the same type

### ISSUE THREAD

**Issue by nils** [bdring/FluidNC#341]
FluidNC v3.4.1/Adafruit Huzzah32 Feather

Hi,

first of all, FluidNC is amazing! Only getting started with a self-designed wall plotter project, but I like it a lot already.

One thing I wonder though is whether it's possible to instantiate multiple spindles of the same type, e.g. like this:
```yaml
[ ... ]
besc:
  - pwm_hz: 50
    output_pin: gpio.12
    enable_pin: gpio.13:low
    direction_pin: NO_PIN
    disable_with_s0: false
    s0_with_disable: true
    spinup_ms: 0
    spindown_ms: 0
    tool_num: 0
    speed_map: 0=0.000% 255=100.000%
    min_pulse_us: 500
    max_pulse_us: 2500

  - pwm_hz: 50
    output_pin: gpio.33
    enable_pin: gpio.27:low
    direction_pin: NO_PIN
    disable_with_s0: false
    s0_with_disable: true
    spinup_ms: 0
    spindown_ms: 0
    tool_num: 100
    speed_map: 0=0.000% 255=100.000%
    min_pulse_us: 500
    max_pulse_us: 2500
```

Doing it exactly like that results in 
```
[MSG:INFO: Configuration file:config.yaml]
[MSG:ERR: Configuration parse error: Expected identifier. Line 52 column 4]
```

Am I doing it wrong or is that not possible?

If it's not possible but considered merge-worthy, I'd be happy to take it as a junior job :slightly_smiling_face:
I would try to enhance the logic that it accepts both an object as well as an array.
Any thoughts?
