### ISSUE TITLE
FluidNC on CNC xPRO v5

### ISSUE THREAD

**Issue by lagnat** [bdring/FluidNC#363]
Edit: Added config file

Steps taken:
1.  Loaded the latest release
2. Used the auto convert feature to generate yaml from the config file in the Spark Concepts GitHub repo.
3. File failed to load.  Had to add spi_index and remove the cs_pin in the other motors to put into daisy-chain mode.
4. File loaded but produced an error about not being able to self-test the motors.
5. Tried to follow FAQ for `Motors don't move`.
    `$stepping/idle_ms=255` gave me errors about trying to re-use pins.
    Didn't see anything called "disable pin" but tried flipping `cs_pin` to `high`.  
    kernel panic

Thanks in advance for any advice.

```
[MSG:INFO: FluidNC v3.4.3]
[MSG:INFO: Compiled with ESP32 SDK:v3.3.5-1-g85c43024c]
[MSG:INFO: Configuration file:v5.yaml]
[MSG:INFO: Machine CNC_xPRO_V5_Machine_Template]
[MSG:INFO: Board unknown]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:gpio.12 Dir:gpio.14 CS:gpio.17 Disable:NO_PIN Index:1 R:0.050]
[MSG:INFO:     All Limit gpio.35:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:gpio.27 Dir:gpio.26 CS:NO_PIN Disable:NO_PIN Index:2 R:0.050]
[MSG:INFO:     All Limit gpio.34:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     tmc_5160 Step:gpio.33 Dir:gpio.32 CS:NO_PIN Disable:NO_PIN Index:3 R:0.050]
[MSG:INFO: Axis Z (-300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:gpio.15 Dir:gpio.2 CS:NO_PIN Disable:NO_PIN Index:4 R:0.050]
[MSG:INFO:     All Limit gpio.39:low]
[MSG:INFO:   Motor1]
[MSG:INFO: X Axis driver test passed]
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400e1e25  PS      : 0x00060d30  A0      : 0x800e2050  A1      : 0x3ffb1e40  
A2      : 0x3ffb9984  A3      : 0x00000000  A4      : 0x3ffce71c  A5      : 0x00000000  
A6      : 0x00000707  A7      : 0x80000000  A8      : 0x800e1e19  A9      : 0x3ffb1e20  
A10     : 0x3ffb3848  A11     : 0x00000000  A12     : 0x3ffb97f0  A13     : 0x00000707  
A14     : 0x7ff00000  A15     : 0x7ffc1fff  SAR     : 0x0000000f  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000010  LBEG    : 0x40002390  LEND    : 0x4000239f  LCOUNT  : 0x00000000  

ELF file SHA256: 0000000000000000

Backtrace: 0x400e1e25:0x3ffb1e40 0x400e204d:0x3ffb1e90 0x400e1a5c:0x3ffb1eb0 0x401b3c2b:0x3ffb1ed0 0x400da90f:0x3ffb1ef0 0x400da33d:0x3ffb1f10 0x400da5ad:0x3ffb1f30 0x400dd9f5:0x3ffb1f60 0x4010cf82:0x3ffb1fb0 0x4008c0ba:0x3ffb1fd0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8

[MSG:INFO: FluidNC v3.4.3]
[MSG:INFO: Compiled with ESP32 SDK:v3.3.5-1-g85c43024c]
[MSG:ERR: Skipping configuration file due to panic]
[MSG:INFO: Using default configuration]
[MSG:INFO: Axes: using defaults]
[MSG:INFO: Machine Default (Test Drive)]
[MSG:INFO: Board None]
[MSG:INFO: SPI not defined]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-1000.000,0.000)]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.4 [FluidNC v3.4.3 (wifi) '$' for help]
```

```yaml
name: CNC_xPRO_V5_Machine_Template
board: unknown

kinematics:
  Cartesian:

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 0
  pulse_us: 4
  disable_delay_us: 0

axes:
  x:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 2500.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    motor0:
      limit_all_pin: gpio.35:low
      hard_limits: false
      tmc_5160:
        direction_pin: gpio.14
        step_pin: gpio.12
        run_amps: 1.800
        hold_amps: 1.250
        microsteps: 8
        stallguard: 16
        stallguard_debug: false
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        r_sense_ohms: 0.050
        spi_index: 1
        cs_pin: gpio.17:high
    motor1:
      null_motor:
  y:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 2500.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    motor0:
      limit_all_pin: gpio.34:low
      hard_limits: false
      tmc_5160:
        direction_pin: gpio.26
        step_pin: gpio.27
        run_amps: 1.800
        hold_amps: 1.250
        microsteps: 8
        stallguard: 16
        stallguard_debug: false
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        r_sense_ohms: 0.050
        spi_index: 2
    motor1:
      tmc_5160:
        direction_pin: gpio.32
        step_pin: gpio.33
        run_amps: 1.800
        hold_amps: 1.250
        microsteps: 8
        stallguard: 16
        stallguard_debug: false
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        r_sense_ohms: 0.050
        spi_index: 3
  z:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 2500.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    motor0:
      limit_all_pin: gpio.39:low
      hard_limits: false
      tmc_5160:
        direction_pin: gpio.2
        step_pin: gpio.15
        run_amps: 1.800
        hold_amps: 1.250
        microsteps: 8
        stallguard: 16
        stallguard_debug: false
        run_mode: Stallguard
        homing_mode: Stallguard
        use_enable: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        r_sense_ohms: 0.050
        spi_index: 4
    motor1:
      null_motor:

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5

control:
  safety_door_pin: gpio.16:low:pu
  macro0_pin: gpio.13:low:pu
  macro1_pin: gpio.0:low:pu

coolant:
  mist_pin: gpio.21
  delay_ms: 1000.000

probe:
  pin: gpio.22:low:pu
  check_mode_start: false

macros:
  startup_line0: 
  startup_line1: 
  macro0: 
  macro1: 
  macro2: 
  macro3: 

start:
  must_home: true
  check_limits: true
  deactivate_parking: false

user_outputs:

PWM:
  tool_num: 0
  speed_map: 0=0.0% 12000=100.0%
  spinup_ms: 0
  spindown_ms: 0
  output_pin: gpio.25
  enable_pin: gpio.4
  disable_with_s0: false
  s0_with_disable: false
  pwm_hz: 5000
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false 
```
