### ISSUE TITLE
Stepper movement stops when running a ? command

### ISSUE THREAD

**Issue by haraldkubota** [bdring/FluidNC#393]
Please answer the following questions.

What version of the firmware are you using? 3.4.3

Is the problem repeatable? Yes

Under what conditions does the bug occur?

I send 4 commands via TCP connection (telnet server) to move the x axis: move to 0, then to 100, then to 0, then to 100. This works flawlessly and smooth.
I then added to send a "?\n" every 200ms to check if the controller is idle, but when I send or receive the result, the motor seems to stop. See https://youtu.be/pRsrsQokiOg
Changing the 200ms to 1s instead, I get corresponding less "jerky moves". They also happen at exactly the same point in time. Very reproducible, so it seems to be that the processing of incoming traffic causes the stepper loop to halt for a short time.
Same I can do manually: Send a long move (G0X0 then G0X400), and during the move send ? to get the current position. You'll get a very short but noticeable stop.

**Comment by haraldkubota** [comment]
Forgot add: Using MKS DLC32 board. Config for the x axis:
```
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 428.0
    max_rate_mm_per_min: 15000.000
    acceleration_mm_per_sec2: 1500.000
    max_travel_mm: 440.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36
      hard_limits: true
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2
```
