### ISSUE TITLE
Problem: Test form-based problem report

### ISSUE THREAD

**Issue by MitchBradley** [bdring/FluidNC#428]
### Controller Board

Gecko Blaster v0.0

### Machine Description

Geometric Robotics Pro 2x2 gantry router with GeckoDrive.  DeWalt 1.75 HP router for spindle.  Nema 23 motors.  No endstops.

### Configuration file

```yaml
name: "Putter Router"
board: "Gecko Blaster v1"

use_line_numbers: true

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 4
  pulse_us: 4
  disable_delay_us: 0

start:
  must_home: false

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

axes:
  x:
    steps_per_mm: 400
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 600
    homing:
      cycle: 2
      positive_direction: true

    motor0:
      limit_pos_pin: gpio.34:low
      stepstick:
        direction_pin: gpio.25
        step_pin: gpio.27

  y:
    steps_per_mm: 400
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 600
    homing:
      cycle: 2
      positive_direction: true

    motor0:
      limit_pos_pin: gpio.35:low
      stepstick:
        direction_pin: gpio.12
        step_pin: gpio.32

  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 110
    homing:
      cycle: 1
      positive_direction: true

    motor0:
      limit_pos_pin: gpio.36:low
      stepstick:
        direction_pin: gpio.14
        step_pin: gpio.17

probe:
  pin: gpio.39
```

### Startup Messages

```shell
$/axes/x/max_travel_mm=600.000
$/axes/x/homing/mpos_mm=0.000
$/axes/x/homing/positive_direction=true
$/axes/y/max_travel_mm=600.000
$/axes/y/homing/mpos_mm=0.000
$/axes/y/homing/positive_direction=true
[GC:G0 G54 G17 G20 G90 G94 M5 M9 T3 F889 S9000]
$ss
[MSG:INFO: FluidNC v3.3.0 (Devt-e5ef0d4-dirty)]
[MSG:INFO: Compiled with ESP32 SDK:v3.3.5-1-g85c43024c]
[MSG:INFO: Configuration file:gr3_2000.flnc]
[MSG:INFO: Machine Putter Router]
[MSG:INFO: Board Gecko Blaster v1]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 dectect:NO_PIN]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:4us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-600.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.27 Dir:gpio.25 Disable:NO_PIN]
[MSG:INFO:     Pos Limit gpio.34:low]
[MSG:INFO: Axis Y (-600.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.32 Dir:gpio.12 Disable:NO_PIN]
[MSG:INFO:     Pos Limit gpio.35:low]
[MSG:INFO: Axis Z (-110.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.17 Dir:gpio.14 Disable:NO_PIN]
[MSG:INFO:     Pos Limit gpio.36:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Probe Pin: gpio.39:low]
[MSG:INFO: Connecting to STA SSID:CampOlinda]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.68.122]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

WebUI

### What happened?

I ran a GCode program and expected it to cut, but the stock remained uncut.

![image](https://user-images.githubusercontent.com/4861133/168491235-22f79e6e-f205-4a88-aa20-eee5f4a71e27.png)

### Other Information

```shell
There was no cutting tool in the spindle.  Should I have put one in?
```
