### ISSUE TITLE
Inconsistent stepping speed

### ISSUE THREAD

**Issue by MrGashler77** [bdring/FluidNC#449]
### Controller Board

Totally custom design using DM542 drivers. Issue is not the step drivers.

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

Basically a 3018 cnc that has been modified to utilize my custom controller. 

### Configuration file

```yaml
name: "ESP32 Dev Controller V4"
board: "ESP32 Dev Controller V4"

stepping:
  engine: RMT
  idle_ms: 240
  dir_delay_us: 5
  pulse_us: 2
  disable_delay_us: 0
  segments: 6

axes:
  shared_stepper_disable_pin: gpio.21
  shared_stepper_reset_pin: NO_PIN
  
  x:
    steps_per_mm: 3203.187
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 1000
    soft_limits: false
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false
      allow_single_axis: true
      feed_mm_per_min: 1000
      seek_mm_per_min: 1000
    
    motor0:
      limit_all_pin: gpio.34:high:pd
      pulloff_mm: 30.00
      standard_stepper:
        direction_pin: gpio.16:low
        step_pin: gpio.4
    motor1:
      null_motor:

  y:
    steps_per_mm: 3201.598
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 1000
    soft_limits: false
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false
      allow_single_axis: true
      feed_mm_per_min: 1000
      seek_mm_per_min: 1000

    motor0:
      limit_all_pin: gpio.39:high:pd
      pulloff_mm: 30.00
      standard_stepper:
        direction_pin: gpio.19:low
        step_pin: gpio.18
    motor1:
      null_motor:

  z:
    steps_per_mm: 3201.951
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 1000
    soft_limits: false
    homing:
      cycle: 1
      mpos_mm: 10
      positive_direction: false
      allow_single_axis: true
      feed_mm_per_min: 1000
      seek_mm_per_min: 1000


    motor0:
      limit_all_pin: gpio.36:high:pd
      pulloff_mm: 5.00
      standard_stepper:
        direction_pin: gpio.5:low
        step_pin: gpio.17
    motor1:
      null_motor:

spi:
  miso_pin: NO_PIN
  mosi_pin: NO_PIN
  sck_pin: NO_PIN

sdcard:
  cs_pin: NO_PIN
  card_detect_pin: NO_PIN

coolant:
  flood_pin: gpio.33
  mist_pin:  NO_PIN

        
probe:
  pin: gpio.32:low:pu

PWM:
  pwm_hz: 5000
  output_pin: gpio.26
  enable_pin: gpio.14
  direction_pin: NO_PIN
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 500
  spindown_ms: 1000
  tool_num: 0
  speed_map: 0=0% 10000=100%
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.4.5]
[MSG:INFO: Compiled with ESP32 SDK:v4.4-beta1-189-ga79dc75f0a]
[MSG:INFO: Local filesystem type is SPIFFS]
[MSG:INFO: Configuration file:custom.yaml]
[MSG:WARN: gpio.34 does not support :pd attribute]
[MSG:WARN: gpio.39 does not support :pd attribute]
[MSG:WARN: gpio.36 does not support :pd attribute]
[MSG:INFO: Machine ESP32 Dev Controller V4]
[MSG:INFO: Board ESP32 Dev Controller V4]
[MSG:INFO: SPI not defined]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:5us Idle Delay:240ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.21]
[MSG:INFO: Axis X (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.4 Dir:gpio.16:low Disable:NO_PIN]
[MSG:INFO:     All Limit gpio.34]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.18 Dir:gpio.19:low Disable:NO_PIN]
[MSG:INFO:     All Limit gpio.39]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.17 Dir:gpio.5:low Disable:NO_PIN]
[MSG:INFO:     All Limit gpio.36]
[MSG:INFO:   Motor1]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: PWM Spindle Ena:gpio.14 Out:gpio.26 Dir:NO_PIN Freq:5000Hz Res:13bits]
[MSG:INFO: Using spindle PWM]
[MSG:INFO: Flood coolant gpio.33]
[MSG:INFO: Probe Pin: gpio.32:low:pu]
[MSG:INFO: Connecting to STA SSID:SLABY]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.0.7]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.4 [FluidNC v3.4.5 (wifi) '$' for help]
```

### User Interface Software

FluidTerm, UGS

### What happened?

When I tell the machine to jog a given axis using something like $J=G91 X20 F1000, sometimes the machine will run at the speed I expect and move the distance I tell it to but other times it moves very very slowly and only moves a very small amount. I've adjusted all kinds of settings in my config file and I can't seem to get consistent behavior out of the thing.
