### ISSUE TITLE
Problem:  in v3.4.6 and v3.4.5 axes X, Y do not work 

### ISSUE THREAD

**Issue by vadim7272** [bdring/FluidNC#462]
### Controller Board

in v3.4.6 and v3.4.5 axes X, Y do not work and axes Z, A work
in v3.4.1..2..3 all axes work
I have coreXY , tried it in different ways and rolled back
please correct and how can I help you?

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [ ] Not Applicable

### Machine Description

coreXY , esp32 , 4axis xyza , tangential knife 
![tang](https://user-images.githubusercontent.com/106640789/171321484-eff81a3d-eb64-43d6-a281-6f0ef84084c6.jpg)

### Configuration file

```yaml
name: "ESP32 V4 corexy"
board: "ESP32"
meta: "N_ver 3.4.1"

stepping:
  engine: RMT
  idle_ms: 254
  dir_delay_us: 2
  pulse_us: 1
  disable_delay_us: 0

kinematics:
  corexy:
  

axes:
  shared_stepper_disable_pin: gpio.25:low

  x:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 300.000
    homing:
      cycle: 2
      mpos_mm: -3.000
      feed_mm_per_min: 200.000
      settle_ms: 200
      positive_direction: false
    
    motor0:
      limit_all_pin: gpio.36:low
      hard_limits: true
      pulloff_mm: 3.000
      stepstick:
        direction_pin: gpio.14
        step_pin: gpio.15

  y:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 6000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 300.000
    homing:
      cycle: 2
      mpos_mm: -3.000
      feed_mm_per_min: 50.000
      settle_ms: 200
      positive_direction: false
    
    motor0:
      limit_all_pin: gpio.35:low
      hard_limits: true
      pulloff_mm: 3.000
      stepstick:
        direction_pin: gpio.27
        step_pin: gpio.13

  z:
    steps_per_mm: 426.000
    max_rate_mm_per_min: 500.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 50.000
    homing:
      cycle: 1
      mpos_mm: 3.000
      feed_mm_per_min: 100.000
      positive_direction: false
    
    motor0:
      limit_pos_pin: gpio.34:low
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        direction_pin: gpio.26
        step_pin: gpio.12

  a:
    steps_per_mm: 4.444
    max_rate_mm_per_min: 30000.000
    acceleration_mm_per_sec2: 10000.000
    homing:
      cycle: 0
      positive_direction: false
      
    motor0:
      stepstick:
        direction_pin: gpio.32
        step_pin: gpio.33

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: gpio.4

start:
  must_home: false
  deactivate_parking: true
  check_limits: false

Laser:
  pwm_hz: 5000
  output_pin: gpio.2
  enable_pin: gpio.17
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 100
  speed_map: 0=0.000% 255=100.000%
```

### Startup Messages

```text
normal all ok
```

### User Interface Software

webui

### What happened?

in v3.4.1 everything worked, the configuration file did not change, then I installed v3.4.6 the xX, Y axes do not work, the log passes normally, the Z, A axes work
then returned to v3.4.1 everything works again
put v3.4.1,2,3 everything works
set v3.4.5,6 does not work XY
