### ISSUE TITLE
Problem: Axis homing speed and steps are wrong and after homing axis no longer jogs correctly

### ISSUE THREAD

**Issue by symekutz** [bdring/FluidNC#503]
### Controller Board

6-pack 
socket / board
  1 / 4x Switch Input module
  2 / 4x Switch Input module
  3 / Relay module
  4 / 5v output module
  5 / Quad MOSFET CNC I/O module

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [ ] Not Applicable

### Machine Description

Fixed gantry router, single Nema 23 driving leadscrew per axis, x/y have limit switches at both ends, z has positive limit switch only, spindle is a trend router controlled via Solid State Relay SSR-60DA which is hooked up to the relay module. I have 4 TMC5160's installed but only 3 configured.

### Configuration file

```yaml
board: 6 P ack
name: 6 Pack External XYZA Relay
meta: 2022-06-07 B. Dring for Syme Kutz 331662
stepping:
  engine: I2S_stream
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
  segments: 12

axes:
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN
  x:
    steps_per_mm: 615.000
    max_rate_mm_per_min: 1500.000
    acceleration_mm_per_sec2: 20.000
    max_travel_mm: 500.000
    soft_limits: false
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33:low
      limit_pos_pin: gpio.32:low
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 15.000
      tmc_5160:
        step_pin: I2SO.2
        direction_pin: I2SO.1:low
        disable_pin: I2SO.0
        r_sense_ohms: 0.075
        run_amps: 2.500
        hold_amps: 1.000
        microsteps: 16
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        cs_pin: I2SO.3
        spi_index: -1
        run_mode: StealthChop
        homing_mode: StealthChop
        stallguard: 0
        stallguard_debug: false
        toff_coolstep: 3
        tpfd: 4
  y:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 1500.000
    acceleration_mm_per_sec2: 20.000
    max_travel_mm: 500.000
    soft_limits: false
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: gpio.35:low
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 15.000
      tmc_5160:
        step_pin: I2SO.5
        direction_pin: I2SO.4:high
        disable_pin: I2SO.7
        r_sense_ohms: 0.075
        run_amps: 2.500
        hold_amps: 1.000
        microsteps: 16
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        cs_pin: I2SO.6
        spi_index: -1
        run_mode: StealthChop
        homing_mode: StealthChop
        stallguard: 0
        stallguard_debug: false
        toff_coolstep: 3
        tpfd: 4
  z:
    steps_per_mm: 615.000
    max_rate_mm_per_min: 500.000
    acceleration_mm_per_sec2: 10.000
    max_travel_mm: 300.000
    soft_limits: false+-
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 150.000
      seek_mm_per_min: 300.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 15.000
      tmc_5160:
        step_pin: I2SO.10
        direction_pin: I2SO.9:low
        disable_pin: I2SO.8
        r_sense_ohms: 0.075
        run_amps: 2.500
        hold_amps: 1.000
        microsteps: 16
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: false
        cs_pin: I2SO.11
        spi_index: -1
        run_mode: StealthChop
        homing_mode: StealthChop
        stallguard: 0
        stallguard_debug: false
        toff_coolstep: 3
        tpfd: 4
  
kinematics:
  Cartesian:

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

probe:
  pin: gpio.2
  check_mode_start: true

macros:
  startup_line0: 
  startup_line1: 
  macro0: 
  macro1: 
  macro2: 
  macro3: 

start:
  must_home: true
  deactivate_parking: false
  check_limits: false

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: true
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16

Relay:
  direction_pin: NO_PIN
  output_pin: gpio.26
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 100
  speed_map: 0=0.000% 0=100.000% 1=100.000%
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.4.7]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is SPIFFS]
[MSG:INFO: Configuration file:6P_5160_XYZA_Relay.yaml]
[MSG:INFO: Machine 6 Pack External XYZA Relay]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,500.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:I2SO.2 Dir:I2SO.1:low CS:I2SO.3 Disable:I2SO.0 Index:-1 R:0.075]
[MSG:INFO:     Neg Limit gpio.33:low]
[MSG:INFO:     Pos Limit gpio.32:low]
[MSG:INFO: Axis Y (0.000,500.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:I2SO.5 Dir:I2SO.4 CS:I2SO.6 Disable:I2SO.7 Index:-1 R:0.075]
[MSG:INFO:     Neg Limit gpio.34:low]
[MSG:INFO:     Pos Limit gpio.35:low]
[MSG:INFO: Axis Z (-150.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:I2SO.10 Dir:I2SO.9:low CS:I2SO.11 Disable:I2SO.8 Index:-1 R:0.075]
[MSG:INFO:     Neg Limit gpio.36:low]
[MSG:INFO: X Axis driver test passed]
[MSG:INFO: Y Axis driver test passed]
[MSG:INFO: Z Axis driver test passed]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Relay Spindle Ena:NO_PIN Out:gpio.26 Dir:NO_PIN]
[MSG:INFO: Using spindle Relay]
[MSG:INFO: Probe Pin: gpio.2]
[MSG:INFO: Connecting to STA SSID:Kutz-WiFi]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.1.186]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

WebUI, Arduino Serial Terminal

### What happened?

Unlock machine (using button on dashboard or by typing $X in either program) test jogging X Axes (via dashboard controls, or tablet controls) I make sure the x axis is jogging correctly and at normal speed, then I Hit the Home x button in the WebUI dashboard screen / controls section. The machine will begin to home but moves at a very slow speed and the distance is not correct. The gantrty is in the middle it will say it moved 500 mm and did not find a switch but it only moved maybe 50mm, if I continue this cycle eventually it will reach the switch back off and perform the correct homing procedure and correctly set x. However when I try and jog now it will jog at the same reduced rate that it homed at. 

### Other Information

The only anomaly I see in the logs is that some times when it starts up I get a driver error. Restarting it with $bye and within a couple restarts all will pass.

[MSG:INFO: FluidNC v3.4.7]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is SPIFFS]
[MSG:INFO: Configuration file:6P_5160_XYZA_Relay.yaml]
[MSG:INFO: Machine 6 Pack External XYZA Relay]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,500.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:I2SO.2 Dir:I2SO.1:low CS:I2SO.3 Disable:I2SO.0 Index:-1 R:0.075]
[MSG:INFO:     Neg Limit gpio.33:low]
[MSG:INFO:     Pos Limit gpio.32:low]
[MSG:INFO: Axis Y (0.000,500.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:I2SO.5 Dir:I2SO.4 CS:I2SO.6 Disable:I2SO.7 Index:-1 R:0.075]
[MSG:INFO:     Neg Limit gpio.34:low]
[MSG:INFO:     Pos Limit gpio.35:low]
[MSG:INFO: Axis Z (-150.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:I2SO.10 Dir:I2SO.9:low CS:I2SO.11 Disable:I2SO.8 Index:-1 R:0.075]
[MSG:INFO:     Neg Limit gpio.36:low]
[MSG:INFO: X Axis driver test passed]
**[MSG:ERR: Y Axis driver test failed. Check motor power]**
[MSG:INFO: Z Axis driver test passed]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Relay Spindle Ena:NO_PIN Out:gpio.26 Dir:NO_PIN]
[MSG:INFO: Using spindle Relay]
[MSG:INFO: Probe Pin: gpio.2]
[MSG:INFO: Connecting to STA SSID:Kutz-WiFi]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.1.186]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
