### ISSUE TITLE
Installing FluidNC   Problem: 

### ISSUE THREAD

**Issue by Ronsayer** [bdring/FluidNC#515]
### Controller Board

6-pack With XYYZ Relay Setup ( don't use the relay ) works Ok with ' Grbl_Esp32 , 

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

Gantry router withXYYZ format
![WIN_20220703_17_58_22_Pro](https://user-images.githubusercontent.com/41843396/177049746-1f0ff9a6-b23c-44ae-b3cf-52b9cd91f965.jpg)
 

### Configuration file

```yaml
oard: 6-pack
name: MPCNC External Steppers Relay
meta: 
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN
  x:
    steps_per_mm: 800.000
    max_rate_mm_per_min: 12000.000
    acceleration_mm_per_sec2: 450.000
    max_travel_mm: 370.000
    soft_limits: true
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 700.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

    motor1:
      limit_neg_pin: gpio.32:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7

  y:
    steps_per_mm: 800.000
    max_rate_mm_per_min: 12000.000
    acceleration_mm_per_sec2: 450.000
    max_travel_mm: 370.000
    soft_limits: true
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 700.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9:low
        disable_pin: I2SO.8

    motor1:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.18
        direction_pin: I2SO.17:low
        disable_pin: I2SO.16

  z:
    steps_per_mm: 800.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 126.000
    soft_limits: false
     homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 700.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.32
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: I2SO.22
        step_pin: I2SO.21
        direction_pin: I2SO.20:low
        disable_pin: I2SO.23

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      null_motor:

kinematics:
  Cartesian:

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

control:
  safety_door_pin: gpio.2:low   
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 1000

probe:
  pin: gpio.25:pu
  check_mode_start: false

macros:
  startup_line0: 
  startup_line1: 
  macro0: 
  macro1: 
  macro2: 
  macro3: 

start:
  must_home: true
  deactivate_parking: false
  check_limits: true
```

### Startup Messages

```text
I have pasted my config file in plain text but have tried it in yaml
```

### User Interface Software

WebUI,  with Grbl_esp32 works with WebUI, and Cnc3d commander

### What happened?

I am tring to load FluidNC because I get Jumping with Grbl_esp on x and other axis I had it on z but it only happen occasionally  @Mitch Bradly said they had found issues with Girbl but did not have the time to look in to it as they were committed to  FluidNc

### Other Information

![Screenshot_5](https://user-images.githubusercontent.com/41843396/177050203-9005952d-69c7-48fd-a809-bdbea0e73ccb.png)
![Screenshot_6](https://user-images.githubusercontent.com/41843396/177050204-0e927b88-db76-445a-a8d0-3181934989ca.png)
![Screenshot_7](https://user-images.githubusercontent.com/41843396/177050205-25c16624-380d-4c5e-a624-8d899fa1fc06.png)
![Screenshot_8](https://user-images.githubusercontent.com/41843396/177050206-64eb3ac0-9611-44a3-82a3-3685e72090fb.png)
![Screenshot_9](https://user-images.githubusercontent.com/41843396/177050207-4a412211-301d-4963-99d6-e3ef40953ad2.png)
![Screenshot_10](https://user-images.githubusercontent.com/41843396/177050208-f260509a-8332-408b-9cd9-b48ee2da37b2.png)
![Screenshot_11](https://user-images.githubusercontent.com/41843396/177050209-6eda118c-5785-4148-b2d5-d6c2ab13a863.png)
