### ISSUE TITLE
Servo not moving

### ISSUE THREAD

**Issue by deranku** [bdring/FluidNC#516]
### Controller Board

FluidNC Pen Laser Controller (SPI)

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

It will be a string art machine with external stepper driver on x, solenoid on y and servo on z.

### Configuration file

```yaml
name: "Stringer"
board: "FluidNC Pen/Laser"

start:
  must_home: false
  deactivate_parking: true


stepping:
  engine: RMT
  # 255: dauerhaft an
  idle_ms: 255
  # dir_delay_us: 5 us
  dir_delay_us: 10
  # pulse_us: not less than 2.5 us
  pulse_us: 3
  # Some motors need a delay from when they are enabled to when they can take the first step.: at least 5 us
  disable_delay_us: 10

axes:
  shared_stepper_disable_pin: gpio.13
  
  # Teller/Stepper
  x: 
    # actually steps per nail
    steps_per_mm: 300
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      limit_neg_pin: gpio.39:high
      hard_limits: false
      pulloff_mm: 1.0
      standard_stepper:
        step_pin: gpio.14
        direction_pin: gpio.12


  # Fädler/Solenoid
  y:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 5.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 5.000
        
    motor0:
      solenoid:
        output_pin: gpio.27:high
        pwm_hz: 1000
        off_percent: 0.000
        pull_percent: 100.000
        hold_percent: 100.000
        pull_ms: 100


  # Bohrer/Servo
  z:
    steps_per_mm: 100
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 40
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0
    
    motor0:
      rc_servo:
        pwm_hz: 50
        # output_pin: gpio.22
        output_pin: gpio.21
        min_pulse_us: 540
        max_pulse_us: 2470


spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  # M7
  mist_pin:  NO_PIN
  # M8
  flood_pin: NO_PIN
  # M9 turns both off

probe:
  pin: NO_PIN

# macros:
#   startup_line0:
#   startup_line1:
#   macro0: G90&G53G0Z-1&G0X0Y0
#   macro1: $SD/Run=drill.nc
#   macro2:
#   macro3:
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.5.0-pre4]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is SPIFFS]
[MSG:INFO: Configuration file:stringer_config.yaml]
[MSG:INFO: Machine Stringer]
[MSG:INFO: Board FluidNC Pen/Laser]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:RMT Pulse:3us Dsbl Delay:10us Dir Delay:10us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13]
[MSG:INFO: Axis X (150.000,1150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.14 Dir:gpio.12 Disable:NO_PIN]
[MSG:INFO:     Neg Limit gpio.39]
[MSG:INFO: Axis Y (0.000,5.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     solenoid Pin: gpio.21 Off: 0.000 Hold: 100.000 Pull:100.000 Duration:100 pwm hz:1000]
[MSG:INFO: Axis Z (-5.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     rc_servo Pin:gpio.27 Pulse Len(900,2100)]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:Hakaniemi]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.178.63]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://stringer.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.5 [FluidNC v3.5.0-pre4 (wifi) '$' for help]
```

### User Interface Software

WebUI

### What happened?

The z-axis with a servo attached to the servo output pins is not moving at all. The other axis work as expected.

I tried three different ones. The first went up in smoke during an OTA-update of FNC. A little panic came up and I can't rule out that I connected it wrong.

Then I tried two different 5 V hobby servos, which both work fine with the Arduino "Sweep" example. The Arduino Servo lib provides a 50 Hz signal, so I took on to that for the FNC config. The min and max pulse come from one servos datasheet, but I played around with different values (and the default). One of the servos moves a bit when the ESP is powered on and the other one is just dead. Both can not be moved by the Web interface.

The 5 V provided by the board can be measured, but just to rule out that either power or GPIO 22 broke during the death of servo #1, I attached the servos to external power and GPIO 21, with the same result.

### Other Information

![IMG_5748](https://user-images.githubusercontent.com/3035234/177206780-dab57d36-34e6-472b-b4b8-252e5856ce41.jpg)
Standard 5 V hobby servos. The confg above is work in progress. The axis/motors section should work, though.
