### ISSUE TITLE
problemi di scansione utilizzando mks dlc32 e lightburn

### ISSUE THREAD

**Issue by distebia** [bdring/FluidNC#537]
### Controller Board

mks dlc32 v.2.1

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

Laser co2 50w su telaio autocostruito con piano di 1300x900.

### Configuration file

```yaml
board: MKS DLC32 2.1
name: MKS DLC32 XYZ
meta: (08/07/2022) Biagio

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16

stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 10
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: i2so.0
  x:
    steps_per_mm: 79.973
    max_rate_mm_per_min: 20000.000
    acceleration_mm_per_sec2: 3000.000
    max_travel_mm: 1226.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      stepstick:
        step_pin:  i2so.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 80.194
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 350.000
    max_travel_mm: 898.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6

  z:
    steps_per_mm: 640.000
    max_rate_mm_per_min: 200.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 170.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 200.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4:low

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.15

probe:
  pin: gpio.2
  check_mode_start: false

start:
  must_home: false

Laser:
  pwm_hz: 5000
  output_pin: gpio.32
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  speed_map: 0=0.000% 0=9.000% 1000=100.000%
```

### Startup Messages

```text
nessun errore
```

### User Interface Software

lightburn

### What happened?

Salve, ho la configurazione come sopra e ho notato problemi di scansione di testo riempito con lightburn. in pratica il mio testo, anche impostando una sovrascansione del 5% viene come sdoppiato. sono riuscito ad accendere il laser al 1% grazie a speed_map, anche variandolo non ottengo cambiamenti. ho trovato in rete di impostare I2S_static al posto di I2S_stream. ottengo benefici senza perdere niente?

**Comment by Skorpi08** [comment]
Du kannst auch einfach meine yaml Datei nehmen, die funktioniert in einem K40 Laser mit Lightburn.

**Comment by distebia** [comment]
ho anche problemi con i finecorsa...se carico il firmware originale tutto funziona perfettamente, ripetibile e preciso. se carico fluidnc l'homing certe volte parte verso la direzione sbagliata, riavvio e funziona. altre volte è come se non legge i finecorsa e va a sbattere, altre volte mi richiede una distanza di pull-up maggiore e, anche aumentandola, mi segnala l'errore. riavvio e tutto torna alla normalità ma non mi sento sicuro in quanto i problemi si ripresentano ad ogni accensione. se rimetto il firmware originale tutto funziona a meraviglia, tranne il fatto che sono costretto ad accendere il laser al 10%

**Comment by MitchBradley** [comment]
Use IS2_STATIC mode with lasers.  IS2_STREAM mode has extra latency that prevents the laser power from synchronizing properly with the motion.  Use FluidNC version 3.4.4 instead of later versions.  In later versions, we switched over to the new core code from Espressif and we are still debugging problems with that code.

**Comment by distebia** [comment]
Grazie per la dritta. Attualmente uso la 3.4.9. ho un dubbio però. Ho scaricato la 3.4.9 e ho messo i dentro il repository di makerbase/fluidnc, decomprimendo il file zip nella robot di fluidnc. Poi ho lanciato installa wifi. Forse sbaglio questo passaggio?

**Comment by MitchBradley** [comment]
Do not use 3.4.9.

I do not now what you mean by "il repository di makerbase/fluidnc".  I did not know that makerbase had such a repository.

**Comment by Skorpi08** [comment]
https://github.com/makerbase-mks/FluidNC

**Comment by distebia** [comment]
https://github.com/makerbase-mks?tab=repositories&q=Fluid&type=&language=&sort=

**Comment by distebia** [comment]
Ma ho installato correttamente il repository di makerbase dentro la root di fluidnc?

**Comment by MitchBradley** [comment]
Ignore the makerbase repository. The only thing of value in the Makerbase repo is just the example file MKS_DLC32_BASE.yaml, and that file will have to be edited for different machine setups, as you have already done. You should install FluidNC from a [release installer](https://github.com/bdring/FluidNC/releases).

After you have installed FluidNC, you can upload your YAML config file either from WebUI or with FluidTerm via the CTRL-U upload command.

**Comment by distebia** [comment]
Quindi non devo caricare il loro repository? Pensavo potesse essere di aiuto a definire i Pin ecc.... Domani provo con la 3.4.4 e vediamo che succede. Un'altra cosa, devo cancellare prima tutto con installfs? Ho ricaricato il firmware makerbase

**Comment by MitchBradley** [comment]
The Makerbase FluidNC repository is useless.  They did not make any changes to FluidNC.  They just took a snapshot of a very old version of FluidNC and added an example configuration file.  The current bdring/FluidNC repo has two DLC32 examples, and there are many more DLC32 configurations that have been auto-generated by the automatic translation program.

You do not need to fork the entire source code just to define pins.

You should do an installfs when migrating from Makerbase/Grbl_ESP32 to FluidNC.  There is nothing magic about installfs; it just deletes everything in the SPIFFS filesystem and replaces index.html.gz with an up to date version. You could do that manually by using WebUI or FluidTerm to delete individual files and upload new ones.  The only important files are index.html.gz, which is necessary for the full WebUI, and your own custom config.yaml that describes your machine.

If there is no index.html.gz, you can still use the browser to upload files, because FluidNC includes a built-in very simple WebUI subset that only has file management features.

**Comment by distebia** [comment]
sembra che tutto funzioni a meraviglia, grazie per l'aiuto. non so quali sono i pin sulla mks per fare un sistema autoquadrante (2 motori e 2 finecorsa per l'asse y) ma, eventualmente, come dovrei configurare il file yaml?

**Comment by MitchBradley** [comment]
Can somebody else help with this?  I have already spent more time on it than I can spare.  I think he wants to make an auto-squaring XYY system (DLC32 has only 3 stepper sockets).

**Comment by daxliniere** [comment]
Hi @distebia,

> sembra che tutto funzioni a meraviglia, grazie per l'aiuto. non so quali sono i pin sulla mks per fare un sistema autoquadrante (2 motori e 2 finecorsa per l'asse y) ma, eventualmente, come dovrei configurare il file yaml?

Okay, sounds like this thread covers multiple issues. Assuming it's just the auto-squaring Y-axis you're trying to get working now, your config.yaml file should look something like this. I have highlighted the important lines:

```
  x:
    steps_per_mm: 157.750
    max_rate_mm_per_min: 18000.000
    acceleration_mm_per_sec2: 1500.000
    max_travel_mm: 325.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 157.750
    max_rate_mm_per_min: 12000.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 220.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    **motor0:**
      limit_neg_pin: gpio.35
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        **step_pin: I2SO.5
        direction_pin: I2SO.6**
        
    **motor1:**
      limit_neg_pin: gpio.34
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        **step_pin: I2SO.3
        direction_pin: I2SO.4**
```
