### ISSUE TITLE
TMC2209: Microsteps config not working

### ISSUE THREAD

**Issue by Michaelcombs** [bdring/FluidNC#573]
### Controller Board

ESP-32S DEVKIT DOIT

BigTreeTech TMC2209 motor drivers 
[docs](https://github.com/bigtreetech/BIGTREETECH-TMC2209-V1.2)

Custom made control board
![image](https://user-images.githubusercontent.com/7946660/185243710-632e26fb-71b0-4ca4-85f0-c71b9bcceec9.png)

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

Coil winder with 1 axis for bobbin rotation and another axis for wire guide which drives T8 screw. I've isolated the problem to a single axis in the config below.

### Configuration file

```yaml
name: "ESP32 Dev Controller V4"
board: "ESP32 Dev Controller V4"

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  
  x:
    steps_per_mm: 200
    max_rate_mm_per_min: 500
    acceleration_mm_per_sec2: 25
    max_travel_mm: 200
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: true
    motor0:
       tmc_2209:
        uart:
          txd_pin: gpio.10
          rxd_pin: gpio.9
          rts_pin: NO_PIN
          cts_pin: NO_PIN
          baud: 115200
          mode: 8N1
        addr: 0
        r_sense_ohms: 0.110
        run_amps: 0.700
        hold_amps: 0.700
        microsteps: 2
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: gpio.22
        direction_pin: gpio.23
        disable_pin: gpio.21
    motor1:
      null_motor:
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.5.1]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is SPIFFS]
[MSG:INFO: Configuration file:config2.yaml]
[MSG:WARN: microsteps value 0 constrained to range (1,256)]
[MSG:INFO: Machine ESP32 Dev Controller V4]
[MSG:INFO: Board ESP32 Dev Controller V4]
[MSG:INFO: SPI not defined]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-190.000,10.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Trinamic Stepper Uart Tx:gpio.10 Rx:gpio.9 RTS:NO_PIN Baud:115200]
[MSG:INFO:     tmc_2209 Step:gpio.22 Dir:gpio.23 Disable:gpio.21 Addr:3 R:0.110]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:ERR: X Axis driver test failed. Check motor power]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:XXXXXXX]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is XXX.XXX.X.XX]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://Grbl2.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.5 [FluidNC v3.5.1 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
[MSG:INFO: Caution: Unlocked]
```

### User Interface Software

ESP3D

### What happened?

The microstep setting is either not sent to the TMC2209 correctly OR the FluidNC step or microstep calculations or pulses are not correct.  I am using a 200 steps per revolution motor and counting bobbin rotations. 

Upload config and reboot through interface:
steps_per_mm: 200
microsteps: 0
Move X access 1mm with ESP3d interface => 1 rotation ( .13A idle current) This is what I expected.

Upload changed config and reboot through interface:
steps_per_mm: 200
microsteps: 2
Move X access 1mm with ESP3d interface => 1 rotation ( .13A idle current). I expected 1/2 rotation. 
2 microsteps/Step * 200 Steps/rotation * = 400 steps/rotation.  
1mm * 200 steps/mm = 200 steps. 200 steps/400 steps/rotation = 1/2 rotation.

Cycle controller power AND 12V motor supply voltage
steps_per_mm: 200
microsteps: 2
Move X access 1mm with ESP3d interface => 1/8 rotation ( .75A idle current). I expected 1/2 rotation.

I can replicate this problem with various microstep settings. 

I can then take the same controller, upload a small program using an arduino framework and the TMC2209Stepper library and set the microsteps reliably. I can then reload FluidNC onto the controller and the config microsteps has no impact until I power cycle the driver.
