### ISSUE TITLE
Problem: Only 2 of 3 TMC2209-Boards reachable via UART

### ISSUE THREAD

**Issue by botboe** [bdring/FluidNC#574]
### Controller Board

[MKS TinyBee](https://github.com/makerbase-mks/MKS-TinyBee)

### Help From Board Vendor

- [ ] Yes
- [X] No
- [ ] Not Applicable

### Machine Description

CNC3018-Router with switched controller-board, rest unchanged. TMC2209-Drivers with exposed UART-Pin connected via star-shaped cable to USART2.
FluidNC v3.5.1

### Configuration file

```yaml
board: MKS TinyBee V1.0
name: CNC3018-Pro
meta: (08.08.2022) by Tobias

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
  segments: 12

axes:
  x:
    steps_per_mm: 400
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 100.000

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2.000
      tmc_2209:
        uart:
          txd_pin: gpio.17
          rxd_pin: gpio.16
          rts_pin: NO_PIN
          cts_pin: NO_PIN
          baud: 115200
          mode: 8N1
        addr: 0
        step_pin: I2SO.1
        direction_pin: I2SO.2:low
        disable_pin: I2SO.0

  y:
    steps_per_mm: 400
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 100.000

    motor0:
      limit_neg_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2.000
      tmc_2209:
        uart:
          txd_pin: gpio.17
          rxd_pin: gpio.16
          rts_pin: NO_PIN
          cts_pin: NO_PIN
          baud: 115200
          mode: 8N1
        addr: 1
        step_pin: I2SO.4
        direction_pin: I2SO.5
        disable_pin: I2SO.3

  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 100.000

    motor0:
      limit_neg_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2.000
      tmc_2209:
        uart:
          txd_pin: gpio.17
          rxd_pin: gpio.16
          rts_pin: NO_PIN
          cts_pin: NO_PIN
          baud: 115200
          mode: 8N1
        addr: 2
        step_pin: I2SO.7
        direction_pin: I2SO.8:low
        disable_pin: I2SO.6

i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  # EXP1 BTN_ENC
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

#probe:
#  pin: gpio.2
#  check_mode_start: true

relay:
  direction_pin: NO_PIN
  output_pin: I2SO.17:high
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 250
  spindown_ms: 500
  tool_num: 0

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: false
```

### Startup Messages

```text
rst:0xc (SW_CPU_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:12812
load:0x40080400,len:3032
entry 0x400805e4

[MSG:INFO: FluidNC v3.5.1]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is SPIFFS]
[MSG:INFO: Configuration file:config.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine CNC3018-Pro]
[MSG:INFO: Board MKS TinyBee V1.0]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Trinamic Stepper Uart Tx:gpio.17 Rx:gpio.16 RTS:NO_PIN Baud:115200]
[MSG:DBG: TMCStepper Library Ver. 0x703]
[MSG:INFO:     tmc_2209 Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0 Addr:0 R:0.110]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 Step:I2SO.4 Dir:I2SO.5 Disable:I2SO.3 Addr:1 R:0.110]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6 Addr:2 R:0.110]
[MSG:ERR: X Axis driver test failed. Check motor power]
[MSG:ERR: Y Axis driver test failed. Check motor power]
[MSG:ERR: Z Axis driver test failed. Check motor power]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Relay Spindle Ena:NO_PIN Out:I2SO.17 Dir:NO_PIN]
[MSG:INFO: Using spindle Relay]
[MSG:INFO: Connecting to STA SSID:Skynet - Global Defense Network]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 192.168.241.139]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://CNC-3018.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.5 [FluidNC v3.5.1 (wifi) '$' for help]
[MSG:DBG: Cannot open file /spiffs/macrocfg.json]
[MSG:DBG: Cannot open file /spiffs/macrocfg.json.gz]
```

### User Interface Software

WebUI

### What happened?

I exposed the UART-Pins of the TMC2209-Drivers as the controller-board doesn't support UART. I connected the star-shaped to the USART2 of the board, with the corresponding 1k-resistor on the TX-line.
When all drivers are connected, I get the following error:
```
$MI
[MSG:ERR: X Axis driver test failed. Check motor power]
[MSG:ERR: Y Axis driver test failed. Check motor power]
[MSG:ERR: Z Axis driver test failed. Check motor power]
```
But when I disconnect one of the drivers - no matter which one, the still connected drivers are reachable. In the following exampe I removed each drivers cable one after another:
```
$MI
[MSG:ERR: X Axis driver test failed. Check motor power]
[MSG:ERR: Y Axis driver test failed. Check motor power]
[MSG:ERR: Z Axis driver test failed. Check motor power]
ok
$MI
[MSG:ERR: X Axis driver test failed. Check motor power]
[MSG:INFO: Y Axis driver test passed]
[MSG:DBG: Y Axis StealthChop]
[MSG:INFO: Z Axis driver test passed]
[MSG:DBG: Z Axis StealthChop]
ok
$MI
[MSG:INFO: X Axis driver test passed]
[MSG:DBG: X Axis StealthChop]
[MSG:ERR: Y Axis driver test failed. Check motor power]
[MSG:INFO: Z Axis driver test passed]
[MSG:DBG: Z Axis StealthChop]
ok
$MI
[MSG:INFO: X Axis driver test passed]
[MSG:DBG: X Axis StealthChop]
[MSG:INFO: Y Axis driver test passed]
[MSG:DBG: Y Axis StealthChop]
[MSG:ERR: Z Axis driver test failed. Check motor power]
```
I'm running out of ideas... I hope you can help!
