### ISSUE TITLE
Problem: config.yaml / 2 axis not available 

### ISSUE THREAD

**Issue by wollo-fpv** [bdring/FluidNC#588]
### Controller Board

ESPDUINO-32 with external stepper driver

### Help From Board Vendor

- [ ] Yes
- [X] No
- [ ] Not Applicable

### Machine Description

4 axis hotwire with external steppers

### Configuration file

```yaml
board: WeMOS D1 R32 
name: 4_axis_hotwire
meta: 20/08/2022

kinematics:
  Cartesian:
  

stepping:
  pulse_us: 2
  dir_delay_us: 1
  disable_delay_us: 0
  
  
axes:
  x:
    # X
    steps_per_mm: 320
    max_rate_mm_per_min: 18000.000
    acceleration_mm_per_sec2: 1500.000
    max_travel_mm: 1300.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.25
      hard_limits: false
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: gpio.22
        direction_pin: gpio.21
        disable_pin: gpio.18

  y:
    # Y
    steps_per_mm: 320
    max_rate_mm_per_min: 12000.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 1300.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.26
      hard_limits: false
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: gpio.19
        direction_pin: gpio.23
        disable_pin: gpio.5

  z:
    # Z
    steps_per_mm: 320
    max_rate_mm_per_min: 12000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 600.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

     motor0:
      limit_neg_pin: gpio.15
      hard_limits: false
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: gpio.13
        direction_pin: gpio.12
        disable_pin: gpio.14
        
  a:
    # A
    steps_per_mm: 320
    max_rate_mm_per_min: 12000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 600.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

     motor0:
      limit_neg_pin: gpio.33
      hard_limits: false
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: gpio.27
        direction_pin: gpio.16
        disable_pin: gpio.17
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.5.1]                                                                                                                                                       
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]                                                                                                                         
[MSG:INFO: Local filesystem type is SPIFFS]                                                                                                                                      
[MSG:INFO: Configuration file:config.yaml]                                                                                                                                       
[MSG:ERR: Skipping key motor0 indent 5 thisIndent 4]                                                                                                                             
[MSG:ERR: Skipping key limit_neg_pin indent 6 thisIndent 4]                                                                                                                      
[MSG:ERR: Skipping key hard_limits indent 6 thisIndent 4]                                                                                                                        
[MSG:ERR: Skipping key pulloff_mm indent 6 thisIndent 4]                                                                                                                         
[MSG:ERR: Skipping key standard_stepper indent 6 thisIndent 4]                                                                                                                   
[MSG:ERR: Skipping key step_pin indent 8 thisIndent 4]                                                                                                                           
[MSG:ERR: Skipping key direction_pin indent 8 thisIndent 4]                                                                                                                      
[MSG:ERR: Skipping key disable_pin indent 8 thisIndent 4]                                                                                                                        
[MSG:ERR: Skipping key motor0 indent 5 thisIndent 4]                                                                                                                             
[MSG:ERR: Skipping key limit_neg_pin indent 6 thisIndent 4]                                                                                                                      
[MSG:ERR: Skipping key hard_limits indent 6 thisIndent 4]                                                                                                                        
[MSG:ERR: Skipping key pulloff_mm indent 6 thisIndent 4]                                                                                                                         
[MSG:ERR: Skipping key standard_stepper indent 6 thisIndent 4]                                                                                                                   
[MSG:ERR: Skipping key step_pin indent 8 thisIndent 4]                                                                                                                           
[MSG:ERR: Skipping key direction_pin indent 8 thisIndent 4]                                                                                                                      
[MSG:ERR: Skipping key disable_pin indent 8 thisIndent 4]                                                                                                                        
[MSG:INFO: Machine 4_axis_hotwire]                                                                                                                                               
[MSG:INFO: Board WeMOS D1 R32 ]                                                                                                                                                  
[MSG:INFO: SPI not defined]                                                                                                                                                      
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]                                                                                                 
[MSG:INFO: Axis count 4]                                                                                                                                                         
[MSG:INFO: Axis X (0.000,1300.000)]                                                                                                                                              
[MSG:INFO:   Motor0]                                                                                                                                                             
[MSG:INFO:     standard_stepper Step:gpio.22 Dir:gpio.21 Disable:gpio.18]                                                                                                        
[MSG:INFO:     Neg Limit gpio.25]                                                                                                                                                
[MSG:INFO: Axis Y (0.000,1300.000)]                                                                                                                                              
[MSG:INFO:   Motor0]                                                                                                                                                             
[MSG:INFO:     standard_stepper Step:gpio.19 Dir:gpio.23 Disable:gpio.5]                                                                                                         
[MSG:INFO:     Neg Limit gpio.26]                                                                                                                                                
[MSG:INFO: Axis Z (0.000,600.000)]                                                                                                                                               
[MSG:INFO: Axis A (0.000,600.000)]                                                                                                                                               
[MSG:INFO: Kinematic system: Cartesian]                                                                                                                                          
[MSG:INFO: Using spindle NoSpindle]
```

### User Interface Software

bCNC

### What happened?

I don't understand what is wrong with the config.yaml.
I have checked the gpio's pins on the wiki page.
Please help...

Best regards,

Wolf
