### ISSUE TITLE
Problem: Scan offset, diode laser

### ISSUE THREAD

**Issue by xpozec** [bdring/FluidNC#603]
### Controller Board

custom board 
![0-02-05-38d1237c79ea54a36d592164535c46b1fee4cea283a0e6ace16f848c96a21512_60751ca5bd221d9d](https://user-images.githubusercontent.com/113240530/189480421-73ccdf3f-916c-4eb5-87a6-c08763d0c4d0.jpg)

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

Laser engraver, custom made. using A4988 stepper drivers, 7.5W diode laser
120W 12V power supply (meanwell) 
2 machines 
![0-02-05-0b1be2b94acf10e3f659d3d3a798d26d3c20839196d2cf725949c44a50c340bd_1ba36667f135bb32](https://user-images.githubusercontent.com/113240530/189480510-72a5fbc8-7441-45bd-a6ab-3e44c38e1b9a.jpg)
![0-02-05-7b34c6d5f02bd3267940940af512a705693d4c49b162badd1f0c403fac247337_ce3c029384992981](https://user-images.githubusercontent.com/113240530/189480513-61678ce8-1fe4-4585-8969-a9cd63c02a73.jpg)
![0-02-05-a961b846104c50ead516dbc7dbe2fd32a21b29abd2c43a0a69d83c0323986f95_f31ca68c48897119](https://user-images.githubusercontent.com/113240530/189480514-cb954d8f-c704-4277-8471-eacff656ff2f.jpg)

### Configuration file

```yaml
name: "Laser"
board: "Byte 4axis"

stepping:
  engine: RMT 
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.13:high
  
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 4800
    acceleration_mm_per_sec2: 1200
    max_travel_mm: 450
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 400.000
      seek_mm_per_min: 3000.000
      settle_ms: 250
      seek_scaler: 1.0
      feed_scaler: 1.0
    
    motor0:
      limit_neg_pin: gpio.34:low
      pulloff_mm: 3.000
      stepstick:
        direction_pin: gpio.2:low
        step_pin: gpio.0
    motor1:
      null_motor:

  y:
    steps_per_mm: 80
    max_rate_mm_per_min: 4800
    acceleration_mm_per_sec2: 1200
    max_travel_mm: 450
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 400.000
      seek_mm_per_min: 3000.000
      settle_ms: 250
      seek_scaler: 1.0
      feed_scaler: 1.0

    motor0:
      limit_neg_pin: gpio.35:low
      pulloff_mm: 3.000
      stepstick:
        direction_pin: gpio.15:high
        step_pin: gpio.26
    motor1:
      null_motor:

 
  # z:
  #   steps_per_mm: 2000
  #   max_rate_mm_per_min: 500
  #   acceleration_mm_per_sec2: 100
  #   max_travel_mm: 5
  #   homing:
  #     cycle: 0
  #     mpos_mm: 0
  #     positive_direction: false

  #   motor0:
  #     rc_servo:
  #       pwm_hz: 50
  #       output_pin: gpio.27
  #       min_pulse_us: 700
  #       max_pulse_us: 2200
        
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin:  gpio.21

probe:
  pin: gpio.32:low:pu
  
Laser:
  pwm_hz: 5000
  output_pin: gpio.25
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
```

### Startup Messages

```text
no errors, all green
```

### User Interface Software

Lightburn, lasergrbl

### What happened?

Engraving over USB. 
There is some kind of strange  offset happening with 3.4.4
With new version, i am unable to test, as at this moment I am unable to home my machines, it only works like 20% of the time. 
when using Arduino board, or ESP32grbl (discontinued) it does not happen photos of those beautiful lades and Robbin Williams, done on the same machine arduino board and same board with ESP32grbl (discontinued), this rules out hardware issues i think
Engraving with 35mm/s 67% power
If you need any more information in order to be able to help, please ask, I will do my best to provide all.

### Other Information

![0-02-05-d1b65d2a9b2474b5d1e7c98a5ded6380a558e7338645264f46d4430d1f4fb76f_acb65ff8b3dd18fb](https://user-images.githubusercontent.com/113240530/189480563-fe22f3a2-6805-4d90-ace4-9adf1a85761b.jpg)
![0-02-05-f3899a727605d329ffa9b7c1a09d4ebdecd02495d01eed96b3e1d3cb2b1f148f_7b3f41154579e3ca](https://user-images.githubusercontent.com/113240530/189480568-08d3bf0b-1677-4d7c-8092-520f4584cfe4.jpg)
![0-02-05-ac0c16f893eb9e94c6adef493160a538725ae3b3f59f20294f6fffea0c8db663_1a19fc6f2b539999](https://user-images.githubusercontent.com/113240530/189480573-5f143298-4059-49ec-9f2a-5d2921586085.jpg)
![0-02-05-98f8f85ec1d62de3d71b9626dac435ff83156ca8ca863f81a078e276fc46d325_8e5147e8f8f9cc80](https://user-images.githubusercontent.com/113240530/189480577-1763a3fc-c37e-434b-aaad-8e54bf691213.jpg)
