### ISSUE TITLE
 3.6.0 parking does not work on corexy, and the field of several actions is getting an alarm: 

### ISSUE THREAD

**Issue by vadim7272** [bdring/FluidNC#606]
### Controller Board

MKS TinyBee V1.0_001
kinematics:
  corexy:

I have tried different limit switches.
optical, induction
and simple ones with a pull-up of 10 k ohm

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

a4988

### Configuration file

```yaml
board: MKS TinyBee V1.0_001
name: Laser corexy
meta: (01.02.2022) by Skorpi

kinematics:
  corexy:

stepping:
  engine: I2S_STATIC
  idle_ms: 254
  pulse_us: 2
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  x:
    # X
    steps_per_mm: 80.000
    max_rate_mm_per_min: 8000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: -3.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.32:low
      hard_limits: true
      pulloff_mm: 3.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2
        disable_pin: I2SO.0

  y:
    # Y
    steps_per_mm: 80.000
    max_rate_mm_per_min: 8000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: -3.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.33:low
      hard_limits: true
      pulloff_mm: 3.000
      stepstick:
        step_pin: I2SO.4
        direction_pin: I2SO.5
        disable_pin: I2SO.3

  

i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

arc_tolerance_mm: 0.6
junction_deviation_mm: 0.3

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0


control:
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN



macros:
 macro0: G91&G21 F200 X5&G91&G21 F200 y-50
 macro1: m0&G91&G21 F200 X5&G91&G21 F200 y-50

 

   
start:
  must_home: false
  deactivate_parking: true
  check_limits: true
  
Laser:
  pwm_hz: 5000
  output_pin: gpio.13
  enable_pin: I2SO.16
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 100
  speed_map: 0=0.000% 255=100.000%
  
  
#parking:
  #enable: true
  #axis: x
  #target_mpos_mm: -5.000
  #pullout_distance_mm: 5.000
  #rate_mm_per_min: 800.000
  #pullout_rate_mm_per_min: 250.000
```

### Startup Messages

```text
normal
```

### User Interface Software

webui laser grbl ,ploter grbl

### What happened?

v3.4.1-3.4.3 trailers fall into alarm.
the firmware is working fine.
3.4.4-3.5.0 firmware does not work.
3.6.0 limit switches stop the axis and all pull offs do not work at $Home , does not fall in alarm .
after several actions we get alarm again, exit alarm only by rebooting.
The firmware itself does not work very well.

if I put Kinematics Cartesian then the parking works but without pull off.

test firmware
fluidnc-TestPullups-win64.zip and luidnc-TestParking2-win64.zip are the same, parking does not work a little bit and we get an alarm .

sort it out please with limit switches, parking, on Core xy
