### ISSUE TITLE
Problem: 3.6.0 homing fails on CoreXY (FYSETC E4)

### ISSUE THREAD

**Issue by anatolyrc** [bdring/FluidNC#607]
### Controller Board

FYSETC E4

### Help From Board Vendor

- [ ] Yes
- [X] No
- [ ] Not Applicable

### Machine Description

DIY CoreXY diode engraver, Comgrow 10W (optical) head

### Configuration file

```yaml
name: "Fysetc E4 CoreXY"
board: "Fysetc E4"

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

kinematics:
  corexy:

axes:
  shared_stepper_disable_pin: gpio.25:high
  
  x:
    steps_per_mm: 160.000
    max_rate_mm_per_min: 9000.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 400.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.34:high
      hard_limits: false
      pulloff_mm: 1.000
      tmc_2209:
        uart:
          txd_pin: gpio.22
          rxd_pin: gpio.21
          baud: 115200
          mode: 8N1
        addr: 1
        r_sense_ohms: 0.110
        run_amps: 1.200
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: gpio.27
        direction_pin: gpio.26:low
        disable_pin: NO_PIN

  y:
    steps_per_mm: 160.000
    max_rate_mm_per_min: 9000.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 400.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35:high
      hard_limits: false
      pulloff_mm: 1.000
      tmc_2209:
        addr: 3
        r_sense_ohms: 0.110
        run_amps: 1.200
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: gpio.33
        direction_pin: gpio.32:low
        disable_pin: NO_PIN

  z:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 1200.000
    acceleration_mm_per_sec2: 50.000
    soft_limits: false

    motor0:
      tmc_2209:
        addr: 2
        r_sense_ohms: 0.110
        run_amps: 0.800
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: gpio.16
        direction_pin: gpio.17:low
        disable_pin: NO_PIN

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

start:
  must_home: false
  deactivate_parking: false
  check_limits: false

coolant:
  flood_pin: gpio.2:low
  delay_ms: 500

Laser:
  pwm_hz: 5000
  enable_pin: gpio.4
  output_pin: gpio.13:high
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 500=40% 1000=100.000%
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.5.1]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is SPIFFS]
[MSG:INFO: Configuration file:fysetc_e4_corexy_laser.yml]
[MSG:INFO: Machine Fysetc E4 CoreXY]
[MSG:INFO: Board Fysetc E4]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.25]
[MSG:INFO: Axis X (0.000,400.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Trinamic Stepper Uart Tx:gpio.22 Rx:gpio.21 RTS:NO_PIN Baud:115200]
[MSG:INFO:     tmc_2209 Step:gpio.27 Dir:gpio.26:low Disable:NO_PIN Addr:1 R:0.110]
[MSG:INFO:     Neg Limit gpio.34]
[MSG:INFO: Axis Y (0.000,400.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 Step:gpio.33 Dir:gpio.32:low Disable:NO_PIN Addr:3 R:0.110]
[MSG:INFO:     Neg Limit gpio.35]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 Step:gpio.16 Dir:gpio.17:low Disable:NO_PIN Addr:2 R:0.110]
[MSG:INFO: X Axis driver test passed]
[MSG:INFO: Y Axis driver test passed]
[MSG:INFO: Z Axis driver test passed]
[MSG:INFO: Kinematic system: CoreXY]
[MSG:INFO: Laser Ena:gpio.4 Out:gpio.13 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Flood coolant gpio.2:low]
[MSG:INFO: Connecting to STA SSID:wetexit2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 192.168.86.68]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://laser-fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

[MSG:INFO: FluidNC v3.6.0]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is SPIFFS]
[MSG:INFO: Configuration file:fysetc_e4_corexy_laser.yml]
[MSG:INFO: Machine Fysetc E4 CoreXY]
[MSG:INFO: Board Fysetc E4]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.25]
[MSG:INFO: Axis X (0.000,400.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Trinamic Stepper Uart Tx:gpio.22 Rx:gpio.21 RTS:NO_PIN Baud:115200]
[MSG:INFO:     tmc_2209 Step:gpio.27 Dir:gpio.26:low Disable:NO_PIN Addr:1 R:0.110]
[MSG:INFO:     Neg Limit gpio.34]
[MSG:INFO: Axis Y (0.000,400.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 Step:gpio.33 Dir:gpio.32:low Disable:NO_PIN Addr:3 R:0.110]
[MSG:INFO:     Neg Limit gpio.35]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 Step:gpio.16 Dir:gpio.17:low Disable:NO_PIN Addr:2 R:0.110]
[MSG:INFO: Kinematic system: CoreXY]
[MSG:INFO: Laser Ena:gpio.4 Out:gpio.13 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Flood coolant gpio.2:low]
[MSG:INFO: Connecting to STA SSID:wetexit2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 192.168.86.68]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://laser-fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

ESP3D Web UI, LightBurn

### What happened?

Upgraded firmware from 3.5.1 to 3.6.0, no change to config file.

3.5.1: Homing and all cutting/engraving operations work perfectly
3.6.0: Homing fails; either homes Y and fails to home X, or fails to recognize limit switch active and grinds Y while trying to home X. In both cases, I get a homing failed message, "Homing fail. Cycle failed to clear limit switch when pulling off. Try increasing pull-off setting or check wiring.". Also, $limits does not show limits configured for X and Y as it does for 3.51.

3.5.1 $limits shows
```
Homing Axes: xyz         
Limit  Axes: xy
```

3.6.0 $limits shows
```
Homing Axes: xyz         
Limit  Axes:
```

Reverted to 3.5.1 for now.
