### ISSUE TITLE
Problem: The list of preset codes includes G94, but it is not listed in supported codes

### ISSUE THREAD

**Issue by maxcel2** [bdring/FluidNC#620]
### Controller Board

N/A

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

Manual milling machine

### Configuration file

```yaml
name: "WARCO WM16 MILL"
board: "ESP32-WROOM-32"

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 10.0
  pulse_us: 5.0
  disable_delay_us: 10.0

axes:

# Ball screws are 5mm lead
# Set driver to 1000 pulse/rev will give 200 steps/mm
# which gives 0.005mm/step.

  x:
    steps_per_mm: 200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 2.0
    max_travel_mm: 480
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.35:high
      pulloff_mm: 1.000
      Standard_Stepper:
        step_pin: gpio.13:low
        direction_pin: gpio.14:low
        disable_pin: gpio.27:low
  y:
    steps_per_mm: 200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 2.0
    max_travel_mm: 160
    soft_limits: true
    homing:
      cycle: 3
      mpos_mm: 0
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.34:high
      pulloff_mm: 1.000
      Standard_Stepper:
        step_pin: gpio.26:low
        direction_pin: gpio.25:low
        disable_pin: gpio.33:low
  z:
    steps_per_mm: 200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 10
    max_travel_mm: 270
    soft_limits: true
    homing:
      cycle: 1
      mpos_mm: 0
      positive_direction: true

    motor0:
      limit_neg_pin: gpio.39:high
      pulloff_mm: 3.000
      Standard_Stepper:
        step_pin: gpio.32:low
        direction_pin: gpio.15:high
        disable_pin: gpio.4:low
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin:  NO_PIN

probe:
  pin: gpio.36:low

10V:
  pwm_hz: 2500
  output_pin: gpio.22:low
  enable_pin: NO_PIN
  direction_pin: gpio.21
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 1500
  spindown_ms: 100
  tool_num: 0
  speed_map: 0=0% 2750=100%
```

### Startup Messages

```text
G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0
Serial Messages
$/axes/x/max_travel_mm=480.000
$/axes/x/homing/mpos_mm=0.000
$/axes/x/homing/positive_direction=false
$/axes/y/max_travel_mm=160.000
$/axes/y/homing/mpos_mm=0.000
$/axes/y/homing/positive_direction=false
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]
```

### User Interface Software

WebUI

### What happened?

N/a
