### ISSUE TITLE
Y-axis not working after update v3.6.2

### ISSUE THREAD

**Issue by arlimbad222** [bdring/FluidNC#641]
### Controller Board

Custom board

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

4-axis cnc milling machine

### Configuration file

```yaml
name: "4-axis MACHINE"
board: "4-axis MACHINE"

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  
  x:
    steps_per_mm: 100
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 300
    max_travel_mm: 317
    soft_limits: true
    homing:
      cycle: 2
      allow_single_axis: true
      mpos_mm: -2
      positive_direction: true
      feed_mm_per_min: 200
      seek_mm_per_min: 1500
      settle_ms: 250
      seek_scaler: 1
      feed_scaler: 1
    
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.16:low:pu
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        direction_pin: gpio.25
        step_pin: gpio.18
    motor1:
      null_motor:

  y:
    steps_per_mm: 100
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 300
    max_travel_mm: 250
    soft_limits: true
    homing:
      cycle: 2
      allow_single_axis: true
      mpos_mm: -2
      positive_direction: true
      feed_mm_per_min: 200
      seek_mm_per_min: 1500
      settle_ms: 250
      seek_scaler: 1
      feed_scaler: 1

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.17:low:pu
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        direction_pin: gpio.15
        step_pin: gpio.26
    motor1:
      null_motor:

  z:
    steps_per_mm: 100
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 300
    max_travel_mm: 140
    soft_limits: true
    homing:
      cycle: 1
      allow_single_axis: true
      mpos_mm: -2
      positive_direction: true
      feed_mm_per_min: 200
      seek_mm_per_min: 1500
      settle_ms: 250
      seek_scaler: 1
      feed_scaler: 1
      

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.4:low:pu
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        direction_pin: gpio.33
        step_pin: gpio.27
    motor1:
      null_motor:

  a:
    steps_per_mm: 8.889
    max_rate_mm_per_min: 30000
    acceleration_mm_per_sec2: 20000
    max_travel_mm: 0

    motor0:
      limit_all_pin: NO_PIN
      stepstick:
        direction_pin: gpio.13
        step_pin: gpio.12
    motor1:
      null_motor:        

coolant:
  flood_pin: gpio.21
  mist_pin:  gpio.23

        
probe:
  pin: gpio.32:low:pu

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.5:low:pu
  cycle_start_pin: gpio.19:low:pu
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

PWM:
  pwm_hz: 5000
  output_pin: gpio.2
  enable_pin: gpio.22
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0% 18000=100%
```

### Startup Messages

```text
Grbl 3.6 [FluidNC v3.6.2 (bt) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
$SS
[MSG:INFO: FluidNC v3.6.2]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:SHRIKE_V1.YAML]
[MSG:WARN: max_travel_mm value 0.000 constrained to range (0.100,10000000.000)]
[MSG:INFO: Machine 4-axis MACHINE]
[MSG:INFO: Board 4-axis MACHINE]
[MSG:INFO: SPI not defined]
[MSG:INFO: No SD Card CS Pin]
[MSG:INFO: See http://wiki.fluidnc.com/en/config/sd_card#sdfallbackcs-access-sd-without-a-config-file]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 4]
[MSG:INFO: Axis X (-319.000,-2.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.18 Dir:gpio.25 Disable:NO_PIN]
[MSG:INFO:  X All Limit gpio.16:low:pu]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (-252.000,-2.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.26 Dir:gpio.15 Disable:NO_PIN]
[MSG:INFO:  Y All Limit gpio.17:low:pu]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (-142.000,-2.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.27 Dir:gpio.33 Disable:NO_PIN]
[MSG:INFO:  Z All Limit gpio.4:low:pu]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis A (-0.100,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.12 Dir:gpio.13 Disable:NO_PIN]
[MSG:INFO:   Motor1]
[MSG:INFO: feed_hold_pin gpio.5:low:pu]
[MSG:INFO: cycle_start_pin gpio.19:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: PWM Spindle Ena:gpio.22 Out:gpio.2 Dir:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle PWM]
[MSG:INFO: Flood coolant gpio.21]
[MSG:INFO: Mist coolant gpio.23]
[MSG:INFO: Probe Pin: gpio.32:low:pu]
[MSG:INFO: BT Started with FluidNC]
ok
```

### User Interface Software

UGS

### What happened?

I just updated the #fluidnc version from 3.6.1 to 3.6.2 because I face some resume problems and suddenly the y-axis stop moving I just erase esp and went back to 3.6.1, it's not about hardware because everything running well with V3.6.1, I am hardware guy I can't write code that's why I am here.

thank you for such a nice firmware.
