### ISSUE TITLE
Problem: 

### ISSUE THREAD

**Issue by doowneergtam** [bdring/FluidNC#658]
### Controller Board

6 Pack Universal CNC Controller (Bart's V1p5)

Using 
- (2x) 4x Input CNC I/O Modules (Socket 1 and 2) Limits and Probe
- 5V Output Module (Socket 4) Laser Enable and PWM
- Relay CNC I/O Module (Socket 5) Air Assist Pump

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [ ] Not Applicable

### Machine Description

600mm X 1200mm Custom Built 130W Co2 Laser

### Configuration file

```yaml
board: 6 Pack
name: 6 Pack External XYZA Laser
meta:
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 3
  dir_delay_us: 3
  disable_delay_us: 0
  segments: 16

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 160.423
    max_rate_mm_per_min: 18000.000
    acceleration_mm_per_sec2: 800.000
    max_travel_mm: 1260.000
    hard_limits: true
    soft_limits: true
    homing:
      cycle: 3
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 4000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      pulloff_mm: 6.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

  y:
    steps_per_mm: 99.945
    max_rate_mm_per_min: 30000.000
    acceleration_mm_per_sec2: 8000.000
    max_travel_mm: 604.000
    hard_limits: true
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 4000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.32:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      pulloff_mm: 6.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4
        disable_pin: I2SO.7

  z:
    steps_per_mm: 106.750
    max_rate_mm_per_min: 500.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 140.000
    soft_limits: true
    hard_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
        
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.35:low
      limit_all_pin: NO_PIN
      pulloff_mm: 4.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8
        
  a:
    steps_per_mm: 35.545
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 2000.000
    max_travel_mm: 1000.000
    soft_limits: false
    hard_limits: false
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
        
   motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15

probe:
  pin:  gpio.34
  check_mode_start: true
  
        
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: gpio.2
  reset_pin: gpio.25
  feed_hold_pin: gpio.39
  cycle_start_pin: gpio.36
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

start:
  must_home: true
  
coolant:
  flood_pin: I2SO.24
  mist_pin:  gpio.12
  delay_ms: 0

Laser:
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  pwm_hz: 20000
  output_pin: gpio.14
  enable_pin: gpio.13
  disable_with_s0: false
  s0_with_disable: true
  speed_map: 0=0.000% 1000=100.000%

planner_blocks: 16
```

### Startup Messages

```text
Waiting for connection...
[VER:3.6 FluidNC v3.6.2:]
[OPT:MPHS]
[MSG: Machine: 6 Pack External XYZA Laser]
[MSG: Mode=AP:SSID=FluidNC:IP=192.168.0.1:MAC=A8-03-2A-EB-F0-DD]
ok
Homing
ok
```

### User Interface Software

Lightburn (USB Serial Connection)

### What happened?

I'm having an offset between scanning (fill) and line. It's always in the same direction (along scanning axis) and it widens at higher speeds. It doesn't make a difference if I do the line first or the fill first, the result is identical. When scanning in only one direction the alignment between fill and line is nearly perfect but still off a hair.

I've already ruled out scanning offset, I went through Lightburn's instructions and my scans are starting and ending in the correct timings with good non-wavey lines . My engravings on their own look great at all speeds and if I rerun an engraving it lines up perfectly with the engraving I did first.

I've also ruled out steppers losing steps, machine squareness, and other possible mechanical issues.

I'm at a loss solving this one. Any help would be greatly appreciated.

### Other Information

![IMG_8466](https://user-images.githubusercontent.com/24616171/194968792-1d1f8bfc-d985-4858-b807-24cf26af5402.jpg)
