### ISSUE TITLE
Problem: YL620 VFD and RS485 communication

### ISSUE THREAD

**Issue by HenrykXXX** [bdring/FluidNC#660]
### Controller Board

Custom Dev Board

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

Gantry router with 3x TB6600 motor drivers + Chinesse water cooled 2.2kw spindle with YL620 VFD

### Configuration file

```yaml
name: "6050 3-axes"
board: "ESP32 Dev Controller V4"

start:
  must_home: false
  deactivate_parking: false
  check_limits: false

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 4
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.13:high
  
  x:
    steps_per_mm: 160
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 1000
    homing:
      cycle: 0
    
    motor0:
      limit_all_pin: NO_PIN
      stepstick:
        direction_pin: gpio.32:high
        step_pin: gpio.33:high

  y:
    steps_per_mm: 200
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 1000
    homing:
      cycle: 0

    motor0:
      limit_all_pin: NO_PIN
      stepstick:
        direction_pin: gpio.25:high
        step_pin: gpio.26:high

  z:
    steps_per_mm: 200
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 1000
    homing:
      cycle: 0
    motor0:
      limit_all_pin: NO_PIN
      stepstick:
        direction_pin: gpio.27:low
        step_pin: gpio.14:high


coolant:
  flood_pin: gpio.22
  mist_pin:  gpio.23

        
probe:
  pin: gpio.4:low:pu

YL620:
  uart:
    txd_pin: gpio.16
    rxd_pin: gpio.17
    rts_pin: gpio.5
    baud: 9600
    mode: 8N1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%
  off_on_alarm: false
```

### Startup Messages

```text
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8

[MSG:INFO: FluidNC v3.4.4]
[MSG:INFO: Compiled with ESP32 SDK:v3.3.5-1-g85c43024c]
[MSG:INFO: Configuration file:config.yaml]
[MSG:WARN: Ignored key off_on_alarm]
[MSG:INFO: Machine 6050 3-axes]
[MSG:INFO: Board ESP32 Dev Controller V4]
[MSG:INFO: SPI not defined]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13]
[MSG:INFO: Axis X (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.33 Dir:gpio.32 Disable:NO_PIN]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.26 Dir:gpio.25 Disable:NO_PIN]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.14 Dir:gpio.27:low Disable:NO_PIN]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: YL620 Spindle Uart Tx:gpio.16 Rx:gpio.17 RTS:gpio.5 Baud:9600]
[MSG:INFO: Using spindle YL620]
[MSG:INFO: Flood coolant gpio.22]
[MSG:INFO: Mist coolant gpio.23]
[MSG:INFO: Probe Pin: gpio.4:low:pu]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
[MSG:INFO: VFD setState:0 SpindleSpeed:0]

Grbl 3.4 [FluidNC v3.4.4 (wifi) '$' for help]
[MSG:INFO: VFD RS485 Unresponsive]

```

### User Interface Software

UGS

### What happened?

Hello!

I am trying to connect FluidNC controller to YL620 VFD via rs-485 and it does not want to work. I am using pins 5, 16 and 17 for UART output and uart to rs-485 converter board. Even with converter board disconnected when i check activity on esp32 pins with my scope i can see that rx and tx pins are staying high and rts pin pulses high every second or so. There is no frames beeing send from controller. VFD is set correctly to work with rs485 input, I have no idea what is happening but there is some issue here, i hope we can figgure it out!

Have a great day!

**Comment by bdring** [comment]
Show the schematic and a photo of your custom controller.

**Comment by HenrykXXX** [comment]
I separated it there is nothing more then dev board connected to rs adapter powered via usb
![rsconnection](https://user-images.githubusercontent.com/16263093/195152773-ec9452b0-362a-48ae-b444-95225f7705c1.png)

**Comment by bdring** [comment]
I hooked up a logic analyzer to my controller. It seems to be sending TX and RTS

I used these pins because they are easier to connect.

```yaml
YL620:
  uart:
    txd_pin: gpio.25
    rxd_pin: gpio.27
    rts_pin: gpio.26
    baud: 9600
    mode: 8N1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%
  off_on_alarm: false
```
![image](https://user-images.githubusercontent.com/189677/195159615-0d6c5b54-ae14-4346-ab7f-2e38498237f6.png)

![image](https://user-images.githubusercontent.com/189677/195159669-d6adeb82-9b8d-43f5-9f3b-bc75146306e8.png)
