### ISSUE TITLE
Problem: Dive into workpiece when running long programs

### ISSUE THREAD

**Issue by matthewfallshaw** [bdring/FluidNC#676]
### Controller Board

Root Controller

### Help From Board Vendor

- [X] Yes
- [ ] No
- [ ] Not Applicable

### Machine Description

Openbuilds / Maker Store [Lead CNC V3](https://makerhardware.net/wiki/doku.php?id=manuals:lead_v3_cnc) (high Z mod)

### Configuration file

```yaml
board: Root Controller ISO
name: Lead CNC 1010
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
#  dir_delay_us: 1
#  disable_delay_us: 3

axes:
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN
  x:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 730.000
    soft_limits: true
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 50.000
      seek_mm_per_min: 1000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: GPIO.26:low
      hard_limits: true
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1:high
        disable_pin: I2SO.0:high

  y:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 810.000
    soft_limits: true
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 50.000
      seek_mm_per_min: 1000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: GPIO.2:low
      hard_limits: true
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.6
        direction_pin: I2SO.5:low
        disable_pin: I2SO.4:high

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: GPIO.32:low
      hard_limits: true
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.26
        direction_pin: I2SO.25:low
        disable_pin: I2SO.24:high

  z:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 3500.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 210.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 50.000
      seek_mm_per_min: 500.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: GPIO.15:low
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 5.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9:high
        disable_pin: I2SO.8:high

kinematics:
  Cartesian:

i2so:
  bck_pin: gpio.22
  data_pin: gpio.12
  ws_pin: gpio.21

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.36
  cycle_start_pin: gpio.39
  macro0_pin: gpio.34
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: i2so.12
  mist_pin: i2so.13
  delay_ms: 0

probe:
  pin: gpio.27
  check_mode_start: true

macros:
  startup_line0:
  startup_line1:
  macro0:
# G21&G54&G17&G94&G90
  macro1:
  macro2:
  macro3:

start:
  must_home: false
  deactivate_parking: false
  check_limits: true

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: i2so.15
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN


arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16

# NoSpindle:
# pwm:
#   pwm_hz: 2000
#   direction_pin: i2so.16
#   output_pin: gpio.25
#   enable_pin: i2so.17
#   disable_with_s0: false
#   s0_with_disable: true
#   spinup_ms: 0
#   spindown_ms: 0
#   tool_num: 0
#   speed_map: 0=0.000% 3500=100.000%
# H2A:
#   uart:
#     txd_pin: gpio.17
#     rxd_pin: gpio.16
#     rts_pin: gpio.4
#     baud: 9600
#     mode: 8N1
#   modbus_id: 1
#   tool_num: 0
#   speed_map: 0=0% 0=15% 24000=100%

# Note that the relay spindle is not real — I'm currently manually controlling a Folinn/Fuling VFD
relay:
  direction_pin: NO_PIN
  output_pin: i2so.14
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 0=100.000% 1=100.000%
  off_on_alarm: false
Laser:
  pwm_hz: 5000
  output_pin: gpio.25
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 100
  speed_map: 0=0.000% 1000=100.000%
```

### Startup Messages

```text
$ss
<Idle|MPos:350.000,400.000,0.000|FS:0,0>
[MSG:INFO: FluidNC v3.6.3]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine Lead CNC 1010]
[MSG:INFO: Board Root Controller ISO]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.21 DATA:gpio.12]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: User Digital Output:0 on Pin:I2SO.15]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,730.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.1 Disable:I2SO.0]
[MSG:INFO:  X All Limit gpio.26:low]
[MSG:DBG:  X All Limit 0]
[MSG:INFO: Axis Y (0.000,810.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.6 Dir:I2SO.5:low Disable:I2SO.4]
[MSG:INFO:  Y All Limit gpio.2:low]
[MSG:DBG:  Y All Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.26 Dir:I2SO.25:low Disable:I2SO.24]
[MSG:INFO:  Y2 All Limit gpio.32:low]
[MSG:DBG:  Y2 All Limit 0]
[MSG:INFO: Axis Z (-210.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.9 Disable:I2SO.8]
[MSG:INFO:  Z Pos Limit gpio.15:low]
[MSG:DBG:  Z Pos Limit 0]
[MSG:INFO: feed_hold_pin gpio.36]
[MSG:INFO: cycle_start_pin gpio.39]
[MSG:INFO: macro0_pin gpio.34]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Relay Spindle Ena:NO_PIN Out:I2SO.14 Dir:NO_PIN]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.25 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Relay]
[MSG:INFO: Flood coolant I2SO.12]
[MSG:INFO: Mist coolant I2SO.13]
[MSG:INFO: Probe Pin: gpio.27]
[MSG:INFO: Connecting to STA SSID:blacknode]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 192.168.1.9]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
ok
```

### User Interface Software

gSender

### What happened?

Twice, during long `G0` travel moves, the machine has plunged into the workpiece.
Most recently at the following GCODE, from line 24881 of a longer file (full file available):
```gcode
X73.206 Y733.347 Z-6.009
X73.221 Y733.374 Z-5.914
X73.23 Y733.391 Z-5.815
X73.233 Y733.397 Z-5.715
G0 Z5
```

… and all of that was working perfectly, then:
```gcode
X69.401 Y-5.541
```

From the line above it's still in `G0` modal, and this is a long travel move up to the front end of the table. At approximately a Y value of 470, which is about a third of the way through the travel move, it plunged down to at least Z-30 before I hit the E-stop.

The GCODE immediately following this section, in case that helps:
```gcode
Z-3.5
G1 Z-4.5 F500
Z-6.5
G3 X73.508 Y-5.158 I1.67 J4.309
G1 X73.123 Y-5.024
X72.981 Y-4.971
X72.739 Y-4.869
X72.642 Y-4.832
X72.546 Y-4.806
X72.45 Y-4.79
X72.354 Y-4.784
X72.258 Y-4.787
X72.161 Y-4.798
```

The previous time this happened was also during a long `G0` travel move. It plunged directly downwards, far enough that the collet hit the workpiece, then it dragged through an L shaped move that could have been it executing the moves that should have come after the travel move.

### Other Information

I've run several short programs without problems.

Z axis is solid and not slipping. It's **driving** downwards, not slipping.
![x-0 1](https://user-images.githubusercontent.com/5561/196938619-77f13e07-e256-48b4-8ff4-92b994bfe0e1.jpg)
I can supply the gcode for this program, but a quick summary can be gleaned from this:
![x-1 1](https://user-images.githubusercontent.com/5561/196938861-b7ab91d2-c5bb-4117-9ab7-004150b575e2.jpg)

Unfortunately I've been unable to inspect machine state, since both times I've hit E-stop and that's turned off the controller.

I've described these issues on the Root CNC Discord. They're a very helpful group, but are out of ideas and suggested that I come here.

Any help is greatly appreciated.
In the meantime I'll try uploading future programs via WebUI to cut any comms with a sender out of the picture.
