### ISSUE TITLE
Problem: MMC card not Initialized on version 3.6.3

### ISSUE THREAD

**Issue by mstfyghm** [bdring/FluidNC#677]
### Controller Board

I made it myself using ESP32-WROOM32. I used an old 256MB mmc.

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

My machin is a CO2 laser cnc that has DM542E stepper drivers.

### Configuration file

```yaml
stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 3
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.27:low
  
  x:
    steps_per_mm: 125.98425
    max_rate_mm_per_min: 60000
    acceleration_mm_per_sec2: 4500
    max_travel_mm: 900
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 895
      feed_mm_per_min: 300
      seek_mm_per_min: 4000
      settle_ms: 200
      seek_scaler: 1.05
      feed_scaler: 1.1
    
    motor0:
      standard_stepper:
        step_pin: gpio.25:low
        direction_pin: gpio.32:low
        disable_pin: NO_PIN
      limit_pos_pin: gpio.35:high
      pulloff_mm: 5.000

  y:
    steps_per_mm: 125.98425
    max_rate_mm_per_min: 50000
    acceleration_mm_per_sec2: 1100
    max_travel_mm: 600
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 595
      feed_mm_per_min: 300
      seek_mm_per_min: 3000
      settle_ms: 250
      seek_scaler: 1.1
      feed_scaler: 1.1
    
    motor0:
      standard_stepper:
        step_pin: gpio.33:low
        direction_pin: gpio.14:low
        disable_pin: NO_PIN
      limit_pos_pin: gpio.34:high
      pulloff_mm: 5.000

coolant:
  flood_pin: gpio.22:low

Laser:
  pwm_hz: 5000
  output_pin: gpio.2:low
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

  
start:
  must_home: true
  check_limits: true
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.6.3]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine None]
[MSG:INFO: Board None]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:RMT Pulse:3us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.27:low]
[MSG:INFO: Axis X (-5.000,895.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.25:low Dir:gpio.32:low Disable:NO_PIN]
[MSG:INFO:  X Pos Limit gpio.35]
[MSG:INFO: Axis Y (-5.000,595.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.33:low Dir:gpio.14:low Disable:NO_PIN]
[MSG:INFO:  Y Pos Limit gpio.34]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.2:low Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Flood coolant gpio.22:low]
[MSG:INFO: Connecting to STA SSID:XXXXX]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 192.168.1.XXX]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://XXXXXXX.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
ok
```

### User Interface Software

WebUI

### What happened?

My mmc is connected to ESP32 physically but webUI shows that there is no sdcard connected. When I press the "Refresh" button on WebUI, following message appears:
`[MSG:ERR: sdmmc_card_init failed code 0x106]`
As I mentioned in hardware description, I used an old 256MB mmc and everything was OK before v3.6.3.
