### ISSUE TITLE
RS 485 issue  

### ISSUE THREAD

**Issue by lugeral** [bdring/FluidNC#680]
### Controller Board

6-pack

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

Gantry router with tb6600's
Recommended Huanyang vfd
2.2 Kw water cooled spindle
no end stops connected yet

### Configuration file

```yaml
board: 6 Pack
name: FluidNC
meta: 2022-09-05 Andrew Luger 315469
stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 160.000
    max_rate_mm_per_min: 4000.000
    acceleration_mm_per_sec2: 750.000
    max_travel_mm: 1220.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

  y:
    steps_per_mm: 160.000
    max_rate_mm_per_min: 4000.000
    acceleration_mm_per_sec2: 750.000
    max_travel_mm: 640.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.32
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4:low
        disable_pin: I2SO.7
    
    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9:low
        disable_pin: I2SO.8

  z:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 105.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.35
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12:low
        disable_pin: I2SO.15
        

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  
probe:
  pin: gpio.34
  check_mode_start: true

start:
  must_home: false
  
coolant:
  flood_pin: gpio.15
  mist_pin: gpio.12
  delay_ms: 0

Huanyang:
  uart:
    txd_pin: gpio.26
    rxd_pin: gpio.16
    rts_pin: gpio.4
    baud: 19200
    mode: 8N1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%
  off_on_alarm: true
```

### Startup Messages

```text
FluidNC v1.2.0 using COM4
Exit: Ctrl-C, Ctrl-Q or Ctrl-], Clear screen: CTRL-W
Upload: Ctrl-U, Reset ESP32: Ctrl-R, Send Override: Ctrl-O
[MSG:ERR: Huanyang spindle did not reach device units 1073423424. Reported value is 0]

Grbl 1.1h [FluidNC v3.6.3 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
[MSG:INFO: VFD Queue Full]
[MSG:ERR: Huanyang spindle did not reach device units 1073423424. Reported value is 0]
ALARM:10
[MSG:INFO: VFD Queue Full]
[MSG:ERR: Huanyang spindle did not reach device units 1073423424. Reported value is 0]
[MSG:INFO: VFD Queue Full]
[MSG:ERR: Huanyang spindle did not reach device units 1073423424. Reported value is 0]

Grbl 1.1h [FluidNC v3.6.3 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
[MSG:INFO: VFD Queue Full]
[MSG:ERR: Huanyang spindle did not reach device units 1073423424. Reported value is 0]
ALARM:10
[MSG:INFO: VFD Queue Full]
[MSG:ERR: Huanyang spindle did not reach device units 1073423424. Reported value is 0]
[MSG:INFO: VFD Queue Full]
[MSG:ERR: Huanyang spindle did not reach device units 1073423424. Reported value is 0]

Grbl 1.1h [FluidNC v3.6.3 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
[MSG:INFO: VFD Queue Full]
[MSG:ERR: Huanyang spindle did not reach device units 1073423424. Reported value is 0]
ALARM:10
[MSG:INFO: VFD Queue Full]
[MSG:ERR: Huanyang spindle did not reach device units 1073423424. Reported value is 0]
[MSG:INFO: VFD Queue Full]
Resetting MCU

[MSG:INFO: FluidNC v3.6.3]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine PrintNC]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,1220.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.1 Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33]
[MSG:INFO: Axis Y (-640.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.5 Dir:I2SO.4:low Disable:I2SO.7]
[MSG:INFO:  Y Neg Limit gpio.32]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.9:low Disable:I2SO.8]
[MSG:INFO: Axis Z (-105.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.12:low Disable:I2SO.15]
[MSG:INFO:  Z Pos Limit gpio.35]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Huanyang Spindle Uart Tx:gpio.26 Rx:gpio.16 RTS:gpio.4 Baud:19200]
[MSG:INFO: Using spindle Huanyang]
[MSG:INFO: Flood coolant gpio.15]
[MSG:INFO: Mist coolant gpio.12]
[MSG:INFO: Probe Pin: gpio.34]
[MSG:INFO: Connecting to STA SSID:LUGER]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 192.168.50.100]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 1.1h [FluidNC v3.6.3 (wifi) '$' for help]
[MSG:INFO: VFD RS485 Unresponsive
```

### What happened?

I cannot start the spindle

Connection with Rs 485 seems to be ok,  however communication is garbled. I have tried this at 9600 and 19200  and i get the exact same results. 

VFD sends back the the stuff at the top. as well as the queue full errors so i'm not sure what is going on

Rs 485 is installed on module 3

thanks
