### ISSUE TITLE
Can't pipe output to fluidterm.exe

### ISSUE THREAD

**Issue by PBandParker** [bdring/FluidNC#686]
### Controller Board

KeeYees ESP32 Development Board.

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

A CNC with a spindle and an X, Y, A axis cutting arm.

### Configuration file

```yaml
name: "ESP32 Dev Controller V4"
board: "ESP32 Dev Controller V4"

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 0
  pulse_us: 10
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  
  x:
    steps_per_mm: 40
    max_rate_mm_per_min: 7500
    acceleration_mm_per_sec2: 1250
    max_travel_mm: 1000
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 800
      feed_mm_per_min: 50
      settle_ms: 0
    
    motor0:
      limit_neg_pin: NO_PIN
      standard_stepper:
        direction_pin: gpio.14
        step_pin: gpio.13
    motor1:
      null_motor:
  y:
    steps_per_mm: 40
    max_rate_mm_per_min: 7500
    acceleration_mm_per_sec2: 1250
    max_travel_mm: 1000
    homing:
      cycle: 1
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 800
      feed_mm_per_min: 50
      settle_ms: 0
    
    motor0:
      limit_neg_pin: NO_PIN
      standard_stepper:
        direction_pin: gpio.4
        step_pin: gpio.5
    motor1:
      null_motor:
  
  a:
    steps_per_mm: 1.111
    max_rate_mm_per_min: 100000
    acceleration_mm_per_sec2: 16666
    max_travel_mm: 1000
    homing:
      cycle: 3
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 800
      feed_mm_per_min: 50
      settle_ms: 0
    
    motor0:
      limit_neg_pin: NO_PIN
      standard_stepper:
        direction_pin: gpio.16
        step_pin: gpio.17
    motor1:
      null_motor:
DAC:
  output_pin: gpio.25
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 100
  speed_map: 0=0.000% 3300=100.00%
  off_on_alarm: false
```

### Startup Messages

```text
setConsoleModes failed
Press any key to continue...
```

### User Interface Software

Command Line and a Python Script

### What happened?

I'm hoping to be able to send inputs to fluidterm from a program so I could log certain macros.  I tried searching for the setConsoleModes failure error in the wiki but I didn't see anything.

FluidNCControl.py below:
import numpy as np
import time
import os
import subprocess
import sys
p1 = subprocess.Popen(['py', '-3.9', 'FluidNCOutput.py'], stdout=subprocess.PIPE)
p2 = subprocess.run(['C:\\Users\\mylogin\\Documents\\fluidnc-v3.6.4-pre1-win64\\win64\\fluidterm.exe'], stdin=p1.stdout, creationflags=subprocess.CREATE_NEW_CONSOLE)

FluidNCOutput.py below:
print("$X")
