### ISSUE TITLE
Problem: frequent freezing on v3.6.5-pre2

### ISSUE THREAD

**Issue by ipsod** [bdring/FluidNC#700]
### Controller Board

Makerbase MKS TinyBee V1.0  - no drivers, motors, or other hardware attached

### Machine Description

n/a

### Input Circuits

```yaml
n/a
```

### Configuration file

```yaml
name: "ESP32 Dev Controller V4"
board: "ESP32 Dev Controller V4"


stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  # shared_stepper_disable_pin: gpio.13:low

  x:
    steps_per_mm: 3200
    max_rate_mm_per_min: 60
    acceleration_mm_per_sec2: 120
    max_travel_mm: 100
    motor0:
      # limit_neg_pin: gpio.17:low:pu
      stepstick:
        step_pin: gpio.12
        direction_pin: gpio.13
        disable_pin: gpio.5
    motor1:
      null_motor:

  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000.0
    acceleration_mm_per_sec2: 1000.0
    max_travel_mm: 1000
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
      stepstick:
        step_pin: gpio.27
        direction_pin: gpio.14
        disable_pin: gpio.16
    motor1:
      null_motor:

  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 200.0
    acceleration_mm_per_sec2: 200.0
    max_travel_mm: 1000
    homing:
      cycle: 1
      mpos_mm: 10
      positive_direction: true

    motor0:
      stepstick:
        step_pin: gpio.19
        direction_pin: gpio.23
        disable_pin: gpio.18
    motor1:
      null_motor:
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.6.5-pre2]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine ESP32 Dev Controller V4]
[MSG:INFO: Board ESP32 Dev Controller V4]
[MSG:INFO: SPI not defined]
[MSG:INFO: No SD Card CS Pin]
[MSG:INFO: See http://wiki.fluidnc.com/en/config/sd_card#sdfallbackcs-access-sd-without-a-
config-file]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-100.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.12 Dir:gpio.13 Disable:gpio.5]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.27 Dir:gpio.14 Disable:gpio.16]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (-990.000,10.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.19 Dir:gpio.23 Disable:gpio.18]
[MSG:INFO:   Motor1]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.6 [FluidNC v3.6.5-pre2 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
```

### User Interface Software

custom software written with Python and PySerial

### What happened?

 FluidNC hangs frequently.  It doesn't seem to be in response to any particular event, unless it may be triggered by between one and 15 $j= jog commands (though they usually don't trigger it) - it's hard to say if they actually cause it, because I'm doing that so frequently that it's almost always the last thing I did.

Sometimes it will freeze almost immediately (after connecting and running through some startup polling/config commands), and other times it will take 10+ minutes, but it usually happens within 5 minutes.  At least once, it has frozen the very first time I issued 15 jog commands (my first action after my startup script).  I've since updated my code, so that it shouldn't have more than 120 chars in the serial buffer.  It seems time-dependent, as the chances that it will be broken after a long period of nothing happening are pretty good.

After it freezes, it quits giving output of any sort (those 15 jog commands never received an ok line).  After the freeze, I can disconnect with my sender, connect with FluidTerm, and it will not echo my keystrokes or respond to any commands.  It will reset with `ctrl+r`, then go back to working, so, I don't know if that eliminates USB serial mischief, but I suspect it does.

Below are the last lines received and then sent before the crash.  I updated my sender last night to use a 120 char serial buffer limit (counts characters sent only in messages expecting `ok` response of some sort, then subtracts them from the count when `ok` is received), and the last jog commands count out to 118 characters, and that's why there aren't more `$j=` commands.

```
    << <Idle|WPos:1.208,-10.001,0.000|Bf:15,128|FS:0,0>
    >> $j=g91x0y-0.00167z0f1000
    >> $j=g91x0y-0.00333z0f1000
    >> $j=g91x0y-0.005z0f1000
    >> $j=g91x0y-0.00667z0f1000
    >> $j=g91x0y-0.00833z0f1000
```

### Other Information

full serial logs of last 2 failure here:
https://github.com/ipsod/my-FluidNC-log-files/blob/main/log1.txt
https://github.com/ipsod/my-FluidNC-log-files/blob/main/log2.txt
