### ISSUE TITLE
Negative homing bails out before max travel is reached

### ISSUE THREAD

**Issue by arhuaco** [bdring/FluidNC#702]
### Controller Board

6 Pack External Driver CNC Controller

### Machine Description

3 axis Chinese 3040 machine.

### Configuration file

```yaml
board: 6 Pack
name: 6 Pack External XYYZ No Square - v2
meta: Based on 2022-09-19 B. Dring for Dean Embrey

stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 500
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 285
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      allow_single_axis: true
      mpos_mm: 0
      seek_mm_per_min: 800

    motor0:
      limit_all_pin: gpio.34:low
      hard_limits: true
      pulloff_mm: 2
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

  y:
    steps_per_mm: 500
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 382
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      allow_single_axis: true
      mpos_mm: 382
      seek_mm_per_min: 1000
    motor0:
      limit_all_pin: gpio.35:low
      hard_limits: true
      pulloff_mm: 2
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.4:low
        disable_pin: I2SO.7

  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 48
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      allow_single_axis: true
      mpos_mm: 48
      seek_mm_per_min: 400

    motor0:
      limit_all_pin: gpio.36:low
      hard_limits: true
      pulloff_mm: 2
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9:low
        disable_pin: I2SO.8

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

#sdcard:
#  card_detect_pin: NO_PIN
#  cs_pin: gpio.5

start:
  must_home: false
  deactivate_parking: false
  check_limits: false

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: true
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16

NoSpindle:

coolant:
  mist_pin: i2so.3
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.6.4]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine 6 Pack External XYYZ No Square - v2]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: No SD Card CS Pin]
[MSG:INFO: See http://wiki.fluidnc.com/en/config/sd_card#sdfallbackcs-access-sd-without-a-config-file]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,285.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.1 Disable:I2SO.0]
[MSG:INFO:  X All Limit gpio.34:low]
[MSG:INFO: Axis Y (0.000,382.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.5 Dir:I2SO.4:low Disable:I2SO.7]
[MSG:INFO:  Y All Limit gpio.35:low]
[MSG:INFO: Axis Z (0.000,48.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.9:low Disable:I2SO.8]
[MSG:INFO:  Z All Limit gpio.36:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Mist coolant I2SO.3]
[MSG:INFO: Connecting to STA SSID:3_Primo]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 192.168.1.34]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

WebUI

### What happened?

H there!

Using latest release v3.6.4.

After clearing up switches, X is set to 280 and max travel is 285. But  it bails when -250 is reached (traveling 250 mm).

Unless I am not getting something, it should bail out after 285.

$h
  <Home|MPos:0.000,0.000,4.293|FS:400,0>
  <Home|MPos:0.000,0.000,24.255|FS:400,0>
  <Home|MPos:0.000,0.000,44.255|FS:400,0>
  <Home|MPos:0.000,0.000,48.472|FS:50,0>
  <Home|MPos:0.000,0.000,49.865|FS:50,0>
  <Home|MPos:-0.002,0.002,48.000|FS:419,0>
  <Home|MPos:-30.310,50.784,48.000|FS:1281,0|WCO:0.000,0.000,0.000>
  <Home|MPos:-63.106,105.730,48.000|FS:1281,0|Ov:100,100,100>
  <Home|MPos:-95.872,160.628,48.000|FS:1281,0>
  <Home|MPos:-128.676,215.588,48.000|FS:1281,0>
  <Home|MPos:-161.488,270.564,48.000|FS:1281,0>
  <Home|MPos:-194.288,325.516,48.000|FS:1281,0>
  <Home|MPos:-227.088,380.472,48.000|FS:1281,0>
  <Home|MPos:-250.800,384.170,48.000|FS:0,0|Pn:Y>
  ALARM:9
  Homing fail. Could not find limit switch within search distances. Try increasing max travel, decreasing pull-off distance, or check wiring.
  ok
