### ISSUE TITLE
Problem: Y axis motor keeps driving into limit switch while X axis seeks home

### ISSUE THREAD

**Issue by ColPaulR** [bdring/FluidNC#721]
### Controller Board

MKS Tinybee

### Machine Description

4 Axis dual Y-axis motor gantry (XYYZA)  

### Input Circuits

```yaml
1 limit switch on Y with 2 DM556 drivers for Y using separate IO pins (e.g. 2 DM556s are not wired in parallel but controlled with unique io pins)
```

### Configuration file

```yaml
board: MKS TinyBee V1.0_001
name: CNC Router XYZ no spindle
meta: (01.02.2022) by Skorpi

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  x:
    # X
    steps_per_mm: 250
    max_rate_mm_per_min: 5250.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 1300.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 2000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33:low
      hard_limits: true
      pulloff_mm: 2.500
      standard_stepper:
        step_pin: I2SO.1
        direction_pin: I2SO.2:low
        disable_pin: I2SO.0

  y:
    # Y
    steps_per_mm: 250
    max_rate_mm_per_min: 5250.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 1300.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.32:low
      hard_limits: true
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: I2SO.4
        direction_pin: I2SO.5:low
        disable_pin: I2SO.3
    motor1:
      limit_neg_pin: NO_PIN
      #hard_limits: false
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: I2SO.7
        direction_pin: I2SO.8:low
        disable_pin: I2SO.6
 
  z:
    # Z
    steps_per_mm: 250
    max_rate_mm_per_min: 5250.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 1300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.22:low
      hard_limits: true
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.11
        disable_pin: I2SO.9

  a:
    # Rotary
    steps_per_mm: 26.666666666666
    max_rate_mm_per_min: 18000.000
    acceleration_mm_per_sec2: 1500.000
    max_travel_mm: 325.000
    soft_limits: false
#    homing:
#      cycle: 1
#      positive_direction: false
#      mpos_mm: 0.000
#      feed_mm_per_min: 300.000
#      seek_mm_per_min: 5000.000
#      settle_ms: 500
#      seek_scaler: 1.100
#      feed_scaler: 1.100
#
    motor0:
#      limit_neg_pin: gpio.35
      hard_limits: false
#      pulloff_mm: 2.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.14
        disable_pin: I2SO.12

i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.39:low:pu
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0: 
  macro1:
  macro2:
  macro3:

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

#probe:
#  pin: gpio.2
#  check_mode_start: true

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: false

 # USB  TX0(1)  RX0(3)
 # J3-> TX2(17) RX2(16)
 # J1-> I2SO.23 I2SO.22
 # TH1(36)        TH2(34)        THB(39)
 # HE0(I2SO.17)   HE1(I2SO.18)   HBED(I2SO.16)
 # FAN1(I2SO.19)  FAN2(I2SO.20)
 #                   EXP1                                   EXP2
 #(BEEPER) I2SO.21 | 1  2 | 13 (BTN_ENC)    (SPI MISO) 19 | 1  2 | 18 (SPI SCK)
 #    (LCD_EN)  21 | 3  4 |  4 (LCD_RS)      (BTN_EN1) 14 | 3  4 |  5 (SPI CS)
 #    (LCD_D4)   0 | 5  6   16 (LCD_D5)      (BTN_EN2) 12 | 5  6   23 (SPI MOSI)
 #    (LCD_D6)  15 | 7  8 | 17 (LCD_D7)      (SPI_DET) 34 | 7  8 | RESET
 #             GND | 9 10 | 5V                        GND | 9 10 | 3.3V
```

### Startup Messages

```text
Resetting MCU
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:12812
load:0x40080400,len:3032
entry 0x400805e4

[MSG:INFO: FluidNC v3.6.4]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:MKS_TinyBee_1_XYZAB.yaml]
[MSG:WARN: gpio.39:low does not support :pu attribute]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine CNC Router XYZ no spindle]
[MSG:INFO: Board MKS TinyBee V1.0_001]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 4]
[MSG:INFO: Axis X (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.1 Dir:I2SO.2:low Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33:low]
[MSG:DBG:  X Neg Limit 0]
[MSG:INFO: Axis Y (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.4 Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32:low]
[MSG:DBG:  Y Neg Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.7 Dir:I2SO.8:low Disable:I2SO.6]
[MSG:INFO: Axis Z (-1300.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO:  Z Neg Limit gpio.22:low]
[MSG:DBG:  Z Neg Limit 0]
[MSG:INFO: Axis A (-325.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: feed_hold_pin gpio.39:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:RounsavallWPA2]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 192.168.0.235]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.6 [FluidNC v3.6.4 (wifi) '$' for help]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG:  Y Neg Limit 0]
[MSG:DBG:  Z Neg Limit 0]
ok
[MSG:DBG: Homing Cycle Z]
[MSG:DBG: Homing nextPhase FastApproach]
[MSG:DBG: Starting from 0.000,0.000,0.000]
[MSG:DBG: Planned move to 0.000,0.000,1430.000 @ 1000.000]
[MSG:DBG:  Z Neg Limit 1]
[MSG:DBG: Homing limited Z]
[MSG:DBG: Homing nextPhase Pulloff0]
[MSG:DBG: Starting from 0.000,0.000,51.196]
[MSG:DBG: Planned move to 0.000,0.000,50.196 @ 100.000]
[MSG:DBG:  Z Neg Limit 0]
[MSG:DBG: CycleStop Pulloff0]
[MSG:DBG: Homing nextPhase SlowApproach]
[MSG:DBG: Starting from 0.000,0.000,50.196]
[MSG:DBG: Planned move to 0.000,0.000,51.296 @ 100.000]
[MSG:DBG:  Z Neg Limit 1]
[MSG:DBG: Homing limited Z]
[MSG:DBG: Homing nextPhase Pulloff1]
[MSG:DBG: Starting from 0.000,0.000,51.000]
[MSG:DBG: Planned move to 0.000,0.000,50.000 @ 100.000]
[MSG:DBG:  Z Neg Limit 0]
[MSG:DBG: CycleStop Pulloff1]
[MSG:DBG: Homing nextPhase Pulloff2]
[MSG:DBG: mpos was 0.000,0.000,50.000]
[MSG:DBG: mpos becomes 0.000,0.000,0.000]
[MSG:DBG: mpos transformed 0.000,0.000,0.000]
[MSG:DBG: Homing Cycle XY]
[MSG:DBG: Homing nextPhase FastApproach]
[MSG:DBG: Starting from 0.000,0.000,0.000]
[MSG:DBG: Planned move to -1430.000,-1430.000,0.000 @ 2828.427]
[MSG:DBG:  Y Neg Limit 1]
[MSG:DBG: Homing limited Y Y2]
[MSG:DBG:  X Neg Limit 1]
[MSG:DBG: Homing limited X Y Y2]
[MSG:DBG: Homing nextPhase Pulloff0]
[MSG:DBG: Starting from -152.608,-102.136,0.000]
[MSG:DBG: Planned move to -150.108,-100.136,0.000 @ 424.264]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG:  Y Neg Limit 0]
[MSG:DBG: CycleStop Pulloff0]
[MSG:DBG: Homing nextPhase SlowApproach]
[MSG:DBG: Starting from -150.108,-100.136,0.000]
[MSG:DBG: Planned move to -152.858,-102.336,0.000 @ 424.264]
[MSG:DBG:  Y Neg Limit 1]
[MSG:DBG: Homing limited Y Y2]
[MSG:DBG:  X Neg Limit 1]
[MSG:DBG: Homing limited X Y Y2]
[MSG:DBG: Homing nextPhase Pulloff1]
[MSG:DBG: Starting from -152.504,-101.976,0.000]
[MSG:DBG: Planned move to -150.004,-99.976,0.000 @ 424.264]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG:  Y Neg Limit 0]
[MSG:DBG: CycleStop Pulloff1]
[MSG:DBG: Homing nextPhase Pulloff2]
[MSG:DBG: mpos was -150.004,-99.976,0.000]
[MSG:DBG: mpos becomes 0.000,0.000,0.000]
[MSG:DBG: mpos transformed 0.000,0.000,0.000]
[MSG:DBG: Homing done]
ok
```

### User Interface Software

Fluidterm and  CNCjs

### What happened?

I manually moved to X150 Y100 Z-50 after homing so that the X axis has to move a longer distance than the Y when homing. I reset (WebGUI) the Tinybee and then executed a homing cycle. Both X and Y are homing cycle 2. As expected, Y gets to the limit switch first and Y keeps driving (griding noise) until X hits the home switch. After that, they both reverse, slow seek the switches and then pull back. I would expect the Y axis to quit driving once Y hits the Y limit switch, but it does not sound like that is happening.

I reversed the condition so that Y has to travel further than X, and everything behaves correctly (X quits driving while waiting for Y to find the switch). This leads me to believe that this has something to do with me only currently having 1 Y limit switch for 1 motors. My goal is to add another limit switch to the other Y motor and execute axis squaring, but I'm not there yet. I tried adding the same Y limit switch pin (gpio.32:low) to motor1 but got an error message ([MSG:ERR: Configuration error at /machine/axes/y/motor1: ERR: gpio.32:low - Pin is already used.]).
