### ISSUE TITLE
Problem: During a hot reset, GPIO does not get updated

### ISSUE THREAD

**Issue by SnowBeaver** [bdring/FluidNC#729]
### Controller Board

6-pack with 0-10V module

### Machine Description

6-pack with two input module in slot 1 and 2, 1 relay module in slot 3, and one 0-10V module in slot 4

### Input Circuits

```yaml
I was using GPIO.13 and GPIO.15 to access the output of the 0-10V module in slot 4.
```

### Configuration file

```yaml
board: 6 Pack
name: 3 axis std_step X--ZYY v1.2
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 53.400
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 1050.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: -3.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 400.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.33:low:pu
      hard_limits: false
      pulloff_mm: 3.000
      tmc_2130:
        cs_pin: i2so.3
        r_sense_ohms: 0.110
        run_amps: 0.500
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0

  y:
    steps_per_mm: 53.400
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 960.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: -3.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 400.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.36:low
      hard_limits: false
      pulloff_mm: 3.000
      tmc_2130:
        cs_pin: i2so.19
        r_sense_ohms: 0.110
        run_amps: 0.500
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: I2SO.18
        direction_pin: I2SO.17
        disable_pin: I2SO.16

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.39:low
      hard_limits: false
      pulloff_mm: 3.000
      tmc_2130:
        cs_pin: i2so.22
        r_sense_ohms: 0.110
        run_amps: 0.500
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: I2SO.21
        direction_pin: I2SO.20
        disable_pin: I2SO.23

  z:
    steps_per_mm: 808.000
    max_rate_mm_per_min: 500.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 360.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: -3.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 400.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.35:low
      hard_limits: false
      pulloff_mm: 3.000
      tmc_2130:
        cs_pin: i2so.14
        r_sense_ohms: 0.110
        run_amps: 0.6500
        hold_amps: 0.6500
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

probe:
  pin: gpio.2:high:pu
  check_mode_start: true

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: false
  
relay:
  output_pin: gpio.26
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 1=100.000%

laser:
  pwm_hz: 2000
  output_pin: gpio.13:low
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 100
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: false
```

### Startup Messages

```text
$ss
[MSG:INFO: FluidNC v3.6.5-pre4]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine 3 axis std_step X--ZYY v1.2]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-3.000,1047.000)]
[MSG:INFO:   Motor0]
[MSG:DBG: TMCStepper Library Ver. 0x703]
[MSG:INFO:     tmc_2130 Step:I2SO.2 Dir:I2SO.1 CS:I2SO.3 Disable:I2SO.0 Index:-1 R:0.110]
[MSG:INFO:  X All Limit gpio.33:low:pu]
[MSG:DBG:  X All Limit 0]
[MSG:INFO: Axis Y (-3.000,957.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2130 Step:I2SO.18 Dir:I2SO.17 CS:I2SO.19 Disable:I2SO.16 Index:-1 R:0.110]
[MSG:INFO:  Y All Limit gpio.36:low]
[MSG:DBG:  Y All Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO:     tmc_2130 Step:I2SO.21 Dir:I2SO.20 CS:I2SO.22 Disable:I2SO.23 Index:-1 R:0.110]
[MSG:INFO:  Y2 All Limit gpio.39:low]
[MSG:DBG:  Y2 All Limit 0]
[MSG:INFO: Axis Z (-3.000,357.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2130 Step:I2SO.13 Dir:I2SO.12 CS:I2SO.14 Disable:I2SO.15 Index:-1 R:0.110]
[MSG:INFO:  Z All Limit gpio.35:low]
[MSG:DBG:  Z All Limit 0]
[MSG:INFO: X Axis driver test passed]
[MSG:DBG: X Axis StealthChop]
[MSG:INFO: Y Axis driver test passed]
[MSG:DBG: Y Axis StealthChop]
[MSG:INFO: Y2 Axis driver test passed]
[MSG:DBG: Y2 Axis StealthChop]
[MSG:INFO: Z Axis driver test passed]
[MSG:DBG: Z Axis StealthChop]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Relay Spindle Ena:NO_PIN Out:gpio.26 Dir:NO_PIN]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.15:low Freq:2000Hz Period:32767]
[MSG:INFO: Using spindle Relay]
[MSG:INFO: Probe Pin: gpio.2:pu]
[MSG:INFO: Connecting to STA SSID:wifi_terrain]
[MSG:INFO: Connecting.]
[MSG:INFO: Connected - IP is 10.0.0.202]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
ok
```

### User Interface Software

WEBUI

### What happened?

Was in the process of configuring a laser output. I edited the yaml file to change output from GPIO.15 to GPIO.13. The system was running with laser output on GPIO.15 . From the webui I loaded the edited config.yaml with the output on GPIO.13 and I clicked on Restart FluidNC button in the FluidNC Settings panel. After restart. both GPIO.13 and GPIO.15 leds were active high as can be seen from the leds on the 0-10V module. I repowered the 6-pack and only GPIO.13 led was shown active.
