### ISSUE TITLE
SD card issue with files over 2Mb

### ISSUE THREAD

**Issue by txg5230** [bdring/FluidNC#732]
### Controller Board

6-pack

### Machine Description

Esp32 development board

### Configuration file

```yaml
board: 6 Pack
name: 6 Pack StepStick XYZABC
stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 20000.000
    acceleration_mm_per_sec2: 600.000
    max_travel_mm: 1250.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.14:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
       
        step_pin: I2SO.6
        direction_pin: I2SO.5
    

  y:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 20000.000
    acceleration_mm_per_sec2: 600.000
    max_travel_mm: 2450.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.12:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        
        step_pin: I2SO.4
        direction_pin: I2SO.3
        

  z:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 15000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.13:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        
        step_pin: I2SO.2
        direction_pin: I2SO.1
        
        
  a:
    steps_per_mm: 320
    max_rate_mm_per_min: 15000.000
    acceleration_mm_per_sec2: 600.000
    max_travel_mm: 960.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.15:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.000
      stepstick:
       
        step_pin: I2SO.0
        direction_pin: I2SO.7
     


        

i2so:
  bck_pin: gpio.17
  data_pin: gpio.4
  ws_pin: gpio.16

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: gpio.33:low:pu  
  feed_hold_pin: gpio.25:low:pu
  cycle_start_pin: gpio.26:low:pu
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN



probe:
  pin: gpio.27:low:pu
  check_mode_start: true

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

planner_blocks: 99

start:
  must_home: false

PWM:
  pwm_hz: 5000
  output_pin: gpio.2
  enable_pin: gpio.32
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 1000
  spindown_ms: 1000
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
```

### Startup Messages

```text
[12:09:55.070]收←◆
[MSG:INFO: FluidNC v3.6.5-pre4]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:4595.yaml]
[MSG:INFO: Machine 6 Pack StepStick XYZABC]
[MSG:INFO: Board 6 Pack]
[MSG:INFO: I2SO BCK:gpio.17 WS:gpio.16 DATA:gpio.4]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 4]
[MSG:INFO: Axis X (150.000,1400.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.6 Dir:I2SO.5 Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.14:low:pu]
[MSG:INFO: Axis Y (150.000,2600.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.4 Dir:I2SO.3 Disable:NO_PIN]
[MSG:INFO:  Y Neg Limit gpio.12:low:pu]
[MSG:INFO: Axis Z (-150.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.2 Dir:I2SO.1 Disable:NO_PIN]
[MSG:INFO:  Z Neg Limit gpio.13:low:pu]
[MSG:INFO: Axis A (150.000,1110.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.0 Dir:I2SO.7 Disable:NO_PIN]
[MSG:INFO:  A Neg Limit gpio.15:low:pu]
[MSG:INFO: safety_door_pin gpio.33:low:pu]
[MSG:INFO: feed_hold_pin gpio.25:low:pu]
[MSG:INFO: cycle_start_pin gpio.26:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: PWM Spindle Ena:gpio.32 Out:gpio.2 Dir:NO_PIN Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle PWM]
[MSG:INFO: Probe Pin: gpio.27:low:pu]

[12:09:55.334]收←◆[MSG:INFO: Connecting to STA SSID:yygg]
[MSG:INFO: Connecting.]

[12:09:57.334]收←◆[MSG:INFO: Connecting..]

[12:09:59.343]收←◆[MSG:INFO: Connected - IP is 192.168.2.8]
[MSG:INFO: WiFi on]

[12:09:59.368]收←◆[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.6 [FluidNC v3.6.5-pre4 (wifi) '$' for help]
```

### User Interface Software

webul

### What happened?

Upload a file larger than 2 m on the webpage, the controller restarts, and cannot upload it.
