### ISSUE TITLE
4th axis is not working...

### ISSUE THREAD

**Issue by nsiatras** [bdring/FluidNC#75]
My config is the following 

```
name: "4-Axis CNC Motherboard v1.2"
board: "4-Axis CNC Motherboard v1.2"

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 10
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.15:low
  
    x:
        steps_per_mm: 400
        max_rate_mm_per_min: 4000
        acceleration_mm_per_sec2: 80
        max_travel_mm: 302
        soft_limits: true
        homing:
          cycle: 2
          mpos_mm: 0
          positive_direction: false
          seek_mm_per_min: 1500.000
          feed_mm_per_min: 200.000

        motor0:
          limit_all_pin: gpio.36:high
          hard_limits: false
          pulloff_mm: 2.000
          
          standard_stepper:
            direction_pin: gpio.33
            step_pin: gpio.0
            
        motor1:
          null_motor:

    y:
        steps_per_mm: 400
        max_rate_mm_per_min: 4000
        acceleration_mm_per_sec2: 80
        max_travel_mm: 202
        soft_limits: true
        homing:
          cycle: 2
          mpos_mm: 0
          positive_direction: false
          seek_mm_per_min: 1500.000
          feed_mm_per_min: 200.000

        motor0:
          limit_all_pin: gpio.39:high
          hard_limits: false
          pulloff_mm: 2.000
          
          standard_stepper:
            direction_pin: gpio.26
            step_pin: gpio.25
            
        motor1:
          null_motor:

    z:
        steps_per_mm: 400
        max_rate_mm_per_min: 3000
        acceleration_mm_per_sec2: 80
        max_travel_mm: 180
        soft_limits: true
        homing:
          cycle: 1
          mpos_mm: 180
          positive_direction: true
          seek_mm_per_min: 1500.000
          feed_mm_per_min: 200.000
          

        motor0:
          limit_all_pin: gpio.34:high
          hard_limits: false
          pulloff_mm: 2.000
          
          standard_stepper:
            direction_pin: gpio.14:low
            step_pin: gpio.27
            
        motor1:
          null_motor:
      
    a:
        steps_per_mm: 800.000
        max_rate_mm_per_min: 5000.000
        acceleration_mm_per_sec2: 100.000
        max_travel_mm: 300.000
        soft_limits: false
        homing:
          cycle: 3
          positive_direction: true
          mpos_mm: 150.000
          feed_mm_per_min: 100.000
          seek_mm_per_min: 800.000
          debounce_ms: 500
          seek_scaler: 1.100
          feed_scaler: 1.100

        motor0:
          limit_neg_pin: NO_PIN
          limit_pos_pin: NO_PIN
          limit_all_pin: NO_PIN
          hard_limits: false
          pulloff_mm: 1.000
          standard_stepper:       
            step_pin: gpio.12
            direction_pin: gpio.13
      
spi:
  miso_pin: NO_PIN
  mosi_pin: NO_PIN
  sck_pin: NO_PIN

sdcard:
  cs_pin: NO_PIN
  card_detect_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN

        
probe:
  pin: gpio.32:low:pu

PWM:
  pwm_hz: 5000
  output_pin: gpio.21
  enable_pin: NO_PIN
  direction_pin: gpio.2
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0% 10000=100%

```

Axis X,Y and Z are working fine. Axis A is not even visible in the status report message
`<Idle|MPos:0.000,0.000,0.000|FS:0.000,0>`

Any ideas?
