### ISSUE TITLE
spinup_ms and down is not work right.

### ISSUE THREAD

**Issue by RDS356** [bdring/FluidNC#760]
### Controller Board

Self made 4 axis and analog out 0-10.
![IMG_1410](https://user-images.githubusercontent.com/25726497/209819785-cf123876-0c69-475f-89bd-2c2fefe52c5b.JPG)

### Machine Description

Router with vfd 400hz and spindle 2.2 kW.

### Configuration file

```yaml
name: "RDS CNC"
board: "RDS ESP32 V.1.1"
# Oct 2022 by Rei

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  dir_delay_us: 4
  pulse_us: 4
  disable_delay_us: 0
  
axes:
  shared_stepper_disable_pin: gpio.27
  x:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 255.000
    max_travel_mm: 500.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1000.000
      settle_ms: 100
      seek_scaler: 1.000
      feed_scaler: 1.000

    motor0:      
      limit_neg_pin: gpio.33      
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
       step_pin: I2SO.1
       direction_pin: I2SO.2:low
       
  y:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 255.000
    max_travel_mm: 500.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1000.000
      settle_ms: 100
      seek_scaler: 1.000
      feed_scaler: 1.000

    motor0:      
      limit_neg_pin: gpio.32      
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
       step_pin: I2SO.3
       direction_pin: I2SO.4:low
  
  z:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 800.000
    acceleration_mm_per_sec2: 255.000
    max_travel_mm: 80.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1000.000
      settle_ms: 100
      seek_scaler: 1.000
      feed_scaler: 1.000

    motor0:      
      limit_neg_pin: gpio.35    
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
       step_pin: I2SO.5
       direction_pin: I2SO.6:low
  
  a:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 255.000
    max_travel_mm: 500.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 100
      seek_scaler: 1.000
      feed_scaler: 1.000

    motor0:      
      limit_neg_pin: gpio.34
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
       step_pin: I2SO.7
       direction_pin: I2SO.0:low
       
i2so:
  ws_pin: gpio.12
  bck_pin: gpio.13
  data_pin: gpio.14  

#spi:
#  miso_pin: gpio.19
#  mosi_pin: gpio.23
#  sck_pin: gpio.18

#sdcard:
#  cs_pin: gpio.5
#  card_detect_pin: NO_PIN

control:
  safety_door_pin: gpio.25:low
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

coolant:
  flood_pin: gpio.15
  mist_pin: gpio.21
  delay_ms: 0

probe:
  pin: gpio.26
  check_mode_start: true
  
PWM:
  pwm_hz: 5000
  output_pin: gpio.2
  enable_pin: gpio.4
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 6000
  spindown_ms: 6000
  tool_num: 0
  speed_map: 0=0% 24000=100%

start:
  must_home: false
  deactivate_parking: true
  check_limits: true
```

### Startup Messages

```text
m3s8000
```

### User Interface Software

bcnc

### What happened?

Simple, the acceleration ramp configs in VFDs  is note proportional with frequency  setuped.(frequency is relative with rotation).
Eg.:  if in VFD the configurations in acceleration ramp is 6 seconds, no matter the frequency , the time to came the frequency setuped will be the same, in this case 6 seconds.
But the FluidNC make a proportional time with speed, it is wrong.
How must be ?
- If the value in spinup_ms is 6000, after m3, only m3, FluidNC must wait 6 seconds before start rest of gcode.

The same in spindown.

Regards, 
Reinaldo de Souza
