### ISSUE TITLE
Crashing when disconnect from WiFi & random move with micro pin

### ISSUE THREAD

**Issue by mani-fa** [bdring/FluidNC#782]
### Controller Board

2 Axis pen/Laser

### Machine Description

2 Axis pen/Laser with a4988 driver

### Input Circuits

```yaml
for input pin I just put a push button for "macro0_pin: gpio.34:low" to run "1.nc" file from SD, which I use it as a reset pin before reconfiguration.
```

### Configuration file

```yaml
name: "ESP32 Pen/Laser V3"
board: "ESP32 Pen/Laser V3"
meta: M@N!_F@

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.13
  
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 320
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false
    
    motor0:
      limit_all_pin: gpio.15:low:pu
      stepstick:
        direction_pin: gpio.26
        step_pin: gpio.12
    motor1:
      null_motor:

  y:
    steps_per_mm: 80
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 240
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
      limit_all_pin: gpio.4:low:pu
      stepstick:
        direction_pin: gpio.25
        step_pin: gpio.14
    motor1:
      null_motor:

  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 500
    max_travel_mm: 5.00
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 5
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.27
        min_pulse_us: 2100
        max_pulse_us: 1000

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.36:low
  cycle_start_pin: gpio.39:low
  macro0_pin: gpio.34:low
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin:  NO_PIN
  delay_ms: 0
        
probe:
  pin: NO_PIN

macros:
  startup_line0: 
  startup_line1:
  macro0: $sd/run=1.nc
  macro1:
  macro2:
  macro3:

start:
  must_home: false

Laser:
  pwm_hz: 1000
  output_pin: gpio.17
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0% 1000=100%
```

### Startup Messages

```text
rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:12812
load:0x40080400,len:3032
entry 0x400805e4

[MSG:INFO: FluidNC v3.6.6]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:pen_laser_v3.yaml]
[MSG:WARN: Ignored key direction_pin]
[MSG:WARN: Ignored key spinup_ms]
[MSG:WARN: Ignored key spindown_ms]
[MSG:INFO: Machine ESP32 Pen/Laser V3]
[MSG:INFO: Board ESP32 Pen/Laser V3]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13]
[MSG:INFO: Axis X (10.000,330.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.12 Dir:gpio.26 Disable:NO_PIN]
[MSG:INFO:  X All Limit gpio.15:low:pu]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (10.000,250.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.14 Dir:gpio.25 Disable:NO_PIN]
[MSG:INFO:  Y All Limit gpio.4:low:pu]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (0.000,5.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     rc_servo Pin:gpio.27 Pulse Len(2100,1000 period:1048575)]
[MSG:INFO: feed_hold_pin gpio.36:low]
[MSG:INFO: cycle_start_pin gpio.39:low]
[MSG:INFO: macro0_pin gpio.34:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.17 Freq:1000Hz Period:65535]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID ESP32.T-Laser IP 192.168.4.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 8080]

Grbl 3.6 [FluidNC v3.6.6 (wifi) '$' for help]
```

### User Interface Software

WebUI , LasrGrbl

### What happened?

1. everything works ok when connecting and selecting file from sd card but after selecting a file to work ,if before closing browser I disconnect wifi , then esp32 stop working and freezes (On PC or Phone) , re-connecting may solve the problem but sometimes it crashes and I cannot connect to it , reboot required to back to normal state.

2. another problem is when connecting again to working machine , it freeses for a second.

3. I put a push button to run a file from sd card. When It runs and done ,I push it again to do job again, but somehow it crashes and just process bar never ended it goes up and down and just do some gcode randomly. (maybe after 4 or 5 time that I press it). It happens randomly without any reason. As I realize it mostly happens when there is no any Wi-Fi connected and just [MSG:VRB: micropin] massage shows up but it needs to mount SD card 
like [MSG:VRB: Mount_sd] right after micro pin
to run gcode but sometimes it does not show up.

4. MKSlaser and Atomstack app for android works Ok with FluidNc , I can control and take picture and upload it to SD card , after uploading it ask to start working and by confirming, it shows proccess bar , pause and stop works as well , only part that it worked before and now not supported is showing files on SD card. with these apps anything can be done over phone.
Error :
         [MSG:VRB: Mount_sd]
         [MSG:VRB: Cannot open file /spiffs/chat]
         [MSG:VRB: Cannot open file /spiffs/chat.gz]
         [MSG:VRB: Unmount_sd]
As I see it works like refresh in SD card section and just Mount and Unmount state reported it console area and I have no idea about chat.gz!

5. Z axis is micro servo and I need to set positive_direction: true to false to move opposite direction but after set this parameter to false , servo does not move anymore.
