### ISSUE TITLE
Problem: Pen plotter : uln2003 - unipolar 28byj-48 stepper motor config 

### ISSUE THREAD

**Issue by Ammar56788** [bdring/FluidNC#788]
### Controller Board

Pen plotter run with simple diy circuit such as Breadboard.!

### Machine Description

Pen plotter

28byj-48 as x axis motor.
28byj-48 as y axis motor.
sg90 as z axis motor (pen up and down)
Two simple limit switch circuit.
Esp32 devkit as main processor and wifi etc.

### Configuration file

```yaml
There is noting
```

### Startup Messages

```text
No
```

### User Interface Software

WebUI

### What happened?

I cant write new or edit other exist example config .yaml for my pen plotter
Because i dont know yaml language...

### Other Information

Excuse me for bad English

**Comment by Ammar56788** [comment]
And wiki.fluidnc.com not responding

**Comment by mani-fa** [comment]
> And wiki.fluidnc.com not responding
It works try VPN to access.

**Comment by Ammar56788** [comment]
Thnaks and Damn to who boycott a country!
And is there any code for plotter with both uln2003 and esp32?

**Comment by evgeny-smirnov** [comment]
To configure 28byj needs to use unipolar drive

here is example
```
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 500
    motor0:
      hard_limits: false
      unipolar:
        phase0_pin: gpio.13
        phase1_pin: gpio.12
        phase2_pin: gpio.14
        phase3_pin: gpio.27
        half_step: false
```

and try to use servo settings like in WallPlotter.yaml config example
