### ISSUE TITLE
Missing X-Steps after Homing

### ISSUE THREAD

**Issue by dhaude** [bdring/FluidNC#809]
### Controller Board

Makerbase DLC32 V2.1 

### Machine Description

DIY Laser Engraver @ Makerspace Wiesbaden (Germany)
Configuration: XYY  - NEJE-Laser 12V - 5.5W (TTL-Signal)

### Input Circuits

```yaml
Very simple Input Circuitry: for each axis 2 End Stop Switches in series via Optocoupler
```

### Configuration file

```yaml
board: MKS-DLC32 V2.1
name: Laser Engraver XYY
meta: (16.02.2023 - 16:57) by Dieter

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 80.270
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 1500.000
    max_travel_mm: 790.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.36
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 160.055
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 790.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.35
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6:low
        
    motor1:
      limit_neg_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4   

  z:
    steps_per_mm: 100.0
    max_rate_mm_per_min: 100.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 100.000
    soft_limits: false

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  cs_pin: gpio.15
  card_detect_pin: NO_PIN

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.33:low:pu
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0: $SD/Run=lasertest.gcode
  macro1: $SD/Run=home.gcode
  macro2:
  macro3:

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

probe:
  pin: NO_PIN
  check_mode_start: false

Laser:
  pwm_hz: 5000
  #L on Beeper / IN on TTL
  output_pin: gpio.32
  enable_pin: I2SO.7
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 255=100.000%
  
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: true
  deactivate_parking: false
  check_limits: false
```

### Startup Messages

```text
Cannot provide as machine is at another location.
```

### User Interface Software

WebUI

### What happened?

After 'Homing' the WebUI shows Xw = 0.0 und Yw = 0.0
After selecting (via Jog) 100mm the very first time, the laser moves 100mm in positive x-direction but the WebUI shows just Xw = 8.0mm (missing  92mm)
After selecting (via Jog) 100mm the second time, the laser again moves 100mm in positive x-direction and the WebUI shows just Xw = 108.0mm and this is the same for further commands

The behavior  ist repeatable.
Is this a bug or a problem with our machine?
