### ISSUE TITLE
Problem: System crashes during run

### ISSUE THREAD

**Issue by snakescb** [bdring/FluidNC#812]
### Controller Board

Custom controller, based on 6-Pack schematic, external stepper drivers on I2SO pins, no SD card slot

### Machine Description

DIY machine

### Configuration file

```yaml
board: NCMate
name: CNC PitschBitsch

start:
  must_home: true
  
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 5
  dir_delay_us: 0
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  
  x:
    steps_per_mm: 640.000
    max_rate_mm_per_min: 4000.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 420.000
    soft_limits: true
    
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: -10.000
      feed_mm_per_min:  800.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.2:low:pu
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 7.750

      standard_stepper:
        step_pin: i2so.6
        direction_pin: i2so.5:low
        disable_pin: i2so.4:low

  y:
    steps_per_mm: 640.000
    max_rate_mm_per_min: 4000.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 510.000
    soft_limits: true
    
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 505.000
      feed_mm_per_min:  100.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.15:low:pu
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.6

      standard_stepper:
        step_pin: i2so.10
        direction_pin: i2so.9:high
        disable_pin: i2so.8:low   

    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.13:low:pu
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 3.6

      standard_stepper:
        step_pin: i2so.2
        direction_pin: i2so.1:high
        disable_pin: i2so.0:low    

  z:
    steps_per_mm: 640
    max_rate_mm_per_min: 4000.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 120
    soft_limits: true

    homing:
      cycle: 1
      mpos_mm: 120
      feed_mm_per_min:  100.000
      seek_mm_per_min: 2000.000
      positive_direction: true

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.12:low:pu
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000

      standard_stepper:
        step_pin: i2so.14
        direction_pin: i2so.13:low
        disable_pin: i2so.12:low 
        
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

control:
  safety_door_pin: gpio.25:low
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: gpio.33:low
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  flood_pin: i2so.23
  mist_pin: i2so.22
  delay_ms: 0

probe:
  pin: gpio.4:low
  check_mode_start: true

user_outputs:
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

10V:
  forward_pin: i2so.16
  reverse_pin: i2so.17
  pwm_hz: 5000
  output_pin: gpio.16
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 4000
  spindown_ms: 2000
  tool_num: 0
  speed_map: 0=0.000% 24000=100.000%

parking:
  enable: true
  axis: Z
  pullout_distance_mm: 5.000
  pullout_rate_mm_per_min: 250.000
  target_mpos_mm: 120.000
  rate_mm_per_min: 2000.000
```

### Startup Messages

```text
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8
[MSG:INFO: FluidNC v3.6.8-pre1]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine CNC PitschBitsch]
[MSG:INFO: Board NCMate]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: Stepping:I2S_static Pulse:5us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-10.000,410.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.6 Dir:I2SO.5:low Disable:I2SO.4:low]
[MSG:INFO:  X Neg Limit gpio.2:low:pu]
[MSG:INFO: Axis Y (-5.000,505.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.10 Dir:I2SO.9 Disable:I2SO.8:low]
[MSG:INFO:  Y Pos Limit gpio.15:low:pu]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.2 Dir:I2SO.1 Disable:I2SO.0:low]
[MSG:INFO:  Y2 Pos Limit gpio.13:low:pu]
[MSG:INFO: Axis Z (0.000,120.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.14 Dir:I2SO.13:low Disable:I2SO.12:low]
[MSG:INFO:  Z Pos Limit gpio.12:low:pu]
[MSG:INFO: safety_door_pin gpio.25:low]
[MSG:INFO: cycle_start_pin gpio.33:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:NO_PIN Out:gpio.16 Dir:NO_PIN Fwd:I2SO.16 Rev:I2SO.17 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Flood coolant I2SO.23]
[MSG:INFO: Mist coolant I2SO.22]
[MSG:INFO: Probe Pin: gpio.4:low]
[MSG:INFO: Connecting to STA SSID:Einstein]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 10.64.20.155]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
Grbl 3.6 [FluidNC v3.6.8-pre1 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
```

### User Interface Software

cncjs

### What happened?

I am running a gcode off cncjs installed on a SBC via USB. Web-IF is not connected. The attached gcode runs around 4 hours, but the machine never manages to finish the job, it always crashes with below error message. Sometimes after 30 minutes, sometimes after 2 hours, absolutely random. To me it looks related to issue #794 , why I was upgrading to 3.6.8-pre1, hoping the problem has solved, unfortunately it has not in my case. 

Guru Meditation Error: Core  0 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401e5520: b48c3004 38ee4831 ee233203
Core  0 register dump:
PC      : 0x401e5526  PS      : 0x00060b30  A0      : 0x801e584c  A1      : 0x3ffdd544
A2      : 0x00000000  A3      : 0x000000fc  A4      : 0x3ffde8d4  A5      : 0x00000001
A6      : 0x3ffdef5c  A7      : 0x3ffeda54  A8      : 0x801e548c  A9      : 0x3ffdd530
A10     : 0x00000000  A11     : 0x3ffdf058  A12     : 0x000000e4  A13     : 0x3ffedbac
A14     : 0x00000002  A15     : 0xac0f0000  SAR     : 0x0000001d  EXCCAUSE: 0x00000000
EXCVADDR: 0x00000000  LBEG    : 0x4008bac4  LEND    : 0x4008bada  LCOUNT  : 0x00000000
Backtrace:0x401e5523:0x3ffdd544 |<-CORRUPTED
ELF file SHA256: 0000000000000000
Rebooting...

As a side effect, after this happens the controller fails to restart, it makes 2 or 3 cycles, then everything seems back to normal. Here the Startup message in this case:

[MSG:INFO: '$H'|'$X' to unlock]
assert failed: heap_caps_free heap_caps.c:339 (heap != NULL && "free() target pointer is outside heap areas")
Backtrace:0x400859b1:0x3ffe36400x4008fadd:0x3ffe3660 0x40095b85:0x3ffe3680 0x40085e6a:0x3ffe37b0 0x40095bb5:0x3ffe37d0 0x401a3c59:0x3ffe37f0 0x401ad0c0:0x3ffe3810 0x401b37a5:0x3ffe3830 0x401b3a67:0x3ffe3850 0x401b3ee6:0x3ffe3880 0x401b4254:0x3ffe38c0 0x401b4282:0x3ffe38e0 0x401b4292:0x3ffe3900 0x401a6ae5:0x3ffe3930 0x401a6a31:0x3ffe3950 0x401b3353:0x3ffe3970 0x400ee2d6:0x3ffe3990 0x400ef37e:0x3ffe3a90 0x400f008b:0x3ffe3b10 0x400d5725:0x3ffe3b40 0x400f67c7:0x3ffe3b70 0x400efbb2:0x3ffe3b90 0x400efcbb:0x3ffe3bc0 0x400ed0c3:0x3ffe3be0
ELF file SHA256: 0000000000000000
Rebooting...
ets Jun  8 2016 00:22:57
rst:0xc (SW_CPU_RESET),boot:0x3b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8
[MSG:INFO: FluidNC v3.6.8-pre1]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:ERR: Skipping configuration file due to panic]
[MSG:INFO: Using default configuration]
[MSG:INFO: Axes: using defaults]
[MSG:INFO: Machine Default (Test Drive)]
[MSG:INFO: Board None]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:Einstein]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 10.64.20.155]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
Grbl 3.6 [FluidNC v3.6.8-pre1 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]

[1001.txt](https://github.com/bdring/FluidNC/files/10811907/1001.txt)

Thank you for having a look, really hope I can help to get this fixed.

Best regards
Christian
