### ISSUE TITLE
Problem: axes not working properly for home

### ISSUE THREAD

**Issue by antwal** [bdring/FluidNC#814]
### Controller Board

Custom Board

### Machine Description

CNC Cutter with ESP32-DevKitC + 2x EasyDriver + 2x Nema 17 + Servo + Mcro SD Adapter

### Input Circuits

```yaml
Schematic: https://pasteboard.co/oEFtzJdL7E1v.png
```

### Configuration file

```yaml
name: "Test 5h"
board: "ESP32-DevKitC"

kinematics:
  corexy:

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.13
  shared_stepper_reset_pin: NO_PIN

  x:
    steps_per_mm: 200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 600
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      allow_single_axis: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.39:low
      stepstick:
        direction_pin: gpio.12
        step_pin: gpio.14
    motor1:
      null_motor:

  y:
    steps_per_mm: 200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      allow_single_axis: true
      mpos_mm: 150.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36:low
      stepstick:
        direction_pin: gpio.26
        step_pin: gpio.25
    motor1:
      null_motor:

  z:
    steps_per_mm: 100
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 5
    homing:
      cycle: 1
      mpos_mm: 0
      positive_direction: true

    motor0:
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.27
        min_pulse_us: 1000
        max_pulse_us: 2000

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  frequency_hz: 5000
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.6.7]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config-5h.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine Test 5h]
[MSG:INFO: Board ESP32-DevKitC]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN]
hz = 5000
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13]
[MSG:INFO: Axis X (-450.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.14 Dir:gpio.12 Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.39:low]
[MSG:DBG:  X Neg Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (150.000,1150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.25 Dir:gpio.26 Disable:NO_PIN]
[MSG:INFO:  Y Neg Limit gpio.36:low]
[MSG:DBG:  Y Neg Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (-5.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     rc_servo Pin:gpio.27 Pulse Len(1000,2000 period:1048575)]
[MSG:INFO: Kinematic system: CoreXY]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:Home]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 172.16.85.148]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### What happened?

When I start separate axis home both motors start

I based myself on this example configuration: [fluidnc_pen_laser.yaml](https://github.com/bdring/FluidNC/blob/main/example_configs/fluidnc_pen_laser.yaml)

i tried assigning two separate pins for enable/disable, but i have the same problem, both stepper motors always start:
```
  X:
    motor0:
      limit_neg_pin: gpio.39:low
      stepstick:
        direction_pin: gpio.12
        step_pin: gpio.14
        disable_pin: gpio.13
        reset_pin: NO_PIN
  Y:
    motor0:
      limit_neg_pin: gpio.36:low
      stepstick:
        direction_pin: gpio.26
        step_pin: gpio.25
        disable_pin: gpio.4
        reset_pin: NO_PIN
```
Log:
```
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-450.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.14 Dir:gpio.12 Disable:gpio.13]
[MSG:INFO:  X Neg Limit gpio.39:low]
[MSG:DBG:  X Neg Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (150.000,1150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:gpio.25 Dir:gpio.26 Disable:gpio.4]
[MSG:INFO:  Y Neg Limit gpio.36:low]
[MSG:DBG:  Y Neg Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (-5.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     rc_servo Pin:gpio.27 Pulse Len(1000,2000 period:1048575)]
```

### Other Information

$HX
[MSG:DBG: Homing Cycle X]
[MSG:DBG: Homing nextPhase FastApproach]
[MSG:DBG: Starting from 5.003,149.902,0.000]
[MSG:DBG: Planned move to 665.003,149.902,0.000 @ 200.000]
[MSG:DBG:  X Neg Limit 1]
[MSG:DBG: Homing limited X]
[MSG:DBG: Homing nextPhase Pulloff0]
[MSG:DBG: Starting from 7.397,149.902,0.000]
[MSG:DBG: Planned move to 6.397,149.902,0.000 @ 100.000]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG: CycleStop Pulloff0]
[MSG:DBG: Homing nextPhase SlowApproach]
[MSG:DBG: Starting from 6.400,149.900,0.000]
[MSG:DBG: Planned move to 7.500,149.900,0.000 @ 100.000]
[MSG:DBG:  X Neg Limit 1]
[MSG:DBG: Homing limited X]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG: Homing nextPhase Pulloff1]
[MSG:DBG: Starting from 7.105,149.900,0.000]
[MSG:DBG: Planned move to 6.105,149.900,0.000 @ 100.000]
[MSG:DBG: CycleStop Pulloff1]
[MSG:DBG: Homing nextPhase Pulloff2]
[MSG:DBG: mpos was 6.105,149.900,0.000]
[MSG:DBG: mpos becomes 150.000,149.900,0.000]
[MSG:DBG: mpos transformed 150.000,149.900,0.000]
[MSG:DBG: Homing done]
ok
<Idle|MPos:150.000,149.900,0.000|FS:0,0>$HY
[MSG:DBG: Homing Cycle Y]
[MSG:DBG: Homing nextPhase FastApproach]
[MSG:DBG: Starting from 150.403,141.887,0.000]
[MSG:DBG: Planned move to 150.403,-958.112,0.000 @ 200.000]
[MSG:DBG:  X Neg Limit 1]
[MSG:DBG: Homing limited X]
[MSG:DBG:  Y Neg Limit 1]
[MSG:DBG: Homing limited X Y]
[MSG:DBG: Homing nextPhase Pulloff0]
[MSG:DBG: Starting from 150.917,140.083,0.000]
[MSG:DBG: Planned move to 150.917,141.083,0.000 @ 100.000]
[MSG:DBG:  Y Neg Limit 0]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG: CycleStop Pulloff0]
[MSG:DBG: Homing nextPhase SlowApproach]
[MSG:DBG: Starting from 150.902,141.068,0.000]
[MSG:DBG: Planned move to 150.902,139.967,0.000 @ 100.000]
[MSG:DBG:  X Neg Limit 1]
[MSG:DBG: Homing limited X]
[MSG:DBG:  Y Neg Limit 1]
[MSG:DBG: Homing limited X Y]
[MSG:DBG: Homing nextPhase Pulloff1]
[MSG:DBG: Starting from 150.943,140.533,0.000]
[MSG:DBG: Planned move to 150.943,141.533,0.000 @ 100.000]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG:  Y Neg Limit 0]
[MSG:DBG: CycleStop Pulloff1]
[MSG:DBG: Homing nextPhase Pulloff2]
[MSG:DBG: mpos was 150.940,141.530,0.000]
[MSG:DBG: mpos becomes 150.940,150.000,0.000]
[MSG:DBG: mpos transformed 150.940,150.000,0.000]
[MSG:DBG: Homing done]
ok
<Idle|MPos:150.940,150.000,0.000|FS:0,0>
