### ISSUE TITLE
Problem: Analog output / M67 does not work

### ISSUE THREAD

**Issue by resterampeberlin** [bdring/FluidNC#825]
### Controller Board

ESP32 Prototyping board

### Machine Description

n/a

### Input Circuits

```yaml
n/a
```

### Configuration file

```yaml
name: "3 Axis 5 Motors Lasercutter"
board: "ESP32-DEVKIT"

stepping:
  engine: I2S_STATIC
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: i2so.0:low
  shared_stepper_reset_pin: NO_PIN

  x:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    soft_limits: false

    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
      limit_all_pin: gpio.36:low
      tmc_2130:
        direction_pin: i2so.1
        step_pin: i2so.2
        cs_pin: i2so.3:low
        spi_index: -1

    motor1:
      limit_all_pin: gpio.39:low
      tmc_2130:
        direction_pin: i2so.4
        step_pin: i2so.5
        cs_pin: i2so.6:low
        spi_index: -1

  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    soft_limits: false

    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
      limit_all_pin: gpio.34:low
      tmc_2130:
        direction_pin: i2so.7
        step_pin: i2so.8
        cs_pin: i2so.9:low
        spi_index: -1

    motor1:
      limit_all_pin: gpio.35:low
      tmc_2130:
        direction_pin: i2so.10
        step_pin: i2so.11
        cs_pin: i2so.12:low
        spi_index: -1

  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    soft_limits: false

    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false

    motor0:
      limit_all_pin: gpio.32:low:pu
      tmc_2130:
        direction_pin: i2so.13
        step_pin: i2so.14
        cs_pin: i2so.15:low
        spi_index: -1

    motor1:
      null_motor:

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

sdcard:
  cs_pin: gpio.13
  card_detect_pin: NO_PIN
  frequency_hz: 1000000

i2c0:
   sda_pin: gpio.27
   scl_pin: gpio.14

oled:
   i2c_num: 0
   i2c_address: 61
   width: 128
   height: 64
   radio_delay_ms: 1000

coolant:
  flood_pin: i2so.17
  mist_pin: i2so.16

control:
  safety_door_pin: NO_PIN
  reset_pin: gpio.5:low:pu
  feed_hold_pin: gpio.26:low:pu
  cycle_start_pin: gpio.25:low:pu
  macro0_pin: gpio.33:low:pu
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0: G0Y100&G0X100&G0X0Y0
  macro1:
  macro2:
  macro3:

user_outputs:
  analog0_pin: gpio.15
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: i2so.19
  digital1_pin: i2so.20
  digital2_pin: i2so.21
  digital3_pin: i2so.22

probe:
  pin: gpio.16:low:pu

Laser:
  pwm_hz: 5000
  output_pin: gpio.2
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: false
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.6.8]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:fluidnc.yaml]
[MSG:WARN: Increasing stepping/pulse_us to the IS2 minimum value 4]
[MSG:INFO: Machine 3 Axis 5 Motors Lasercutter]
[MSG:INFO: Board ESP32-DEVKIT]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.13 detect:NO_PIN freq:1000000]
hz = 1000000
[MSG:INFO: I2C SDA: gpio.27, SCL: gpio.14, Freq: 100000, Bus #: 0]
[MSG:INFO: OLED I2C address:0x3d width: 128 height: 64]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Dela]
[MSG:INFO: User Digital Output:0 on Pin:I2SO.19]
[MSG:INFO: User Digital Output:1 on Pin:I2SO.20]
[MSG:INFO: User Digital Output:2 on Pin:I2SO.21]
[MSG:INFO: User Digital Output:3 on Pin:I2SO.22]
[MSG:INFO: User Analog Output 0 on Pin:gpio.15 Freq:5000Hz]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable I2SO.0:low]
[MSG:INFO: Axis X (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2130 Step:I2SO.2 Dir:I2SO.1 CS:I2SO.3:low Disable:NO_PIN Ind]
[MSG:INFO:  X All Limit gpio.36:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     tmc_2130 Step:I2SO.5 Dir:I2SO.4 CS:I2SO.6:low Disable:NO_PIN Ind]
[MSG:INFO:  X2 All Limit gpio.39:low]
[MSG:INFO: Axis Y (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2130 Step:I2SO.8 Dir:I2SO.7 CS:I2SO.9:low Disable:NO_PIN Ind]
[MSG:INFO:  Y All Limit gpio.34:low]
[MSG:INFO:   Motor1]
[MSG:INFO:     tmc_2130 Step:I2SO.11 Dir:I2SO.10 CS:I2SO.12:low Disable:NO_PIN ]
[MSG:INFO:  Y2 All Limit gpio.35:low]
[MSG:INFO: Axis Z (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2130 Step:I2SO.14 Dir:I2SO.13 CS:I2SO.15:low Disable:NO_PIN ]
[MSG:INFO:  Z All Limit gpio.32:low:pu]
[MSG:INFO:   Motor1]
[MSG:ERR: X Axis TMC driver not detected - expected 0x11 got 0xff]
[MSG:ERR: X2 Axis TMC driver not detected - expected 0x11 got 0xff]
[MSG:ERR: Y Axis TMC driver not detected - expected 0x11 got 0xff]
[MSG:ERR: Y2 Axis TMC driver not detected - expected 0x11 got 0xff]
[MSG:ERR: Z Axis TMC driver not detected - expected 0x11 got 0xff]
[MSG:INFO: reset_pin gpio.5:low:pu]
[MSG:INFO: feed_hold_pin gpio.26:low:pu]
[MSG:INFO: cycle_start_pin gpio.25:low:pu]
[MSG:INFO: macro0_pin gpio.33:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.2 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Flood coolant I2SO.17]
[MSG:INFO: Mist coolant I2SO.16]
[MSG:INFO: Probe Pin: gpio.16:low:pu]
[MSG:INFO: Connecting to STA SSID:WCHAPT943]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 10.0.0.6]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.6 [FluidNC v3.6.8 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
```

### User Interface Software

WebUI

### What happened?

- I have an analog output connected to gpio.15. M67 E0 Q50 sets this output constantly to high but does not produce any PWM output. M67 E0 Q0 sets this output as expected to low.
- output is analyzed with an oscilloscope
- PWM output to spindle/laser on gpio.2 works as expected
- I exchanged the spindle/laser output from gpio.2 to gpio.15 and vice versa. The PWM output for the spindle worked always while the PWM output to the analog output did not.
- the ESP32 is just on a prototyping board to verify, that my pin layout for my PCB works.
- I tried different output frequencies with the same result
- All other inputs/outputs worked as expected.
