### ISSUE TITLE
Motor Twitches

### ISSUE THREAD

**Issue by Oleg-Perevyshin** [bdring/FluidNC#841]
### Controller Board

MKS TinyBee v1.0
Standard connection

### Machine Description

Driver - TLC2209
Motor - Nema17
Standard connection

<details>
  <summary>Configuration file</summary>

```yaml
board: MKS TinyBee V1.0
name: OpenPnP
meta: By POE

kinematics:
  corexy:

stepping:
  engine: I2S_STATIC
  idle_ms: 0
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  x:
    # X
    steps_per_mm: 80.00
    max_rate_mm_per_min: 25000.000
    acceleration_mm_per_sec2: 2500.000
    max_travel_mm: 400.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2
        disable_pin: I2SO.0

  y:
    # Y
    steps_per_mm: 80.00
    max_rate_mm_per_min: 25000.000
    acceleration_mm_per_sec2: 2500.000
    max_travel_mm: 400.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.32
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.4
        direction_pin: I2SO.5
        disable_pin: I2SO.3

  z:
    # Z
    steps_per_mm: 8.888
    max_rate_mm_per_min: 25000.000
    acceleration_mm_per_sec2: 2500.000
    max_travel_mm: 360.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.22
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.7
        direction_pin: I2SO.8
        disable_pin: I2SO.6

 a:
   # E0
   steps_per_mm: 8.888
   max_rate_mm_per_min: 25000.000
   acceleration_mm_per_sec2: 2500.000
   max_travel_mm: 360.000
   soft_limits: false
   homing:
     cycle: 1
     positive_direction: false
     mpos_mm: 0.000
     feed_mm_per_min: 1000.000
     seek_mm_per_min: 5000.000
     settle_ms: 500
     seek_scaler: 1.100
     feed_scaler: 1.100

   motor0:
     limit_neg_pin: gpio.35
     hard_limits: false
     pulloff_mm: 2.000
     stepstick:
       step_pin: I2SO.10
       direction_pin: I2SO.11:low
       disable_pin: I2SO.9

 b:
   # E1
   steps_per_mm: 8.888
   max_rate_mm_per_min: 25000.000
   acceleration_mm_per_sec2: 2500.000
   max_travel_mm: 360.000
   soft_limits: false
   homing:
     cycle: 0
     positive_direction: false
     mpos_mm: 0.000
     feed_mm_per_min: 1000.000
     seek_mm_per_min: 5000.000
     settle_ms: 500
     seek_scaler: 1.100
     feed_scaler: 1.100

   motor0:
     limit_neg_pin: gpio.2
     hard_limits: false
     pulloff_mm: 1.000
     stepstick:
       step_pin: I2SO.13
       direction_pin: I2SO.14
       disable_pin: I2SO.12

i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  # EXP1 BTN_ENC
  macro0_pin: gpio.4:low:pu
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0: $SD/Run=lasertest.gcode
  macro1: $SD/Run=home.gcode
  macro2:
  macro3:

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

#probe:
#  pin: gpio.2
#  check_mode_start: true

Laser:
  pwm_hz: 5000
  # EXP1 BTN_ENC
  output_pin: gpio.13
  # FAN1
  enable_pin: I2SO.16
  disable_with_s0: false
  s0_with_disable: false
  tool_num: 0
  speed_map: 0=0.000% 0=12.500% 1700=100.000%
# 135=0mA 270=5mA 400=10mA 700=16mA
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: false

 # USB  TX0(1)  RX0(3)
 # J3-> TX2(17) RX2(16)
 # J1-> I2SO.23 I2SO.22
 # TH1(36)        TH2(34)        THB(39)
 # HE0(I2SO.17)   HE1(I2SO.18)   HBED(I2SO.16)
 # FAN1(I2SO.19)  FAN2(I2SO.20)
 #                   EXP1                                   EXP2
 #(BEEPER) I2SO.21 | 1  2 | 13 (BTN_ENC)    (SPI MISO) 19 | 1  2 | 18 (SPI SCK)
 #    (LCD_EN)  21 | 3  4 |  4 (LCD_RS)      (BTN_EN1) 14 | 3  4 |  5 (SPI CS)
 #    (LCD_D4)   0 | 5  6   16 (LCD_D5)      (BTN_EN2) 12 | 5  6   23 (SPI MOSI)
 #    (LCD_D6)  15 | 7  8 | 17 (LCD_D7)      (SPI_DET) 34 | 7  8 | RESET
 #             GND | 9 10 | 5V                        GND | 9 10 | 3.3V
```

</details>

<details>
  <summary>Startup Messages</summary>

```text
$ss
[MSG:INFO: FluidNC v3.0.x (noGit)]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:ERR: Skipping key a indent 1 this indent 0]
[MSG:ERR: Skipping key steps_per_mm indent 3 this indent 0]
[MSG:ERR: Skipping key max_rate_mm_per_min indent 3 this indent 0]
[MSG:ERR: Skipping key acceleration_mm_per_sec2 indent 3 this indent 0]
[MSG:ERR: Skipping key max_travel_mm indent 3 this indent 0]
[MSG:ERR: Skipping key soft_limits indent 3 this indent 0]
[MSG:ERR: Skipping key homing indent 3 this indent 0]
[MSG:ERR: Skipping key cycle indent 5 this indent 0]
[MSG:ERR: Skipping key positive_direction indent 5 this indent 0]
[MSG:ERR: Skipping key mpos_mm indent 5 this indent 0]
[MSG:ERR: Skipping key feed_mm_per_min indent 5 this indent 0]
[MSG:ERR: Skipping key seek_mm_per_min indent 5 this indent 0]
[MSG:ERR: Skipping key settle_ms indent 5 this indent 0]
[MSG:ERR: Skipping key seek_scaler indent 5 this indent 0]
[MSG:ERR: Skipping key feed_scaler indent 5 this indent 0]
[MSG:ERR: Skipping key motor0 indent 3 this indent 0]
[MSG:ERR: Skipping key limit_neg_pin indent 5 this indent 0]
[MSG:ERR: Skipping key hard_limits indent 5 this indent 0]
[MSG:ERR: Skipping key pulloff_mm indent 5 this indent 0]
[MSG:ERR: Skipping key stepstick indent 5 this indent 0]
[MSG:ERR: Skipping key step_pin indent 7 this indent 0]
[MSG:ERR: Skipping key direction_pin indent 7 this indent 0]
[MSG:ERR: Skipping key disable_pin indent 7 this indent 0]
[MSG:ERR: Skipping key b indent 1 this indent 0]
[MSG:ERR: Skipping key steps_per_mm indent 3 this indent 0]
[MSG:ERR: Skipping key max_rate_mm_per_min indent 3 this indent 0]
[MSG:ERR: Skipping key acceleration_mm_per_sec2 indent 3 this indent 0]
[MSG:ERR: Skipping key max_travel_mm indent 3 this indent 0]
[MSG:ERR: Skipping key soft_limits indent 3 this indent 0]
[MSG:ERR: Skipping key homing indent 3 this indent 0]
[MSG:ERR: Skipping key cycle indent 5 this indent 0]
[MSG:ERR: Skipping key positive_direction indent 5 this indent 0]
[MSG:ERR: Skipping key mpos_mm indent 5 this indent 0]
[MSG:ERR: Skipping key feed_mm_per_min indent 5 this indent 0]
[MSG:ERR: Skipping key seek_mm_per_min indent 5 this indent 0]
[MSG:ERR: Skipping key settle_ms indent 5 this indent 0]
eg_pin indent 5 this indent 0]
[MSG:ERR: Skipping key hard_limits indent 5 this indent 0]
[MSG:ERR: Skipping key pulloff_mm indent 5 this indent 0]
[MSG:ERR: Skipping key stepstick indent 5 this indent 0]
[MSG:ERR: Skipping key step_pin indent 7 this indent 0]
[MSG:ERR: Skipping key direction_pin indent 7 this indent 0]
[MSG:ERR: Skipping key disable_pin indent 7 this indent 0]
[MSG:ERR: Skipping key b indent 1 this indent 0]
[MSG:ERR: Skipping key steps_per_mm indent 3 this indent 0]
[MSG:ERR: Skipping key max_rate_mm_per_min indent 3 this indent 0]
[MSG:ERR: Skipping key acceleration_mm_per_sec2 indent 3 this indent 0]
[MSG:ERR: Skipping key max_travel_mm indent 3 this indent 0]
[MSG:ERR: Skipping key soft_limits indent 3 this indent 0]
[MSG:ERR: Skipping key homing indent 3 this indent 0]
[MSG:ERR: Skipping key cycle indent 5 this indent 0]
[MSG:ERR: Skipping key positive_direction indent 5 this indent 0]
[MSG:ERR: Skipping key mpos_mm indent 5 this indent 0]
[MSG:ERR: Skipping key feed_mm_per_min indent 5 this indent 0]
[MSG:ERR: Skipping key seek_mm_per_min indent 5 this indent 0]
[MSG:ERR: Skipping key settle_ms indent 5 this indent 0]
[MSG:ERR: Skipping key motor0 indent 3 this indent 0]
[MSG:ERR: Skipping key limit_neg_pin indent 5 this indent 0]
[MSG:ERR: Skipping key hard_limits indent 5 this indent 0]
[MSG:ERR: Skipping key pulloff_mm indent 5 this indent 0]
[MSG:ERR: Skipping key stepstick indent 5 this indent 0]
[MSG:ERR: Skipping key step_pin indent 7 this indent 0]
[MSG:ERR: Skipping key direction_pin indent 7 this indent 0]
[MSG:ERR: Skipping key disable_pin indent 7 this indent 0]
[MSG:INFO: Machine OpenPnP]
[MSG:INFO: Board MKS TinyBee V1.0]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:0]
[MSG:INFO: Stepping:I2S_static Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:0ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,400.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33]
[MSG:INFO: Axis Y (0.000,400.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.4 Dir:I2SO.5 Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32]
[MSG:INFO: Axis Z (0.000,360.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.7 Dir:I2SO.8 Disable:I2SO.6]
[MSG:INFO:  Z Neg Limit gpio.22]
[MSG:INFO: macro0_pin gpio.4:low:pu]
[MSG:INFO: Kinematic system: CoreXY]
[MSG:INFO: Laser Ena:I2SO.16 Out:gpio.13 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Connecting to STA SSID:POE-Net]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.1.15]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://OpenPnP.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
ok
```

</details>

### User Interface Software

WebUI

### What happened?

I run the axis move command and the motor jerks. First it spins, then it goes back a little, then it spins again.
This was not the case with other firmware.
[Link video](https://www.youtube.com/shorts/mR8sd86xvEg)

**Comment by MitchBradley** [comment]
1. You should probably fix those indentation errors in your yaml file first.
2. I have never heard of TLC2209.  Do you mean TMC2209?
3. What exactly is "other firmware"?
4. If the drivers are TMC2209, are they set up for UART configuration or jumper-based configuration?

**Comment by MitchBradley** [comment]
5. The startup messages show "FluidNC v3.0.x (noGit)" which suggests that you compiled yourself instead of installing from a precompiled release package.  We only support precompiled versions because otherwise we do not know exactly what source you are working and what else you might have done.

**Comment by Oleg-Perevyshin** [comment]
2. Yes, the TMC2209 was wrong.
3. I tried marlin.
4. TMC2209 without UART. I only use Step, Dir, Enable and divide by 16
5. Now I'll do it right.

**Comment by bdring** [comment]
The indent problems start at the a axis. I think there is an extra space before it and the following axes.

**Comment by Oleg-Perevyshin** [comment]
<details>
  <summary>Already other errors</summary>

```cpp
$ss
[MSG:INFO: FluidNC v3.6.8]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:WARN: Ignored key axes]
[MSG:ERR: Configuration parse error on line 34: Invalid character]
[MSG:INFO: Using default configuration]
[MSG:INFO: Axes: using defaults]
[MSG:ERR: Initialization error at /stepping: I2SO bus must be configured for this stepping type]
[MSG:INFO: Configuration is invalid]
[MSG:INFO: Connecting to STA SSID:POE-Net]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.1.15]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://OpenPnP.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
ok
```

</details>


<details>
  <summary>Config</summary>

```cpp
board: MKS TinyBee
name: OpenPnP
meta: By POE Config 22.03.2023

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16

start:
  must_home: false
  deactivate_parking: false
  check_limits: true

kinematics:
  corexy:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
  segments: 12

axes:
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN

axes:
  [x:|y:|z:|a:|b:|c:]
  x:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 25000.000
    acceleration_mm_per_sec2: 2500.000
    max_travel_mm: 400.000
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      seek_mm_per_min: 5000.000
      feed_mm_per_min: 500.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: gpio.33
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2
        disable_pin: I2SO.0
  y:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 25000.000
    acceleration_mm_per_sec2: 2500.000
    max_travel_mm: 400.000
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      seek_mm_per_min: 5000.000
      feed_mm_per_min: 500.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: gpio.32
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.4
        direction_pin: I2SO.5
        disable_pin: I2SO.3
  z:
    steps_per_mm: 8.888
    max_rate_mm_per_min: 25000.000
    acceleration_mm_per_sec2: 2500.000
    max_travel_mm: 360.000
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      seek_mm_per_min: 1000.000
      feed_mm_per_min: 250.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: gpio.22
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.7
        direction_pin: I2SO.8
        disable_pin: I2SO.6
  a:
    steps_per_mm: 8.888
    max_rate_mm_per_min: 25000.000
    acceleration_mm_per_sec2: 2500.000
    max_travel_mm: 360.000
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      seek_mm_per_min: 1000.000
      feed_mm_per_min: 250.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.10
        direction_pin: I2SO.11
        disable_pin: I2SO.9
  b:
    steps_per_mm: 8.888
    max_rate_mm_per_min: 25000.000
    acceleration_mm_per_sec2: 2500.000
    max_travel_mm: 360.000
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      seek_mm_per_min: 1000.000
      feed_mm_per_min: 250.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.13
        direction_pin: I2SO.14
        disable_pin: I2SO.12

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  frequency_hz: 0

i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  # EXP1 BTN_ENC
  macro0_pin: gpio.4:low:pu
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0: $SD/Run=lasertest.gcode
  macro1: $SD/Run=home.gcode
  macro2:
  macro3:

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

#probe:
#  pin: gpio.2
#  check_mode_start: true

Laser:
  pwm_hz: 5000
  # EXP1 BTN_ENC
  output_pin: gpio.13
  # FAN1
  enable_pin: I2SO.16
  disable_with_s0: false
  s0_with_disable: false
  tool_num: 0
  speed_map: 0=0.000% 0=12.500% 1700=100.000%
# 135=0mA 270=5mA 400=10mA 700=16mA
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

 # USB  TX0(1)  RX0(3)
 # J3-> TX2(17) RX2(16)
 # J1-> I2SO.23 I2SO.22
 # TH1(36)        TH2(34)        THB(39)
 # HE0(I2SO.17)   HE1(I2SO.18)   HBED(I2SO.16)
 # FAN1(I2SO.19)  FAN2(I2SO.20)
 #                   EXP1                                   EXP2
 #(BEEPER) I2SO.21 | 1  2 | 13 (BTN_ENC)    (SPI MISO) 19 | 1  2 | 18 (SPI SCK)
 #    (LCD_EN)  21 | 3  4 |  4 (LCD_RS)      (BTN_EN1) 14 | 3  4 |  5 (SPI CS)
 #    (LCD_D4)   0 | 5  6   16 (LCD_D5)      (BTN_EN2) 12 | 5  6   23 (SPI MOSI)
 #    (LCD_D6)  15 | 7  8 | 17 (LCD_D7)      (SPI_DET) 34 | 7  8 | RESET
 #             GND | 9 10 | 5V                        GND | 9 10 | 3.3V
```

</details>

I don't understand anything anymore.

What am I doing wrong?

**Comment by MitchBradley** [comment]
- In your most recent config file there are two axes: sections.  There should only be one
- There is an invalid line `  [x:|y:|z:|a:|b:|c:]` that should not be present.  I'm not sure where you got that, but I can guess.  Some people use the notation `[p|q|s]` to mean "choose one of p or q or s".  Perhaps there is documentation somewhere that uses that notation without explaining it.
- You said "I run the axis move command" but you did not tell us exactly which command, so we do not know which axis or axes were affected, nor do we know which speed you were trying to move
- We need to know which UI (sender, terminal, or WebUI) you used to issue the command.  Different UIs use different commands for movement like jogs.
- The speeds and accelerations that you have configured are rather high.  It is best to start slow and test different speeds until you find what the motors can handle.  Twitching motors can be caused by too much acceleration or top speeds that are too high.

**Comment by Oleg-Perevyshin** [comment]
I got rid of the errors.
I did it like the wiki.
But the motors are not spinning at all.
I manage through a standard web interface.

<details>
  <summary>config.yaml</summary>

```yaml
# http://wiki.fluidnc.com/en/config/top_level_config_items
name: OpenPnP
board: MKS TinyBee
meta: 23.03.2023 by POE

# http://wiki.fluidnc.com/en/config/config_IO
i2so:
  bck_pin: gpio.25
  ws_pin: gpio.26
  data_pin: gpio.27

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

# http://wiki.fluidnc.com/en/config/sd_card
sdcard:
  cs_pin: gpio.5
  card_detect_pin: gpio.34

# http://wiki.fluidnc.com/en/config/axes
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN
  x:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 1500.000
    max_travel_mm: 400.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.33
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        disable_pin: I2SO.0
        step_pin: I2SO.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 400.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 5000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.32
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        disable_pin: I2SO.3
        step_pin: I2SO.4
        direction_pin: I2SO.5

  z:
    steps_per_mm: 8.888
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 180.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.22
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        disable_pin: I2SO.6
        step_pin: I2SO.7
        direction_pin: I2SO.8

  a:
    steps_per_mm: 8.888
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 360.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        disable_pin: I2SO.9
        step_pin: I2SO.10
        direction_pin: I2SO.11

  b:
    steps_per_mm: 8.888
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 360.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        disable_pin: I2SO.12
        step_pin: I2SO.13
        direction_pin: I2SO.14

# http://wiki.fluidnc.com/en/config/kinematics
kinematics:
  corexy:

# http://wiki.fluidnc.com/en/config/control
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

# http://wiki.fluidnc.com/en/config/coolant
coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

# http://wiki.fluidnc.com/en/config/probe
probe:
  pin: NO_PIN
  check_mode_start: true

# http://wiki.fluidnc.com/en/config/macros
macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

# http://wiki.fluidnc.com/en/config/user_outputs
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: I2SO.17
  digital1_pin: I2SO.18
  digital2_pin: I2SO.19
  digital3_pin: I2SO.20

# http://wiki.fluidnc.com/en/config/start_group
start:
  must_home: false
  deactivate_parking: false
  check_limits: false

# http://wiki.fluidnc.com/en/config/uart_sections
# uart2:
#   txd_pin: gpio.17
#   rxd_pin: gpio.16
#   baud: 115200
#   mode: 8N1

# USB  TX0(1)  RX0(3)
# J3-> TX2(17) RX2(16)
# J1-> I2SO.23 I2SO.22
# TH1(36)        TH2(34)        THB(39)
# HE0(I2SO.17)   HE1(I2SO.18)   HBED(I2SO.16)
# FAN1(I2SO.19)  FAN2(I2SO.20)
#                   EXP1                                   EXP2
#(BEEPER) I2SO.21 | 1  2 | 13 (BTN_ENC)    (SPI MISO) 19 | 1  2 | 18 (SPI SCK)
#    (LCD_EN)  21 | 3  4 |  4 (LCD_RS)      (BTN_EN1) 14 | 3  4 |  5 (SPI CS)
#    (LCD_D4)   0 | 5  6   16 (LCD_D5)      (BTN_EN2) 12 | 5  6   23 (SPI MOSI)
#    (LCD_D6)  15 | 7  8 | 17 (LCD_D7)      (SPI_DET) 34 | 7  8 | RESET
#             GND | 9 10 | 5V                        GND | 9 10 | 3.3V

# https://www.linuxcnc.org/docs/html/gcode/m-code.html

```

</details>

<details>
  <summary>Commands List</summary>

```
$ss
[MSG:INFO: FluidNC v3.6.8]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine OpenPnP]
[MSG:INFO: Board MKS TinyBee]
[MSG:INFO: I2SO BCK:gpio.25 WS:gpio.26 DATA:gpio.27]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:gpio.34 freq:0]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: User Digital Output:0 on Pin:I2SO.17]
[MSG:INFO: User Digital Output:1 on Pin:I2SO.18]
[MSG:INFO: User Digital Output:2 on Pin:I2SO.19]
[MSG:INFO: User Digital Output:3 on Pin:I2SO.20]
[MSG:INFO: Axis count 5]
[MSG:INFO: Axis X (0.000,400.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:I2SO.0]
[MSG:INFO:  X Neg Limit gpio.33]
[MSG:INFO: Axis Y (0.000,400.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.4 Dir:I2SO.5 Disable:I2SO.3]
[MSG:INFO:  Y Neg Limit gpio.32]
[MSG:INFO: Axis Z (0.000,180.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.7 Dir:I2SO.8 Disable:I2SO.6]
[MSG:INFO:  Z All Limit gpio.22]
[MSG:INFO: Axis A (0.000,360.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.10 Dir:I2SO.11 Disable:I2SO.9]
[MSG:INFO: Axis B (0.000,360.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.13 Dir:I2SO.14 Disable:I2SO.12]
[MSG:INFO: Kinematic system: CoreXY]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:POE-Net]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.1.15]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://OpenPnP.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
ok
```

</details>

I click on the arrows in the web interface and see in response:
```
$J=G91 G21 F2500 X10
ok
<Idle|MPos:0.000,0.000,0.000,0.000,0.000|FS:0,0|Pn:XYZ|WCO:0.000,0.000,0.000,0.000,0.000>
$J=G91 G21 F2500 Y10
ok
<Idle|MPos:0.000,0.000,0.000,0.000,0.000|FS:0,0|Pn:XYZ|Ov:100,100,100>
```

What could be the problem?
