### ISSUE TITLE
Problem: Version 3.6.8 is not working for me

### ISSUE THREAD

**Issue by Aljo003** [bdring/FluidNC#846]
### Controller Board

ESP32 WROOM 32 with TB6560 motor drivers.

### Machine Description

Laser engraver with 2 motors for Y axis and one for X axis driven with TB6560. 

### Input Circuits

```yaml
https://imgur.com/a/s3vCA2U
```

### Configuration file

```yaml
name: "ESP32 Dev Controller V4"
board: "ESP32 Dev Controller V4"

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 0
  pulse_us: 4
  disable_delay_us: 0

axes:
  x:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 3500
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 10.00
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0: #X1
      limit_neg_pin: gpio.17:high
      limit_pos_pin: gpio.5:high
      hard_limits: true
      pulloff_mm: 0.500
      standard_stepper:
        step_pin: gpio.32
        direction_pin: gpio.33
        
  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 3500
    soft_limits: false
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 10.00
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0: #Y2
      limit_neg_pin: gpio.4:high
      limit_pos_pin: gpio.16:high
      hard_limits: true
      pulloff_mm: 0.500
      standard_stepper:
        step_pin: gpio.25
        direction_pin: gpio.26
    motor1: #Y1
      limit_neg_pin: gpio.15:high
      limit_pos_pin: gpio.2:high
      hard_limits: true
      pulloff_mm: 0.500
      standard_stepper:
        step_pin: gpio.27
        direction_pin: gpio.14:low        

spi:
  miso_pin: gpio.23
  mosi_pin: gpio.22
  sck_pin: gpio.21

sdcard:
  cs_pin: gpio.19
  card_detect_pin: NO_PIN


Laser:
  pwm_hz: 5000
  output_pin: gpio.12
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 255=100.000%
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.6.8]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine ESP32 Dev Controller V4]
[MSG:INFO: Board ESP32 Dev Controller V4]
[MSG:INFO: SPI SCK:gpio.21 MOSI:gpio.22 MISO:gpio.23]
[MSG:INFO: SD Card cs_pin:gpio.19 detect:NO_PIN freq:0]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (10.000,3510.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.32 Dir:gpio.33 Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.17]
[MSG:INFO:  X Pos Limit gpio.5]
[MSG:INFO: Axis Y (10.000,3510.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.25 Dir:gpio.26 Disable:NO_PIN]
[MSG:INFO:  Y Neg Limit gpio.4]
[MSG:INFO:  Y Pos Limit gpio.16]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:gpio.27 Dir:gpio.14:low Disable:NO_PIN]
[MSG:INFO:  Y2 Neg Limit gpio.15]
[MSG:INFO:  Y2 Pos Limit gpio.2]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.12 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Connecting to STA SSID:TP-LINK_8452]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.0.107]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

FluidTerm, WebUI

### What happened?

Nothing seems to work, limit swith LED is not even turning on. When using version 3.3.1 everything is working fine. No errors given when starting machine
