### ISSUE TITLE
Dangerous safety issue

### ISSUE THREAD

**Issue by Xplode85** [bdring/FluidNC#856]
### Controller Board

xPro V5

### Machine Description

Ratrig Killerbee with RS485 controlled spindle

### Configuration file

```yaml
name: CNC_xPRO_V5_XYYZ_NC v1.2
board: CNC xPRO V5

kinematics:
  Cartesian:

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 0
  pulse_us: 4
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 1600.000
    max_rate_mm_per_min: 2400.000
    acceleration_mm_per_sec2: 400.000
    max_travel_mm: 1300.000
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 0.000
      positive_direction: false
      settle_ms: 250.000
      seek_mm_per_min: 2000.000
      feed_mm_per_min: 200.000
      seek_scaler: 1.100
      feed_scaler: 5.000
    motor0:
      limit_all_pin: gpio.35:high
      hard_limits: true
      pulloff_mm: 2.000
      tmc_5160:
        direction_pin: gpio.14:low
        step_pin: gpio.12
        run_amps: 1.800
        hold_amps: 0.500
        microsteps: 64
        stallguard: 16
        stallguard_debug: false
        run_mode: StallGuard
        homing_mode: StallGuard
        use_enable: true
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        tpfd: 4
        r_sense_ohms: 0.050
        cs_pin: gpio.17
        spi_index: 1
    motor1:
      null_motor:
  y:
    steps_per_mm: 1600.000
    max_rate_mm_per_min: 2400.000
    acceleration_mm_per_sec2: 400.000
    max_travel_mm: 1280.000
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 1284.000
      positive_direction: true
      settle_ms: 250.000
      seek_mm_per_min: 2000.000
      feed_mm_per_min: 200.000
      seek_scaler: 1.100
      feed_scaler: 5.000
    motor0:
      limit_all_pin: gpio.36:high
      hard_limits: true
      pulloff_mm: 3.400
      tmc_5160:
        direction_pin: gpio.26
        step_pin: gpio.27
        run_amps: 1.800
        hold_amps: 0.500
        microsteps: 64
        stallguard: 16
        stallguard_debug: false
        run_mode: StallGuard
        homing_mode: StallGuard
        use_enable: true
        cs_pin: NO_PIN
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        tpfd: 4
        r_sense_ohms: 0.050
        spi_index: 2
    motor1:
      limit_all_pin: gpio.34:high
      hard_limits: true
      pulloff_mm: 3.000
      tmc_5160:
        direction_pin: gpio.32
        step_pin: gpio.33
        run_amps: 1.800
        hold_amps: 0.500
        microsteps: 64
        stallguard: 16
        stallguard_debug: false
        run_mode: StallGuard
        homing_mode: StallGuard
        use_enable: true
        cs_pin: NO_PIN
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        tpfd: 4
        r_sense_ohms: 0.050
        spi_index: 3
  z:
    steps_per_mm: 1600.000
    max_rate_mm_per_min: 2400.000
    acceleration_mm_per_sec2: 400.000
    max_travel_mm: 70.000
    soft_limits: true
    homing:
      cycle: 1
      mpos_mm: 70.000
      positive_direction: true
      settle_ms: 250.000
      seek_mm_per_min: 2000.000
      feed_mm_per_min: 200.000
      seek_scaler: 1.100
      feed_scaler: 5.000
    motor0:
      limit_all_pin: gpio.39:high
      hard_limits: true
      pulloff_mm: 2.500
      tmc_5160:
        direction_pin: gpio.2
        step_pin: gpio.15
        run_amps: 1.800
        hold_amps: 0.750
        microsteps: 64
        stallguard: 16
        stallguard_debug: false
        run_mode: StallGuard
        homing_mode: StallGuard
        use_enable: true
        cs_pin: NO_PIN
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        tpfd: 4
        r_sense_ohms: 0.050
        spi_index: 4
    motor1:
      null_motor:
      
Huanyang:
  uart:
    txd_pin: gpio.4
    rxd_pin: gpio.25
    rts_pin: NO_PIN
    baud: 9600
    mode: 8N1
  speed_map: 0=0% 0=25% 6000=25% 24000=100%
  
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

control:
  safety_door_pin: gpio.16:pu
  macro1_pin: gpio.13:low:pu
  macro2_pin: gpio.0:low:pu

coolant:
  mist_pin: gpio.21
  delay_ms: 1000.000

probe:
  pin: gpio.22:low:pu
  check_mode_start: true

macros:
  startup_line0: 
  startup_line1: 
  macro0: 
  macro1: 
  macro2: 
  macro3: 

start:
  must_home: false
  check_limits: true
  deactivate_parking: false

user_outputs:
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false 
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.6.8]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine CNC_xPRO_V5_XYYZ_NC v1.2]
[MSG:INFO: Board CNC xPRO V5]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:0]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,1300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:gpio.12 Dir:gpio.14:low CS:gpio.17 Disable:NO_PIN Index:1 R:0.050]
[MSG:INFO:  X All Limit gpio.35]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (4.000,1284.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:gpio.27 Dir:gpio.26 CS:NO_PIN Disable:NO_PIN Index:2 R:0.050]
[MSG:INFO:  Y All Limit gpio.36]
[MSG:INFO:   Motor1]
[MSG:INFO:     tmc_5160 Step:gpio.33 Dir:gpio.32 CS:NO_PIN Disable:NO_PIN Index:3 R:0.050]
[MSG:INFO:  Y2 All Limit gpio.34]
[MSG:INFO: Axis Z (0.000,70.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_5160 Step:gpio.15 Dir:gpio.2 CS:NO_PIN Disable:NO_PIN Index:4 R:0.050]
[MSG:INFO:  Z All Limit gpio.39]
[MSG:INFO:   Motor1]
[MSG:INFO: X Axis driver test passed]
[MSG:INFO: Y Axis driver test passed]
[MSG:INFO: Y2 Axis driver test passed]
[MSG:INFO: Z Axis driver test passed]
[MSG:INFO: safety_door_pin gpio.16:pu]
[MSG:INFO: macro1_pin gpio.13:low:pu]
[MSG:INFO: macro2_pin gpio.0:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: UART1 Tx:gpio.4 Rx:gpio.25 RTS:NO_PIN Baud:9600]
[MSG:INFO: Huanyang Spindle  Tx:gpio.4 Rx:gpio.25 RTS:NO_PIN Baud:9600]
[MSG:INFO: Using spindle Huanyang]
[MSG:INFO: Mist coolant gpio.21]
[MSG:INFO: Probe Pin: gpio.22:low:pu]
[MSG:INFO: Connecting to STA SSID:Bygning5]
[MSG:INFO: Connecting.]
[MSG:INFO: Huanyang PD005,PD011 Freq range (100,400) Hz (6000,24000) RPM]
[MSG:INFO: Huanyang PD144 Rated RPM @ 50Hz:3000]
[MSG:INFO: Huanyang PD143 Poles:4]
[MSG:INFO: Huanyang PD014 Accel:2.000]
[MSG:INFO: Huanyang PD015 Decel:8.000]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 10.228.34.40]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

cncjs

### What happened?

While testing safety on the CNC running FluidNC i found some serious safety issues.

If a hard limit or soft limit is triggered the stepper motors loose power creating the issue of the Z axis lowering by gravity, if this happens while the spindle is running the spindle will stay running.

Here's the hole my CNC made when i trigged the hard limit while running G code, Z axis lowered by gravity and the spindle stayed running. 

![image](https://user-images.githubusercontent.com/72715336/230783939-e4cb6cd5-95e8-478b-a68d-080c3a73780a.png)

The same thing happens when doing a soft trigger.
When a hard or soft limit is triggered i would at least expect the spindle to be stopped, but prefer also all axis to stay powered with holding power.
