### ISSUE TITLE
Problem: Inconsistent behaviour with servo motors

### ISSUE THREAD

**Issue by Dominykasssx** [bdring/FluidNC#859]
### Controller Board

Custom board.

### Machine Description

I'm using external stepper drivers DM556. Stepper motors works fine for X, Y and Z axis. Servo does not work properly on any axis.

### Input Circuits

```yaml
I have 2 servo motors connected to PIN 21 and 19
```

### Configuration file

```yaml
name: "Solo robot"
board: "solo robot board"

stepping:
  engine: RMT
  idle_ms: 150
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes: 
  x:
    steps_per_mm: 50
    max_rate_mm_per_min: 800
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 900
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 150.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      limit_neg_pin: gpio.13:high
      standard_stepper:
        direction_pin: gpio.27:low
        step_pin: gpio.18

  y:
    steps_per_mm: 50
    max_rate_mm_per_min: 800
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 1200
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 150.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      limit_neg_pin: gpio.34:high
      standard_stepper:
        direction_pin: gpio.25:low
        step_pin: gpio.26

  z:
    steps_per_mm: 80
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 150
    soft_limits: true
    homing:
      cycle: 3
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 150.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      limit_neg_pin: gpio.39:high
      standard_stepper:
        direction_pin: gpio.32:low
        step_pin: gpio.33

  a:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 5.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 5.000

    motor0:
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.19
        min_pulse_us: 1000
        max_pulse_us: 2000

  b:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 5.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 5.000

    motor0:
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.21
        min_pulse_us: 1000
        max_pulse_us: 2000
```

### Startup Messages

```text
rst:0xc (SW_CPU_RESET),boot:0x16 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:12812
load:0x40080400,len:3032
entry 0x400805e4

[MSG:INFO: FluidNC v3.6.8]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:solo1.yaml]
[MSG:INFO: Machine Solo robot]
[MSG:INFO: Board solo robot board]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:150ms]
[MSG:INFO: Axis count 5]
[MSG:INFO: Axis X (150.000,1050.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.18 Dir:gpio.27:low Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.13]
[MSG:INFO: Axis Y (150.000,1350.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.26 Dir:gpio.25:low Disable:NO_PIN]
[MSG:INFO:  Y Neg Limit gpio.34]
[MSG:INFO: Axis Z (150.000,300.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.33 Dir:gpio.32:low Disable:NO_PIN]
[MSG:INFO:  Z Neg Limit gpio.39]
[MSG:INFO: Axis A (0.000,5.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     rc_servo Pin:gpio.19 Pulse Len(1000,2000 period:1048575)]
[MSG:INFO: Axis B (0.000,5.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     rc_servo Pin:gpio.21 Pulse Len(1000,2000 period:1048575)]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.6 [FluidNC v3.6.8 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
```

### User Interface Software

WebUI

### What happened?

I have a problem while trying to use RC servo motors.  I want to use 2 servo motors on A and B axis. Servos are moving very weird. For example I'm moving A axis, but B axis starts to spin too sometimes.

I do not know why my servos are not working with FluidNC correctly, I'm using 12v servos and they work just fine with ESP32 and it doesn't require signal to be 0-12V or similar. I'm using external power source of 12V. Ground and Signal is connected to ESP32

Maybe my config is wrong? 

I already tried to change value of idle_ms and remove it completely. Change pwm_hz, steps_per_mm. Configure those Servo motors on X, Y or Z axis. Nothing helped

Problem video: https://youtu.be/33M7h_5wbLg

### Other Information

I trought maybe my servo motors are connected wrong or something bad with wiring. So I tested my servo motors with simple sketch:
```
#include <WiFi.h>
#include <Servo.h>

Servo myservo; 

// GPIO the servo is attached to
static const int servoPin = 21;

const char* ssid     = "SSID";
const char* password = "PASS";

WiFiServer server(80);

String header;

String valueString = String(5);
int pos1 = 0;
int pos2 = 0;

unsigned long currentTime = millis();
unsigned long previousTime = 0; 
const long timeoutTime = 2000;

void setup() {
  Serial.begin(115200);

  myservo.attach(servoPin); 

  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected.");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  server.begin();
}

void loop(){
  WiFiClient client = server.available();  

  if (client) {                           
    currentTime = millis();
    previousTime = currentTime;
    Serial.println("New Client.");          
    String currentLine = "";               
    while (client.connected() && currentTime - previousTime <= timeoutTime) {
      currentTime = millis();
      if (client.available()) {            
        char c = client.read();             
        Serial.write(c);                    
        header += c;
        if (c == '\n') {                   
          // if the current line is blank, you got two newline characters in a row.
          // that's the end of the client HTTP request, so send a response:
          if (currentLine.length() == 0) {
            // HTTP headers always start with a response code (e.g. HTTP/1.1 200 OK)
            // and a content-type so the client knows what's coming, then a blank line:
            client.println("HTTP/1.1 200 OK");
            client.println("Content-type:text/html");
            client.println("Connection: close");
            client.println();
            client.println("<!DOCTYPE html><html>");
            client.println("<head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
            client.println("<link rel=\"icon\" href=\"data:,\">");
            client.println("<style>body { text-align: center; font-family: \"Trebuchet MS\", Arial; margin-left:auto; margin-right:auto;}");
            client.println(".slider { width: 300px; }</style>");
            client.println("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>");
                     
            client.println("</head><body><h1>ESP32 with Servo</h1>");
            client.println("<p>Position: <span id=\"servoPos\"></span></p>");          
            client.println("<input type=\"range\" min=\"0\" max=\"180\" class=\"slider\" id=\"servoSlider\" onchange=\"servo(this.value)\" value=\""+valueString+"\"/>");
            
            client.println("<script>var slider = document.getElementById(\"servoSlider\");");
            client.println("var servoP = document.getElementById(\"servoPos\"); servoP.innerHTML = slider.value;");
            client.println("slider.oninput = function() { slider.value = this.value; servoP.innerHTML = this.value; }");
            client.println("$.ajaxSetup({timeout:1000}); function servo(pos) { ");
            client.println("$.get(\"/?value=\" + pos + \"&\"); {Connection: close};}</script>");
           
            client.println("</body></html>");     
            
            if(header.indexOf("GET /?value=")>=0) {
              pos1 = header.indexOf('=');
              pos2 = header.indexOf('&');
              valueString = header.substring(pos1+1, pos2);
              
              myservo.write(valueString.toInt());
              Serial.println(valueString); 
            }         
            client.println();
            break;
          } else {
            currentLine = "";
          }
        } else if (c != '\r') { 
          currentLine += c; 
        }
      }
    }
    header = "";
    client.stop();
    Serial.println("Client disconnected.");
    Serial.println("");
  }
}
```

And it worked just fine without any lagging or delay.

Video: https://youtube.com/shorts/PDRU53byrSg

So what can be wrong with my configuration?

**Comment by bdring** [comment]
Try changing idle_ms to 255

**Comment by Dominykasssx** [comment]
> Try changing idle_ms to 255

Already tried. didn't helped.

**Comment by bdring** [comment]
Was the video taken with `idle_ms: 255` ?

**Comment by Dominykasssx** [comment]
Video was taken with `idle_ms: 150`. But I already tested and testing now with 255.

Not really understand what happining... Sometimes I try to move A or B axis, and X, Y or Z starts to move. Why?

Video WebUI example: https://youtu.be/SiKnWTKoyTk

**Comment by bdring** [comment]
Can you send a photo of your controller?

**Comment by Dominykasssx** [comment]
Servo and stepper motors pinout

![image](https://user-images.githubusercontent.com/50581706/231846790-3b9a01c5-4c3f-43c9-9d7b-f65544645362.png)

S1 - Servo1
S2 - Servo2

**Comment by Prelo96** [comment]
The stepper drivers went creazy couse the low voltage of the logic, dm556 need 4/5V mininum for the logic.
U need to amplify the dir ena and pulse signals from 0÷3.3V to 0÷5V

**Comment by bdring** [comment]
Thanks for letting me know that. My test is easier if use a 6 pack and an RC Servo module. That uses I2SO_Stream steps instead of your RMT.

It sounds like the steppers motors are not related to this issue.

I just tested about 100 moves on A and it never caused B to move. Same with B moves.

Can you compile and load the the devt branch? It allows you to set the servo update interval with a `timer_ms:` setting. The default is 75, but 20 would be better for servos.

```yaml
    motor0:
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.4
        min_pulse_us: 1000
        max_pulse_us: 2000
        timer_ms: 20
 ```
