### ISSUE TITLE
Problem: MKS DLC32 V2.1 cannot open Config after wrong flash Firmware

### ISSUE THREAD

**Issue by Jet-A1** [bdring/FluidNC#872]
### Controller Board

MKS DLC32 V2.1

### Machine Description

Sculpfun S10 modified. 2 Belt driven Axes X, Y. 10W Diode Laser Modul TTL driven, fixed Focus. No Z Axes. 

### Configuration file

```yaml
# Basic configuration file for X/Y Laser using GT2 belts 1.8ºNEMA motors
# at 16 microSteps and 16 Tooth pulleys

board: MKS-DLC32 V2.1
name: 3dpBurner3
meta: villamany 30/Jan/2023

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 100
    max_rate_mm_per_min: 16000
    acceleration_mm_per_sec2: 1500
    max_travel_mm: 895
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 16000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36:low
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2:low

  y:
    steps_per_mm: 100
    max_rate_mm_per_min: 16000
    acceleration_mm_per_sec2: 1500
    max_travel_mm: 880
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 16000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35:low
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6:high
 
  z:
    steps_per_mm: 80
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 80.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.34
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4
        
i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  cs_pin: gpio.15
  card_detect_pin: NO_PIN
#  card_detect_pin: gpio.39
  
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

#probe:
#  pin: gpio.22
#  check_mode_start: true

Laser:
  pwm_hz: 5000
  output_pin: gpio.32
  disable_with_s0: false
  s0_with_disable: false
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
#PWM:
#  direction_pin: NO_PIN
#  spinup_ms: 1000
#  spindown_ms: 1000
  
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  #Beeper connector. Command: "M62 P0" turn beeper On. 
  #"G4 P0.5" wait for 0.5s. "M63 P0" turn beeper OFF
  digital0_pin: I2SO.7
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: false


#MKS DLC32 v2.1 pinMap

# X- gpio.36
# SD_DET gpio.39
# Z- gpio.34
# Y- gpio.35
# SPINDLE PWM gpio.32
# LCD_RS gpio.33
# LCD_CS_INV gpio.25
# LCD_TOUCH_CS_INV gpio.26
# LCD_RST_INV gpio.27
# SD_SCK gpio.14
# SD_DO gpio.12
# SD_DI gpio.13
# SD_CS gpio.15
# I2C_SDA gpio.0
# I2C_SCL gpio.4
# I2S_BCK gpio.16
# I2S_WS gpio.17
# LCD_EN_INV gpio.5
# LCD_SCK gpio.18
# LCD_MISO gpio.19
# I2S_DATA gpio.21
# RXD0 gpio.3
# TXD0 gpio.1
# Probe gpio.22
# LCD_MOSI gpio.23

# XYZ_EN I2SO.0
# X_STEP I2SO.1
# X_DIR I2SO.2
# Z_STEP I2SO.3
# Z_DIR I2SO.4
# Y_STEP I2SO.5
# Y_DIR I2SO.6
# BEEPER I2SO.7
```

### Startup Messages

```text
$ss
[MSG:INFO: FluidNC v3.6.8]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:WARN: Cannot open configuration file:MKS_DLC32_V21_laser.yaml]
[MSG:INFO: Using default configuration]
[MSG:INFO: Axes: using defaults]
[MSG:INFO: Machine Default (Test Drive)]
[MSG:INFO: Board None]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
ok
```

### User Interface Software

Lightburn, GRBL

### What happened?

The first time insatlling Fluidnc i did after erase.bat the install-fs.bat, witch broke up with Error.

I did today the following:

-Start Controller with 12v wait 3 sec. than connect USB. Power Supply is an 750W PC Power Supply. Computer is Windows 64 22H2 all Updates done.
-Then start Erase.bat from fluidnc-v3.6.8-win64 Screenshot
-Switch Power off and disconnect USB, wait 10 sec.
-Switch Power on wait 3 sec. connect USB
-Start install-wifi.bat from fluidnc-v3.6.8-win64 Screenshot
-Get Warn MSG could not open Configuration

### Other Information

![Screenshot (3)](https://user-images.githubusercontent.com/22130877/233910071-87e362f4-3630-4175-8513-715519b4e891.png)
![Screenshot (4)](https://user-images.githubusercontent.com/22130877/233910082-c460e42c-7b89-44d4-ad33-eb79e3c55f0a.png)
![Screenshot (5)](https://user-images.githubusercontent.com/22130877/233910089-53bd9e4b-7dd6-4482-b304-57824f875ddc.png)
![Screenshot (6)](https://user-images.githubusercontent.com/22130877/233910094-e32acca4-0380-45cb-bde8-e5e6e5640a91.png)
![Screenshot (7)](https://user-images.githubusercontent.com/22130877/233910098-44f6220d-925b-457a-99ee-a407cdf63c95.png)
![Screenshot (8)](https://user-images.githubusercontent.com/22130877/233910106-12ca5c8b-c8ae-4974-afca-0866ab8e1286.png)
![Screenshot (9)](https://user-images.githubusercontent.com/22130877/233910127-4ea28e63-af74-4277-8d0c-14d52900bb00.png)
![Screenshot (10)](https://user-images.githubusercontent.com/22130877/233910138-18744248-1088-4d60-8f77-1ed3d4ce32f7.png)
![Screenshot (11)](https://user-images.githubusercontent.com/22130877/233910143-bde08590-f15c-4ff3-95a8-2acc609c55bb.png)
![Screenshot (12)](https://user-images.githubusercontent.com/22130877/233910150-18311f55-7449-41b2-b76e-4ee5812fbff2.png)
![Screenshot (13)](https://user-images.githubusercontent.com/22130877/233910159-a5394a82-a18e-470f-8c19-8d81b45b3111.png)
![Screenshot (14)](https://user-images.githubusercontent.com/22130877/233910165-3c2c25d5-3c63-4d37-b3f9-c7e9906c38d9.png)
![Screenshot (15)](https://user-images.githubusercontent.com/22130877/233910181-3e8e3169-8acc-4873-8
![Screenshot (16)](https://user-images.githubusercontent.com/22130877/233910189-ccc6f05f-c126-4c21-877b-a7c0560a36c5.png)
966-8a5fac211198.png)
![Screenshot (17)](https://user-images.githubusercontent.com/22130877/233910219-c92cbbe1-360d-43df-97f7-1faba4bbb133.png)
![Screenshot (18)](https://user-images.githubusercontent.com/22130877/233910226-629e3aaf-58a7-4925-a499-c02da8
![Screenshot (19)](https://user-images.githubusercontent.com/22130877/233910233-25d26a2c-d247-401a-baa7-9ec381a7dad7.png)
76043
![Screenshot (20)](https://user-images.githubusercontent.com/22130877/233910254-dfb3f770-fe95-44eb-8547-fea5265065e2.png)
2.png)
![Screenshot (21)](https://user-images.githubusercontent.com/22130877/233910269-6155d465-c759-46ef-a529-ff7e53a6
![Screenshot (22)](https://user-images.githubusercontent.com/22130877/233910287-62446a91-7a8f-48eb-a46c-5d227ff44c2b.png)
b01d.png)
![Screenshot (23)](https://user-images.githubusercontent.com/22130877/233910301-29be768f-73ef-421e-a204-0e3fd3
![Screenshot (24)](https://user-images.githubusercontent.com/22130877/233910316-778cada1-dd2a-4480-82ed-200b49d679a2.png)
a29674.png)
![Screenshot (25)](https://user-images.githubusercontent.com/22130877/233910328-64547cb0-0c90-4476-9773-d4bc8cc2cc28.png)
![Screenshot (26)](https://user-images.githubusercontent.com/22130877/233910340-688274e4-731a-4555-9c3d-3fc6e95e8f7c.png)
![Screenshot (27)](https://user-images.githubusercontent.com/22130877/233910350-10b4a4ff-0d7d-4fa4-b7dc-12b2735d11d5.png)
