### ISSUE TITLE
Problem: Realtime Macro

### ISSUE THREAD

**Issue by April1004** [bdring/FluidNC#897]
### Controller Board

ESP32-WROOM-32

### Machine Description

ESP32-WROOM-32 with FluidNC on it. Connected via USB to a Linx laptop. Not connected to any other hardware than jumper wires.

### Configuration file

```yaml
control:
  safety_door_pin: NO_PIN
  feed_hold_pin: NO_PIN
  reset_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.5:low:pu
  macro1_pin: gpio.18:low:pu
  macro2_pin: gpio.19:low:pu
  macro3_pin: gpio.21:low:pu

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:f>
  macro2:#f<
  macro3:
```

### Startup Messages

```text
MSG:INFO: FluidNC v3.6.5]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.1-1-gb8050b365e]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine Eriks cnc]
[MSG:INFO: Board Eriks cnc]
[MSG:INFO: SPI not defined]
[MSG:INFO: No SD Card CS Pin]
[MSG:INFO: See http://wiki.fluidnc.com/en/config/sd_card#sdfallbackcs-access-sd-without-a-config-file]
[MSG:INFO: Stepping:RMT Pulse:10us Dsbl Delay:0us Dir Delay:10us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.12:low Dir:gpio.26:low Disable:NO_PIN]
[MSG:INFO:  X All Limit gpio.0:pu]
[MSG:INFO: Axis Y (10.000,1010.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.14:low Dir:gpio.25:low Disable:NO_PIN]
[MSG:INFO:  Y All Limit gpio.2:pu]
[MSG:INFO: Axis Z (-990.000,10.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.27:low Dir:gpio.33:low Disable:NO_PIN]
[MSG:INFO: macro0_pin gpio.5:low:pu]
[MSG:INFO: macro1_pin gpio.18:low:pu]
[MSG:INFO: macro2_pin gpio.19:low:pu]
[MSG:INFO: macro3_pin gpio.21:low:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Probe Pin: gpio.4:low:pu]
[MSG:INFO: WiFi is disabled]
ok
```

### User Interface Software

FluidTerm

### What happened?

First of all:
Thank you for this awesome FluidNC-Project :).

I would like to adjust the feedrate while running a job with hardware buttons.

I shorted the configured macro pins to GND for a second. One after another.

I do that while there is a Gcode command running. For example: G1X1000

On shorting a macro-pin to GND I get:
_[MSG:ERR: Macro can only be used in idle state]_
No matter which macro pin I use.

The Feedrate is not overridden as indicated by:
<Run|MPos:-179.161,0.000,0.000|FS:100,0|Pn:XY|Ov:100,100,100>

How is a real-time command macro supposed to look in the config file?
It would be nice to have an example in http://wiki.fluidnc.com/config/macros#config-example

Or am I facing another problem here?

Many thanks in advance
