### ISSUE TITLE
Unable to connect with Lightburn GRBL (1.1f or later)

### ISSUE THREAD

**Issue by Murugesh-Hobbyist** [bdring/FluidNC#898]
### Controller Board

ESP32 Dev Module

![Screenshot - 18-05-2023 , 1 55 46 PM](https://github.com/bdring/FluidNC/assets/75427145/22824c32-e19a-47e5-9b38-bd1b28c82b7b)

### Machine Description

Neema-23 with DM556T

### Configuration file

```yaml
name: "ESP32 Dev Controller V4"
board: "ESP32 Dev Controller V4"

stepping:
  engine: RMT
  idle_ms: 0
  dir_delay_us: 1
  pulse_us: 4
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.13:high

  x:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 220
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 10
      seek_mm_per_min: 500
      feed_mm_per_min: 300
      settle_ms: 250
      seek_scaler: 1.5
      feed_scaler: 1.5
    
    motor0:
      limit_all_pin: gpio.17:low:pu
      pulloff_mm: 10.000
      stepstick:
        direction_pin: gpio.14
        step_pin: gpio.12
    motor1:
      null_motor:

  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 220
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 10
      seek_mm_per_min: 500
      feed_mm_per_min: 300
      settle_ms: 250
      seek_scaler: 1.5
      feed_scaler: 1.5

    motor0:
      limit_all_pin: gpio.4:low:pu
      pulloff_mm: 10.000
      stepstick:
        direction_pin: gpio.15
        step_pin: gpio.26
    motor1:
      null_motor:

  z:
    steps_per_mm: 80
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 220
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 10
      seek_mm_per_min: 500
      feed_mm_per_min: 300
      settle_ms: 250
      seek_scaler: 1.5
      feed_scaler: 1.5

    motor0:
      limit_all_pin: gpio.16:low:pu
      pulloff_mm: 10.000
      stepstick:
        direction_pin: gpio.33
        step_pin: gpio.27
    motor1:
      null_motor:

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: gpio.25
  mist_pin:  gpio.21

        
probe:
  pin: gpio.32:low:pu

PWM:
  pwm_hz: 5000
  output_pin: gpio.2
  enable_pin: gpio.22
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0% 255=100%
```

### Startup Messages

```text
Waiting for connection...
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
Grbl 3.7 [FluidNC v3.7.0 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
[MSG:DBG:  X All Limit 0]
[MSG:DBG:  Z All Limit 0]
[MSG:DBG:  Y All Limit 0]
G0
G0
G0
G0
G0
G0
G0
G0
G0
G0
G0
G0
```

### User Interface Software

Light Burn

### What happened?

Hi Team,

in doument -> [Github_issue.docx](https://github.com/bdring/FluidNC/files/11522307/Github_issue.docx)

I have installed Fluid NC in ESP32 board pictured below.

![Screenshot - 18-05-2023 , 1 55 46 PM](https://github.com/bdring/FluidNC/assets/75427145/20c44046-4b99-4bf1-ba11-0033445aa0d1)

Uploaded the mentioned yaml file.
In Light Burn, we have 3 options of GRBL.

![Screenshot - 20-05-2023 , 4 42 21 PM](https://github.com/bdring/FluidNC/assets/75427145/d52582ad-9538-426f-9197-7eb7f47e3024)

Among them, GRBL-M3 (1.1e or earlier) works fine.
Below are the screen shots:

![Screenshot - 20-05-2023 , 11 20 35 AM](https://github.com/bdring/FluidNC/assets/75427145/41d9dc33-486e-464a-b2e3-cd2a04231806)

![Screenshot - 20-05-2023 , 11 21 41 AM](https://github.com/bdring/FluidNC/assets/75427145/b5822545-facb-4285-ac3c-d9e048ecdc02)

But as am trying to build laser machine, I want to achieve a laser mode functionality of M4 Dynamic Laser Power Mode which is achievable in GRBL (1.1f or later). 

https://docs.lightburnsoftware.com/CommonGrblSetups.html

![Screenshot - 20-05-2023 , 11 32 07 AM](https://github.com/bdring/FluidNC/assets/75427145/8fe5e2ca-2679-4d48-b5b5-3d61501bb4eb)
 

https://github.com/gnea/grbl/blob/master/doc/markdown/laser_mode.md

![Screenshot - 20-05-2023 , 4 57 09 PM](https://github.com/bdring/FluidNC/assets/75427145/e51c12b5-6cd5-41bf-a865-fbed78632cf7)

So I tried using the GRBL (1.1f or later).

![Screenshot - 20-05-2023 , 4 38 59 PM](https://github.com/bdring/FluidNC/assets/75427145/f3ebd7a1-6161-4c2b-8eb4-05fc66d88de2)

But am unable to connect with the Fluid NC. Loads firmware and start generating G0 command irrespective of any inputs.

![Screenshot - 20-05-2023 , 11 19 30 AM](https://github.com/bdring/FluidNC/assets/75427145/9aa927f4-e9d1-4175-9838-8591ad536f36)

Please help me to connect with GRBL (1.1f or later) in Light Burn with this ESP32 - Fluid NC.
