### ISSUE TITLE
Problem: RC servo not working on S3 using v3.7.0

### ISSUE THREAD

**Issue by arksega** [bdring/FluidNC#903]
### Controller Board

esp32-s3-wroom DevKitC-1

### Machine Description

TMC2208 pen controller

### Input Circuits

_No response_

### Configuration file

```yaml
name: "TMC2209 ZenXY"            
board: "FluidNC Pen/Laser 2209"      
                                                           
stepping:             
  engine: RMT
  idle_ms: 255
  dir_delay_us: 2              
  pulse_us: 2       
  disable_delay_us: 0
                                                           
axes:          
                                                           
  x:                       
    steps_per_mm: 642.66  
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 220
    soft_limits: true
    homing:      
      cycle: 1       
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 3000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      null_motor:
    motor1:
      null_motor:
  y:
    steps_per_mm: 1276.39
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 220
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 3000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      null_motor:
    motor1:
      null_motor:

  z:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 5.000
    soft_limits: false
    homing:
      cycle: 3
      xpositive_direction: true
      mpos_mm: 5.000

    motor0:
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.13
        min_pulse_us: 1000
        max_pulse_us: 2000
        timer_ms: 20

    motor1:
      null_motor:
```


### Startup Messages

```text
ESP-ROM:esp32s3-20210327                                                                                                                                                                                                                    
Build:Mar 27 2021                                                                                                                                                                                                                           
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)                                                                                                                                                                                            
SPIWP:0xee                                                                                                                                                                                                                                  
mode:DIO, clock div:1                                                                                                                                                                                                                       
load:0x3fce3808,len:0x44c                                                                                                                                                                                                                   
load:0x403c9700,len:0xbe4                                                                                                                                                                                                                   
load:0x403cc700,len:0x2a38                                                                                                                                                                                                                  
entry 0x403c98d4                                                                                                                                                                                                                            
E (305) esp_core_dump_flash: No core dump partition found!                                                                                                                                                                                  
E (305) esp_core_dump_flash: No core dump partition found!                                                                                                                                                                                  
                                                                                                                                                                                                                                            
[MSG:INFO: FluidNC v3.7.0]                                                                                                                                                                                                                  
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]                                                                                                                                                                                                  
[MSG:DBG: Spiffs mount failed: ESP_FAIL]                                                                                                                                                                                                    
[MSG:INFO: Local filesystem type is littlefs]                                                                                                                                                                                               
[MSG:INFO: Configuration file:config.yaml]                                                                                                                                                                                                  
[MSG:WARN: Ignored key xpositive_direction]                                                                                                                                                                                                 
[MSG:DBG: Running after-parse tasks]                                                                                                                                                                                                        
[MSG:DBG: Checking configuration]                                                                                                                                                                                                           
[MSG:INFO: Machine TMC2209 ZenXY]                                                                                                                                                                                                           
[MSG:INFO: Board FluidNC Pen/Laser 2209]                                                                                                                                                                                                    
[MSG:DBG: SPI not defined]                                                                                                                                                                                                                  
[MSG:DBG: See http://wiki.fluidnc.com/en/config/sd_card#sdfallbackcs-access-sd-without-a-config-file]                                                                                                                                       
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:2us Idle Delay:255ms]                                                                                                                                                            
[MSG:INFO: Axis count 3]                                                                                                                                                                                                                    
[MSG:INFO: Axis X (0.000,220.000)]                                                                                                                                                                                                          
[MSG:INFO:   Motor0]                                                                                                                                                                                                                        
[MSG:INFO:   Motor1]                                                                                                                                                                                                                        
[MSG:INFO: Axis Y (0.000,220.000)]                                                                                                                                                                                                          
[MSG:INFO:   Motor0]                                                                                                                                                                                                                        
[MSG:INFO:   Motor1]                                                                                                                                                                                                                        
[MSG:INFO: Axis Z (0.000,5.000)]                                                                                                                                                                                                            
[MSG:INFO:   Motor0]                                                                                                                                                                                                                        
E (96) ledc: freq_hz=50 duty_resolution=20                                                                                                                                                                                                  
[MSG:ERR: ledc timer setup failed]                                                                                                                                                                                                          
                                                                                                                                                                                                                                            
abort() was called at PC 0x420d531b on core 1                                                                                                                                                                                               
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
Backtrace: 0x40378afa:0x3fcebd00 0x4037e2c5:0x3fcebd20 0x403857d1:0x3fcebd40 0x420d531b:0x3fcebdc0 0x420d5362:0x3fcebde0 0x420d56cf:0x3fcebe00 0x42003c9b:0x3fcebe20 0x420147ef:0x3fcebe90 0x4201213b:0x3fcebec0 0x4200dd0f:0x3fcebef0 0x4200d721:0x3fcebf20 0x42012bd5:0x3fcebf50 0x420469e6:0x3fcebfa0
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
ELF file SHA256: f8bb8ad7b9b642cb                                                                                                                                                                                                           
                                                                                                                                                                                                                                            
E (189) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0                                                                                                                                             
Rebooting...
```


### User Interface Software

_No response_

### What happened?

I'm building a pen machine and I'm using TMC2208 for X and Y with success using a S3, but when I include Z config with RC servo it just crashes and restart without config as you can see in the startup message.

Using the exact same commit 76bc1ff4 (v3.7.0) building for esp32 works fine, the issue seams to be only on esp32-s3 build.



### Other Information

_No response_
