### ISSUE TITLE
Problem: When running Gcode all moves xyz continue even if the RS485 spindle is reported as unresponsive(e.g. if VFD switched off or not connected). When connected the spindle speed is controllable

### ISSUE THREAD

**Issue by JohnCMBC** [bdring/FluidNC#910]
### Controller Board

MKS DLC32 V2.1

### Machine Description

Gantry router, XYYZ, external drivers DQ542MA ,Huanyang spindle - RS485 controlled using generic 485 board connected to display headers on DLC, XYZ proximity endstops and probe via 12/3.3v opto-isolator

### Configuration file

```yaml
board: MKS-DLC32 V2.1
name: Johns CNC
meta: (17-05-2023) by AJM

verbose_errors: true


kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 250
  pulse_us: 5
  dir_delay_us: 5
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: I2SO.0
  
  x:
    steps_per_mm: 800
    max_rate_mm_per_min: 2900
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 750.000
    soft_limits: true
    homing:
      feed_mm_per_min: 100
      seek_mm_per_min: 2000
      cycle: 2
      mpos_mm: 0.000
      positive_direction: false
    
    motor0:
      limit_neg_pin: gpio.36:low
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2
    motor1:
      null_motor:

  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 2900.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 750.000
    soft_limits: true
    homing:
      feed_mm_per_min: 100
      seek_mm_per_min: 2000
      cycle: 2
      mpos_mm: 0.000
      positive_direction: false
      
    motor0:
      limit_neg_pin: gpio.35:low
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6
    motor1:
      null_motor:

  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 2900.000
    acceleration_mm_per_sec2: 500.000
    max_travel_mm: 150.000
    soft_limits: true
    homing:
      feed_mm_per_min: 100
      seek_mm_per_min: 2000
      cycle: 2
      mpos_mm: 0
      positive_direction: true

    motor0:
      limit_neg_pin: gpio.34:low
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4
    motor1:
      null_motor:
      
i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  cs_pin: gpio.15
  card_detect_pin: NO_PIN
  frequency_hz: 1000000

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  
macros:
  startup_line0:
  startup_line1:
  macro0: 
  macro1:
  macro2:
  macro3:
 
coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

probe:
  pin: gpio.22
  check_mode_start: true
  
Huanyang:
  spinup_ms:10000
  spindown_ms:10000
  uart:
    txd_pin: gpio.25
    rxd_pin: gpio.33:pd
    rts_pin: gpio.26
    baud: 9600
    mode: 8N1
  modbus_id: 1
  tool_num: 0
  off_on_alarm: true
  speed_map: 0=0% 0=25% 6000=25% 24000=100%

start:
  must_home: false
```

### Startup Messages

```text
$SS
[MSG:INFO: FluidNC v3.7.0]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:MKS_DLC32_21_XYZ.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine Johns CNC]
[MSG:INFO: Board MKS-DLC32 V2.1]
[MSG:INFO: I2SO BCK:gpio.16 WS:gpio.17 DATA:gpio.21]
[MSG:INFO: SPI SCK:gpio.14 MOSI:gpio.13 MISO:gpio.12]
[MSG:INFO: SD Card cs_pin:gpio.15 detect:NO_PIN freq:1000000]
[MSG:INFO: Stepping:I2S_static Pulse:5us Dsbl Delay:0us Dir Delay:5us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable I2SO.0]
[MSG:INFO: Axis X (0.000,750.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.1 Dir:I2SO.2 Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.36:low]
[MSG:DBG:  X Neg Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (0.000,750.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.5 Dir:I2SO.6 Disable:NO_PIN]
[MSG:INFO:  Y Neg Limit gpio.35:low]
[MSG:DBG:  Y Neg Limit 1]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (-150.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     stepstick Step:I2SO.3 Dir:I2SO.4 Disable:NO_PIN]
[MSG:INFO:  Z Neg Limit gpio.34:low]
[MSG:DBG:  Z Neg Limit 1]
[MSG:INFO:   Motor1]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: UART1 Tx:gpio.25 Rx:gpio.33:pd RTS:gpio.26 Baud:9600]
[MSG:INFO: Huanyang Spindle  Tx:gpio.25 Rx:gpio.33:pd RTS:gpio.26 Baud:9600]
[MSG:INFO: Using spindle Huanyang]
[MSG:INFO: Probe Pin: gpio.22]
[MSG:INFO: Connecting to STA SSID:BlueDragon]
[MSG:INFO: Connecting.]
[MSG:INFO: Huanyang PD005,PD011 Freq range (25,400) Hz (1500,24000) RPM]
[MSG:INFO: Huanyang PD144 Rated RPM @ 50Hz:3000]
[MSG:INFO: Huanyang PD143 Poles:2]
[MSG:INFO: Huanyang PD014 Accel:10.000]
[MSG:INFO: Huanyang PD015 Decel:10.000]
[MSG:DBG: vfd_cmd_task mode:1]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.0.231]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
ok

and after FluidNC connects:

[MSG:DBG: path /index.html CT text/html]
[MSG:DBG: WebSocket 0 from 192.168.0.202 uri /]
[MSG:INFO: Channel auto report interval set to 50 ms]
[MSG:DBG: path /preferences.json CT text/html]
```

### User Interface Software

FluidNC, OpenBuildsCONTROL, ugsplatform, Candle

### What happened?

Loaded Gcode to any of the user interfaces and after setting up work co-ords, ran the file (tried more than 1).
Expected the router to move to the start location then to the safe distance from the stock, run the spindle up to speed, then proceed to cutting...
What happens is that the job continues (after G4 P10 delay) even if the VFD is unresponsive or disconnected which would result in broken endmills (I haven't actually gone this far - am still testing but have had a similar problem on the same router mechanics controlled by LinuxCNC  which was sorted by configuration/program changes). Please note I only have the hardware for one axis during testing which moves and homes correctly for X,Y and Z when configured for same.
I don't know if this is a config/Gcode/Fluid problem.

Gcode loaded:
(Post-Processor : OpenbuildsFusion360PostGrbl.cps V1.0.32)
(Units = mm)

(Drawing name : pcb trace modded v4)
(Program Name : 1001)

(1 Operation :)
(1 : 2D Contour1)
(  Tool 2: Flat End Mill 2 Flutes, Diam = 0.4mm, Len = 12.00mm)
(  Spindle : RPM = 7277)
(  Machining time : 5 min 32 sec)

G90 G94 G17
G21

(Operation 1 of 1 : 2D Contour1)
G54

G53 G0 Z-10
G0 X46.414 Y27.627
S7277 M3
G4 P10.
G0 X46.414 Y27.627 Z15 F584
Z5
G1 Z1 F195
Z-0.05
X46.416 Y27.646 F584
Y27.648
X46.419 Y27.662
...................................................
