### ISSUE TITLE
Problem: Downloading files via XModem doesn't work if configuration is broken

### ISSUE THREAD

**Issue by breiler** [bdring/FluidNC#919]
### Controller Board

Barts ESP32 CNC Dev Controller v4.1

### Machine Description

N/A

### Input Circuits

```yaml
N/A
```

### Configuration file

```yaml
name: Testconfig
board: 6 Pack
axes:
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: NO_PIN
        direction_pin: NO_PIN
        disable_pin: NO_PIN
```

### Startup Messages

```text
N/A
```

### User Interface Software

FluidTerm

### What happened?

The config that is included has a problem with the step_pin not being defined which will result in an config parse error on reboot:

```
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4
E (604) esp_core_dump_flash: N�ؽɕ�dump partition found!
E (604) esp_core_dump_flash: No core dump partition found!

[MSG:INFO: FluidNC v3.7.2-pre]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:ERR: Validation error at /axes/x/motor0/standard_stepper: Step pin must be configured.]
[MSG:ERR: Configuration is invalid]
[MSG:INFO: Using default configuration]
[MSG:INFO: Axes: using defaults]
[MSG:ERR: Configuration is invalid]
[MSG:INFO: STA SSID is not set]
[MSG:INFO: AP SSID FluidNC IP 192.168.0.1 mask 255.255.255.0 channel 1]
[MSG:INFO: AP started]
[MSG:INFO: WiFi on]
[MSG:INFO: Captive Portal Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC v3.7.2-pre (wifi) '$' for help]
[MSG:ERR: Configuration is invalid. Check boot messages for ERR's.]
```

If I want to fix this problem by first downloading the version of the config from the controller I get the error 8 (IdleError):
```
$XModem/Send=/littlefs/config.yaml
error:8
```

This is usually solved by issuing an unlock command but I then get error 152 (ConfigurationInvalid)
```
$X
error:152
```

So there is no way to retrieve the file to fix it. This is needed to get a smooth user flow in the web installer.
