### ISSUE TITLE
Problem: The workpiece zero on the visualization panel of the Tablet tab is off to the left, so the left hand side of the track is obscured.

### ISSUE THREAD

**Issue by maxcel2** [bdring/FluidNC#924]
### Controller Board

10V

### Machine Description

N/a

### Input Circuits

```yaml
N/A
```

### Configuration file

```yaml
name: "WM16 Mill"
board: "ESP32 Dev Controller V4"

control:
    safety_door_pin: gpio.27:high:pu
#

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 5
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN

  x:
    steps_per_mm: 200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 485
    homing:
      cycle: 2
      mpos_mm: 5
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.35:high
      pulloff_mm: 2
      standard_stepper:
        step_pin: gpio.13
        direction_pin: gpio.14

  y:
    steps_per_mm: 200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 150
    homing:
      cycle: 3
      mpos_mm: 5
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.34:high
      pulloff_mm: 2
      standard_stepper:
        step_pin: gpio.26
        direction_pin: gpio.25

  z:
    steps_per_mm: 200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 300
    homing:
      cycle: 1
      mpos_mm: 5
      positive_direction: true

    motor0:
      limit_pos_pin: gpio.22:high
      pulloff_mm: 5
      standard_stepper:
        step_pin: gpio.33
        direction_pin: gpio.32


spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin:  NO_PIN


probe:
  pin: gpio.21:low:pu

PWM:
  pwm_hz: 5000
  output_pin: gpio.15
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0% 2500=100%
```

### Startup Messages

```text
--- FluidTerm v1.2.0 on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] or Ctrl+Q | Upload: Ctrl+U | Reset: Ctrl+R | ClearScreen: Ctrl+W ---
Resetting MCU
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4

[MSG:INFO: FluidNC v3.7.1]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:config_nolimit.yaml]
[MSG:INFO: Machine WM16 Mill]
[MSG:INFO: Board ESP32 Dev Controller V4]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:5us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,485.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.13 Dir:gpio.14 Disable:NO_PIN]
[MSG:INFO:  X Neg Limit gpio.32:low]
[MSG:INFO: Axis Y (0.000,160.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.27 Dir:gpio.26 Disable:NO_PIN]
[MSG:INFO:  Y Pos Limit gpio.35:low]
[MSG:INFO: Axis Z (-270.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:gpio.25 Dir:gpio.33 Disable:NO_PIN]
[MSG:INFO:  Z Pos Limit gpio.34:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: 10V Spindle Ena:gpio.15:low Out:gpio.22 Dir:NO_PIN Fwd:gpio.21:low Rev:gpio.4:low Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle 10V]
[MSG:INFO: Connecting to STA SSID:TP-Link_0E2F]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.1.132]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC v3.7.1 (wifi) '$' for help]
```

### User Interface Software

WebUI

### What happened?

In the Tablet window/tab, load a GRBL file from SD card.
In the visualisation panel, lower-right, the workpiece G54 zero point is offset to the left by about 25% of the panel in one isometric view, i.e. 1/4 way in from the left-hand side of the panel. The left-hand portion of the track is not visible.
In another view, it is right down in the bottom left-hand corner.

### Other Information

[fluidnc_visualization_panel.pdf](https://github.com/bdring/Fl
![IMG_20230614_152459901_HDR](https://github.com/bdring/FluidNC/assets/35602326/421f3f17-226a-4db0-a301-c200784166d7)
uidNC/files/11746741/fluidnc_visualization_panel.pdf)
