### ISSUE TITLE
Problem: Moving too fast for Wifi to keep up streaming

### ISSUE THREAD

**Issue by anon65453** [bdring/FluidNC#930]
### Controller Board

Sculpfun S30 Pro Max 20w Laser MKS DLC32

This is an image of the exact board in use
https://diode-laser-wiki.com/wp-content/uploads/2023/03/S30-Pinout-1024x787.png

### Machine Description

Sculpfun S30 Pro Max 20w Laser with XY Extension 890mm x 900mm

### Configuration file

```yaml
board: XY-DLC32-MC V1.1
name: Sculpfun S30
meta: (06/20/2023) k. raab - S30 Pro Max 20w XY Extension - Refined Settings

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.01
verbose_errors: false
report_inches: false

start:
  must_home: false
  deactivate_parking: true
  check_limits: false

stepping:
  engine: RMT
  idle_ms: 25
  pulse_us: 10
  dir_delay_us: 0
  disable_delay_us: 0
  segments: 12

axes:
  shared_stepper_disable_pin: gpio.25
  shared_stepper_reset_pin: NO_PIN
  
  x:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 890.000
    soft_limits: true
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 3000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.000
      stepstick:
        step_pin:  gpio.27
        #change direction using direction_pin: gpio.26:low
        direction_pin: gpio.26

  y:
    steps_per_mm: 80.000
    max_rate_mm_per_min: 10000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 900.000
    soft_limits: true
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 3000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 2.000
      stepstick:
        step_pin: gpio.33
        #change direction using direction_pin: gpio.32:low
        direction_pin: gpio.32


coolant:
  flood_pin: gpio.21
  delay_ms: 0

Laser:
  pwm_hz: 1500
  output_pin: gpio.4
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: true

#user outputs can be controlled with M64 P0 (turn P0 on) and M65 P0 (turn P0 off)
#http://wiki.fluidnc.com/en/config/user_outputs
#it seems only 4 ports work at a time, but all pins work
#on command makes pin 3.3V (high), off command 0V (low)
#available pins: 2, 13, 16, 17, 19, 22
user_outputs:
#  digital0_pin: gpio.2
#  digital1_pin: gpio.13
#  digital2_pin: gpio.16
#  digital3_pin: gpio.17

#define user inputs
control:
  #all the following pins can have be assigned those pins: 
  #gpio.2:low:pu; # Pin 2, logic is active low (connected switch should pull to GND when pressed) and pull-up resistor activated
  #available pins: 2, 13, 16, 17, 19, 22
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.22:low:pu
  macro1_pin: gpio.17:low:pu
  macro2_pin: gpio.2:low:pu
  macro3_pin: gpio.16:low:pu

#executed when macro_pin is activated
macros:
  startup_line0:
  startup_line1:
  #example commands to jog the laser +-10mm for x and y
  macro0: $J=G91 G21 F1000 Y10
  macro1: $J=G91 G21 F1000 Y-10
  macro2: $J=G91 G21 F1000 X10
  macro3: $J=G91 G21 F1000 X-10
  
#if you want to connect a small display to the board, define I2C bus and oled sections
#http://wiki.fluidnc.com/en/config/displays
#this configuration uses the SDA/SCL labeled pins available on the DLC32 board.
i2c0:
   sda_pin: gpio.19
   scl_pin: gpio.13

oled:
   i2c_num: 0
   i2c_address: 60
   width: 128
   height: 64
   radio_delay_ms: 1000
```

### Startup Messages

```text
I have a photo of the startup msg, but photos are not allowed. And this is the default startup message so I didnt think to hand type it all in here. If interested let me know and I can send the image. Too bad I cannot copy and paste the text or put the image here. I actually attached it below in the main description, if you don't see it there let me know.
```

### User Interface Software

Lightburn

### What happened?

I ran a job in Lightburn and it failed, multiple times. Seems that Wifi connection is slow which causes the X axis to forget what its doing.

![startupmsg](https://github.com/bdring/FluidNC/assets/137181509/8e80b0d5-91a8-4438-8de8-d3407edfae33)

![IMG_2897](https://github.com/bdring/FluidNC/assets/137181509/bc02131d-0c91-4c87-8efd-7b10ba4940dd)

You can see here how slow the Wifi connection is compared to USB. 

This is operating over Wifi, you can see the belts shaking violently and how slow it is to frame the job.
https://youtube.com/shorts/TymS4qBxlb0

This is operating directly over USB/Serial and appears to have much smoother movement.
https://www.youtube.com/shorts/4KRMixaf-WA
