### ISSUE TITLE
Problem: Image raster is not "smooth"

### ISSUE THREAD

**Issue by Avataar120** [bdring/FluidNC#933]
### Controller Board

Custom board for a K40 laser engraver

### Machine Description

K40 laser machine

### Input Circuits

```yaml
N/A
```

### Configuration file

```yaml
name: K40_AvaShield
board: 4_Ava_Shield_8.x_XY_OLED

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 4
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN

  x:
    steps_per_mm: 78.74
    max_rate_mm_per_min: 20000.000
    acceleration_mm_per_sec2: 2000.000
    max_travel_mm: 310.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 2500.000
      settle_ms: 250.000
      seek_scaler: 1.500
      feed_scaler: 5.000

    motor0:
      limit_neg_pin: gpio.39:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 5.000
      stepstick:
        ms3_pin: I2SO.3
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0


  y:
    steps_per_mm: 78.74
    max_rate_mm_per_min: 20000.000
    acceleration_mm_per_sec2: 2000.000
    max_travel_mm: 210.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 2500.000
      settle_ms: 250.000
      seek_scaler: 1.500
      feed_scaler: 5.000

    motor0:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 5.000
      stepstick:
        ms3_pin: I2SO.7
        step_pin: I2SO.6
        direction_pin: I2SO.5:low
        disable_pin: I2SO.4

  z:
    steps_per_mm: 1000.000
    max_rate_mm_per_min: 200.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 20.000
    soft_limits: false
    homing:
      cycle: 
      positive_direction: true
      mpos_mm: 9.500
      feed_mm_per_min: 100.000
      seek_mm_per_min: 100.000
      settle_ms: 250.000
      seek_scaler: 1.500
      feed_scaler: 5.000

    motor0:
      limit_neg_pin: gpio.35:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 9.500
      stepstick:
        ms3_pin: I2SO.11
        step_pin: I2SO.10
        direction_pin: I2SO.9:low
        disable_pin: I2SO.8
    motor1:
      null_motor:

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5

i2c0:
   sda_pin: gpio.25
   scl_pin: gpio.33

oled:
   i2c_num: 0
   i2c_address: 60
   width: 128
   height: 64
   radio_delay_ms: 1000

control:
  safety_door_pin: gpio.27:low:pu
  reset_pin: gpio.12:low:pu
  feed_hold_pin: gpio.14:low:pu
  cycle_start_pin: gpio.13:low:pu

coolant:
  mist_pin: gpio.4
  delay_ms: 50.000

probe:
  pin: gpio.36:low
  check_mode_start: false

macros:
  startup_line0: 
  startup_line1: 
  macro0: 
  macro1: 
  macro2: 
  macro3: 

start:
  must_home: true
  check_limits: true
  deactivate_parking: false

user_outputs:

laser:
  tool_num: 0
  speed_map: 0=0.0% 1000=100.0%
  output_pin: gpio.15
  enable_pin: gpio.16:low
  disable_with_s0: false
  s0_with_disable: false
  pwm_hz: 15000

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
```

### Startup Messages

```text
N/A
```

### User Interface Software

Lightburn

### What happened?

When engraving a image through Lightburn, movement is "jerky"
When starting a new line, I'm expecting : 
- laser to go outside of the image by 2.5% (my overscanning setting)
- start to accelerate on X, reach target speed (350mm/s)
- Turn on and off laser according to GCODE but w/o decelerating / accelerating at each new GCODE command

What I observe : 
- laser is accelerating / deceleration at each G0 GCODE command (even if those commands are moving only on X axis at constant speed)

Do I miss something ?

See extract of my gcode below (F is constant, S is variating), however, laser is accelerating / decelerating wiith each & every command.

; LightBurn 1.4.00
; GRBL device profile, absolute coords
; Bounds: X11.96 Y26.7 to X216.56 Y178.5
G00 G17 G40 G21 G54
G90
M4
; Image @ 350 mm/sec, 20% power
M7
G0 X13.564Y178.499
M3
G0 Z0
; Layer C00
G91
G1 X8.75F21000S0
G1 X1.2S200
G1 X8.75S0
G1 X0.5Y-0.1S0
G1 X-8.75S0
G1 X-2.1S200
G1 X-8.75S0
G1 X-0.2Y-0.1S0
G1 X8.75S0
G1 X2.5S200
G1 X8.75S0
G1 X0.4Y-0.1S0
...

Thanks !
