### ISSUE TITLE
Problem: Controller crash, self-resets and then skips config file

### ISSUE THREAD

**Issue by TITAN3737** [bdring/FluidNC#936]
### Controller Board

Root Controller ISO Rev 3 (https://www.rootcnc.com/product/root-controller-rev-3/) running FluidNC v3.7.1.

### Machine Description

Gantry diode laser with external DM556 stepper drivers, dual Y motors, endstops switches on all axes, 80W laser module.

### Configuration file

```yaml
nboard: Root Controler v3.0
name: CNC-1250x1250
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN

  x:
   steps_per_mm: 800.000
   max_rate_mm_per_min: 4000.000
   acceleration_mm_per_sec2: 100.000
   max_travel_mm: 1280.000
   soft_limits: true
   homing:
    cycle: 2
    positive_direction: false
    mpos_mm: 0.000
    feed_mm_per_min: 300.000
    seek_mm_per_min: 3000.000
    settle_ms: 100
    seek_scaler: 1.100
    feed_scaler: 1.100

   motor0:
    limit_neg_pin: gpio.34
    limit_pos_pin: NO_PIN
    limit_all_pin: NO_PIN
    pulloff_mm: 3.000
    standard_stepper:
      step_pin: I2SO.7:low
      direction_pin: I2SO.5:low
      disable_pin: I2SO.3:high

  y:
   steps_per_mm: 800.000
   max_rate_mm_per_min: 4000.000
   acceleration_mm_per_sec2: 100.000
   max_travel_mm: 1280.000
   soft_limits: true
   homing:
    cycle: 2
    positive_direction: false
    mpos_mm: 0.000
    feed_mm_per_min: 300.000
    seek_mm_per_min: 3000.000
    settle_ms: 100
    seek_scaler: 1.100
    feed_scaler: 1.100

   motor0:
    limit_neg_pin: gpio.32
    limit_pos_pin: NO_PIN
    limit_all_pin: NO_PIN
    pulloff_mm: 3.000
    standard_stepper:
      step_pin: I2SO.12:low
      direction_pin: I2SO.10:high
      disable_pin: I2SO.8:high

   motor1:
#   limit_neg_pin: gpio.26
    limit_pos_pin: NO_PIN
    limit_all_pin: NO_PIN
    pulloff_mm: 3.000
    standard_stepper:
      step_pin: I2SO.6:low
      direction_pin: I2SO.4:high
      disable_pin: I2SO.2:high

  z:
   steps_per_mm: 2000.000
   max_rate_mm_per_min: 1000.000
   acceleration_mm_per_sec2: 100.000
   max_travel_mm: 180.000
   soft_limits: true
   homing:
    cycle: 1
    positive_direction: true
    mpos_mm: 0.000
    feed_mm_per_min: 300.000
    seek_mm_per_min: 2000.000
    settle_ms: 100
    seek_scaler: 1.100
    feed_scaler: 1.100

   motor0:
    limit_neg_pin: NO_PIN
    limit_pos_pin: gpio.27
    limit_all_pin: NO_PIN
    pulloff_mm: 3.000
    standard_stepper:
      step_pin: I2SO.18:low
      direction_pin: I2SO.16:high
      disable_pin: I2SO.14:high

i2so:
  bck_pin: gpio.22
  data_pin: gpio.12
  ws_pin: gpio.21

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5
# frequency_hz: 1000000

control:
  safety_door_pin: gpio.15:low
  reset_pin: NO_PIN
# feed_hold_pin: gpio.15:low
  cycle_start_pin: NO_PIN

probe:
  pin: gpio.2
  check_mode_start: false

Laser:
  pwm_hz: 5000
  output_pin: gpio.33
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0% 1000=100%
  off_on_alarm: true

macros:
  startup_line0:
  startup_line1:
 #macro0: $SD/Run=lasertest.gcode
  macro1:
  macro2:
  macro3:

user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: true
```

### Startup Messages

```text
Resetting MCU
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4

[MSG:INFO: FluidNC v3.7.1]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:con12.yaml]
[MSG:DBG: Running after-parse tasks]
[MSG:DBG: Checking configuration]
[MSG:INFO: Machine CNC-1250x1250]
[MSG:INFO: Board Root Controler v3.0]
[MSG:INFO: I2SO BCK:gpio.22 WS:gpio.21 DATA:gpio.12]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:I2S_stream Pulse:4us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (0.000,1280.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.7:low Dir:I2SO.5:low Disable:I2SO.3]
[MSG:INFO:  X Neg Limit gpio.34]
[MSG:DBG:  X Neg Limit 0]
[MSG:INFO: Axis Y (0.000,1280.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.12:low Dir:I2SO.10 Disable:I2SO.8]
[MSG:INFO:  Y Neg Limit gpio.32]
[MSG:DBG:  Y Neg Limit 0]
[MSG:INFO:   Motor1]
[MSG:INFO:     standard_stepper Step:I2SO.6:low Dir:I2SO.4 Disable:I2SO.2]
[MSG:INFO: Axis Z (-180.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     standard_stepper Step:I2SO.18:low Dir:I2SO.16 Disable:I2SO.14]
[MSG:INFO:  Z Pos Limit gpio.27]
[MSG:DBG:  Z Pos Limit 0]
[MSG:INFO: safety_door_pin gpio.15:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.33 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Probe Pin: gpio.2]
[MSG:INFO: Connecting to STA SSID:CNC_Router]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.0.201]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC v3.7.1 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
[MSG:DBG:  X Neg Limit 0]
[MSG:DBG:  Y Neg Limit 0]
[MSG:DBG:  Z Pos Limit 0]
```

### User Interface Software

WebUI

### What happened?

I am trying to make my new controller (Root Controller ISO Rev 3) work, but when using WebUI the controller very often crashes and I need to restart it several times before it works again. 
After many days of trial and error I now know that CPU self-resets and then skips the config file. Hence the need for multiple physical resets of the controller. On next start it uses the config again without skipping.
But that is as far as I can track the issue. After reading many other issues, I have connected my controller to USB and I can see in the console what is happening during the crash. I don’t know why is this happening, but I cannot finish almost any gcode without crash.
When I run the job from the WebUI, it works few seconds and then, at first it stutters, then continues and come to full stop and continues after few seconds. Then finally ten stops completely and restarts.
Can somebody please tell what can I do to make the controller stable and reliable? 
Example gcode file: [EngraveTest1.zip](https://github.com/bdring/FluidNC/files/11835481/EngraveTest1.zip)
Text from the console: [fluidterm_log_2023-06-22.txt](https://github.com/bdring/FluidNC/files/11835306/fluidterm_log_2023-06-22.txt)
