### ISSUE TITLE
Problem: MSG:WARN: Low memory with latest 8/16MB build

### ISSUE THREAD

**Issue by SparkyDan555** [bdring/FluidNC#944]
### Controller Board

FluidNC Pen Laser Controller (SPI)

### Machine Description

Feungsake 4040 Laser Engraver with 4W PWM Laser Module

### Configuration file

```yaml
name: "TMC2130 XY Laser"
board: "FluidNC Laser (Daniel White)"

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.13:high

  x:
    steps_per_mm: 160
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 150
    max_travel_mm: 500
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.00
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1000.000
      settle_ms: 0
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36 
      limit_all_pin: gpio.34:low
      hard_limits: true
      pulloff_mm: 2.000
      tmc_2130:
        direction_pin: gpio.12
        step_pin: gpio.14
        cs_pin: gpio.16
        r_sense_ohms: 0.110
        run_amps: 0.5
        hold_amps: 0.25
        microsteps: 32
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: true
    motor1:
      null_motor:

  y:
    steps_per_mm: 160
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 150
    max_travel_mm: 410
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.00
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1000.000
      settle_ms: 0
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.39
      limit_all_pin: gpio.35:low
      hard_limits: true
      pulloff_mm: 2.000
      tmc_2130:
        direction_pin: gpio.26
        step_pin: gpio.25
        cs_pin: gpio.17
        r_sense_ohms: 0.110
        run_amps: 0.75
        hold_amps: 0.5
        microsteps: 32
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: true
    motor1:
      null_motor:

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin:  NO_PIN

probe:
  pin: NO_PIN

Laser:
  pwm_hz: 5000
  output_pin: gpio.22
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 255=100.000%
  off_on_alarm: true

control:
  safety_door_pin: gpio.32:pu
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

# Board Inputs:
# Input 1: gpio.32
# Input 2: gpio.33
# Input 3: gpio.4
# Input 4: gpio.15

user_outputs:
  digital1_pin: NO_PIN
  digital1_pin: gpio.27
  digital2_pin: gpio.2
  digital3_pin: gpio.21

# Board Outputs:
# Output 1: gpio.27
# Output 2: gpio.2 (LED)
# Output 3: gpio.21

parking:
  enable: true
  axis: Y
  pullout_distance_mm: 0
  pullout_rate_mm_per_min: 250.000
  target_mpos_mm: 410
  rate_mm_per_min: 1000.00
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.6.8 (main-33576ba2-dirty)]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine TMC2130 XY Laser]
[MSG:INFO: Board FluidNC Laser (Daniel White)]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:250ms]
[MSG:INFO: User Digital Output:1 on Pin:gpio.27]
[MSG:INFO: User Digital Output:2 on Pin:gpio.2]
[MSG:INFO: User Digital Output:3 on Pin:gpio.21]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13]
[MSG:INFO: Axis X (0.000,500.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2130 Step:gpio.14 Dir:gpio.12 CS:gpio.16 Disable:NO_PIN Index:-1 R:0.110]
[MSG:INFO:  X Neg Limit gpio.36]
[MSG:INFO:  X All Limit gpio.34:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (0.000,410.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2130 Step:gpio.25 Dir:gpio.26 CS:gpio.17 Disable:NO_PIN Index:-1 R:0.110]
[MSG:INFO:  Y Neg Limit gpio.39]
[MSG:INFO:  Y All Limit gpio.35:low]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: X Axis driver test passed]
[MSG:INFO: Y Axis driver test passed]
[MSG:INFO: safety_door_pin gpio.32:pu]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Laser Ena:NO_PIN Out:gpio.22 Freq:5000Hz Period:8191]
[MSG:INFO: Using spindle Laser]
[MSG:INFO: Connecting to STA SSID:########]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 10.2.1.89]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.6 [FluidNC v3.6.8 (main-33576ba2-dirty) (wifi+bt) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
[MSG:WARN: Low memory: 14780 bytes]
[MSG:WARN: Low memory: 14660 bytes]
[MSG:WARN: Low memory: 14456 bytes]
[MSG:WARN: Low memory: 11964 bytes]
[MSG:WARN: Low memory: 9488 bytes]
[MSG:WARN: Low memory: 9288 bytes]
[MSG:ERR: sdmmc_card_init failed code 0x0x107]
[MSG:WARN: Low memory: 8124 bytes]
[MSG:WARN: Low memory: 7716 bytes]
[MSG:WARN: Low memory: 7284 bytes]
[MSG:INFO: Channel auto report interval set to 50 ms]
[MSG:WARN: Low memory: 5904 bytes]
[MSG:WARN: Low memory: 5712 bytes]
[MSG:WARN: Low memory: 5296 bytes]
```

### User Interface Software

FluidTerm

### What happened?

I have built a 16MB version of FluidNC for a 16MB ESP32-DevKit with the following lines in platform.ini:

```
board_build.partitions = FluidNC/ld/esp32/app3M_spiffs9M_16MB.csv ; For 16Meg ESP32
board_upload.maximum_size = 16777216 ; For 16Meg ESP32
board_upload.flash_size = 16MB ; For 16Meg ESP32
```
This does work but when connecting to the web interface, the console is filled with `MSG:WARN: Low memory`. I have a previous build up to commit [468fee9](https://github.com/bdring/FluidNC/commit/468fee94c191b7729e8d87817dd83dfddfc1ec0c) with the same changes in platformio.ini which does not have this issue.
