### ISSUE TITLE
mks dlc32 + lightburn problema  flood_pin: gpio.4

### ISSUE THREAD

**Issue by distebia** [bdring/FluidNC#958]
### Wiki Search Terms

board: MKS DLC32 2.1
name: MKS DLC32 XYZ CO2+DIODO uso CO2
meta: (08/07/2022) Biagio CO2+DIODO uso CO2

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 120
#planner_blocks: 16

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
  #segments: 12

axes:
  shared_stepper_disable_pin: i2so.0
  x:
    steps_per_mm: 79.9781
    max_rate_mm_per_min: 20000.000
    acceleration_mm_per_sec2: 2000.000
    max_travel_mm: 1100.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.500
      standard_stepper:
        step_pin:  i2so.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 79.874
    max_rate_mm_per_min: 10000.000
   #acceleration_mm_per_sec2: 300.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 890.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: gpio.33
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.500
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.6

  z:
    steps_per_mm: 640.000
    max_rate_mm_per_min: 200.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 170.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 200.000
      settle_ms: 250.000
      seek_scaler: 1.500
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
     #limit_pos_pin: gpio.22:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.3
        direction_pin: I2SO.4:low

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  card_detect_pin: gpio.39
  cs_pin: gpio.15

coolant:
  flood_pin: gpio.4
  mist_pin: NO_PIN
 #mist_pin: gpio.0
  delay_ms: 0

probe:
  pin: gpio.2
  check_mode_start: false

start:
  must_home: false

Laser:
  pwm_hz: 5000
  output_pin: gpio.32
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: false
 #speed_map: 0=0.000% 0=11.000% 1000=100.000%
  speed_map: 0=0.000% 0=10.000% 1000=100.000%

### Controller Board

mks dlc32

### Machine Description

autocostruita

### Input Circuits

```yaml
flood_pin: gpio.4
```

### Configuration file

```yaml
board: MKS DLC32 2.1
name: MKS DLC32 XYZ CO2+DIODO uso CO2
meta: (08/07/2022) Biagio CO2+DIODO uso CO2

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 120
#planner_blocks: 16

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
  #segments: 12

axes:
  shared_stepper_disable_pin: i2so.0
  x:
    steps_per_mm: 79.9781
    max_rate_mm_per_min: 20000.000
    acceleration_mm_per_sec2: 2000.000
    max_travel_mm: 1100.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.500
      standard_stepper:
        step_pin:  i2so.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 79.874
    max_rate_mm_per_min: 10000.000
   #acceleration_mm_per_sec2: 300.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 890.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: gpio.33
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.500
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.6

  z:
    steps_per_mm: 640.000
    max_rate_mm_per_min: 200.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 170.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 200.000
      settle_ms: 250.000
      seek_scaler: 1.500
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
     #limit_pos_pin: gpio.22:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.3
        direction_pin: I2SO.4:low

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  card_detect_pin: gpio.39
  cs_pin: gpio.15

coolant:
  flood_pin: gpio.4
  mist_pin: NO_PIN
 #mist_pin: gpio.0
  delay_ms: 0

probe:
  pin: gpio.2
  check_mode_start: false

start:
  must_home: false

Laser:
  pwm_hz: 5000
  output_pin: gpio.32
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: false
 #speed_map: 0=0.000% 0=11.000% 1000=100.000%
  speed_map: 0=0.000% 0=10.000% 1000=100.000%
```

### Startup Messages

```text
tutto ok
```

### What happened?

Salve, avevo installato il firmware 3.6.5 e non avevo nessun problema. oggi installo la [v3.7.2-pre3](https://github.com/bdring/FluidNC/releases/tag/v3.7.2-pre3) e riscontro il problema sull'attivazione del relè collegato al pin gnd gpio.4 della scheda mks dlc32. All'avvio il pin teneva spento, attraverso il relè, la pompa dell'aria e si attivava soltanto da lightburn (impostato su m8) e si spegneva con m9. so che dalla 3.6.5 alla 3.7.2 sono cambiate tante cose a riguardo, tipo 7.1 e 8.1, ma non riesco a capire cosa devo modificare per avere la situazione come prima. Grazie
