### ISSUE TITLE
Problem: Reboot caused by Guru Meditation Error?

### ISSUE THREAD

**Issue by ianwestwood** [bdring/FluidNC#959]
### Wiki Search Terms

I searched for 'errors' and 'reboots' here http://wiki.fluidnc.com/en/support/troubleshooting_config_files and am asking for help & advice please.

### Controller Board

'FluidNC Pen Laser Controller TMC2209' purchased from [tindie](https://www.tindie.com/products/33366583/fluidnc-penlaser-cnc-controller-tmc2209/) & delivered last week along with  the 'ESP32 W/PCB Antenna + FluidNC Programming' option. 

### Machine Description

I'm using the controller for a ZenXY V2, designed by the folks over at V1 engineering.  Build details here https://docs.v1e.com/zenxy/.  

Currently running on a bench PSU at 12V.

Photos of setup here:

![BF5C1DE0-FEC0-499E-B90F-24F61F274812_1_102_o](https://github.com/bdring/FluidNC/assets/13510279/a2b3ebf6-01b9-48b2-a648-ec13fec423e2)

![5011B777-DCA4-4411-A8C7-71DE78D71A76_1_102_o](https://github.com/bdring/FluidNC/assets/13510279/9042680f-0bce-47c1-a05a-2b11f94117c9)

![47E03350-5B7E-4D0D-91D0-0CDC66E1891C_1_102_o](https://github.com/bdring/FluidNC/assets/13510279/11d57064-da75-4a42-897d-f9dfbb08577c)

![507810E8-A61C-49C1-BC74-AF6FDD85A63D_1_105_c](https://github.com/bdring/FluidNC/assets/13510279/f2ec71e4-a9f0-422a-8182-f270c9e995d0)

![D6EDC4A9-061B-4C27-B61C-41D6AC3AEE8E_1_105_c](https://github.com/bdring/FluidNC/assets/13510279/3ea5fb48-989b-4d6e-acfe-19e55f833d26)

### Input Circuits

```yaml
I don't think this is limit switch related, but for completion I'm using optical switches connected to gpio 36 & 39 (yellow wires are 'sig' in the photo). 

They appear to be working as expected and it homes OK.
```

### Configuration file

```yaml
board: FluidNC Pen Laser TMC2209
name: V1 Engineering ZenXY V2 hello world
meta: Optical end stops enabled

kinematics:
  corexy:

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0
  
uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 115200
  mode: 8N1

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

start:
  must_home: false

axes:
  shared_stepper_disable_pin: gpio.13:high
  
  x:
    steps_per_mm: 100
    max_rate_mm_per_min: 8000
    acceleration_mm_per_sec2: 300
    max_travel_mm: 653
    soft_limits: false
    
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: false
      feed_mm_per_min: 400.000
      seek_mm_per_min: 1200.000
      settle_ms: 200
      seek_scaler: 1.500
      feed_scaler: 1.500
    
    motor0:
      limit_pos_pin: gpio.39:high
      hard_limits: false
      pulloff_mm: 3.00
      tmc_2209:
        uart_num: 1
        addr: 0
        r_sense_ohms: 0.110
        run_amps: 0.500
        hold_amps: 0.150
        microsteps: 16
        stallguard: 16
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: gpio.14
        direction_pin: gpio.12
        disable_pin: NO_PIN

    motor1:
      null_motor:

  y:
    steps_per_mm: 100
    max_rate_mm_per_min: 8000
    acceleration_mm_per_sec2: 300
    max_travel_mm: 437
    soft_limits: false

    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: false
      feed_mm_per_min: 400.000
      seek_mm_per_min: 1200.000
      settle_ms: 200
      seek_scaler: 1.500
      feed_scaler: 1.500
    
    motor0:
      limit_pos_pin: gpio.36:high
      hard_limits: false
      pulloff_mm: 2.000
      tmc_2209:
        uart_num: 1
        addr: 1
        r_sense_ohms: 0.110
        run_amps: 0.500
        hold_amps: 0.150
        microsteps: 16
        stallguard: 16
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: gpio.25
        direction_pin: gpio.26
        disable_pin: NO_PIN
    
    motor1:
      null_motor:
      
  z:
    motor0:
      null_motor:
```

### Startup Messages

```text
[MSG:INFO: FluidNC v3.7.1]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:TMC2209_ZenXY_V1.yaml]
[MSG:INFO: Machine V1 Engineering ZenXY V2 hello world]
[MSG:INFO: Board FluidNC Pen Laser TMC2209]
[MSG:INFO: UART1 Tx:gpio.17 Rx:gpio.16 RTS:NO_PIN Baud:115200]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:RMT Pulse:2us Dsbl Delay:0us Dir Delay:1us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13]
[MSG:INFO: Axis X (0.000,653.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 UART1 Addr:0 Step:gpio.14 Dir:gpio.12 Disable:NO_PIN R:0.110]
[MSG:INFO:  X Pos Limit gpio.39]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Y (0.000,437.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 UART1 Addr:1 Step:gpio.25 Dir:gpio.26 Disable:NO_PIN R:0.110]
[MSG:INFO:  Y Pos Limit gpio.36]
[MSG:INFO:   Motor1]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: X Axis driver test passed]
[MSG:INFO: Y Axis driver test passed]
[MSG:INFO: Kinematic system: CoreXY]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:XXXXXXXXX]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.XX.XX]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

fluidterm.exe

### What happened?

All gcode in this example was generated using https://sandify.org/.

'Rose polygon.gcode' crashes at about the same location(ish).  For reference in the picture above where you see the ball bearing in the sand is approximately where it reboots each time.  FluidNC UI says it is 36.51% complete.  

Previously, 'sandify linear wiper 650x435 F2500.gcode' gave me very similar reboots and error messages (although I didn't save any dumps for this ticket).  I had increased X & Y max_travel a couple mm in config yaml, and this did seem to allow me to run the gcode successfully.  I also tried changing soft_limits to false when 'Rose polygon' gave me trouble, but this didn't seem to make any difference.  I guess I was just grasping at straws.

Additionally it occasionally it pauses for a couple of seconds (motors stop) when executing gcode.  This seems random at the time of writing.  No problem for my sand table really, but I imagine it would be a pain for CNC!

I am using a Apple MBP running Ventura 13.3.1 and Chrome 114.0.5735.198 to access the FluidNC UI over wifi.

I am using a Parallels VM on the same MBP running Windows 10 to run fluidterm and Notepad++ to make config files and edit gcode.

### GCode File

[Rose polygon.txt](https://github.com/bdring/FluidNC/files/12010855/Rose.polygon.txt)
[sandify linear wiper 650x435 F2500.txt](https://github.com/bdring/FluidNC/files/12010864/sandify.linear.wiper.650x435.F2500.txt)

### Other Information

Here is the error copy paste from fluidterm.exe:

Grbl 3.7 [FluidNC v3.7.1 (wifi) '$' for help]
[MSG:INFO: Channel auto report interval set to 50 ms]
[MSG: /littlefs/macro1.g file job succeeded]
[MSG:INFO: Channel auto report interval set to 50 ms]
[MSG: /littlefs/macro1.g file job succeeded]
Guru Meditation Error: Core  0 panic'ed (InstrFetchProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x00000000  PS      : 0x00060430  A0      : 0x800f33d2  A1      : 0x3ffe8600
A2      : 0x3ffcb628  A3      : 0x3ffcb4d5  A4      : 0x00000000  A5      : 0x00000000
A6      : 0x3ffcab80  A7      : 0x00000000  A8      : 0x800f3270  A9      : 0x3ffe85e0
A10     : 0x3ffeedd8  A11     : 0x3ffeedd8  A12     : 0x3ffbc170  A13     : 0x00000000
A14     : 0x00000000  A15     : 0x00000001  SAR     : 0x0000001f  EXCCAUSE: 0x00000014
EXCVADDR: 0x00000000  LBEG    : 0x4008b6c4  LEND    : 0x4008b6da  LCOUNT  : 0xffffffff

Backtrace: 0xfffffffd:0x3ffe8600 0x400f33cf:0x3ffe8630 0x400f0707:0x3ffe8650

ELF file SHA256: c0232e7857604a85

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4

[MSG:INFO: FluidNC v3.7.1]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:ERR: Skipping configuration file due to panic]
[MSG:INFO: Using default configuration]
[MSG:INFO: Axes: using defaults]
[MSG:INFO: Machine Default (Test Drive)]
[MSG:INFO: Board None]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:ShaManorHouse]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.86.27]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.7 [FluidNC v3.7.1 (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]

This is a screenshot from the FluidNC UI after crash:

<img width="1623" alt="Screenshot 2023-07-10 at 10 21 03 PM" src="https://github.com/bdring/FluidNC/assets/13510279/58a869cf-1922-423c-b81f-fb67e026a18a">
