### ISSUE TITLE
da 3.6.5 a 3.7.4 problemi gpio.4 coolant

### ISSUE THREAD

**Issue by distebia** [bdring/FluidNC#967]
### Wiki Search Terms

.

### Controller Board

mks dlc32 v2.1

### Machine Description

Autocostruita

### Input Circuits

```yaml
gpio.4
```

### Configuration file

```yaml
board: MKS DLC32 2.1
name: MKS DLC32 XYZ CO2+DIODO uso CO2
meta: (08/07/2022) Biagio CO2+DIODO uso CO2

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 120
#planner_blocks: 16

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
  #segments: 12

axes:
  shared_stepper_disable_pin: i2so.0
  x:
    steps_per_mm: 79.9781
    max_rate_mm_per_min: 20000.000
    acceleration_mm_per_sec2: 2000.000
    max_travel_mm: 1100.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.500
      standard_stepper:
        step_pin:  i2so.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 79.874
    max_rate_mm_per_min: 10000.000
   #acceleration_mm_per_sec2: 300.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 890.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: gpio.33
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.500
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.6

  z:
    steps_per_mm: 640.000
    max_rate_mm_per_min: 200.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 170.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 200.000
      settle_ms: 250.000
      seek_scaler: 1.500
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
     #limit_pos_pin: gpio.22:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.3
        direction_pin: I2SO.4:low

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  card_detect_pin: gpio.39
  cs_pin: gpio.15

coolant:
  flood_pin: gpio.4
  mist_pin: NO_PIN
 #mist_pin: gpio.0
  delay_ms: 0

probe:
  pin: gpio.2
  check_mode_start: false

start:
  must_home: false

Laser:
  pwm_hz: 5000
  output_pin: gpio.32
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: false
 #speed_map: 0=0.000% 0=11.000% 1000=100.000%
  speed_map: 0=0.000% 0=10.000% 1000=100.000%
```

### Startup Messages

```text
tutto ok
```

### User Interface Software

lightburn, lasergrbl

### What happened?

Salve, ho aggiornato la scheda passando dalla versione 3.6.5 alla 3.7.3 poi 3.7.4 e riscontro sempre lo stesso problema: l'attivazione del pin gpio.4 avviene in modo del tutto irregolare, con la 3.6.5 tutto funziona perfettamente. 
Pensando a qualche errore di installazione ho anche formattato la scheda con il tools proprietario, poi fatto erase.bat, install.fs (che mi restituisce un errore in fase di ctrl-U) e install-wifi.bat
![image](https://github.com/bdring/FluidNC/assets/52679577/78a3ee92-3036-40f6-ac01-8b0469113f13)
successivamente per ritornare alla versione 3.6.5 ho rifatto la stessa procedura e l'attivazione del pin si comporta in modo regolare. sono a conoscenza delle migliorie di M7.1 e M8.1. Utilizzo lightburn con attivazione m8 e disattivazione m9
Vorrei aggiornare a 3.7.4 anche per l'incisione fluida ma se non riesco a risolvere il problema dell'attivazione del pin gpio.4 avrò una macchina incompleta.
Certe volte m8 attiva e m9 disattiva, altre volte m8 attiva e m9 non reagisce, altre volte ancora m8 attiva e m9 disattiva con ritardo di 1-2 sec., tutte le prove fatte da fluidterm

### GCode File

.

### Other Information

.
