### ISSUE TITLE
Problem: Crash and Reboot on Long Jobs (still occurs on v3.7.4)

### ISSUE THREAD

**Issue by msxmatt** [bdring/FluidNC#968]
### Wiki Search Terms

N/A

### Controller Board

Custom ESP32-S3 board

### Machine Description

3-axis gantry machine

### Configuration file

```yaml
name: "custom"
board: "custom"

stepping:
  engine: TIMED
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 4
  disable_delay_us: 1

start:
  must_home: false

planner_blocks: 16

control:
    feed_hold_pin: gpio.36:low

# uart1:
#   txd_pin: gpio.22
#   rxd_pin: gpio.21
#   baud: 115200
#   mode: 8N1

kinematics:
  corexy:

# 20t pulley
# steps per mm/microsteps   80/16   40/8    20/4    10/2    5/1
# resolution in mm          0.0125  0.025   0.050   0.100   0.200

# 16t pulley
# steps per mm/microsteps   100/16  50/8    25/4    12.5/2  6.25/1
# resolution in mm          0.010   0.020   0.050   0.080   0.160

# 1/4 microsteps gives best torque for a wide range of speeds

# Board stepper driver address and gpio
# axis  add   step  dir
# x     1     27    26
# y     3     33    32
# z     0     14    12
# e     2     16    17

axes:
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN

  x:
    steps_per_mm: 40
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 5000
    max_travel_mm: 1275
    soft_limits: false
    homing:
      cycle: 2
      allow_single_axis: true
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 4000
      feed_mm_per_min: 600
      settle_ms: 200
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.1:high
      pulloff_mm: 10
      stepstick:
        disable_pin: gpio.15:low
        direction_pin: gpio.16:low
        step_pin: gpio.17
    motor1:
      null_motor:

  y:
    steps_per_mm: 40
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 5000
    max_travel_mm: 1024
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      mpos_mm: -1025
      positive_direction: false
      seek_mm_per_min: 4000
      feed_mm_per_min: 600
      settle_ms: 200
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.2:high
      pulloff_mm: 10
      stepstick:
        disable_pin: gpio.18:low
        direction_pin: gpio.21:low
        step_pin: gpio.26
    motor1:
      null_motor:

  z:
    steps_per_mm: 16
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 3000.000
    max_travel_mm: 25
    soft_limits: false
    homing:
      cycle: -1

    motor0:
      #limit_pos_pin: gpio.4:high
      pulloff_mm: 4
      stepstick:
        disable_pin: gpio.47:low
        direction_pin: gpio.33
        step_pin: gpio.34
    motor1:
      null_motor:

spi:
  miso_pin: gpio.8
  mosi_pin: gpio.9
  sck_pin: gpio.10

sdcard:
  cs_pin: gpio.12
  card_detect_pin: gpio.14
  frequency_hz: 8000000

user_outputs:
  digital0_pin: gpio.5
  digital1_pin: gpio.43
  digital2_pin: gpio.44
  digital3_pin: gpio.42
  digital4_pin: gpio.6

# run a fan off the 24V/5V fan header – switch on and off with the WebUI mist button or by issuing an M8 command, turn off with M9
coolant:
  mist_pin: gpio.13
  delay: 0

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:
```

### Startup Messages

```text
[MSG:INFO: FluidNC bantam_v0.4.0]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.4]
[MSG:INFO: Local filesystem type is spiffs]
[MSG:INFO: RESET: Software reset due to exception/panic]
[MSG:ERR: Skipping configuration file due to panic]
[MSG:INFO: Using default configuration]
[MSG:INFO: Axes: using defaults]
[MSG:INFO: Machine Default (Test Drive)]
[MSG:INFO: Board None]
[MSG:INFO: Stepping:RMT Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:255ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Y (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Z (-1000.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:Workshop]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.5.55]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]
```

### User Interface Software

WebUI, FluidTerm

### What happened?

We're running a custom ESP32-S3 based board to run FluidNC (thanks for your work on S3 so far).  On a long job (typically 18 hours), we're seeing our machine randomly reboot at some point during the run, similar to #936 .  Typically the error looks like this:

```
[MSG:INFO: Mount_sd]
[MSG:INFO: Unmount_sd]
[MSG:INFO: Channel auto report interval set to 50 ms]
[MSG:INFO: Mount_sd]
Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed). 


Core  1 register dump:
PC      : 0xbad00bad  PS      : 0x00060034  A0      : 0x803757e9  A1      : 0x3fc9a2e0
A2      : 0x3fcf7354  A3      : 0x00000001  A4      : 0x00000020  A5      : 0x80000000
A6      : 0x3fca506c  A7      : 0x3fca4a2c  A8      : 0x8037c559  A9      : 0xffffffff
A10     : 0x3fceeb20  A11     : 0x00000001  A12     : 0x00000000  A13     : 0x00000020
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000006  EXCCAUSE: 0x00000007
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000


Backtrace: 0x7ad00baa:0x3fc9a2e0 |<-CORRUPTED




ELF file SHA256: aeff0da83d1ef40a

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x28 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40045c0c
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
```

It seemed to be related to Wi-Fi sockets since we've been able to run the job once or twice with Wi-Fi off, however it's hard to tell with such a long time to failure.  We've merged in the latest (v3.7.4) since it sounds like there's been a lot of improvement in the wifi code, but the issue persists.

Currently, we're monitoring the heap using `heapCheckTask` and we don't seem to have a memory leak so that's good 👍 .  I thought it might be an SD card failure, so I'm currently debugging.

Is this still caused by websockets or potentially something else?  Happy to debug as needed.

### GCode File

(file is too big to attach)
