### ISSUE TITLE
problema incisione immagine con nuova versione 3.7.5, tutto ok con 3.6.5.

### ISSUE THREAD

**Issue by distebia** [bdring/FluidNC#987]
### Wiki Search Terms

planner block

### Controller Board

mks dlc32 v.2.1

### Machine Description

autocostruita

### Configuration file

```yaml
board: MKS DLC32 2.1
name: MKS DLC32 XYZ CO2+DIODO uso CO2
meta: (08/07/2022) Biagio CO2+DIODO uso CO2

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
#planner_blocks: 120
planner_blocks: 16

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
  segments: 12

axes:
  shared_stepper_disable_pin: i2so.0
  x:
    steps_per_mm: 79.9781
    max_rate_mm_per_min: 40000.000
   #max_rate_mm_per_min: 20000.000
    acceleration_mm_per_sec2: 4000.000
    max_travel_mm: 1100.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.500
      standard_stepper:
        step_pin:  i2so.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 79.874
    max_rate_mm_per_min: 10000.000
   #acceleration_mm_per_sec2: 300.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 890.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 5000.000
      settle_ms: 250.000
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: gpio.33
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.500
      standard_stepper:
        step_pin: I2SO.5
        direction_pin: I2SO.6

  z:
    steps_per_mm: 640.000
    max_rate_mm_per_min: 200.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 170.000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 200.000
      settle_ms: 250.000
      seek_scaler: 1.500
      feed_scaler: 1.500

    motor0:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
     #limit_pos_pin: gpio.22:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      standard_stepper:
        step_pin: I2SO.3
        direction_pin: I2SO.4:low

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  card_detect_pin: gpio.39
  cs_pin: gpio.15

coolant:
  flood_pin: gpio.4
  mist_pin: NO_PIN
 #mist_pin: gpio.0
  delay_ms: 0

probe:
  pin: gpio.2
  check_mode_start: false

start:
  must_home: false

Laser:
  pwm_hz: 10000
  output_pin: gpio.32
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: false
 #speed_map: 0=0.000% 0=11.000% 1000=100.000%
  speed_map: 0=0.000% 0=10.000% 1000=100.000%
```

### Startup Messages

```text
tutto ok
```

### User Interface Software

lightburn

### What happened?

salve, ho inciso un'immagine stucki grande 300x200 con lightburn (stucki, intervallo 0.1mm) collegato alla scheda mediante cavo usb. Proprio all'inizio del lavoro mi accorgo che ho un movimento a scatti e non fluido. oltrepassando i 5-6mm di incisione il movimento diventa fluido e senza scatti. osservo il lavoro finito e mi accorgo che presenta, proprio all'inizio dell'incisione, una banda ben marcata che si distingue da tutto il resto. Non contento del lavoro eseguito lo rifaccio ma riporto alcuni parametri ai valori di default nel file di configurazione: planner block da 120 a 16 e segments a 12. Rieseguo il lavoro e il comportamento è uguale al precedente. Utilizzo lightburn con fluidNc 3.7.5. allego foto
![image](https://github.com/bdring/FluidNC/assets/52679577/72da13e8-2ec5-49b4-9ff2-a04c64525e49)
![image](https://github.com/bdring/FluidNC/assets/52679577/16d59bfd-535b-4e41-9322-95d80aa27a77)
![image](https://github.com/bdring/FluidNC/assets/52679577/ab81682f-4db7-45c3-9c28-f1fd3f736176)
![image](https://github.com/bdring/FluidNC/assets/52679577/8724b79b-6a17-4fe7-b81b-c5a78b9b3567)

### GCode File

[compensato1.zip](https://github.com/bdring/FluidNC/files/12268221/compensato1.zip)
